### ISSUE TITLE
AWS Terraform example should populate wildcard DNS entry to support application access

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#10089]
### What

Both the starter and ha cluster aws terraform examples do not publish a wildcard certificate. This is needed for application access to work nicely.

### How

Add an additional route53 record to/route53.tf

### Why

To use application access

### Workaround

manually create a wildcard record after running terraform

**Comment by webvictim** [comment]
This is actually already done here: https://github.com/gravitational/teleport-cluster-terraform/blob/master/route53.tf

The issue is mostly I moved off the Teleport team before being able to rewrite all the references to `ha-autoscale-cluster` to point here instead. We could probably just backport the code for ease, as the module structure for `teleport-cluster-terraform` is quite a lot different to the current example code.

**Comment by webvictim** [comment]
There are a number of other enhancements to that module which I have now totally forgotten about too :(

**Comment by evilmog** [comment]
The example code should be backported then, we just signed up for enterprise and are using the example code for deployment. A working production example for enterprise customers would be appreciated.

**Comment by stevenGravy** [comment]
implemented in #12972
