### ISSUE TITLE
tctl auth sign --format=kubernetes does not respect `kube_public_addr` settings

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#10396]
### Description

**What happened**:
If using the `tctl auth sign --format=kubernetes` functionality as described in our kubernetes ci/cd docs (https://goteleport.com/docs/kubernetes-access/guides/cicd/) with a non-default port in the proxy `kube_public_addr`, this is not taken into account in the generated kubeconfig file and the credentials will not work.

For comparison, an interactive `tsh kube login` generates the correct kubeconfig file with the `server` respecting the `kube_public_addr`

This is of particular concern for cloud customers where changing the `kube_public_addr` is not possible and it can be set to a non-default value.

**What you expected to happen**:
 `tctl auth sign --format=kubernetes` should respect the `kube_public_addr` when generating a kubeconfig file.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1.Set the `kube_public_addr` in the proxy service to something other than 3026 (leave `kube_listen_addr` port at 3026)
2.Run `tctl auth sign --format=kubernetes` as a remote user and observe the generated `server` value in the kubeconfig file

gz#5892

**Comment by mcbattirola** [comment]
Looks like this is set using the proxy address here: https://github.com/gravitational/teleport/blob/master/tool/tctl/common/auth_command.go#L642

`a.proxyAddr` is set by [this](https://github.com/gravitational/teleport/blob/master/tool/tctl/common/auth_command.go#L719) function, which tries to guess the proxy if none is sent via CLI.

If it couldn't find the correct proxy in any way, it uses the default port (3026)

Testing on my cloud instance, if I don't add a proxy, it will generate the credentials with the default (wrong) port:

```bash
auth sign --format=kubernetes --auth-server=https://matheus13.cloud.gravitational.io:443
```

Adding the correct address as `--proxy` makes the credentials have the correct value:

```bash
auth sign --format=kubernetes --auth-server=https://matheus13.cloud.gravitational.io:443 --proxy=http://matheus13.cloud.gravitational.io:11117
```

Is this the expected behavior? 
It feels like it should be able to find the correct address by itself. Should we try pinging the proxy server and retrieving the correct address before using the default?
