### ISSUE TITLE
Simplify OpenSSH client integration with Teleport

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#10488]
If you have many leaf clusters with Teleport today, your `~/.ssh/config` grows in complexity each time you add a cluster. Furthermore, if you use `-J` to directly connect to a leaf cluster, you have to loop over all clusters and log in to each one everytime you add a leaf cluster.

Simplify this process for users so they can add a simple `~/.ssh/config` that can be used across multiple leaf clusters and reduces maintenance complexity.

RFD: https://github.com/gravitational/teleport/pull/11528.

**Comment by r0mant** [comment]
@Joerger As discussed today, when implementing this, let's keep in mind that the behavior we want is not requiring the users to log into each leaf cluster beforehand so they would only need to log into their root cluster once and use that certificate to connect to leaf's proxies. I _think_ it already works like this today because leaf's trust root's CA (similar to proxy jump use-case) but let's double-check, otherwise we might need to update `proxy ssh` command to auto-fetch the cert for leaf is it's not present. I've included a note in the [RFD 62](https://github.com/gravitational/teleport/blob/master/rfd/0062-tsh-proxy-template.md#auto-login).
