### ISSUE TITLE
Update `tsh` to use certificates in SSH agent when connecting to a host

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#10489]
Right now `tsh` will only use certificates in `~/.tsh` when connecting to a host. Update `tsh` to first search in the agent running at `SSH_AUTH_SOCK` then search `~/.tsh` similar to OpenSSH.

This will allow users to use `tsh login --add-keys-to-agent=only` with [yubikey-agent](https://github.com/FiloSottile/yubikey-agent) and never have a certificate on disk.

yubikey-agent should work with macOS, investigate how difficult it would be to contribute Windows support.

**Comment by russjones** [comment]
Normal YubiKey's appear to only have one slot of certs and YubiKey bios no slots. We need to investigate this further.

**Comment by russjones** [comment]
We should fix the issue outlined here as well: https://github.com/gravitational/teleport/issues/11678 to really make single key in yubikey-agent mode work.

**Comment by Joerger** [comment]
I've done some POC work with the [piv-go](https://pkg.go.dev/github.com/go-piv/piv-go@v1.9.0) library to interface with the yubikey PIV smart application available on all Yubikey 5 series.

The good news is that overall, yubikey PIV integration should be pretty straightforward, and I've confirmed that we can use it to sign tls and ssh certs with the Auth server without holding any private keys in disk or memory. 

The main challenge will be reworking our key storage interfaces to plug in yubikey, since we don't have access to the private key in PEM format, which is how we currently interact with private keys in Teleport. I believe the best way forward in this regard will be to rework `lib/client.Key` to export the necessary interfaces for tls/ssh connections (`crypto.PrivateKey`, `ssh.Signer`, etc.) rather than exporting PEM-encoded private keys.

Another issue is that, if I understand correctly, the yubikey won't be usable as an `ssh.agent` key, because the yubikey `PrivateKey` is not one of the supported PEM-encoded keys. I don't fully understand the implications here, but I'm assuming this will affect agent forwarding and therefore proxy recording mode? Maybe we'd need to also utilize `yubikey-agent` for this reason?

There's also a lot of questions for the UX design:
 - Will we provide a flag to tsh like `--yubikey` to signal that we want to use a yubikey key rather than a new generated one?
 - If the user has multiple yubikeys, should they provide the name of the yubikey device, or should we randomly select one?
 - If a user has certificates generated from a yubikey in their `~/.tsh`, should we require that the yubikey still be present when using the certificates (with certificate [attestation](https://docs.yubico.com/hardware/yubikey/yk-5/tech-manual/yk5-apps.html#attestation))?
   - Should we restructure `~/.tsh` to create separate directories for different keys? How would this interact with our `current-profile` logic?

My plan is to continue hacking away at a POC (from scratch :disappointed: took too many shortcuts and broke too many things), so any thoughts, ideas, or concerns would be appreciated as I do that.

**Comment by r0mant** [comment]
@Joerger Good stuff.

> Will we provide a flag to tsh like --yubikey to signal that we want to use a yubikey key rather than a new generated one?

I think it would probably rather be a cluster or a role level setting so it can be enforced by admins.

> If the user has multiple yubikeys, should they provide the name of the yubikey device, or should we randomly select one?

How does our per-session MFA choose the device in this case? Can the user tap any device they have and we would remember it somehow when saving the certs?

> If a user has certificates generated from a yubikey in their ~/.tsh, should we require that the yubikey still be present when using the certificates

Don't you need to have yubikey plugged in in order to be able to use the certs?
