### ISSUE TITLE
Improve UX for moderated sessions

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#10818]
### Description

While testing moderated sessions, I found the lack of feedback a tough UX. Sessions the require a use to join, look like they just hang. 

**What happened**:
```
Teleport > Creating session with ID: 544c73f5-a56d-4160-8f70-4779e3ec433e...

Teleport > User ben-test joined the session.
```

**What you expected to happen**:
We should provide context for which roles need to join. 

```
Creating session with uuid <example-uuid>...
This session requires moderator. Waiting for others to join:
- role: auditor-role x1
```

**Comment by xacrimon** [comment]
Hi, due to the RBAC model of moderated sessions, there's many possible combinations that could exist that would allow a session to start. Would broadcasting `Teleport > "Waiting for required participants...` be sufficient or would we be better of making a list of sections, each containing a list of at least one item that must be satisfied. This feels very clunky to do in the terminal however and eats a lot of space.

**Comment by benarent** [comment]
> Would broadcasting `Teleport > Waiting for required participants...` be sufficient

To start, I think this will be a good place to start.  But we might want to double check with @xinding33

**Comment by xacrimon** [comment]
Yep, we can, as part of #10725 I'm making some changes to the UX, this proposal is also pending review from Xin. Let's move this discussion there.
