### ISSUE TITLE
SSH session stops outputting stdout and stderr

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#10983]

**Comment by Joerger** [comment]
This issue is caused by a race condition between a session party leaving and the session writing to that party. It can be solved by closing the session when a session write error is encountered, or by gracefully handling those errors, or by fixing the underlying race condition (which would require a decent amount of work to refactor the session writer).

However, this issue is fixed in `v9` due to the changes made for moderated sessions. For `pre-v9` versions, we could implement one or both of the first two solutions if needed.
