### ISSUE TITLE
Can I use teleport with automation tools like fabric?

### ISSUE THREAD

**Issue by enm10k** [gravitational/teleport#1114]
I'd like to use teleport with automation tools like [fabric](http://www.fabfile.org/).
Did anyone already try it?

**Comment by nikatjef** [comment]
I have not been able to get Fabric to work reliably, but I have gotten it to work with Ansible. 

Ansible has the option to override the SSH mechanism (Paramiko by default) to use the system's SSH client.  This works fine with the recent 2.2 patch making the SSH and SCP aliases for Teleport.

Fabric also uses Paramiko, but I have been unable to figure out how to override it to use the system's SSH client...  Having said that, Paramiko does support non-standard keys and non-standard ports, so it can be made to work reliably with Teleport, I am just not there yet.

If you feel comfortable with your Fabric Fu, look at the Teleport documentation for using the regular SSH client to connect to Teleport.  It provides enough information about configuring the SSH client, that you should be able to figure out how to make Fabric / Ansible work using the Paramiko SSH code.

**Comment by kontsevoy** [comment]
@enm10k as nikatjef said, Fabirc uses its own SSH implementation based on Python's Paramico library, but they make a good effort of playing nice with SSH standards.

I would recommend looking at
1. [Native SSH config](http://docs.fabfile.org/en/1.13/usage/execution.html#ssh-config) first. See `ProxyCommand` section which should cover configuring Paramico to use an SSH proxy instead of connecting to nodes directly (proxy is mandatory in Teleport world).
2. [gateway option](http://docs.fabfile.org/en/1.13/usage/env.html#gateway) to tell Paramico to use a Teleport proxy to connect.

**Comment by IgorBerman** [comment]
A bit late for the party, but have somebody managed to make fabric work with teleport?
my ssh works seamlessly with teleport with ProxyCommand, however fabric can't make it
I'm getting following error:
Unexpected error: (<class 'paramiko.ssh_exception.PasswordRequiredException'>, PasswordRequiredException('Private key file is encrypted'), <traceback object at 0x7f97b8158b00>)
private key file is part of teleport keys most probably(judging from debug log)

so i've tried to configure connection properties in fabric script with port (3022) and user that teleport uses, but same exception pops
it seems that teleport uses it's own private keys(given I have following 2 under ssh config)
IdentityFile "~/.tsh/keys/teleport.<domain>/<user>"
CertificateFile "~/.tsh/keys/teleport.<domain>/<user>-ssh/teleport.<domain>-cert.pub"

and it's not clear how to configure access to them if they encrypted
any advice will be appreciated

**Comment by schenkp1** [comment]
Is there any update on how to make fabric work with teleport nodes?
