### ISSUE TITLE
Support of db_service config in teleport-cluster helm chart

### ISSUE THREAD

**Issue by ligol** [gravitational/teleport#11157]
### What
I'd like the possibility for the teleport-cluster helm chart to expose value allowing it to configure the db_service.

### How
By replicating what have been done in the teleport-kube-agent chart who now support db_service for aws and direct config.

I've created a PR doing it at #11156

**Comment by hugoShaka** [comment]
App, database and kube access are handled by the `teleport-kube-agent` chart, which is different from the `teleport-cluster` chart. The recommended pattern is to deploy both `teleport-cluster` and `teleport-kube-agent` in the same cluster if you need to host the Teleport cluster and have database access in this same cluster.

Configuring `app_service`, `db_service` and `kube_service` in the `teleport-cluster` chart is not supported out of the box because we strongly encourage users to split responsibilities between `teleport-cluster` and `teleport-kube-agent`. Splitting between the core cluster and the agents provides a better availability, scalability and the pattern allows multiple kubernetes clusters to connect to a single teleport-cluster with the same values. 

In the `teleport-kube-agent` chart you can configure `db_service` through the following parameters:
- [`databases`](https://goteleport.com/docs/reference/helm-reference/teleport-kube-agent/#databases) for statically declared applications
- [`dbResources`](https://goteleport.com/docs/reference/helm-reference/teleport-kube-agent/#dbresources) to watch for dynamically declared applications 

If you still want to have the `teleport-cluster` chart run `app_service` (strongly discouraged) we suggest you use the `teleport-cluster` chart in [custom mode](https://goteleport.com/docs/deploy-a-cluster/helm-deployments/custom/) (you provide your own config to the chart).
