### ISSUE TITLE
Proposal: do not set TTL on heartbeat

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1118]
## Description

Our auth servers, proxies, reverse tunnels and nodes all heartbeat back to the presence service (Auth server + backend) and currently get removed from the database when the TTL expires.

This behavior crates problems in real world scenarios, because when heartbeat fails we loose present information about the entry and it disappears from the node list. In case if the node has missed heartbeat because of the network latency, it is possible we would still be able to connect, but expired TTL prevents us from seeing the node.

In addition to that we are forced to heartbeat more often than necessary - putting more load on the system.

## Proposed solution

* Keep heartbeats, but remove TTL with expiration time. Keep all entries persistent.
* Update "LastHeartbeat" property with every heartbeat instead. 
* Use this property to display node as offline in UI and CLI
* Introduce `tctl delete nodes/<node>` to allow users to clean up stale nodes, auth servers and other entries.

**Comment by russjones** [comment]
"Keep all entries persistent" By this you mean just remove the TTL, not that we are keeping every heartbeat in the database right and that would very quickly fill up the backend.

Also, what are your thoughts about not persisting this information at all? Instead just keeping it in memory and reconstructing it each time Teleport starts?

**Comment by klizhentas** [comment]
@russjones Ev has a couple of ideas how to balance it out, he'll post it soon.

**Comment by kontsevoy** [comment]
Here are the notes from our discussion earlier (perhaps update the top-level description to reflect them?)

## Code changes

* When a node skips 3 pings (or whatever is the current deault) it needs to go into the "offline state". 
* Introduce "node linger TTL". It's a maximum time a node can spend in "offline state" before being automatically removed from the cluster.

## UX changes

* `tsh ls` should not display offline nodes by default.
* `tsh ls --all` should display both offline and offline nodes. Careful here: the CLI parsing library we use does not allow this syntax by default, i.e. `--all` should be an argument and a flag.
* Web UI should not show offline nodes by default.

Maybe to make UI/UX changes minimal our implementation of GetNodes() should take an argument defaulting to "online only"? This way only minimal code changes will be required and they will be caught by the compiler.

## Lingering TTL

Lets not expose it to Teleport users in any form (we have plenty of other TTLs that need documenting / configuration, maybe we'll do them all at once in the future). 

The default should be set to `1 hour`.

## Concerns

I remember we have a node name resolution code. This code would need to be reviewed. Because it is now possible to have two nodes with identical names (one online another offline). Basically that code needs to exclude offline nodes from the consideration. In that sense making `auth_API.GetNodes()` call return online-only by-default (just like for the UI) will help to make this change very lightweight.

**Comment by klizhentas** [comment]
I'm going to assign myself as this came up in prod. I will fix it and will also fix it for infamous `authservers.json` that has the same problem: if auth servers miss several heartbeats, it gets refreshed too aggressively and looses many entries as a result of this.

**Comment by benarent** [comment]
This recently came up again, I'm going to close so we have a more concise ticket. The updated ticket is referenced above.
