### ISSUE TITLE
Teleport logs

### ISSUE THREAD

**Issue by papiveron** [gravitational/teleport#1119]
Hi,

Please, I just one to understand teleport logs. 

I'm using teleport version 2.2.3, and in my ssh events logs I don't have informations described in the Admin Manual.
As example :

> {"event":"resize","login":"root","ms":-279,"namespace":"default","offset":0,"sid":"0c5fba22-6259-11e7-9519-0a66db607aed","size":"224:59","time":"2017-07-06T14:40:45.721Z","user":"eugene"}
> {"event":"session.leave","ms":6572,"namespace":"default","offset":0,"server_id":"51340bdb-3837-45f6-8aa9-5056b4527748","sid":"0c5fba22-6259-11e7-9519-0a66db607aed","time":"2017-07-06T14:40:52.572Z","user":"eugene"}
> {"event":"session.end","ms":6580,"namespace":"default","offset":0,"sid":"0c5fba22-6259-11e7-9519-0a66db607aed","time":"2017-07-06T14:40:52.58Z","user":"eugene"}
> {"bytes":10,"event":"print","ms":-405,"offset":0,"time":"2017-07-06T14:40:52.595Z"}
> bytes":1,"event":"print","ms":5866,"offset":51,"time":"2017-07-06T14:40:23.866Z"}
> 

I can see some missing keys in the logs json objects. Why there is no address entry here as described in the documentation?
 
I'm also looking for where to find  errors logs, for example when a user tries to log in a node with a non valid login (e.g a login which does not exist on the target node's system) and gets a permission denied in the client/proxy side, where is that error recorded on the auth server? Is the error recorded directly on the target node?
I've look even in the **messages** and **auth.log** files, but there is no login error trace....

Regards,
Eugène NG

**Comment by nikatjef** [comment]
Okay, so that is your session log, which shows the individual node login sessions.  The very first line should include both the local and remote addresses as well as the username and login of the user.

Login logs are located in the daily log, usually under teleport/log and they will be called something like 'YYYY-MM-DD-HH.mm:00:00:00.log'.

You can adjust the log level by changing the severity entry in the teleport configuration file.  IIRC, you have to have a severity higher than 'INFO' to see failures.

**Comment by kontsevoy** [comment]
@nikatjef thanks, that is correct.
