### ISSUE TITLE
policy/v1beta1 PodSecurityPolicy is deprecated

### ISSUE THREAD

**Issue by FakeSummer** [gravitational/teleport#11287]
### Description

**What happened**:
On a helm install with the `teleport-cluster` chart, I get the following warning:
`policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+`

**What you expected to happen**:
No warning on helm installation.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Fresh install of `teleport-cluster` on a GKE cluster via helm
2. Warning will populate but install should complete successfully (with a good config)

### Server Details
- Teleport version (run `teleport version`): v9.0.1
- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): GCP

Other details should be irrelevant, this just requires an update of `PodSecurityPolicy` from `policy/v1beta1` to `policy/v1`.

Thanks!

**Comment by webvictim** [comment]
> Other details should be irrelevant, this just requires an update of PodSecurityPolicy from policy/v1beta1 to policy/v1.

Unfortunately it's not _quite_ that simple as `PodSecurityPolicy` is being fully deprecated and replaced with the PodSecurity admission controller instead, which isn't an enabled feature gate by default [until Kubernetes 1.23](https://kubernetes.io/blog/2021/12/07/kubernetes-1-23-release-announcement/#podsecurity-graduates-to-beta). Given that we need to keep backwards compatibility with older versions, this is likely going to need some special casing based on the target cluster's supported features.

**Comment by yanntoque** [comment]
There is a linked issue as described below : 

# Expected behavior:

When running `make lint-helm test-helm` at the root the expected behavior is that all tests should pass.

# Current behavior:

When running `make lint-helm test-helm` at the root, the lint test has failure due to the fact that there is a warning message concerning a deprecated apiVersion for PodSecurityPolicy 

#### Link(s) to logs

##### ``make lint-helm test-helm`` lint test, Fails :
```
Using values from 'examples/chart/teleport-cluster/.lint/acme-off.yaml': ==> Linting examples/chart/teleport-cluster
[WARNING] templates/psp.yaml: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+

Error: 1 chart(s) linted, 1 chart(s) failed
make: *** [lint-helm] Error 1
```

As `--strict` is used in this [line](https://github.com/gravitational/teleport/blob/8a4ee05dbb2d7b21a7869955df39b658332065ca/Makefile#L734) `helm lint --strict $${CHART} -f $${VALUES} ||  exit 1;` from the [Makefile](https://github.com/gravitational/teleport/blob/master/Makefile)  : 
> --strict                   fail on lint warnings

**Comment by mnordstr** [comment]
So now that we are running 1.25, is there any way to get teleport on the cluster?
