### ISSUE TITLE
Upgrading kube agent causes kubectl to hang

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#11546]
### Description

**What happened**:

After a somewhat automated upgrade of the teleport-kube-agent chart, access to the cluster was no longer possible.

An action such as `kubectl exec` would just hang indefinitely.

Teleport logs included this error:

```
 2022-03-29T16:18:48Z INFO [KUBERNETE] Failed to ping web proxy "example.teleport.sh:3024" addr: Get "https://example.teleport.sh:3024/webapi/find": tls: first record does not look like a TLS handshake leaseID:1 target:example.teleport.sh:3024 reversetunnel/agent.go:273
```

**What you expected to happen**:

A version upgrade should not cause this severe of an issue without warning about version mismatches.

With breakage this bad, the agent should issue loud warnings and/or refuse to start due to version mismatch.

This, combined with issues such as the apt repository not housing multiple versions of the teleport package, this situation will likely affect a large number of users. Last week's script to install the teleport agent may no longer work.

A better long term solution would be to make agents and other clients of teleport backwards compatible with at least one major version of teleport to avoid this type of situation and make the entire upgrade process go much more smoothly.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Deploy a 9.0.2 teleport-kube-agent helm release to an 8.3.5 backend.
2. Observe the teleport-kube-agent pod running and reporting healthy.
3. Try to access it and observe `kubectl` failures.

### Server Details
- Teleport version (run `teleport version`): Teleport Cloud 8.3.5 enterprise

### Teleport Agent Details
- teleport/teleport-kube-agent helm chart version 9.0.2 (no version override)

gz#4583

**Comment by webvictim** [comment]
Another Cloud prospect was also hit by this same issue and it was not at all obvious what the issue was. Seeing this one actually caused me to go and investigate and subsequently realise they had the exact same symptoms. They also reported "...when running `kubectl exec -it` it hangs".

We definitely need to maintain and test compatibility for an `n-1` version of the backend when we're pushing automatic client updates to repos. It's causing a lot of confusion and wasted time for people who are just doing what our instructions tell them to do, especially with Cloud when the deployed backend is often lagging 2-3 weeks behind the latest released update. 

Either we need to give the clients enough knowledge to realise that they're not going to work with the backend version and crash out with a "run a lower version" error, or we need to gracefully downgrade behaviour to allow them to work properly until the backend is updated to match.

**Comment by webvictim** [comment]
The workaround for anyone who is affected by this is to downgrade your `teleport-kube-agent` version using `teleportVersionOverride: 8.3.5` in your chart values, then run a `helm upgrade` to redeploy.

**Comment by highb** [comment]
Thanks for documenting this issue. We're also encountering it after upgrading to Teleport Cloud (running 8.3.6). I made an apparently foolish assumption that the newer 9.0.3 kube agent would be able to talk to the older backend on Cloud. I'll work on pushing out the `teleportVersionOverride` update today.
