### ISSUE TITLE
teleport behing haproxy

### ISSUE THREAD

**Issue by nuved** [gravitational/teleport#1164]
I can't access to teleport proxy (web-ui) from behind  haproxy. 

I got this error:
`2017/07/23 12:35:46 http: TLS handshake error from 172.16.77.110:27916: tls: first record does not look like a TLS handshake`

I try two ways, SSL Termination and SSL Pass-Through! 
in first way, I remove these lines in teleport

```
https_key_file:
https_cert_file:
```
in second way, 
  https_key_file: /etc/letsencrypt/live/teleport.site/privkey.pem
  https_cert_file: /etc/letsencrypt/live/teleport.site/cert.pem

But it doesn't change anything :(

**Comment by kontsevoy** [comment]
Teleport _awlays_ uses HTTPS so it must be SSL pass-through. Even if you remove `https_xxx_file` settings Teleport will automatically generate self-signed HTTPS certificate. The error indicates that you're connecting to a non-HTTPS port, by the way. So:

* Make sure you're using SSL pass-through
* Make sure the ports are correct. Teleport proxy uses 3080 for HTTSP. See others [here](http://gravitational.com/teleport/docs/2.0/admin-guide/#teleport-daemon) (scroll down to "ports").

Otherwise, troubleshoot your HAProxy setup.
