### ISSUE TITLE
[Onboarding] Remove name requirement from https://goteleport.com/signup/

### ISSUE THREAD

**Issue by xinding33** [gravitational/teleport#11674]
Our product targets security-minded folks. Security and privacy often go hand-in-hand. Asking for a full name will often yield two outcomes:
1. User provides bogus name
2. User doesn't complete the signup

We have fairly little to gain from asking for a name so I think we should just remove that requirement.

<img width="787" alt="image" src="https://user-images.githubusercontent.com/24904723/161316906-679c6d93-76f8-4857-b419-e38c2efa52f8.png">

**Comment by anadeliafadeev** [comment]
No objections from Marketing on this. We sometimes use first name in emails but the data we get from here, as you mentioned, tends to include fake names. 

Before we move forward with the change, I want to make sure that @TravisGary have reviewed this, as first name is a required field in Salesforce to create a record so he needs to udpate the field mapping so that we pass on `[[unknown]]` as the value for first name. This not only will allow for the lead record to be created but it is also the value we use to signal to Clearbit it can enrich that field.

cc @rlutsky for visibility

**Comment by xinding33** [comment]
@anadeliafadeev awesome, thanks for your input. I'll wait for Travis to respond.

**Comment by TravisGary** [comment]
I think we may be OK already.

Looking at the query we already send [[Unknown]] if first or last name is missing

https://github.com/gravitational/cloud/blob/master/db/exporting/src/usage.sql#L112

**Comment by TravisGary** [comment]
Also I love the idea of only requiring a email, its the shortest possible form and as someone who fills out a lot of these I love the short ones.
