### ISSUE TITLE
Add --data-dir flag to `teleport configure`

### ISSUE THREAD

**Issue by xinding33** [gravitational/teleport#11739]
In our "manual" resource joining instructions, we ask users to run `teleport start` with a bunch of flags. This can fail in multiple ways, for example:

1. Lack of `sudo` because we write to `/etc` by default
2. Error due to the fact that user tried setting up a cluster beforehand

Almost all production deployments of Teleport heavily relies on `teleport.yaml` file. We can introduce this concept in the onboarding while simultaneously eliminating an entire class of under-tested use cases with regards to `teleport start` by introducing the `--data-dir` flag to `teleport configure`.

Related follow-up work:

**Comment by mcbattirola** [comment]
Here are the flags we currently use in the web UI wizards for `teleport start` vs flags supported by `teleport configure`

### Add Server

```bash
teleport start --roles=node --token=cf7b5bbe32c2103abf32821c7be3b0a5 --auth-server=localhost:8080
```

Flags missing on ``configure``

- --roles (already added on [PR](https://github.com/gravitational/teleport/pull/11766))
- --token (already added on [PR](https://github.com/gravitational/teleport/pull/11766))
- --auth-server (already added on [PR](https://github.com/gravitational/teleport/pull/11766))

### Add App

```bash
teleport start --roles=app --app-name=[example-app] --app-uri=http://localhost/ --token=e65d32c0581c4a0030f31aa54b95a8ca --auth-server=localhost:8080
```

Flags missing on `configure` 

- --roles (already added on [PR](https://github.com/gravitational/teleport/pull/11766))
- --app-name (already added on [PR](https://github.com/gravitational/teleport/pull/11766))
- --app-uri (already added on [PR](https://github.com/gravitational/teleport/pull/11766))
- --token (already added on [PR](https://github.com/gravitational/teleport/pull/11766))
- --auth-server (already added on [PR](https://github.com/gravitational/teleport/pull/11766))

### Add DB

```bash
teleport db start --token=d8fdab74df9aba9d469c4a7382a67d06 --auth-server=localhost:8080 --name=[db-name] --protocol=sqlserver --uri=[uri] --ad-keytab-file=/path/to/teleport.keytab --ad-domain=EXAMPLE.COM --ad-spn=MSSQLSvc/sqlserver.example.com:1433 --ca-cert=[instance-ca-filepath] --gcp-project-id=[project-id] --gcp-instance-id=[instance-id]
```

(params vary based on DB type, this is the one that uses more params, AWS SQL Server)

There is a CLI command specific for configuring db: `teleport db configure create` 

This command covers the flags:

- protocol
- token

Which are the same values we prefill in the `teleport start`. Since the other params the user is expected to edit the command, I think it is okay to tell them to edit the configuration file instead.

One problem though is that the result of `teleport db configure create --protocol=sqlserver --name=mysqlserverdb --uri=localhost:3080` doesn't include an `ad` section to the config generated, which AFAIK is necessary for adding. We can create an issue to improve this.

I think that the flags implemented on https://github.com/gravitational/teleport/pull/11766 are enough to start using `teleport configure` in the web UI. 

Thoughts?

cc @xinding33 @zmb3

**Comment by xinding33** [comment]
Agreed, let's move forward with what we have and revisit DB getting started later. I think we should also follow this up with some flags for vanilla getting started experiences. For example, IMO, the ideal experience would be something like `teleport configure --server` for setting up a server node and `teleport configure --app` for an application. The flags can be different of course but the experience is:

1. User doesn't really care about customizing and they just want a quick command to configure everything to reasonable defaults
2. User runs `teleport configure --whatever` where `--whatever` is the type of resource they're trying to add
3. User runs `teleport start` and they're done, they can now access their new resource

**Comment by mcbattirola** [comment]
backports:

- [ ] v9
- [ ] v8
