### ISSUE TITLE
Automatically test external links in docs on a regular basis

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#11943]
As #11940 is removing external link checking on every PR due to false positives, we should come up with some other way to test external links in the docs on a semi-regular basis (I propose doing so daily).

Couple of options: 
1) Some kind of cron job in Drone/GCB to run nightly and alert somewhere on failures
2) I think we already have an external service that monitors our website as a whole and reports back on SEO and other factors. Maybe this could also check links in the docs to make sure they resolve correctly?

**Comment by ptgott** [comment]
I'm going to work on nudging this toward a more specific plan in the next sprint. In the meantime, CCing @C-STYR and @jeffgaynor—it'd be great to get your thoughts on this. Thanks!

**Comment by ptgott** [comment]
I've talked to @C-STYR and @jeffgaynor on the Web team. We are currently using [Semrush](https://www.semrush.com/) to manually check for 404ing external links on our production docs site on a weekly basis. The Web team will look for ways to check external links in a more automated fashion and for pre-production changes, but we're treating this as a low-priority issue since we have an existing solution.
