### ISSUE TITLE
Improve error messages in advanced search

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#12193]
### Description

Would be cool if we can catch some system messages and convert description to more actionable guidance:

If something is undefined:

<img width="1275" alt="Screen Shot 2022-04-22 at 3 58 46 PM" src="https://user-images.githubusercontent.com/13717/164815184-d5367ad2-4892-40cf-9b82-7bb047fe28ca.png">

We can add, "Name is undefined, check syntax [link to docs] for available labels".

Syntax errors:

<img width="537" alt="Screen Shot 2022-04-22 at 4 00 03 PM" src="https://user-images.githubusercontent.com/13717/164815262-5ceb6032-184f-4972-b3fb-42db7fab9fff.png">

We should probably convert to:

"Failed to parse the expression. Expected operand, found EOF. Check syntax [link to docs]"

**Comment by webvictim** [comment]
We should also use the `labels["key"]` style in our examples rather than `labels.key` - this makes it easier to work with labels that contain dots, dashes, etc - for example:

`labels.teleport.dev/windows_domain` doesn't work:
![image](https://user-images.githubusercontent.com/897821/165167471-27f4ef33-ee30-4998-a964-3f062a0a998f.png)

`labels["teleport.dev/windows_domain"]` does:
![image](https://user-images.githubusercontent.com/897821/165167480-1e5e379b-2fb3-43a5-af4d-241e67631386.png)
