### ISSUE TITLE
Better support for regex in OIDC/SAML connectors.

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#12417]
What would you like Teleport to do?

When using an OIDC/SAML connector like Okta you can map users to various roles if they are specifically defined. You cannot leverage any sort of regex to filter to match roles with Okta traits.

You'll get an error like this:

`"error": "special characters are not allowed in resource names, please use name composed only from characters, hyphens, dots, and plus signs: \"/roles/(a*)/params\""`

or something similar.

What problem does this solve?

Allows orgs to map Okta users to multiple roles even if they are only in 1 Okta group.

If a workaround exists, please include it.

You have to create multiple Okta groups, etc to map 1-to-1 roles.

Some similar issues #5267

**Comment by russjones** [comment]
https://github.com/gravitational/teleport/pull/14977

**Comment by programmerq** [comment]
I think the ask is for the ability to use regex or globbing to determine the list of existing roles to utilize.

For example, if a cluster has the following roles:

```
dev1, dev2, dev3, ... devn, prod1, prod2, ... prodn, stage1, stage2, ... stagen
```

Rather than listing out all the possible matching roles in the connector, the following would be preferable:

```
    - {claim: "project", value: "alldev", roles: ["dev.*"]}
    - {claim: "project", value: "somestage", roles: ["^stage[0-5]$"]}
```

Currently, the list of existing roles is not considered at all when calculating the mapping, and the claim is expected to be a list of specific roles that currently exist.

**Comment by russjones** [comment]
@programmerq I don't think we want to support this. Roles may change in the future and if we supported regexp in `roles` this could change RBAC behavior unexpectedly.
