### ISSUE TITLE
Teleport Should Control Storage Backend Options via `values.yaml`

### ISSUE THREAD

**Issue by Richard-Barrett** [gravitational/teleport#12415]
What would you like Teleport to do?
If the storage backend is selected:

- [Storage Backend Types](https://goteleport.com/docs/setup/reference/backends/)
- Storage Parameters should be controlled via options and/or parameters similar to the options available to the storage backend type
- For example, S3 backend types support encryption options as well as lifecycle management options, we should be able to control such options if the backend type is specified as S3

What problem does this solve?
This solves an issue whereby which storage backend configuration settings can be controlled via `teleport` instead of using an outside resource/tool such as terraform with the `aws` provider. It allows users and organizations to use teleport to control bucket parameters and/or storage parameters inline with the `values.yaml` file when specifying storage backend type.

If a workaround exists, please include it.
No workaround

**Comment by r0mant** [comment]
@Richard-Barrett Is this about Helm's values.yaml or something else? I assumed so but it isn't clear from the ticket description.

**Comment by wadells** [comment]
> For example, S3 backend types support encryption options as well as lifecycle management options, we should be able to control such options if the backend type is specified as S3

In order to configure these, the Teleport's IAM policy will need to be broadened to have the appropriate permissions to govern encryption options or lifecycle management policies.

There is a tension herein: We can provide easier setup UX by requesting users grant Teleport increasingly broad IAM permissions and allowing it to self manage resources, but we sacrifice some security.  E.g if Teleport was compromised such that a retention policy is relevant for forensics, do we _want_ Teleport to be able to edit bucket retention policies?  Having the backing infrastructure managed by a separate process is an advantage in this case.

**Comment by hugoShaka** [comment]
Thank you for opening the feature request and giving us feedback :)

Implementing this feature would require either Helm to provision the AWS infrastructure, or Teleport to do it. It does not feel like Helm is a good tool from provisioning AWS infra, and we are not okay with the security implications of allowing Teleport to manage those settings.

Teleport creating the s3 bucket is a quality of life feature but not a requirement. If you have security constraints requiring you to configure bucket encryption we recommend you to create and manage the bucket outside of Teleport, this setup will be after and more likely to meet your security considerations.

[We'll update our documentation](https://github.com/gravitational/teleport/issues/19974) to mention the bucket can and should be configured outside of Teleport if you're in a position where you need bucket encryption/lifecycle management.
