### ISSUE TITLE
Port forwarding doesn't work for kubernetes

### ISSUE THREAD

**Issue by TheAnachronism** [gravitational/teleport#12459]
Expected behaviour:
If I try to port-forward something with let's say `kubectl port-forward my-pod 8080` my local port 8080 should get forwarded to the port 8080 on that pod.

Current behaviour:
I get the error `error: error upgrading connection: missing parameter MaxLeases`. This is the case for port-forwarding to a pod or to a service.

Bug details:
- Teleport version
  - client: Teleport v9.2.0 git:v9.2.0-0-gc7db54496 go1.17.9
  - server/cluster inside kubernetes: Teleport v9.2.0 git:v9.2.0-0-gc7db54496 go1.17.9
- Recreation steps
  - Installing teleport with helm inside kubernetes
  - Log in on a client and try to port-forward something

Found out a bit later:
The same behaviour is if I try to create an interactive shell to a pod, like this: `kubectl exec -it my-pod -- bash`.

**Comment by stereobutter** [comment]
I experience a similar issue. The error message I get from something like `kubectl port-forward my-pod 8080` is just `error: error upgrading connection: error upgrading connection`. 

The issue appears to be due to teleport v9.2 and/or a conflict between v9.1 and v9.2. In my setup when I use v9.1 for the auth+proxy server and v9.2 with the other node that I want to expose k8s from, I get the issue above. When using v9.1 for both everything works as expected.

**Comment by TheAnachronism** [comment]
OK, O haven't tried downgrading yet but I guess I'll go back to 9.1.3 until this issue is resolved.
I already had a hunch that it was version 9.2.0 as I just upgraded today.

**Comment by zmb3** [comment]
@xacrimon may be related to https://github.com/gravitational/teleport/pull/12275/files#diff-cdfe0b66f7090f9a5e0759d6cce323f7dde1ee1f0f49402d6a7652cd91b69430R910

**Comment by TheAnachronism** [comment]
OK, I just verified on version 9.2.1, and it's fixed.
Thank you very much for the swift response and fix.
👍
