### ISSUE TITLE
tsh status doesn't respect TELEPORT_CLUSTER env var

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#12479]
Expected behavior:

`tsh status` takes the `TELEPORT_CLUSTER` env var into account when reporting the current cluster.

Current behavior:

`tsh status` seems to report the `cluster` value set in the profile YAML file.

`tsh status` might not be the only affected command, though other commands like `tsh ls` or `tsh db ls` generally take `TELEPORT_CLUSTER` into account. 

Bug details:
- Teleport version: running `tsh` from master (`9f2f7bf52`).
- Recreation steps:
   * In one shell session execute `tsh login --proxy=root-cluster && eval $(tsh env)`.
   * In another shell session do `tsh login leaf-cluster`.
   * `tsh status` in the first shell session reports the cluster as `leaf-cluster`, while I'd expect it to report `root-cluster`.

**Comment by ravicious** [comment]
We ran into this in Teleport Connect where we use the same env vars as `tsh env` to pin a local shell session to a specific Teleport cluster (as described here https://github.com/gravitational/teleport/issues/3089#issuecomment-784635126). The user can change their current identity with the selector in the upper right corner, so it made sense for the terminals to point to the same cluster when switching between identities.

**Comment by GavinFrazar** [comment]
I noticed that while `tsh ls` does take the env var into account, somewhere else it's using the profile value instead of the env var for some certificate thing.

Steps to reproduce this behavior:

1. set TELEPORT_CLUSTER to some stub name like "foobar"
2. run `tsh ls`, notice it says "ERROR: cluster foobar not found"
3. change the cluster name in your current profile to something nonsensical too, like "cluster: baz"
4. run `tsh ls` again, notice instead of getting "cluster not found", you get a certificate error.
5. rerun with `tsh ls --insecure` and get an error about foobar not found again, though this one is slightly different from the error message in step 2.

Very interesting! There's a lot to unwind here.

**Comment by GavinFrazar** [comment]
The more I think about it, the more I want to say this isn't totally a bug. `$ tsh status` displays profile status information from the ~/.tsh directory, not environment info. On my local branch I've changed this to respect the TELEPORT_CLUSTER env var, and to print "(TELEPORT_CLUSTER)" next to the cluster when the cluster name is coming from the env var. Here's an example session, where I have cluster1 as a root cluster and cluster2 as a leaf cluster:
```
$ tsh login --insecure --proxy=proxy1.pubaddr.local.gd:3080 --user=gavin
Enter password for Teleport user gavin:
WARNING: You are using insecure connection to SSH proxy https://proxy1.pubaddr.local.gd:3080
> Profile URL:        https://proxy1.pubaddr.local.gd:3080
  Logged in as:       gavin
  Cluster:            cluster1
  Roles:              access, auditor, editor
  Logins:             gavin, -teleport-internal-join
  Kubernetes:         disabled
  Valid until:        2022-05-29 06:05:30 -0700 PDT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

$ eval $(tsh env)
$ env | rg TELEPORT
TELEPORT_PROXY=proxy1.pubaddr.local.gd:3080
TELEPORT_CLUSTER=cluster1
$ tsh status
> Profile URL:        https://proxy1.pubaddr.local.gd:3080
  Logged in as:       gavin
  Cluster:            cluster1
  Roles:              access, auditor, editor
  Logins:             gavin, -teleport-internal-join
  Kubernetes:         disabled
  Valid until:        2022-05-29 06:05:30 -0700 PDT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

$ tsh login --insecure cluster2
> Profile URL:        https://proxy1.pubaddr.local.gd:3080
  Logged in as:       gavin
  Cluster:            cluster2
  Roles:              access, auditor, editor
  Logins:             gavin, -teleport-internal-join
  Kubernetes:         disabled
  Valid until:        2022-05-29 06:05:30 -0700 PDT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

$ tsh status
> Profile URL:        https://proxy1.pubaddr.local.gd:3080
  Logged in as:       gavin
  Cluster:            cluster1 (TELEPORT_CLUSTER)
  Roles:              access, auditor, editor
  Logins:             gavin, -teleport-internal-join
  Kubernetes:         disabled
  Valid until:        2022-05-29 06:05:30 -0700 PDT [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

$ cat ~/.tsh/proxy1.pubaddr.local.gd.yaml 
web_proxy_addr: proxy1.pubaddr.local.gd:3080
ssh_proxy_addr: proxy1.pubaddr.local.gd:3023
postgres_proxy_addr: proxy1.pubaddr.local.gd:3080
user: gavin
cluster: cluster2
dir: ""
```

It's a little odd to login to cluster2, which then prints status showing I'm logged into cluster2, but then immediately after `$ tsh status` tells me I'm in cluster1 due to my env var. I could change the behavior of `$ tsh login` to display the env var if set as well, but the UX is a little surprising either way imo.

Here's a suggestion, let me know what you think @ravicious @r0mant : We make `$ tsh status` display profile info as it does now, but we additionally show if TELEPORT_PROXY is shadowing ~/.tsh/current-profile or if TELEPORT_CLUSTER is shadowing the cluster set in the active profile.

**Comment by ravicious** [comment]
* Conceptually, I think `tsh status` should answer the following question: given the state of my session, which profile and cluster are tsh commands going to use by default in this session?
* Teleport Connect uses env vars returned by `tsh env` to make sure that a local shell tab that the user has opened always stays pinned to that specific cluster and proxy. Well, at least until the user decides to modify the env vars themself, but then all bets are off.
* As far as I understand, you propose adding `(TELEPORT_CLUSTER)` next to the cluster in `tsh status` only if `TELEPORT_CLUSTER` is not equal to what's in `current-profile`.
   * I think we should always include this information in the output if `TELEPORT_CLUSTER` is set, not only when `TELEPORT_CLUSTER` doesn't match the cluster from `current-profile`.
      * This will also help Teleport Connect users, which do not set `TELEPORT_CLUSTER` by themselves. If they type `tsh status` in the local shell tab, they'll always know that this session is impacted by `TELEPORT_CLUSTER`. Otherwise they'd have to login to a different cluster first to discover that.
* I can see how the output of `tsh login` might be confusing. In my opinion, if `tsh env` is set and you do `tsh login` to change clusters, that session should keep using the cluster set by `tsh env`.
* If we take your suggestion, which I really like, and make `tsh status` report that the current cluster is set by `TELEPORT_CLUSTER`, then the output from `tsh login` should report that as well to signal that the current cluster remains set by `TELEPORT_CLUSTER`.
* Then we could make `tsh login` output additional warn messages informing the user that the current profile in this session remains affected by the env variables. So `tsh login` would change the global context by changing files on disk, but the current session keeps prioritizing the env vars.
   * This makes sense to me because then `tsh status` always does the same thing, but in situations where `tsh login` might not have the effect I'd usually expect it to have, we inform the user about that.

How do you like this idea?
