### ISSUE TITLE
Helm Chart ability to configure ingress controllers in place of AWS Load Balancers

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#12533]
What would you like Teleport to do?
Customer have requested the ability to turn off AWS Load Balancer configuration for AWS deployments and instead replace the LBs with an ingress controller such as `ingress-nginx`

What problem does this solve?
Allowing customers more out-of-the-box config modularity for non-custom charts.

If a workaround exists, please include it.
Customers currently have to use custom charts and manually configure all the other components for AWS just to swap out the AWS LBs for ingress-nginx.

gz#5080

**Comment by scottpgallagher** [comment]
Something to consider for you when you add ingress support. Most ingresses assume they do the TLS and the backend is not using TLS. If it is using TLS  you have to tell the ingress controller what CA / Cert the service is using that it should trust. That configuration however - to my knowledge - is not standardized and depends on what ingress controller is used.

**Comment by hugoShaka** [comment]
As far as I understand some (most ?) teleport features won't work if Teleport does not terminate TLS itself. It needs to validate client TLS certs. Maybe @webvictim can confirm ?

As highlighted by @scottpgallagher , Kubernetes ingresses + upstream TLS is a mess, "Kubernetes is cloud-agnostic" becomes a myth as soon as we're dealing with network. Here's a non exhaustive list of the different cloud providers/ingress controllers

| Controller | Default Behaviour | backend-HTTPS annotation | supports backend cert validation | note |
| --- | --- | --- | --- | --- |
| AWS LB | HTTP-only | `alb.ingress.kubernetes.io/backend-protocol: HTTPS` | No ? | [Source](https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#backend-protocol) |
| GKE ingress-controller | HTTP-only | `cloud.google.com/app-protocols: '{"my-https-port":"HTTPS","my-http-port":"HTTP"}'` | No | The service type should be different whether CNLB is used. [Source](https://cloud.google.com/kubernetes-engine/docs/concepts/ingress-xlb#https_tls_between_load_balancer_and_your_application) |
| Nginx ingress controller | HTTP-only | `nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"` | Yes, [with the `proxy-ssl-*` annotations](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#backend-certificate-authentication) | |
| Azure thing | HTTP-only | [`appgw.ingress.kubernetes.io/backend-protocol`](https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#backend-protocol) | Yes but [requires loading cert in their cloud gateway service](https://azure.github.io/application-gateway-kubernetes-ingress/annotations/#appgw-trusted-root-certificate) | [Source](https://azure.github.io/application-gateway-kubernetes-ingress/annotations/) |

The new Gateway API does not seem to standardize things. I have not looked at more custom ingress-controller/api gateways like contour, kong, traefik or service-meshes like istio. Most of them have a TLS passthrough mode and/or implement a way to trust an internal CA.

I think there are too many different setups to support them all out of the box. The load-balancer behaviour can already be turned off by setting `.Values.service.type` to `ClusterIP`. Users can then deploy their own ingress/TCP loadbalancer/...

If we think Teleport + TLS-termination Ingress is a legitimate setup, we can provide a value to deploy a generic ingress, but it will likely be the user's responsibility to pass the correct annotations for whatever ingress controller they use. If we don't think Teleport will work well behind something terminating TLS we should document it with the chart and point then to TLS passthrough alternatives like https://kubernetes.github.io/ingress-nginx/user-guide/exposing-tcp-udp-services/ or https://gateway-api.sigs.k8s.io/concepts/api-overview/?h=tlsroute#route-summary-table.

**Comment by omniproc** [comment]
We currently implemented Ingress infront of Teleport using Traefik. Given the feedback that disabling TLS in Teleport would cause problems we left it enabled. To make that work in case of Traefik we had to disable the TLS certificate verification (for now) which would normaly occure between the ingress controller (Traefik) and the exposed service (Teleport) by setting the propper annotation [insecureskipverify](https://doc.traefik.io/traefik/routing/services/#insecureskipverify) in the service (thankfully, that's a option in the current Helm chart used by Teleport) and it works great. That beeing said: it works because Traefik has that option and you can configure it using annotations. Other Ingress controllers might use different mechanisms out of scope of the Teleport Helm chart (you'd need to implement a different logic for every Ingress controller you want to support).
So the easy thing to do here would be to have an option to disable Teleport's TLS in case a ingress is configured. The problem with that approach could be however that the internal communication between pods (especially a problem when those pods run on different nodes) (e.g. Ingress Controller and Teleport) is not encrypted by default, thus disabling TLS would enable various attacks. Depending on the Ingress Controller used other options might be possible without disabling TLS (e.g. trust the self-signed cert issued by Teleport or use TLS but don't verify the certificate (authentication becomes a issue but at least network traffic is encrypted)) might be options but then again: you end up with different logic per Ingress Controller you want to support.

P.S.: to be precise: we're talking about the TLS connection exposed on port 443 by Teleport, Client-TLS authentication - I'm not sure if both are related in K8s (e.g. mutual auth. during handshaking).

**Comment by webvictim** [comment]
The main issue is that disabling TLS in Teleport (or terminating TLS in front of Teleport) prevents the use of its TLS routing/multiplexing mode ([`proxyListenerMode: multiplex` in the chart values](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L28-L31)) which in turn prevents the use of some Teleport features.

The default for Helm is _not_ to enable this setup, but this is the opposite of the way that a "default" Teleport deployment (using `teleport configure`) works and that's something that will probably need to change eventually. At any rate, the use of an ingress in front of Teleport invariably makes any deployment more complicated and is generally discouraged.

**Comment by omniproc** [comment]
Yes, we just ran into that exact issue. Altought any ingress router that supports TCP routing (-> acting in TLS passthrough) should be easy to support. You'd _just_ have to add a few Helm templates for various Ingress Controllers that you want to support.

**Comment by hugoShaka** [comment]
> Altought any ingress router that supports TCP routing

By definition `Ingress` resources are  L7 loadbalancers. According to the Kubernetes documentation:

> An Ingress does not expose arbitrary ports or protocols. Exposing services other than HTTP and HTTPS to the internet typically uses a service of type [Service.Type=NodePort](https://kubernetes.io/docs/concepts/services-networking/service/#type-nodeport) or [Service.Type=LoadBalancer](https://kubernetes.io/docs/concepts/services-networking/service/#loadbalancer).
 
While some ingress controllers have introduced additional custom resources definitions or hacky ways to deal with L4 loadbalancing (traefik, nginx, contour, istio) those are not standard and we cannot reasonably bake all those custom ways in the chart, both the maintenance cost and the size of the valuefile would explode (plus we don't have the setups to test them).

Hopefully a new standard is slowly on its way:[ the Kubernetes Gateway API](https://gateway-api.sigs.k8s.io/). It introduces the `TCPRoute` and `TLSRoute` resources, which will support TCp routing and TLS pass-through. Most ingress controllers have added pre-alpha support. I think adding the ability to deploy `TCPRoute` and `TLSRoute` in the chart makes a lot of sense.

In the meantime we cannot advise users to use `Ingress` resources as it will hurt them eventually. Building the feature in the chart feels like handing them a footgun. I'll check with the product team what's the best way to deal with this and avoid users to shoot themselves in the foot.

**Comment by omniproc** [comment]
Understandable. K8s gateway APIs sound like a solid plan.

**Comment by hugoShaka** [comment]
FYI there are plans to support TLS multiplexing even with a loadbalancer terminating (with a bit of encapsulation). If this feature is added we would be able to run Teleport behind an Ingress and would be able to add Ingress support in the chart.

**Comment by webvictim** [comment]
This was fixed in https://github.com/gravitational/teleport/pull/25815 and released in Teleport v13.2.2.
