### ISSUE TITLE
[v.9.0] /docs/pages/database-access/guides/mysql-self-hosted.mdx

### ISSUE THREAD

**Issue by dubiZA** [gravitational/teleport#12790]
## Details
The instructions from https://goteleport.com/docs/database-access/guides/mysql-self-hosted/#step-24-create-a-certificatekey-pair are really not clear.

Is tctl auth sign --format=db --host=db.example.com --out=server --ttl=2190h supposed to be executed from the DB Service machine? From my local machine that I setup tctl and tsh on? If my local machine, I get an error because I haven't executed teleport start command on my local machine (which the guide doesn't say I should do when running Teleport Cloud.
### Category

- Improve Existing

**Comment by Baskkra** [comment]
it should be executed inside teleport instance right? the instance that will be bastion for our teleport service

**Comment by alexfornuto** [comment]
The command should be run from whatever location you've already authenticated `tctl` to your Teleport cluster from, as described in the prerequisites section (which may have changed since this issue was filed). The files created then need to be moved to the environment where the database is running. I'll submit a patch shortly to clarify.

>If my local machine, I get an error because I haven't executed teleport start command on my local machine (which the guide doesn't say I should do when running Teleport Cloud.

If a `tctl` command complains that Teleport isn't started it's likely that you haven't yet run `tsh login` at your cluster's proxy service. We've standardized the prerequisite instructions in these guides to make this more clear.

> it should be executed inside teleport instance right? the instance that will be bastion for our teleport service

You _can_ run `tctl` from the environment running the Teleport Auth service, which avoids needing to authenticate with `tsh` first, but that's not how this guide is written.
