### ISSUE TITLE
Usage metrics

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#1332]
## Enterprise Usage Reporting

The feedback / requirement from some enterprise customers is to collect usage information for every Teleport cluster. This should include:

* Number of unique user logins, hourly.
* Number of unique online nodes, hourly.

The usage information should be kept locally (in a cluster storage backend) for at least a year (i.e. 365 latest days) and the auth server should have a CLI command which dumps this usage information to stdout.

## Automatic Shipping

There should be an option to automatically ship this information (anonymizied form) to Houston. This feature should be controlled via a license feature flag. The open source version should never do this.

When shipping, we must ensure that the following is reported: 

* License ID (this should be automatic, AFAIK the license itself is used for authentication to Houston)
* Cluster ID

By combining both, Houston should see how many clusters are out there under the same license.

## Questions to discuss

* What do we count as "online node". Does a single auth ping mean "online node"? Shall we only count nodes that have been pinging for at least 15 minutes? 
* Do we have enough information to determine what does a "unique user" mean?

**Comment by aberoham** [comment]
Enterprise customers have requested that usage-based accounting be a running total of usage in seconds (instead of [x] events per hour). They have also requested billing based on sum of **session seconds** in addition to active users and connected host totals. 

Another consideration: in some pricing conversations we've had requests to meter on specific feature flags as an added dimension to primary metrics. Examples such as "different per-second usage fee for dev/test/qa environments not subject to audit where we won't enable session recording feature", or "cost per second per connected Kubernetes cluster" are starting to pop up.

Why seconds instead of hours? The broad buyer request is that Teleport's internal accounting align with their cloud provider's notions of metering. Prior, and encoded in some contracts, is accounting per _hour_, but recently very large customers with sophisticated scaling systems have protested that hourly isn't aligned with AWS or GCP instance metering which is nowadays per-minute or even per-second.

Also worth mentioning, this usage reporting mechanism could be wired up to cloud-specific marketplace metered usage reporting services in the future such as [AWS Marketplace Metering Service](https://docs.aws.amazon.com/marketplace/latest/userguide/metering-service.html). It could also be quite useful as a prometheus-style /metrics endpoint, in case a Teleport admin wishes to keep an eye on Teleport usage within their own metrics aggregation, visualization & alerting systems.

**Comment by klizhentas** [comment]
https://docs.google.com/document/d/1h0_rw28GAPt9Xu88Sw5EeAVFZBR0RwKA5hUN3hG7pSg/edit#heading=h.66ytssug84ce
