### ISSUE TITLE
Postgres backend - support user/password connection

### ISSUE THREAD

**Issue by hydezhao** [gravitational/teleport#13401]
What would you like Teleport to do?

_Use user/password connection for the setup of postgres backend._

What problem does this solve?

_Currently postgres only support client certificate authentication if we want to use postgres as backend. While in some cases, we cannot configure the postgres backend for client certificate authentication._ 

If a workaround exists, please include it.

**Comment by Asgoret** [comment]
Teleport > Pgbouncer > PSQL
I think it will work) Same problem)

**Comment by zmb3** [comment]
This is possible (though strongly discouraged) in Teleport 13.3+

**Comment by xom4ek** [comment]
@zmb3 can you please explain how its possible? Didnt found any notes in Changelog

**Comment by zmb3** [comment]
https://goteleport.com/docs/reference/backends/#authentication

> If the use of passwords is unavoidable, we recommend configuring them in [the ~/.pgpass file](https://www.postgresql.org/docs/current/libpq-pgpass.html) rather than storing them in Teleport's configuration file.

**Comment by Asgoret** [comment]
@zmb3 it`s a psql configuration, not teleport configuration. We use SaaS of PSQL and it`s give us only login\password for connection. So, we can't edit any PSQL configuration files. Also our PSQL instance don't have any public interfaces, so we need anyway something between. It can be teleport or pgbouncer.

**Comment by zmb3** [comment]
Teleport's postgres connector will read the pgpass file.

I would reiterate that we strongly discourage using password authentication.

**Comment by Asgoret** [comment]
@zmb3 if I understand correctly... I create that file, put it the teleport agent and it read it? We can't put database credentials to user machines) And in my case I don't have any other options rather than password

**Comment by vsychov** [comment]
> that we strongly discourage using password authentication.

Sometimes using passwords is the only way to connect to a database managed by an external provider, such as DigitalOcean's managed PostgreSQL.

@Asgoret , the `~/.pgpass` files work; they should be placed in the user's home directory, under which the `Teleport database service` is running (on teleport server), and have `chmod 600` (I'm not sure if the `pgconn` checks this). 

Another crucial point is the format of this file:
```
HOSTANAME:PORT:*:*:PASSWORD
```

Instead of specifying the database and user, it is MANDATORY to use `*`; otherwise, it will not work. This is because when parsing the config using `pgconn`, the database user is unknown, and it uses the current user's name under which the `Teleport database service` is running, instead of the user specified during the connection.
