### ISSUE TITLE
Machine ID: more gracefully handle lack of bot roles

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#13411]
If a bot user has not been configured with any roles, and the user hasn't configured any roles for `tbot` to request, when the bot attempts to generate impersonated certificates, it will instead receive normal bot certificates (as no roles will be requested by the bot). This will cause the next renewal to cause a generation mismatch lockout.

**Comment by timothyb89** [comment]
I think the underlying issue here is that we use the presence or absence of RoleRequests to determine if we're renewing certs or if we're requesting new impersonated certs. In the former case the returned certs should be renewable with an incremented generation counter, in the latter case they should be impersonated certs (using role requests) with the `DisallowReissue` flag set to prevent privilege (re-)escalation.

There's a few approaches to fixing this:
1. We could add a new certificate request field to make the request intent unambiguous (say, `RoleRequestOnly = true` or something in [`UserCertsRequest`](https://github.com/gravitational/teleport/blob/master/api/client/proto/authservice.proto#L191-L267=))
2. We can consistently require there to be at least one role request in [`CreateBot`](https://github.com/gravitational/teleport/blob/master/lib/auth/bot.go#L114=) when there's no roles would be helpful.
3. We can require at least one role request to fetch impersonated certs in [`renew()`](https://github.com/gravitational/teleport/blob/master/lib/tbot/renew.go#L481-L485=)

I think (1) is the best from a security perspective, (2) and (3) would patch around the issue, and all 3 would be the best from both a security and a UX perspective, since (2) and (3) let us provide an error message early and never let users wind up with a bot that has zero permissions.

Security-wise I think the damage is limited:
1. `tctl bots add` does require `--roles` to be passed in (though `tctl bots add foo --roles` will trigger the issue) so it's unlikely any users have done this by accident
2. The resulting bot will have only minimal permissions since by definition it has no roles (just `readnosecrets` on `cert_authority` which is arguably pretty harmless)
3. The "impersonated certs" will instead be renewable certs, but if an attacker steals these they'll a) have no interesting permissions and b) trigger a generation counter lock very quickly
4. The bot will just lock itself on the first renewal (after 20 minutes by default) since it doesn't handle this condition properly to begin with
