### ISSUE TITLE
Use the following description when describing Teleport agentless

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#13446]
With Teleport in agentless mode, you can easily control access to SSH servers, Kubernetes, clusters, databases and internal applications without running any additional software on your servers. Agentless mode supports session recordings and audit logs to a deep understanding into user behavior. 

For additional capabilities such as kernel level logging and user provisioning, we recommend Teleport as a drop in replacement for OpenSSH. You get deeper analytics without an additional agent on your system

**Comment by ptgott** [comment]
@klizhentas Do we have existing documentation on Teleport Agentless for non-SSH protocols? Is this the same as running an instance of the Teleport Application Service, Database Service, etc. in the same network as the target resource, but not on the same host? Or does it work similarly to the instructions in the [OpenSSH guide](https://goteleport.com/docs/server-access/guides/openssh/), where Teleport-signed credentials are used by non-`teleport` processes to secure their communications?

**Comment by klizhentas** [comment]
@ptgott one Teleport Proxy can handle access to multiple DBs, kubernetes clusters and apps. You can find the docs on how proxies do that in appropriate sections. You still need to have the proxy, just don't have to run agent alongside every resource if Proxy can reach out directly, e.g. in the same network. We need to mention that and gather docs from different resources to mention under agentless umbrella.

Does it make sense?

**Comment by ptgott** [comment]
@klizhentas It does, thanks!

**Comment by webvictim** [comment]
That second paragraph isn't correct, right? You don't get kernel level BPF recording or user provisioning without the Teleport binary running on the target system.

**Comment by klizhentas** [comment]
@webvictim may be I just phrased this wrong, but this is exactly what I tried to say, can you help rephrasing it better?

**Comment by webvictim** [comment]
@klizhentas If the idea is that someone would stop running `sshd` and run `teleport` instead, then I think it reads the way you intend it to. It just wasn't clear to me initially until I re-read it.

**Comment by ardeche07** [comment]
I had to read it a couple times as well to get what you were trying to communicate. I recommend updating to this (also fixed a couple other small typos):

"With Teleport in agentless mode, you can easily control access to SSH servers, Kubernetes clusters, databases and internal applications without running any additional software on your servers. Agentless mode supports session recordings and audit logs for deep understanding into user behavior.

For additional capabilities such as kernel level logging and user provisioning, we recommend Teleport as a drop in replacement for OpenSSH. Since Teleport replaces the OpenSSH agent while preserving OpenSSH functionality, you get deeper analytics without a net addition of an agent on your system."
