### ISSUE TITLE
IP-based validation for Machine ID issued certificates

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#13483]
https://github.com/gravitational/teleport/pull/13243 added support for IP-based validation for SSH Certs, but omitted Machine ID support, which leverages a separate code path.

The request here is that when impersonating a role that requires IP pinning, Machine ID generates SSH certs with the `source_address` critical option set.

**Comment by strideynet** [comment]
So I think it's worth mentioning that once we complete this, we ought to get around to IP pinning TLS certificates if we can. This will be important for locking down the bot's own certificates, to prevent those being used to generate impersonated certificates for a different IP address.

**Comment by strideynet** [comment]
So I've started looking into this, and come across a slight hitch.

`tbot` leverages the same RPC (`GenerateUserCerts`) as `tctl auth sign` does, and this makes it slightly more complicated as to how we decide to implement this logic.

The simplest option is to take a relatively naive approach. `tctl auth sign` does not currently support role impersonation, and therefore, we could choose assume that any role impersonation call to `GenerateUserCerts` is being made by `tbot` and that we should then check the roles to decide if IP pinning should be added to the generated certificates. My concern is that this approach is too naive, a future modification to `tctl auth sign` could add support for role impersonation, and this would mean that certificates produced would then be IP pinned. This could be inconvenient for users intending to generate certificates for use on another machine for a short period, but, this is a use-case that is served by Machine ID.

The more complex option is to properly embrace IP pinning within the `GenerateUserCerts` RPC, and consider it regardless of the type of the certificate being generated. It feels like the most secure option would be to ensure that the certificate is IP pinned regardless of the type of generation (role impersonation, user impersonation, access request) if one of the roles that will be included by the certificate require it. However, I worry that there are circumstances that a user may want to generate certificates without an IP restriction, or for an IP other than their own. In this case, we could allow the user to specify an IP to use instead of theirs, or to specify that they don't want the certificate to be pinned. This certainly has some security repercussions (we could restrict this behaviour to users with specific permissions e.g admins using `tctl` on the auth server itself to mitigate some of this), but increases usability.

I'd be curious on thoughts here. In the interest of time, it may well make sense for us to take the naive approach now, and return to this in future. I don't see any reason why taking the naive approach would prevent us expanding IP pinning to the rest of the `GenerateUserCerts` RPC.

**Comment by zmb3** [comment]
I like the second option, with the following caveats:

> I worry that there are circumstances that a user may want to generate certificates without an IP restriction

This is fine. If a user wants this then they shouldn't request a role that requires IP restrictions.

> or for an IP other than their own. In this case, we could allow the user to specify an IP to use instead of theirs, or to specify that they don't want the certificate to be pinned.

We don't support this now and have no plans to in the near future.

**Comment by strideynet** [comment]
This ticket is blocked by #15521
