### ISSUE TITLE
`tsh login` confusing error messages

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#13782]
_Umbrella: Improve user experience for users trying teleport with self-signed certificates._

Tsh login will fail:

```
tsh ssh --proxy=teleport.example.com --user=test ubuntu@test
ERROR: Get "https://teleport.example.com:3080/webapi/ping": dial tcp 172.16.30.98:3080: connect: connection refused
```

If you run the command with --debug you will see:

```
DEBU [TSH]       Race request failed error:[Get "https://teleport.example.com3080/webapi/ping": dial tcp 1.2.3.4:3080: connect: connection refused] tsh/resolve_default_addr.go:83
DEBU [TSH]       Trying teleport.example.com:443... tsh/resolve_default_addr.go:109
DEBU [TSH]       Race request failed error:[Get "[https://teleport.example.com:443/webapi/ping](https://teleport.example.com/webapi/ping)": x509: certificate signed by unknown authority] tsh/resolve_default_addr.go:83
```

First of all, let's improve this unclear "Race request failed error`. Seems like some strange internal phrasing.

Second, the user facing error should be:

```bash
tsh ssh --proxy=teleport.example.com --user=test ubuntu@test
ERROR: Failed to connect to https://eleport.example.com. The certificate has expired or signed by untrusted certificate authority. Please update your certificate. 

If you are trying teleport with self-signed certificate, please follow this guide: https://goteleport.com/docs/getting-started/self-signed#tsh
```

**Comment by zmb3** [comment]
I moved this one over to @strideynet because I have a feeling it has some overlap with another `tsh login` issue he's already working on.

**Comment by strideynet** [comment]
It looks like this "race request" stuff is for where the port for the proxy has not been provided by the user, so we concurrently attempt to connect to `:3080` and `:443` (with a 250ms break between them to avoid "swamping the network) essentially "racing" the two requests (see `tool/tsh/resolve_default_addr.go`). In most cases, the users proxy will only be listening on one of these ports.

This will often result in a scenario where a "connect: connection refused" is returned instead of a "x509: certificate signed by unknown authority". I need to have a bit more of a think about this, as, at a higher level we are totally unaware that a "certificate signed by unknown authority" has even occurred, but at the same time we can't just assume that a "connect: connection refused" means that a self-signed certificate is being used since this error could bubble up for a multitude of reasons.

My gut feeling, is we could do with returning some kind of aggregate or multi error here, and then we'd be able to check if at least one of the attempts failed with `x509: certificate signed by unknown authority`. Being entirely frank, this entire section of code could be massively simplified. The algorithm that has been implemented would be suitable for testing a large number of ports, but we only ever use it to test two different ports. There's really no reason for it to be this complicated, and a simpler model would make it much easier to select the useful error. I'll do some thinking over this.

**Comment by zmb3** [comment]
Ok, this may need to wait for https://github.com/gravitational/teleport/issues/11524 then.

The idea behind that issue is if we know the user's intent, we don't have to try both approaches and let them "race" - which should allow us to provide a nicer error message.

**Comment by mr-kelly** [comment]
I meet the same problem ,   9.3.6 version
