### ISSUE TITLE
Add more flexibility to `create_host_user` by allowing to set `useradd` options

### ISSUE THREAD

**Issue by hexinal** [gravitational/teleport#14252]
What would you like Teleport to do?
To be able to set `useradd` options in the role definition, setting the shell used by the created user, HOME_DIR, etc.

What problem does this solve?
Extends the usability of the feature and thus being a more convenient alternatives to a fully fledged PAM setup.

If a workaround exists, please include it.
If you don't need multiple scenarios, you could just edit `/etc/default/useradd`. But you can't disable or set the HOME_DIR that way. https://linux.die.net/man/8/useradd

**Comment by gregseb** [comment]
I would also like if this was easier, but for the moment my workaround is to combine `create_host_user` with pam similar to the instructions found [here](https://goteleport.com/docs/server-access/guides/ssh-pam/), except instead of creating a user I am calling things like `/usr/sbin/usermod -s /bin/zsh "${TELEPORT_LOGIN}"` to change the shell, and using the script to generate any configuration that isn't in `/etc/skel`. Seems kind of silly since one of the nice things about `create_host_user` is not needing to mess with pam, but it works, and I like how `create_host_user` keeps things nice and clean without extra work.

**Comment by shovelend** [comment]
We'd also be interested in the ability to pass `useradd` options, since some of our VMs run on Ubuntu 16. There is [a bug](https://bugs.launchpad.net/ubuntu/+source/shadow/+bug/1321854) in the `useradd` package, where the `SHELL` variable under `/etc/default/useradd` is not respected. Thus, when the host user gets created, its shell settings remain empty. We get the following back from a `tsh` command:
``` bash
tsh ssh shovelend@a-ubuntu-16-host
ERROR: ssh: could not start shell
```

These are the logs from teleport running on that host:
```
useradd[85482]: new group: name=shovelend, GID=3002
useradd[85482]: new user: name=shovelend, UID=3001, GID=3002, home=/home/shovelend, shell=
useradd[85482]: add 'shovelend' to group 'teleport-system'
useradd[85482]: add 'shovelend' to shadow group 'teleport-system'
```

Which clearly indicates the issue. It would be great for us to specify extra options to the host user creation via Teleport.

**Comment by bediverus** [comment]
I have Debian 9 (stretch) OS.
`useradd` also does not accept default parameters, and Teleport creates a user without SHELL.

```
Failed to launch: exec: no command.
ERROR: Process exited with status 255
```

```
useradd[31999]: new group: name=bediverus, GID=1010
useradd[31999]: new user: name=bediverus, UID=1009, GID=1010, home=/home/bediverus, shell=
useradd[31999]: add 'bediverus' to group 'teleport-system'
useradd[31999]: add 'bediverus' to shadow group 'teleport-system'
userdel[32067]: delete user 'bediverus'
userdel[32067]: delete 'bediverus' from group 'teleport-system'
userdel[32067]: removed group 'bediverus' owned by 'bediverus'
userdel[32067]: removed shadow group 'bediverus' owned by 'bediverus'
userdel[32067]: delete 'bediverus' from shadow group 'teleport-system'
```
The `create_host_user` function does not work on older Debian/Ubuntu OSes
Is there a resolve or a workaround?

**Comment by eriktate** [comment]
[As of version `1.6.0`](https://goteleport.com/docs/changelog/#other-improvements-and-fixes-1) it's now possible to set a default shell for provisioned host users! I'm closing this issue as completed since it seems like setting the shell was the primary option being discussed. However, if there are any other specific options you would like to see supported during user creation please feel free to open new issues for them.
