### ISSUE TITLE
`UploadCompleter` should flush and upload the active session recordings on termination

### ISSUE THREAD

**Issue by ryanclark** [gravitational/teleport#14294]
@zmb3 @tigrato @webvictim 

**Expected behavior**
Sessions should be uploaded when the `UploadCompleter` gracefully shuts down.

**Current behavior**
When a couple of criteria are met, session recordings that are in progress do not get uploaded when the kube agent is killed
- The kube agent hasn't got a backing store for `/var/lib/teleport`, so the upload is lost if it's terminated
  - This could be quite common - the helm chart by default [specifies an `emptyDir` for the data directory](https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-kube-agent/templates/deployment.yaml#L180-L183) if `existingDataVolume` isn't set
- Auth server has a `session_recording` set to anything other than `proxy-sync`
  - The default for cloud customers is `node`, so this will be quite common too

**The fix**
We should add a flush on [shutdown here](https://github.com/gravitational/teleport/blob/3c1a6b628b437e7ca4f337f0e8eca5e299680f03/lib/events/complete.go#L134-L135). Any active sessions should be marked as terminated and the session should be uploaded before the program is allowed to exit.

To support this, we'd need to change `dumb-init` to rewrite `SIGTERM` to `SIGQUIT` (`--rewrite 15:3`), so the `UploadCompleter` can exit gracefully and process the uploads. @webvictim  suggested an alternative to this - possibly editing the helm chart to send `SIGQUIT` instead of `SIGTERM`. We might want to increase `terminationGracePeriodSeconds` too.

This should fix https://github.com/gravitational/teleport/issues/14120 without any configuration changes on the customer's end.

**Recreation Steps**
- Spin up a k8s cluster with `session_recording` set to `proxy` or `node` (I have a skaffold config if needed so you don't have to provision anything)
- Run the teleport kube agent
- `kubectl exec -it pod /bin/bash` to create an active session
- Terminate the kube agent
- Sessions are lost and not uploaded

**Comment by tigrato** [comment]
Thanks @ryanclark.

Instead of rewriting `SIGTERM` to `SIGQUIT`, one can leverage the [`preStop`](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/#container-hooks) hook to run arbitrary commands in the container before the `TERM` signal is sent to the PID 1 process.

Usually, `preStop` is used to drain cluster nodes, which is more or less our use case. 

Prior to flush and pushing to the proxy, we should terminate the connections that are being recorded, and after we flush everything and push them into the proxy.

**Comment by ryanclark** [comment]
Cheers @tigrato!

**Comment by webvictim** [comment]
Personally I prefer the idea of fixing this in the Docker container itself so that the fix is picked up by anyone running Teleport in Docker - not just anyone using the `teleport-cluster` Helm chart. Obviously the blast radius of such a change is a little larger, but I think it's a fundamental issue that would also affect many customers not using Kubernetes.

**Comment by ryanclark** [comment]
Closing as this solution wouldn't have been great anyway.

Two solutions are -

- Record in a `-sync` mode, so the sessions go to the auth service
- Put a backing store behind the kube agent so if it restarts, it completes any uploads left on disk
