### ISSUE TITLE
Add support for custom tunnel_public_addr to Helm Chart 

### ISSUE THREAD

**Issue by colinedwardwood** [gravitational/teleport#14309]
What would you like Teleport to do?
The helm chart should support specifying a custom tunnel_public_addr.

**Comment by colinedwardwood** [comment]
It would actually be better if all the various `public_addr` options could be configured with the chart.

**Comment by webvictim** [comment]
The other requirement for this is that multiple public addresses should be able to be specified - i.e. the value should be able to take either a list or a string. The reason is that in multi-region deployments, you need to tell Teleport that it has multiple public addresses it should respond on, i.e.:

```yaml
proxy_service:
  public_addr: ['teleport.example.com:443', 'us-teleport.example.com:443']
```

Without the second public address being set, any requests to `us-teleport.example.com` will result in app access responding to incoming requests with a redirect.
