### ISSUE TITLE
Azure MySQL/Postgres Auto discovery 

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#14688]
## What 

Add auto discovery  support for Azure DB MySQL/Postgres instances: 

Databases: 
 -  [x] [MySQL](https://azure.microsoft.com/en-us/services/mariadb/)
 - [x] [Postgres](https://azure.microsoft.com/en-us/services/postgresql/)

Success criteria:
- Teleport can automatically discover and register Azure Postgres/MySQL servers on Azure

**Comment by GavinFrazar** [comment]
Commenting here for discussion: A configured service principal will need to have a role assignment with read permissions in order to list/get DB servers. The built-in "Reader" role will work, or a custom role with minimal required permissions like this:
```json
    "permissions": [
      {
        "actions": [
          "Microsoft.DBforMySQL/servers/read",
          "Microsoft.DBforPostgreSQL/servers/read"
        ],
        "dataActions": [],
        "notActions": [],
        "notDataActions": []
      }
    ]
```
Relevant info:
* Role assignments are 3 things: principal, role, scope.
* Roles have an "assignable scope" as well - meaning what scope you can use with a role in an assignment.
* Custom roles cannot have a "root" assignable scope - the highest assignable scope you can use for a custom role is a management group or subscription.
* Users may, or may not, have their subscriptions organized under management groups - so we should stick to per-subscription scope assignments, imo.

I think based on these facts, we should just create the minimal permissions in a custom role. Otherwise we need the user to escalate their role to Global AD Admin in order to create role assignments at the root scope **and** we would have to use the Builtin "Reader" role which can read everything.

This means we need the user to create a custom role and a role assignment for each subscription they add.
I have not added auto-bootstrapping for Azure in this first-pass implementation - for now a user must create the service principal *and* manually give it the necessary role assignment to list servers. If a user adds a new subscription, they will need to manually add a role assignment for their service principal which includes that subscription. e.g.:
```
                            root
                             |
                         +---+----+
                         |        |
                         |        |
                      +-sub1     sub2--+
                      |                |
+---------------------+               ++--------------------+
|RoleAssignment       |               |RoleAssignment       |
|  Principal: Teleport|               |  Principal: Teleport|
|  Role: DiscoveryRole|               |  Role: DiscoveryRole|
|  Scope: sub1        |               |  Scope: sub2        |
|                     |               |                     |
+---------------------+               +---------------------+

+-------------+                       +-------------+
|DiscoveryRole|                       |DiscoveryRole|
|Permissions: |                       |Permissions: |
|   ...       |                       |   ...       |
+-------------+                       +-------------+
```

Any concerns with this approach? If not I'll describe how to do this in our database-access azure guide, along with updates for using discovery config.

**Comment by smallinsky** [comment]
I think that this is fine if we wan to follow least privilege access. The subscription is considered like a separate management boundaries so I think that  as you mentioned creation of a custom role assignment will be necessary but helpfully we can automate  this inside  `teleport db bootstrap` command. 

cc: @r0mant

**Comment by r0mant** [comment]
@GavinFrazar @smallinsky To make sure I understand correctly - this is going to be a one-time assignment for the database agent allowing it to discover databases, correct? Similar to setting up IAM role for the agent on AWS. If so, yes let's update `teleport db configure bootstrap` to support this.

**Comment by GavinFrazar** [comment]
@r0mant yes, one time assignment for the db agent. However they would need to re-run the bootstrap command if they add a new subscription, since we will make the role assignment for each subscription.

**Comment by GavinFrazar** [comment]
@r0mant @smallinsky @greedy52 I think next steps are to auto-enable Azure AD authentication for discovered databases.

AAD auth is disabled if the Azure AD Admin is not set on a database - to enable it, you just need to set the AD admin (to user, group, or service principal in the same tenant as the Teleport service principal).

Right now, our guide explains that you need to set the Azure AD Admin so you can create users identified by the Teleport service principal ID.

If you unset the AD admin after doing those steps, then AAD auth will be disabled again, and the Teleport service principal will not be able to login as the users you created. (I've added a note warning about that in our guide).

To automatically "re-enable" AAD auth, the service principal would need to set the AD Admin to someone. If it sets itself as AD Admin, then the only way to create new users in the database is via logging in as the service principal. I think a better approach would be to set the AD Admin as a group which the service principal is a member of. That way, you can have more than one AD Admin, and you can add/remove admins by modifying the group membership.

Additionally, having the service principal be an AD Admin may be useful in the future - I think we'd like to be able to create database users automatically eventually, since that's the last manual step left to automate. In order to do that, the Teleport service principal will need to have AD Admin on each database.

Minimal permissions necessary if we want to support auto enabling AD Admin on discovered databases:
```json
"permissions": [
            {
                "actions": [
                    "Microsoft.DBforMySQL/servers/read",
                    "Microsoft.DBforPostgreSQL/servers/read",
                    "Microsoft.DBforMySQL/servers/administrators/read",
                    "Microsoft.DBforMySQL/servers/administrators/write",
                    "Microsoft.DBforMySQL/servers/administrators/delete",
                    "Microsoft.DBforPostgreSQL/servers/administrators/read",
                    "Microsoft.DBforPostgreSQL/servers/administrators/delete",
                    "Microsoft.DBforPostgreSQL/servers/administrators/write"
                ],
                "notActions": [],
                "dataActions": [],
                "notDataActions": []
            }
        ]
```

Having said all that, a couple questions I have:
1. For now, should I change the guide instructions to tell the user to make a group, put the service principal in that group, and then set the AD admin to the group instead of their own account?
2. What should we name this group if we do this? "Teleporters"? It needs to be very unique if we auto-enable auth by setting AD Admin to this group name.

# Alternatively
An alternative to "auto-enabling" AD Admin is to make that all a part of a bootstrap flow: The user runs something like `teleport db configure bootstrap azure --config=/etc/teleport.yaml --set-ad-admin=TeleportersGroup` -- this will use the config file to match/discover databases and set the AD Admin as "TeleportersGroup" for all of them.

"auto-creating-users" could look like this:

Connect interactively as an AD Admin (via tsh!): `tsh db connect --db-user=TeleportersGroup <db>` and create users, grant permissions etc.

We can also do non-interactive sql scripting through tsh for user creation/configuration. For example, I just tested that this already works (I made the group name 'database-access' and my service principal is a member of that group):
```bash
bash-5.1$ cat <<'EOF' | tsh db connect --db-user=database-access teleport-mysql
SET aad_auth_validate_oids_in_tenant = OFF;
CREATE AADUSER 'SomeNewUser' IDENTIFIED BY '64ca60b1-5b77-4dc1-9ad3-79ac7fb1fd09'; # this is the ID of the service principal
GRANT ALL ON `%`.* TO 'SomeNewUser'@'%';
EOF                                     
bash-5.1$ echo "select user();" | tsh db connect --db-user=SomeNewUser teleport-mysql
user()
SomeNewUser@xxx.xxx.xxx.xxx
```

If we added the ability to run such SQL scripts on databases by tag, just like we do for `tsh ssh foo=bar <command>`, then it would significantly reduce the tedium of that last step of user-creation and configuration. It wouldn't be hard to add that feature either. And we can even simplify it further by making a bootstrap command for user creation like `teleport db configure bootstrap azure --create-user=SomeNewUser`. I think we should leave DB-specific permissions to the user to handle via tsh.

My preference here is actually the alternative, once I typed it all out 😆. A bootstrap flow doesn't require any extra permissions for the teleport service principal, allows the user to specify what group or user they want as AD Admin on their DBs, and is significantly simpler.

**Comment by greedy52** [comment]
I am still learning Azure so correct me if I am wrong.

> A bootstrap flow doesn't require any extra permissions for the teleport service principal,
The bootstrap is usually run on the same database service VM so wouldn't it also require the same permissions to check and configure the admin?

I don't think the bootstrap script will be able to catch new database servers either.

**Comment by smallinsky** [comment]
The cons of alternative solution is the fact that the `teleport db configure bootstrap azure --config=/etc/teleport.yaml --set-ad-admin=TeleportersGroup` command will need to be   reexecuted for each database server added in Azure after the first initial `teleport db configure bootstrap azure` call. 

The first solution for me looks more comprehensive where the user admin assignment doesn't require any additional step like in  alternative solution. Adding additional permission to the db agent to do auto admin assignment seems reasonable is we can narrow the scope to particular resource-groups. The `teleport db configure bootstrap azure` command can automatically assign minimal permission needed to do auto admin assigned for the provided teleport azure auto discovery configuration.

**Comment by greedy52** [comment]
If a database server does NOT have AD admin set, most likely it's never been configured. In that case, even after Teleport set itself as the AD admin, there are no AD database users to connect with. And in order to create AD database users, someone has to overwrite the AD admin with their own account/group?

**Comment by GavinFrazar** [comment]
> I am still learning Azure so correct me if I am wrong.
> 
> > A bootstrap flow doesn't require any extra permissions for the teleport service principal,
> 
> The bootstrap is usually run on the same database service VM so wouldn't it also require the same permissions to check and configure the admin?

Bootstrapping will need to be done with the user's account credentials, no? That would be to setup the permissions for the teleport service principal. So we could also set AD Admin as part of bootstrap flow at the same time.

> I don't think the bootstrap script will be able to catch newly created database servers either.

>The cons of alternative solution is the fact that the teleport db configure bootstrap azure --config=/etc/teleport.yaml 
--set-ad-admin=TeleportersGroup command will need to be reexecuted for each database server added in Azure after the first initial teleport db configure bootstrap azure call.

Yes, I didn't think it was that bad of a drawback since they need to manually create users in the database anyway. I was kind of on the fence though - this does seem like a major con now that you both point it out.

@greedy52 
> And in order to create AD database users, someone has to overwrite the AD admin with their own account/group?

Actually, if the service principal is set as AD Admin, then anyone allowed to use `--db-user=<ServicePrincipalName>` by teleport's RBAC would be able to use tsh to login as the service principal - without needing the service principal's credentials.

Likewise, if a group is set as AD Admin and the service principal is a member of that group, then anyone allowed to use `--db-user=<GroupName>` can login as the group via the service principal. In my tsh example above, that's what I did. I do feel uneasy about this from a security perspective though, since you have to be careful with your Teleport RBAC to not accidentally grant someone AD Admin privileges on the databases - what do you think?

Additionally, if we use a group then anyone who is a member of that group can login via mysql/psql with their own Azure credentials.

**Comment by greedy52** [comment]
> Bootstrapping will need to be done with the user's account credentials, no?

The `--config=/etc/teleport.yaml` part suggests the command is run on the VM that is hosting the database service. But of course, there are ways to get around this.

> Actually, if the service principal is set as AD Admin, then anyone allowed to use --db-user=<ServicePrincipalName> by teleport's RBAC would be able to use tsh to login as the service principal - without needing the service principal's credentials.

> I do feel uneasy about this from a security perspective though, since you have to be careful with your Teleport RBAC to not accidentally grant someone AD Admin privileges on the databases

That's interesting. Very convenient for dev environments. But like you said, I also feel it's a security risk that once we automatically set AD admin, some Teleport users may get full access to the database. Not sure how others feel on this.
