### ISSUE TITLE
Add IP-based validation for non-SSH protocols

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#14702]
In v10 we added source IP validation for SSH sessions.

This issue is to track IP validation for other protocols.

Sub-issues:
- https://github.com/gravitational/teleport/issues/13483
- https://github.com/gravitational/teleport/issues/15269

**Comment by russjones** [comment]
| Phase                       | PR              | Date      |
|-----------------------------|-----------------|-----------|
| ~Phase 1: Server Access~    | ~#11719 #13243~ | ~Q2 2022~ |
| Phase 2: Kubernetes Access  |                 | Q3 2022   |
| Phase 3: Database Access    |                 | Q4 2022   |
| Phase 4: Application Access |                 |           |

**Comment by strideynet** [comment]
Phase 1 is mostly complete, bar Machine ID support, which is being tracked here: https://github.com/gravitational/teleport/issues/13483

I think it's worth us considering a "fifth" phase as part of this issue: the Teleport API. Where a user has logged in with a role including IP pinning, we should really validate that their IP matches when they make requests to the Teleport Auth server HTTP and gRPC APIs. Otherwise, I think there's a few pathways that a malicious actor who has compromised a Teleport user's machine could theoretically generate credentials that include their own IP address, thus circumventing this entire element of protection.

**Comment by zmb3** [comment]
@AntonAM @r0mant anything left to do here or can we close this?

**Comment by AntonAM** [comment]
@zmb3 IP based validation is now generally checked across all protocols, the only thing that left in this area is the issue mentioned in description - IP pinning for bot certs ( #13483 ), I don't know how directly it is actually a subissue of this one though, it's relevant also for SSH access, basically it's about delivering correct login IP information when generating bot certs. I'm working on it and will finish it after vacation.

**Comment by zmb3** [comment]
I will close this and keep #13483 open then.
