### ISSUE TITLE
What the right syntax of tsh join command?

### ISSUE THREAD

**Issue by papiveron** [gravitational/teleport#1478]
Hello, 

It seems like it miss something in the `tsh join` command but I don't know what.

It works from the webui but not from `tsh`

Here is what I try join a shared session : 

```
tsh --user=juan.veron --login=admin --proxy=teleport-proxy.domain.com --cluster=main join 06970377-d066-11e7-b407-765964dd7cf9
```
The problem is that on the server I can see teleport is taking the local username for login and getting an access denied.
Here is what is returned on the client side :

```
ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
I saw that in the webui join URL, there is a `host UUID`, maybe there is a way to indicated the same in the `tsh` syntax?

What is the right command?

Cheers.

**Comment by aberoham** [comment]
Hi Eugène, did you ever sort this out?

Could you try running `tsh login` separately from the join command so that you already have an active tsh session certificate for your account before attempting to run a simplified `tsh join` ? (You shouldn't need to specify anything but the session ID if you're already logged in at the command line)

Of note, your command line works for me using Teleport v2.4.x with Enterprise SAML IdP --

1. Login through proxy UI (w/SAML IdP)
2. Start SSH session thru web UI
3. Run tsh join on the command line (using a separate browser than in 1) -- 
`$ tsh --user=abe@abe.us --login=teleport --proxy=[REDACTED] --cluster=main join [session ID from web UI found using teleport status in shell]`
