### ISSUE TITLE
Bot deletion is not consistant when cache is enabled

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#14883]
Expected behavior:

- Run teleport with cache
- Delete a bot using `DeleteBot`
- quickly create the bot back using `CreateBot`
- The bot is created

Current behavior:

Bot creation fails because the bot's role still lives in cache. Retrying later works.

Bug details:
- Teleport version
v11.0.0-dev
- Recreation steps

```go
    name := "mybot"
    role := "access"

    // Delete the bot
    if err := authClient.DeleteBot(ctx, name); err != nil {
        return "", trace.Wrap(err)
    }

    // Delete the bot's role
    roleName := fmt.Sprintf("bot-%s", name)
    if err := authClient.DeleteRole(ctx, roleName); err != nil {
        // This raises an error saying the role doesn't exist, it makes sense and we continue
    }

    // We create the bot and it fails saying the role already exists
    response, err := authClient.CreateBot(ctx, &proto.CreateBotRequest{
        Name:  name,
        Roles: []string{role},
    })

    time.Sleep(5*time.Second)

    // Here the bot creation works
    response, err := authClient.CreateBot(ctx, &proto.CreateBotRequest{
        Name:  name,
        Roles: []string{role},
    })
```

See slack thread: https://gravitational.slack.com/archives/C01TYKHFVTQ/p1658519346840079?thread_ts=1658518996.952949&cid=C01TYKHFVTQ

**Comment by strideynet** [comment]
I see two routes to fixing this (easy, and clean):
- Easiest solution is to adapt the `CreateBot` RPC to directly hit the backend, rather than hitting the cache when checking if the role/user already exists. Whilst we'd take a performance hit on this, it would be relatively insignificant in the grand scheme since the `CreateBot` RPC is going to hit the backend anyway when it tries to create these resources.
- The cleanest solution, would be for us to sort out cache invalidation. This is likely a significant piece of work, but would yield dividends elsewhere.

 I'm going to take a quick look at cache invalidation to assess the amount of work involved, but in all likelihood, the first option makes the most sense for now.
