### ISSUE TITLE
add a fallback mode for ssh displaying a list of servers to choose from.

### ISSUE THREAD

**Issue by james-lawrence** [gravitational/teleport#1506]
current workflow for connecting to a ssh server is cumbersome with many servers that are dynamically created and destroyed, having to ls first then copy the name of the server is a pretty cumbersome process.

would love for a workflow that combines these two steps (perhaps if ssh is provided with no arguments?)

**Comment by kontsevoy** [comment]
James, you should probably be using "static tokens" for adding nodes in the docs. ("adding nodes" section)

**Comment by james-lawrence** [comment]
@kontsevoy think you misunderstood the issue. the problem isn't getting a node to join the cluster, the problem is making a connection to the server via ssh. i.e.

```
tsh ssh user@host
```

this scheme isn't the greatest when the hosts are dynamic =)

**Comment by klizhentas** [comment]
@james-lawrence we fully agree, that's why we rolled out support for `tsh` with labels and not hostnames:

e.g. `tsh ssh user@mongo=master` will work as well. Labels could be static or change the value dynamically. Read more about labels [here](https://gravitational.com/teleport/docs/2.3/quickstart/#using-node-labels) and let us know if that solves your problem

Feel free to reach out either way!
