### ISSUE TITLE
Teleport on GKE guide permissions are not sufficient

### ISSUE THREAD

**Issue by hugoShaka** [gravitational/teleport#15089]
Expected behavior:

- I follow the guide
- teleport works

Current behavior:

- certmanager complaints it cannot list DNS zones
- teleport complains it cannot list storage buckrtd

Bug details:
- Teleport version: v10.1.0, v11.0.0-dev
- Recreation steps: Follow https://goteleport.com/docs/setup/helm-deployments/gcp/

ToDo: identify the correct permissions and update the guide lists and screenshots

**Comment by zmb3** [comment]
How does this relate to #14763?

**Comment by marcelocbf** [comment]
In my case, I followed the guide and left the default teleport-helm-backend, teleport-helm-events collection names and teleport-helm-sessions bucket name. I don't know about the firestore collections but I was getting the "permission" error on listing the bucket because this teleport-helm-sessions bucket already exists in someone else's account since bucket names need to be unique across GCP. I would suggest putting in the tutorial instead of teleport-helm-sessions something like you-unique-bucket-name-for-teleport-sessions-here ... I would probably have paid attention in that case...

**Comment by hugoShaka** [comment]
> How does this relate to #14763? (looks like a duplicate to me)

Yup, I just have a redfish memory and opened a second one

**Comment by hugoShaka** [comment]
> I would suggest putting in the tutorial instead of teleport-helm-sessions something like you-unique-bucket-name-for-teleport-sessions-here ...

Will do, thank you for the  feedback :+1:
