### ISSUE TITLE
Azure Managed Backends

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#15147]
The team will add support for managed backends on Azure.

- [ ] Customer can deploy fully on Azure with high reliability (HA for control plane), security (encryption at rest), and scale (matching DynamoDB, at least 10k).
- [x] Support for auth backend, audit log, and session recording.
  - [x] #15757
  - [x] #16545
  - [x] #16144
- [ ] Update [Scaling](https://goteleport.com/docs/setup/operations/scaling/) documentation for auth backend to match AWS and add scaling information for the audit log.

Fixes https://github.com/gravitational/teleport/issues/6117 https://github.com/gravitational/teleport/issues/5956

**Comment by anthonysomerset** [comment]
Hi Team - is there any news on this? - i note specifically that since https://github.com/gravitational/teleport/pull/16144 was merged - it appears to have been removed again without any obvious/visible reason?

We run an almost entirely Azure based shop except for our on-prem infra - so standing up an environment in AWS is slightly onerous for us from a procurement perspective. when we have no appetite to be in AWS in long term at all

We can make State/Config work in ETCD no problems but i just don't like it as a solution when i have to manage it myself (not a core expertise compared to a plain old DB solution) and then we are still missing session storage and audit storage in supported manners - again we can largely hack this (#22072) but its klunky at best

**Comment by webvictim** [comment]
@anthonysomerset We're planning to release native Azure backend support in Teleport 14.0: https://goteleport.com/docs/upcoming-releases/#1400

**Comment by anthonysomerset** [comment]
thanks - this says only Teleport will add native support for Azure for Auth and Audit backends.

Session recording to azure blob is still in progress?
