### ISSUE TITLE
tsh should not allow 3rd party tool inspects kubeconfig and executes tsh kube credentials

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#15298]
Expected behaviour:
3rd party tools (e.g kubernetes extension on VScode) should not be allowed to open the `.tsh/known_hosts` file in a read-write mode considering its the .kube/kubeconfig that things like VS Code extension (or other clients) read from (which points them to the tsh command).

Current behaviour:
When k8s extension is enabled on VScode, the tool inspects `kubeconfig` and executes `tsh kube` credentials against all cluster entry in the kubeconfig, which prompts tsh to attempt multiple parallel logins to all running Teleport clusters at the same time thereby corrupting the known_host file with `NUL` values.  
No locks on known_hosts file means it gets corrupted by parallel attempts to login. Multiple concurrent instances of `tsh login` appears to be  conflicting over changes to the known_hosts file causing corruption to the file. corrupted logins fails before reaching the server as `tsh` fails to read the corrupted file. 

Bug details:
- Teleport version
Teleport version 9.2.4
Teleport version 10.1.2

Recreation steps 
- A running a teleport setup that has multiple clusters that you login to
- Have the .tsh folder open in VS Code to watch what happens to the known_hosts file.
- Ensure no profile is logged in by executing the `tsh logout` command then we loop over `tsh login` command for in this case 4 different clusters and background them so that it is simultaneously running (A simple script can be used to achieve this action)

```
#!/bin/bash
tsh logout

clusters='cluster1proxyaddr cluster2proxyaddr cluster3proxyaddr cluster4proxyddr'
for c in $clusters
do 
    tsh login -d --proxy=cluster1proxyaddr "$c" &
done
```

- You will see an attempt to access all clusters at once and you should see errors in the terminal as well as well as resulting NUL values in the known_hosts file. It is also observed that while tsh is logging in the file gets cleared and overwritten several times.

Note:
In an ideal use case, login attempt should be initiated to one cluster at a given time, but the above use case is what occurs on the background when the VS code k8s extension is enabled, it triggers simultaneous logins to all the different clusters at once using tsh. VS Code k8s extension interacts .kube/kubeconfig which points them to the tsh kube.

- Debug logs
 corrupted logins fail before reaching the server as tsh fails to read the corrupted file (hence no logs on the server). But client error after failed attempt results in: 

```
ERROR: ssh: handshake failed: ssh: no authorities for hostname: teleport.xx.xx.xx:443
ERROR: ssh: handshake failed: ssh: no authorities for hostname: teleport.xx.xx.xx:443
```

gz#6175

**Comment by danielatjumo** [comment]
> Expected behaviour:
> 3rd party tools (e.g kubernetes extension on VScode) should not be allowed to open the .tsh/known_hosts file in a read-write mode considering its the .kube/kubeconfig that things like VS Code extension (or other clients) read from (which points them to the tsh command).

If I may expand on this section.
The expected behaviour is not that 3rd party tools _should not be allowed to open_ `.tsh/known_hosts`, but rather that they have _no knowledge of it_ and are working from the information provided in the `.kube/config` file (which points them to the `tsh` local command). The expectation is that if a client reads from the `.kube/config` file and attempts to get the credentials for the teleport enabled clusters using `tsh kube credentials` that `tsh` should log in to each cluster in a sequential manner (to prevent concurrent login attempts from corrupting the `.tsh/known_hosts` file), OR for there to be a locking mechanism around `tsh` usage of the `known_hosts` file so that concurrent logins can be completed without the resulting `known_hosts` file ending up in a corrupted state.

Why this is likely a `tsh` related issue is that there _should be_ no other programs editing the `.tsh/known_hosts` file as all they know is to call the `tsh kube credentials` command as defined in the `.kube/config`. Since no other programs are opening `.tsh/known_hosts` in a read/write mode there is no other culprit as to what program is corrupting the file (from my understanding).

So multiple concurrent login attempts are all editing the `known_hosts` file and causing it to have errors in it, causing subsequent reads of the `known_hosts` to cause a failure in the `tsh` command:
`Unable to fetch certificate authorities: illegal base64 data at input byte 3. client/keyagent.go:393`
