### ISSUE TITLE
Copy/paste event should contain hash of contents

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#15399]
Add audit event that is emitted when copy/paste occurs in Server Access and Desktop Access and include hash of content.

Don't include actual content as it may contain sensitive data (PII, passwords, etc).

Make sure the event is consistent in Server Access and Desktop Access.

**Comment by zmb3** [comment]
This is for desktop access only since we aren't doing any sort of copy-paste detection for server access.

**Comment by ibeckermayer** [comment]
Double checking that we really want a hash here, i.e. something like SHA-256. 

I could well be missing something, but at first glance it seems like this would be more or less meaningless to an auditor. They would essentially have to guess the contents of a copy/paste, run it through SHA-256, and see if it matches the hash, in order to gain any relevant information (iow they sorta have to break SHA-256). 

Maybe it makes more sense to encrypt contents with one of Teleport's certificate keypairs (using i.e. RSA). That way no sensitive data is stored plain to disk, but a Teleport admin/auditor with access to the private key can still see it.
