### ISSUE TITLE
Include file information on upload/download audit events

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#15396]
Include file information on upload/download audit events for Server and Desktop Access.

* For Server Access, include full path, filename, and size
* For Desktop Access, because we are implementing directory sharing\*, we'll audit whenever the filesystem has changed

_\* Note: With directory sharing you never transfer a full file, you get a bunch of little requests to update some small range of bytes in a file. So we can't capture size easily._

**Comment by zmb3** [comment]
I'm not so sure about "type" - what are the valid types and how would we determine the type of the file? Are you requesting some sort of introspection to detect file type?

**Comment by russjones** [comment]
@r0mant @zmb3 When we work on this one, let's make sure the events that Server Access and Desktop Access are consistent with each other.

**Comment by russjones** [comment]
The following should also be addressed at the same time. We may get it for free with the switch to sftp.

* https://github.com/gravitational/teleport/issues/9959

**Comment by capnspacehook** [comment]
For Server Access at least, `tsh scp` now uses SFTP which emits an audit event for every SFTP operation, which there are multiple for a file transfer. A normal file transfer will usually go something like this:

- Stat
- Open
- Write
- Write ...
- Close

Since SFTP is a more generic protocol than SCP, clients may just read or change attributes of remote files without transferring any. But in the case that `tsh scp` is used, `tsh` could communicate to a Teleport Node details of files getting transferred, maybe via a special SSH subsystem we create for this purpose and then emit a summary audit event. Otherwise we could try to analyze SFTP operations and determine if files are being copied and emit a summary audit event, though that would be much more difficult to do reliably.
