### ISSUE TITLE
AWS friendly configuration

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1545]
## Description

* Have a way to deploy Teleport in the following fashion:

* Auth server should be in Auto scaling group
* Proxies should be in auto scaling group
* Audit logger should be set up with EFS (AWS version of NFS)
* Backend should be using Dynamo with auto scaling on
* The auth server and proxy should be using load balancer.

The following requirements should work:

* It should convey client IP address for both AWS ELBs (will use proxy protocol) and new style ELBs 

* Write this as a set of terraform scripts in examples as modules. 

https://github.com/gravitational/teleport/tree/master/examples/dynamodb

* Cloudformation is an option if it is possible to have quickstart guide on amazon.com

**Comment by MattiasGees** [comment]
We at Skyscrapers are trying to do the same (kinda). https://github.com/skyscrapers/terraform-teleport

We are now at a stage where we try to get it working on ECS. But we are running into some problems. The problems we have are:
- We have NLB (for CLI, Tunnel and Node) and we have an ALB (for web). This causes us to needing two seperate hostnames and when we want to use `tsh` we have to define the proxy every time.
- Because we run it in containers it is harder to get access to the server and run `tctl`. There is already an issue https://github.com/gravitational/teleport/issues/1525

This is not complete the same as running it on ec2 instances but I think you will run into some of the same issues. Maybe you as creators have some feedback?

Our work in progress to get it running on ECS can be found here https://github.com/skyscrapers/terraform-teleport/tree/feature/ecs/teleport-ecs

**Comment by klizhentas** [comment]
Thanks for sharing this is helpful. I will look into this next week as I'll start digging into terraform stuff. Meanwhile, what's your rationale for using ALB? Is it just to get TLS certs?

**Comment by klizhentas** [comment]
implemented.
