### ISSUE TITLE
Proxy obscures client IP from auth service and nodes

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#15521]
When a client makes a connection to the auth server via the proxy, the real IP of the client is obscured, and the auth service instead sees the proxy's IP address.

This affects both the proxy's ssh reverse tunnel and the ALPN auth proxy ("teleport-auth@"). 

This is a problem because:
- We cannot include the client's real address (`remote.addr`) in audit logs emitted by the auth server. Where this is currently happening, the wrong address will be showing.
- Attempts to ratelimit connections using this address will misbehave
- We cannot correctly implement IP pinning in certificates generated by `GenerateUserCerts`
  - This impacts MFA session certificates, which by the spec are meant to be pinned to the IP (fortunately, this behaviour is currently not implemented correctly, otherwise connections made using per session MFA would be rejected in certain circumstances)
  - This prevents the implementation of https://github.com/gravitational/teleport/issues/13483
- We cannot pin certificates to an IP in relation to API actions (e.g tctl) until this is fixed. These are potentially very powerful actions in the case of an admin user.

Reproduction:
1. Start with an environment where you expect that your remote address will not be 127.0.0.1, e.g you are not operating your client on the same host as you will run the auth/proxy.
2. Create a client that will connect via the proxy SSH reverse tunnel (ALPN enabled or disabled)
3. Run the Ping RPC against the auth server (use `tctl status` with a custom build to output the `RemoteAddr` field.)
4. Inspect the RemoteAddr in the ping response, it will not be the IP you expect (instead showing the IP of the proxy)

## Solutions

Any solution needs to be secure. We cannot have a situation where a client that can connect directly to the auth server uses the solution here to be able to spoof their own IP address, as this compromises the integrity of certificate IP pinning.

Potential complications:
- It's possible for there to be layers between the proxy server and the auth server, in the case of a HA setup, there could even be a PROXY protocol enabled loadbalancer. Any solution must account for this sort of situation.
- There's no guarantee that an auth server will always not be accessible to the public. On some networks, user's may be able to connect directly, and on others, the user may connect via the proxy.

Useful facts:
- So far, when proxying via reverse tunnel or via the ALPN router, the proxy does not currently terminate the TLS connection.

Brain storming solutions:
- Encode client IP within a fresh identity and terminate the initial TLS: This appears to be how we currently handle this within the Database Access (see SignDatabaseCSR) element of the product. The proxy terminates the initial TLS connection and submits a CSR to the Auth Server to produce a certificate extremely similar to the client's but with the client IP added. This seems to make the most sense, as we are already using this implementation.
  - If we allow the Proxy to generate certificates for any user, are we potentially giving it a dangerous amount of power?
- TLS inside TLS : Theoretically, we could open a TLS connection authenticated as the proxy which could then provide some message that passes the client IP forward before then proxying the Client's TLS connection across this.

**Comment by zmb3** [comment]
See also #3557

**Comment by strideynet** [comment]
I've modified the ticket to reflect the fact that this affects both the SSH reverse tunnelling, and when using the "teleport-auth@" ALPN protocol to the auth service via the proxy.

**Comment by jentfoo** [comment]
@strideynet and @AntonAM  I wanted to check if this had been closed prematurely.  Following up from the conversation in the linked PR here: https://github.com/gravitational/teleport/pull/19008#issuecomment-1344566835

It sounded like another fix was still expected here.  Did that fix occur and just not get associated to this issue?  

Additionally can you confirm that this is a concern for IP Pinning bypass?  Thank you!

**Comment by AntonAM** [comment]
@jentfoo second portion was not merged yet, so yes, we can keep this issue open until it is. First part of the fix added IP propagation from client to auth server through ALPN. Second one is adding propagation through SSH paths and general client IP propagation throughout whole Teleport infrastructure. Some concerns about performance were raised so had to accommodate that in implementation and that unfortunately took longer time, but it's on its way.

I think it's probably not concern of IP Pinning as it's implemented now, as it was only implemented for accessing nodes (there's no IP pinning on TLS connections), but this issue is basis for improving IP Pinning implementation to make it general.

**Comment by jentfoo** [comment]
Thank you @AntonAM, that is very helpful.  When the PR is ready just mention this issue and add myself.  Thank you!

**Comment by AntonAM** [comment]
This issue is fixed by the work on IP pinning/IP propagation, according to [RFD#110](https://github.com/gravitational/teleport/blob/master/rfd/0110-ip-pinning-and-propagation.md). We now provide real client IP to the auth server or nodes either using signed PROXY headers or inside proxy dial requests when using tunnelled connections. Basically every communication with Teleport is affected, since ever call to the `authorizer.Authorize()` checks IP pinning, so if user has IP pinning enabled and their IP is not correctly propagated connection will be just denied.

Main PRs that contributed to this:
- https://github.com/gravitational/teleport/pull/19008
- https://github.com/gravitational/teleport/pull/21080
- https://github.com/gravitational/teleport/pull/24743

cc @jentfoo

**Comment by jentfoo** [comment]
Thank you for summarizing the fix here @AntonAM, those last two PR's had escaped my attention.  Everything looks good to me, I have no further recommendations so closing this as `Mitigated`.  Thank you again!
