### ISSUE TITLE
Disable local auth in helm chart

### ISSUE THREAD

**Issue by navi86** [gravitational/teleport#15652]
Expected behavior:
base on this example
https://github.com/gravitational/teleport/blob/master/examples/chart/teleport-cluster/values.yaml#L21
I was expected that
```
authentication:
  type: github
  localAuth: false
```
Would allow to disable local authentication and enable GitHub authentication. But it doesn't work, because latest version of helm chart doesn't have these changes yet 10.1.4. Could you publish new helm chart release ?
Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by hugoShaka** [comment]
Closing because requested feature is part of 10.1.9.

Bugfix releases are usually made within two weeks, three at most. It takes longer for us to triage issues than the usual bugfix release cycle.

The core issue is that our docs can be 2 to 3 weeks in the future compared to our releases, I understand this is a bad user experience and will bring this to the documentation team to see how we can improve.
