### ISSUE TITLE
Login using API

### ISSUE THREAD

**Issue by Myothas** [gravitational/teleport#15786]
**What would you like Teleport to do?**
Is there a non time restraint way to login to teleport without user interaction?
Currently all actions seem to require a user to run tsh login... This puts a time restraint on all subsequent auths as the max ttl controls the length of the session.

I would like to be able to have a long lived token which I can use to authenticate to Teleport and in turn login to applications with.
The goal is to be able to create a tunnel between applications in different clusters without requiring human interaction.

I have looked at Machine ID's with tbot, however in order to create one I need to run the command myself. They are also app specific which doesn't suit my needs.

**What problem does this solve?**
Secure application to application traffic.

**If a workaround exists, please include it.**
None that I have found.

**Comment by zmb3** [comment]
Machine ID is the most secure way to do this, as it will continuously renew a short-lived credential, limiting the risk of compromise. The idea would be to run `tbot` as a background service on whatever machine you need to perform actions without user interaction on.

Alternatively, you can generate a long lived credential with `tctl auth sign`, but we don't recommend long lived credentials due to the security risks involved.
