### ISSUE TITLE
U2F spam when running `tsh --debug`

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#15798]
Any operations which require tapping a security key for `tsh` when `--debug` is provided results in the following spam. While this doesn't seem to prevent interacting with the security key it is very noisy and could cause users to miss the prompt.

```
Tap any security key
            DEBU Error interacting with U2F devices error:[
ERROR REPORT:
Original Error: trace.aggregate hid: privilege violation
Stack Trace:
	teleport/lib/auth/webauthncli/u2f.go:134 github.com/gravitational/teleport/lib/auth/webauthncli.runOnU2FDevicesOnce
	teleport/lib/auth/webauthncli/u2f.go:76 github.com/gravitational/teleport/lib/auth/webauthncli.RunOnU2FDevices
	teleport/lib/auth/webauthncli/u2f_login.go:116 github.com/gravitational/teleport/lib/auth/webauthncli.U2FLogin
	teleport/lib/auth/webauthncli/api.go:144 github.com/gravitational/teleport/lib/auth/webauthncli.crossPlatformLogin
	teleport/lib/auth/webauthncli/api.go:128 github.com/gravitational/teleport/lib/auth/webauthncli.Login
	teleport/lib/client/mfa.go:222 github.com/gravitational/teleport/lib/client.PromptMFAChallenge.func3
	/usr/local/go/src/runtime/asm_amd64.s:1594 runtime.goexit
User Message: hid: privilege violation] webauthncli/u2f.go:80
            DEBU Error interacting with U2F devices error:[
ERROR REPORT:
Original Error: trace.aggregate hid: privilege violation
Stack Trace:
	teleport/lib/auth/webauthncli/u2f.go:134 github.com/gravitational/teleport/lib/auth/webauthncli.runOnU2FDevicesOnce
	teleport/lib/auth/webauthncli/u2f.go:76 github.com/gravitational/teleport/lib/auth/webauthncli.RunOnU2FDevices
	teleport/lib/auth/webauthncli/u2f_login.go:116 github.com/gravitational/teleport/lib/auth/webauthncli.U2FLogin
	teleport/lib/auth/webauthncli/api.go:144 github.com/gravitational/teleport/lib/auth/webauthncli.crossPlatformLogin
	teleport/lib/auth/webauthncli/api.go:128 github.com/gravitational/teleport/lib/auth/webauthncli.Login
	teleport/lib/client/mfa.go:222 github.com/gravitational/teleport/lib/client.PromptMFAChallenge.func3
	/usr/local/go/src/runtime/asm_amd64.s:1594 runtime.goexit
User Message: hid: privilege violation] webauthncli/u2f.go:80
            DEBU Error interacting with U2F devices error:[
ERROR REPORT:
Original Error: trace.aggregate hid: privilege violation
Stack Trace:
	teleport/lib/auth/webauthncli/u2f.go:134 github.com/gravitational/teleport/lib/auth/webauthncli.runOnU2FDevicesOnce
	teleport/lib/auth/webauthncli/u2f.go:76 github.com/gravitational/teleport/lib/auth/webauthncli.RunOnU2FDevices
	teleport/lib/auth/webauthncli/u2f_login.go:116 github.com/gravitational/teleport/lib/auth/webauthncli.U2FLogin
	teleport/lib/auth/webauthncli/api.go:144 github.com/gravitational/teleport/lib/auth/webauthncli.crossPlatformLogin
	teleport/lib/auth/webauthncli/api.go:128 github.com/gravitational/teleport/lib/auth/webauthncli.Login
	/teleport/lib/client/mfa.go:222 github.com/gravitational/teleport/lib/client.PromptMFAChallenge.func3
	/usr/local/go/src/runtime/asm_amd64.s:1594 runtime.goexit
```

**Comment by GavinFrazar** [comment]
I had this issue too.

On OSX it's caused by yubikey acting as a keyboard device.

Relevant info from https://developers.yubico.com/yubikey-manager:
```
Input Monitoring access on MacOS
When running one of the ykman otp commands you may run into an error such as: Failed to open device for communication: -536870174. This indicates a problem with the permission to access the OTP (keyboard) USB interface.

To access a YubiKey over this interface the application needs the Input Monitoring permission. If you are not automatically prompted to grant this permission, you may have to do so manually. Note that it is the terminal you are using that needs the permission, not the ykman executable.

To add your terminal application to the Input Monitoring permission list, go to System Preferences -> Security & Privacy -> Privacy -> Input Monitoring to resolve this.
```

The magical number `-536870174` (hex conversion: -0x1ffffd1e) corresponds to `kIOReturnNotPermitted`, which isn't the same as `kIOReturnNotPrivileged` (hex: -0x1ffffd3f). But I realized I had already configured my security settings to allow my terminal Input Monitoring permission. So I tried removing that permission, and sure enough the error message in our debug log changed from `hid: privilege violation` to `hid: not permitted`. So it's caused by some MacOS bug possibly?

In any case, you can stop your yubikey from pretending to be a keyboard by disabling OTP over USB:
`ykman config usb --disable OTP`

This stops the error from occuring at all and doesn't spam up my terminal anymore in debug mode.

I discussed this with @codingllama who was the one who pointed me to this opened issue. I see two viable paths here:
1. Check the error message for `hid: not permitted` or `hid: privilege violation` and convert the error into a message telling the user to disable OTP for yubikey (idk what other devices this can affect, I only have yubikey)
2. Ignore the error message completely
3. A combination of 1 and 2: Log the message *once* and give the user some info about how to disable OTP on a yubikey

What do you guys think?

**Comment by GavinFrazar** [comment]
Additional info about OSX: https://stackoverflow.com/questions/13629199/how-can-a-daemon-user-access-hid-devices-without-getting-kioreturnnotprivileged/23478172#23478172

**Comment by codingllama** [comment]
Hey Gavin, thanks for posting your findings and a pathway to mitigation, very educational.

I think 2. is the way to go. We could log info about disabling OTP, but I would assume most users would never read/act on it, given that the system still works. Printing an actual user message, as opposed to a logging statement, seems a bit too much.

Just a reminder: the U2F "backend" in tsh is mostly used by Teleport developers now. Our official builds use libfido2 (Linux and macOS) and WebAuthN.dll (Teleport >=11, Windows). We've kept the U2F backend as a fallback for libfido2 and because it's convenient for developers, but it's not a priority right now.

(That said I'm happy to take a PR, it should be relatively simple to put together.)
