### ISSUE TITLE
`TestRoleDeletionDrift` flakiness

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#15815]
#### Link(s) to logs

- https://console.cloud.google.com/cloud-build/builds/42e166e3-f9d3-4c79-8ce1-c24ba876db1a?project=ci-account

#### Relevant snippet

```
        	Test:       	TestRoleDeletionDrift
        	Error:      	Condition never satisfied
        	            				role_controller_test.go:257
        	Error Trace:	suite_test.go:52
    suite_test.go:52: 
--- FAIL: TestRoleDeletionDrift (9.06s)
```

**Comment by hugoShaka** [comment]
According to the logs the operator creates the role, the test removes it from Teleport, but somehow the operator creates it back, likely a subsequent reconciliation triggered by a status update not already processed (we're really inefficient right now as status update also trigger updates, diff-ing should reduce the amount of reconciliations). We then wait for the role deletion and fail.

```
time="2022-08-24T18:49:35Z" level=info msg=role.created cluster_name=root.example.com code=T9000I ei=0 event=role.created expires="0001-01-01T00:00:00Z" fields.time="2022-08-24T18:49:35.33Z" name=role-fc93p trace.component=audit uid=a9a60b18-06bb-430a-ba34-744ebbca0c8b user=operator-r9b8j
time="2022-08-24T18:49:35Z" level=info msg=role.created cluster_name=root.example.com code=T9000I ei=0 event=role.created expires="0001-01-01T00:00:00Z" fields.time="2022-08-24T18:49:35.527Z" name=role-fc93p trace.component=audit uid=2e18387c-b96a-4b2a-9b9a-740bc144925a user=operator-r9b8j
time="2022-08-24T18:49:35Z" level=info msg=role.deleted cluster_name=root.example.com code=T9001I ei=0 event=role.deleted expires="0001-01-01T00:00:00Z" fields.time="2022-08-24T18:49:35.547Z" name=role-fc93p trace.component=audit uid=18b04336-2474-42bc-8b64-fb5eef7bb5ab user=operator-r9b8j
time="2022-08-24T18:49:35Z" level=info msg=role.created cluster_name=root.example.com code=T9000I ei=0 event=role.created expires="0001-01-01T00:00:00Z" fields.time="2022-08-24T18:49:35.552Z" name=role-fc93p trace.component=audit uid=8c694b5d-44c1-4be5-9380-b927658d8248 user=operator-r9b8j
```

It's the operator's job to create the resource back, so I think the issue lies within the racy test suite and not the operator. To test drift-resistance we should have a way to guarantee the operator is not going to reconcile while we're editing the state. Ideally we would stop the operator, make the state drift, eventually change Kubernetes resources, and resume reconciliation.

Here it's is a bit tricky as it's we're deleting the kube resource. If we completely remove the resource the suspended operator will either block deletion (with its finalizer) or won't be aware of the deletion. It means we have to do an async delete: flag the resource for deletion but don't block waiting for its deletion. I don't know if the `DeletionOptions.PropagationPolicy` will od the trick. Else we'll need to patch the resource with a deletion timestamp manually.

On an higher-level, I think being able to run one-shot reconciliations in the test suite would be nice. I have no idea how to do it, but this would allow to remove all those `eventually` and reduce the risk of flakiness.

cc @marcoandredinis
