### ISSUE TITLE
Multiplexer Error

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#1594]
See this sometimes in Teleport logs. The last time I saw is when I tried launching the Web UI (does not always happen when I do this).

```
WARN [MUX]       "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 127.0.0.1:3080->127.0.0.1:38814: i/o timeout\nStack Trace:\n\t/home/rjones/Development/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:254 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/home/rjones/Development/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:194 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/usr/local/go/src/runtime/asm_amd64.s:2198 runtime.goexit\nUser Message: failed to peek connection\n" multiplexer/multiplexer.go:199
WARN [MUX]       "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 127.0.0.1:3080->127.0.0.1:38816: i/o timeout\nStack Trace:\n\t/home/rjones/Development/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:254 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/home/rjones/Development/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:194 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/usr/local/go/src/runtime/asm_amd64.s:2198 runtime.goexit\nUser Message: failed to peek connection\n" multiplexer/multiplexer.go:199
WARN [MUX]       "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 127.0.0.1:3080->127.0.0.1:38820: i/o timeout\nStack Trace:\n\t/home/rjones/Development/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:254 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/home/rjones/Development/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:194 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/usr/local/go/src/runtime/asm_amd64.s:2198 runtime.goexit\nUser Message: failed to peek connection\n" multiplexer/multiplexer.go:199
WARN [MUX]       "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 127.0.0.1:3080->127.0.0.1:38818: i/o timeout\nStack Trace:\n\t/home/rjones/Development/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:254 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/home/rjones/Development/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:194 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/usr/local/go/src/runtime/asm_amd64.s:2198 runtime.goexit\nUser Message: failed to peek connection\n" multiplexer/multiplexer.go:199
```

**Comment by klizhentas** [comment]
I haven't seen this bug actually, so going to move this to 2.5.1 then

**Comment by klizhentas** [comment]
not happening any more, closing

**Comment by aashley** [comment]
Getting this error after upgrading to 2.7.4 from 2.6.7

Sep 19 03:02:44 ip-172-32-1-157 teleport[9784]: WARN [MX:1]      "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 172.32.1.157:3025->172.32.3.246:57028: i/o timeout\nStack Trace:\n\t/gopath/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:257 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/gopath/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:197 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:2338 runtime.goexit\nUser Message: failed to peek connection\n" multiplexer/multiplexer.go:199
Sep 19 03:02:44 ip-172-32-1-157 teleport[9784]: WARN [MX:1]      "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 172.32.1.157:3025->172.32.3.246:56266: i/o timeout\nStack Trace:\n\t/gopath/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:257 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/gopath/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:197 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:2338 runtime.goexit\nUser Message: failed to peek connection\n" multiplexer/multiplexer.go:199
Sep 19 03:02:44 ip-172-32-1-157 teleport[9784]: WARN [MX:1]      "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp 172.32.1.157:3025->172.32.3.246:57220: i/o timeout\nStack Trace:\n\t/gopath/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:257 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/gopath/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:197 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/opt/go/src/runtime/asm_amd64.s:2338 runtime.goexit\nUser Message: failed to peek connection\n" multiplexer/multiplexer.go:199

**Comment by aaraujo-nydig** [comment]
Hi @aashley, did you manage to solve this? I'm getting the same error.

**Comment by webvictim** [comment]
As clarification for anyone else who finds this bug in future, this message is generated by Teleport's multiplexer which allows HTTP, TLS and SSH listeners on the same port. The multiplexer runs when you have `proxy_service.listen_addr` and `proxy_service.tunnel_listen_addr` configured to be on the same port (often 3080). It inspects the first few bytes of any incoming connection to determine what protocol the connection expects, then routes the requests accordingly.

The tunnel port (defaults to 3024, but can be multiplexed on 3080) is used for incoming connections from Teleport [trusted clusters](https://gravitational.com/teleport/docs/trustedclusters/), as well as connections from nodes using [Teleport IoT/node tunnelling](https://gravitational.com/teleport/docs/admin-guide/#adding-a-node-located-behind-nat)

If you're getting this error, it's usually because there is traffic coming into the multiplexer port which Teleport does not know how to route. This can sometimes be due to TCP health checks from a load balancer. It can also potentially be the case if you have something misconfigured to send traffic to Teleport when it should be going somewhere else.

If you need assistance with this or any other problem, please open a topic on our Community forum - https://community.gravitational.com/
