### ISSUE TITLE
Mosh Everywhere

### ISSUE THREAD

**Issue by tomberek** [gravitational/teleport#1595]
This is to start discussion about implementing the use of [mosh](https://mosh.org/) throughout teleport.
Pros:
- reconnections
- latency
- embedded systems
- roaming

Cons: 
- complexity
- dependencies

**Comment by klizhentas** [comment]
I think SSP is a really smart protocol and mosh solves an important problem, but for exactly the cons you have mentioned, this is out of scope of teleport - at least for now.

I'm keeping the door (and issue) open, as I think at some point teleport should promote innovative solutions for the problems folks are facing when working with remote terminals. So folks who care, use this ticket to post your thoughts and feedback here, we'll use it as a reference.

**Comment by remingtonc** [comment]
Huge fan. Hate it when I'm in transit with low-bandwidth or my VPN decides it's time to reconnect and my SSH sessions break. Mosh is absolutely seamless in these scenarios. No idea on the level of difficulty, unfortunately.

**Comment by dadicool** [comment]
Just faced a situation where mosh + teleport would have made my life much less miserable: I've been trying to connect to k8s pod over a vpn connection over 4G while traveling on a fast moving train. Needless to say, I couldn't really fix the problem. I would love to see this implemented!

**Comment by CryptoLunatic** [comment]
Just want to throw in my +1 for this - I use mosh for every host that I connect to for shell access. I'm looking to improve my security, and Teleport has been the most enticing solution I have found. Mosh compatibility was the very first thing I looked up after reading the Quick Start and Architecture guides - This looks like a no-brainer solution to security concerns about SSH (mainly for me, it's the widespread use of SSH keys), but the lack of mosh support has me seriously torn about whether or not I want to implement Teleport.

**Comment by shaneshort** [comment]
I would also love to see mosh support. I'm very often on poor connections (loss/latency) and it's a life saver for me. I also love the statelessness of it, having your WAN link drop and the session just blissfully resume is amazing.

**Comment by keenan-v1** [comment]
Without support, is there a mosh workaround that people have found by chance?

Also +1 for mosh support from 2021 :) 👍

**Comment by vikashch** [comment]
+1 for mosh support.

**Comment by eggbean** [comment]
Came here looking to find out if Teleport supported mosh. Very much looking forward to it being added, as it's something I have been using for years and I've come to depend on it when working remotely, just to connect to my bastion host. I'll probably be using Teleport mainly for server webpage access for the time being.

**Comment by jurajmasar** [comment]
+1 🙏

**Comment by james-lawrence** [comment]
@klizhentas sorry for the bump but teleport might want to consider the quic protocol for transport vs mosh's ssp. It doesn't come with everything but in theory it'd help with the poor connection, roaming and latency issues and can be done fairly transparently and should be fairly trivial to seamlessly upgrade servers.

**Comment by BinaryPaean** [comment]
+1 🙏

**Comment by cwegener** [comment]
I've been reading through comments and most people seem to be highlighting the "slow or unreliable carrier" scenario.

What about the speed of light scenario?

Is nobody using mosh for the local echo feature when the photons need to travel a long distance (tens of thousands of kilometers)?

**Comment by eggbean** [comment]
@cwegener A couple of years ago there was a digital nomad on reddit saying that it was very difficult to access his servers in the USA from Thailand, so I told him about mosh and he thought it was magic.

**Comment by shaneshort** [comment]
.. I opened this page to check on it not an hour ago and now there's activity! 

I agree, some kind of session resumption and local echo like mosh makes long distance SSH actually bearable and would be an excellent addition. Either implementing the features mosh needs in order to orchestrate the udp connection, or implementing it inside teleport would be nice.

**Comment by cwegener** [comment]
I think in summary there are few main use cases then:

1. Regular normal SSH duties from a reliable and fast last mile hookup, involving SSH hosts that are "far away" (@eggbean's Digital Nomad is one example. But other "far away" scenarios do exist that don't involve digital nomads)
2. Occasional duties where the last mile hookup (on either side) has poor performance qualities (high jitter, high packet loss), e.g. urgent SSH access while being on-call using mobile internet.
3.  (Somewhat reverse of 3) Urgent or not so urgent SSH  access while being on a high quality local last mile hookup but the remote SSH host is on either a poor quality last mile hookup or an unreliable last mile hookup. E.g. IoT devices

I think all three above uses cases can also be combinations of each other.

The two main features from mosh that are relevant to these use cases are:

- Local Text Echo
- Seamless Session Re-establishment on disconnect

I have no idea which one of these use cases would be the most valuable for the wider Teleport community to implement.

In general though, I think that think in terms of the two distinct features and how they relate to use cases would be the best in order to reinvigorate this discussion.

**Comment by alexlyee** [comment]
+1 🙏 this would make working on infra with a spotty connection so much better

**Comment by nilx** [comment]
+1 here

* my everyday job involves working remotely on machines located on the other side of the earth. not a digital nomad, just working in global-scale company
* on weekend commutes I'm in a bullet train and sometimes want to make good use of the couple of hours over 5G; sometime I need to, because on-call duty matters

in both situations above, `mosh` is wonderful

**Comment by nilx** [comment]
What would it take to add mosh+teleport support?
- does it imply support for `mosh` protocol in `teleport` *and* support for `teleport` transport in `mosh`?
- would it fit in the current teleport architecture, as "just another protocol", or does it require design evolution?
- how much work would it take, roughly? 

ping @achernya for https://github.com/mobile-shell/mosh

**Comment by timiwahalahti** [comment]
Giving one more +1 here from a person who commutes often and sometimes needs to work via SSH connection during transit.

**Comment by Gunni** [comment]
Typically mosh sessions are established like the following:
- user types `mosh x`
- mosh invokes `ssh <some arguments>` that starts a mosh-server process on the remote system, listening on a UDP port, then disconnects the ssh connection, leaving mosh-server running
- the mosh client then connects to the UDP socket that the mosh-server started

This only works if you can both ssh to a host AND connect to the udp port it listens to.

I am thinking about tunneled end devices, not directly connected where inbound connections are no problem, those cases are simpler, i think.

In teleport, it would need to be changed to something like:
- user types `tsh mosh x`
- tsh would then need to start some kind of mosh-server on the relaying server that the users tsh mosh client connects to via udp
- the relaying server then needs to have the end device somehow connect to this session, and it needs to use UDP to retain the advantages of mosh, imagine reverse mosh, where the client connects to the server but the server gets shell on the client side?
- the relaying server needs to reap sessions when they need to expire to not leave dangling sessions everywhere, "disconnected" has no meaning here, so maybe when their tsh session expires or something

Only connection setup needs to use TCP (via the control channel), everything else must use UDP to maintain the features of mosh.

**Comment by Gunni** [comment]
😭

**Comment by keenan-v1** [comment]
@zmb3 Is it possible to get some clarification on why this isn't planned?

**Comment by zmb3** [comment]
I appreciate the interest, and definitely understand the motivation for the feature request. We've evaluated Mosh several times in the 6 years this issue has been open and have not been able to justify it.

We are instead focusing on QUIC, which offers a lot of similar advantages (UDP-based, friendlier to clients roaming on multiple networks, performs better on slow networks, faster connection establishment, session resumption, etc...)

**Comment by jaens** [comment]
@zmb3 

The main feature of mosh is local terminal prediction, which is the **only** thing that can decrease perceptible latency.

QUIC on its own is just a protocol and does not help with interactive latency or packet loss if the application level protocol stays the same (eg. when tunneling regular SSH streams over QUIC).

To gain any benefits at all, QUIC requires a packet-loss-tolerant **application-level** protocol as well.

 Is teleport planning to implement custom terminal prediction on its own? Because otherwise QUIC will do practically nothing to alleviate the problems and use cases mentioned in this issue.
