### ISSUE TITLE
Query params and fragment are not preserved on initial request to proxied app

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#15998]
Expected behavior:

I open a new private window, go to `https://proxied-app.teleport-cluster/arbitrary/path/?foo=bar#quux`. I go through the login procedure and get redirected to `https://proxied-app.teleport-cluster/arbitrary/path/?foo=bar#quux`.

Current behavior:

As described above but I get redirected to `https://proxied-app.teleport-cluster/arbitrary/path/` instead.

This is important to apps which carry important data in query params or in the fragment of the URL.

Bug details:
- Teleport version: `8f6f6ccbb` (branch/v10), `e076f7835` (master)
- Recreation steps: described above
- Debug logs: none

gz#6770

**Comment by zmb3** [comment]
@avatus @sclevine didn't you all just make some changes here?

**Comment by avatus** [comment]
@zmb3 we added the requested _path_ to the redirect. This ticket is to also add any requested query params to the path as well. [discussed here](https://github.com/gravitational/teleport/pull/15628#issuecomment-1232787209)

**Comment by programmerq** [comment]
the go library in question treats the path, query string, and fragment separately. Both the query string and fragment should be included in this fix.

Additionally, if a user navigates to an app access URL without being logged in to teleport itself, the path portion of the app access page is not preserved at all:

a) Open private Chrome tab
b) Navigate to https://app.cluster.example.com/foo/bar/baz
c) Get redirected to https://cluster.example.com/web/login?redirect_uri=https://cluster.example.com/web/launch/app.cluster.example.com%3Fpath%3D%foo%252Fbar%252Fbaz
d) Login with IDP
e) Redirect works
Now, where things start to get weird:
f) Navigate to https://cluster.example.com/
g) Log out
h) Repeat b) - go to https://app.cluster.example.com/foo/bar/baz
i) Get redirected to https://cluster.example.com/web/login?redirect_uri=https://cluster.example.com/web/launch/ssoprovider (and path is not preserved anymore)
j) Login with IDP
k) Redirect to the default app URL instead of the requested URL

I wasn't sure whether this issue would cover this latter concern. If not, I can open up a dedicated issue for the path being lost during login/idp

**Comment by olidacombe** [comment]
Is there any progress on this?  It's definitely an issue for us.

**Comment by sclevine** [comment]
> Both the query string and fragment should be included in this fix

Fragments are not sent to the server in requests, and some web apps use them to store data that should not leave the browser for security/privacy reasons. Would it be worth making fragment preservation configurable per-app?

**Comment by r0mant** [comment]
This was implemented, except for the fragment which we can't (easily) preserve because it doesn't get sent to the backend.
