### ISSUE TITLE
Check links in the changelog

### ISSUE THREAD

**Issue by ptgott** [gravitational/teleport#16050]
## Details

Our changelog, [`CHANGELOG.md`](https://github.com/gravitational/teleport/blob/09cd4bfdd8d2ad82ad7bd187be6ed4b8493c13b1/CHANGELOG.md), which is included as a partial in [`docs/pages/changelog.mdx`](https://github.com/gravitational/teleport/blob/09cd4bfdd8d2ad82ad7bd187be6ed4b8493c13b1/docs/pages/changelog.mdx), has a lot of links with outdated URLs. These often lead to 404s or long redirect chains. These URLs use schemes and domain names, so our link checker doesn't pick them up. 

We should change all `https://goteleport.com` or `https://gravitational.com` links in the changelog to use the `./docs/pages/filename.mdx` format so our link checker can check them. This would mean that visitors to `CHANGELOG.md` in GitHub would see links to MDX files, but I think that's fine—visitors to `/docs/changelog` in the docs site will see the intended links to other pages in the docs site.

### Category
- Improve Existing

**Comment by alexfornuto** [comment]
@ptgott can you confirm that this has been resolved by #22503?

**Comment by ptgott** [comment]
Not yet!

```
grep -nE "\]\(https://(gravitational|goteleport).com.*\)" CHANGELOG.md | wc -l
      18
```

**Comment by alexfornuto** [comment]
I encountered a strange issue while trying to resolve this: https://github.com/gravitational/teleport/pull/25155#issuecomment-1524010694

**Comment by alexfornuto** [comment]
@ptgott per my comment in the PR, it looks like we can't have a relative links that work for both GitHub and Docs, since the page is viewed from different paths (Docs uses the main CHANGELOG file as an include). As I see it, our options are:

- Do nothing.
- Use soft symlinks to put the CHANGELOG under `docs/` so relative links work while maintaining a presence in the project root.

Do you have additional ideas for resolution, or wanna 👍 one of these suggestions?

**Comment by ptgott** [comment]
The docs engine rewrites relative link paths within partials to be from the including page, so a link in `CHANGELOG.md` to `docs/pages/index.mdx` would become a link to `./index.mdx` in `docs/pages/changelog.mdx`. At least, that's the intended behavior. If there's an issue with this, we can look into it in `gravitational/docs`!
