### ISSUE TITLE
Feature request: adding 2FA users via CLI

### ISSUE THREAD

**Issue by tomberek** [gravitational/teleport#1620]
**What happened**:
Created a new user via tctl

**What you expected to happen**:
I expected it would be possible to complete a new user creation via CLI.

**Comment by kontsevoy** [comment]
@tomberek question for you: how would you activate 2FA for such user? From a security perspective the presence of a 2nd device is absolutely required.

**Comment by tomberek** [comment]
Manual entry. I forget the exact details right now, but I’ve done pairing of 2fa on command line before.

**Comment by tomberek** [comment]
Also kinda cool would be QR code in terminal!

Sounds like a different project.....

**Comment by kontsevoy** [comment]
We'll keep this open for a while, waiting for better ideas, but according to Teleport's design, a user and an admin are (usually) two different people, i.e. we default assumption they aren't in front of the same machine, that's why adding a user with 2FA requires sharing a link. Obviously sometimes it's the same person, so the convenience of such feature is understandable.

**Comment by ocraviotto** [comment]
@kontsevoy Another use case: create a service CI user (say `jenkins`) without sign-in access, required only so that we may then `tctl auth sign` keys in openssh format. 
We currently have a cron job in the auth node regenerating keys (with short ttl) for a particular service user and then putting them (scp) in another server (our Jenkins host) so that they may get used. 

We've manually created the users (the one the cron uses to connect to jenkins as well as the one jenkins uses to connect to other nodes) but it'd make life easier (and checking changes to teleport setup scripts in our testing env) if these _service_ users could be created programmatically.

**Comment by madsonic** [comment]
Another use case: If the proxy server is restricted to SSH access, user sign up would be impossible. 

Regarding the 2FA issue, the proxy server can be configured with PAM

**Comment by sh7dm** [comment]
What's about accepting the invite using `tsh`? Like this:
`tsh signup <token from URL>`

**Comment by zmb3** [comment]
There are no immediate plans to add this feature.
