### ISSUE TITLE
I need access ORACLE database from teleport and all audit envents like other proxy database

### ISSUE THREAD

**Issue by RyanCode** [gravitational/teleport#16233]
Does your team consider supporting the functions of Oracle database，it's efficient and important.

**Comment by zmb3** [comment]
This seems better suited for a discussion than an issue, as it is not a bug. Thank you for registering your interest.

Due to the proprietary nature of Oracle DB, adding support is not as straightforward as supporting an open source database. At this time, I can't say whether we will be able to support it or not.
