### ISSUE TITLE
Bring in some limits to the session list

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1632]
## Description

With many active sessions and active servers, current UI just crashes, because it shows all sessions happened in the last 3 days without hard limit.

## Proposal

Only show the last 100 sessions. If the session list exceeds the list, display the message:

```
showing last 100 sessions, please refine the search or time range
```

The reason I don't want to bring in pagination is mostly because it's useless - if there are many sessions, looking through all of them is not reasonable, so users are expected either to search or use date range.

**Comment by kontsevoy** [comment]
@klizhentas can you suggest a safe but larger number, so search would be more effective. it kind of doesn't matter how much fits into the screen or how useful scrolling can be, because we're optimizing for people zeroing in using search, i.e. you see 250+ results, then type your username and bam -> only see your 2-3 sessions.
