### ISSUE TITLE
How to access with Putty on windows to my server via SSH and record session

### ISSUE THREAD

**Issue by noriuky** [gravitational/teleport#1635]
Hi, i wish to record session using Putty on windows and ssh the ip address.

i have a single server which run teleport and work fine using webpage www.mysite.com:3080/web/login
if is possible can someone plz give me a step by step guido on how to edit config files on server and putty plz?
tnx

**Comment by aberoham** [comment]
At first glance, I don't think this is possible. 

With the new Recording Proxy Mode maybe it's not impossible?

https://stackoverflow.com/questions/28926612/putty-configuration-equivalent-to-openssh-proxycommand and https://www.vscentrum.be/client/windows/putty-proxy look promising as guides for how to make putty use a bastion. 

Why not simply use Teleport Proxy's web interface and its websockets-based web SSH terminal from the Windows machine you're trying to run putty on? That would be a lot easier.

**Comment by dgivens** [comment]
The best case I have figured out in this regard is to install the Windows Subsystem for Linux and a linux distribution under it, then install the linux build of `tsh` onto that, and then connect through the proxy. `tsh` is responsible for retrieving the SSH cert from the auth servers and loading that cert into your ssh key agent. Since `tsh` doesn't work on Windows, you can't get your cert from the teleport auth server for Putty to use.

**Comment by russjones** [comment]
Just checked on this and it looks like Putty still does not support OpenSSH certificates: https://www.chiark.greenend.org.uk/~sgtatham/putty/wishlist/ssh2-openssh-certkeys.html

Since Windows has native OpenSSH support now, let's close this ticket. For Windows users to supported path is either OpenSSH on the CLI or Web UI.

**Comment by webvictim** [comment]
For anyone who finds this issue in future, Teleport has supported using PuTTY 0.78 or higher to connect to Teleport SSH servers since the release of Teleport 14.0.0.

See the docs on using `tsh puttyconfig` to generate saved sessions for use with PuTTY: https://goteleport.com/docs/connect-your-client/putty/
