### ISSUE TITLE
Support configuring `app_service` in helm values.

### ISSUE THREAD

**Issue by junnplus** [gravitational/teleport#16363]
What would you like Teleport to do?

Support configuring `app_service` in helm values.

What problem does this solve?

Now if you use helm to install the teleport cluster, you need to manually execute the command or change the configmap to configure application access, not easy to automate.

If a workaround exists, please include it.

**Comment by hugoShaka** [comment]
App, database and kube access are handled by the `teleport-kube-agent` chart, which is different from the `teleport-cluster` chart. 

Configuring `app_service`, `db_service` and `kube_service` in the `teleport-cluster` chart is not supported out of the box because we strongly encourage users to split responsibilities between `teleport-cluster` and `teleport-kube-agent`. Splitting between the core cluster and the agents provides a better availability, scalability and the pattern allows multiple kubernetes clusters to connect to a single teleport-cluster with the same values.

In the `teleport-kube-agent` chart you can configure `app_service` through the following parameters:
- [`apps`](https://goteleport.com/docs/reference/helm-reference/teleport-kube-agent/#apps) for statically declared applications
- [`appResources`](https://goteleport.com/docs/reference/helm-reference/teleport-kube-agent/#appresources) to watch for dynamically declared applications 

If you still want to have the `teleport-cluster` chart run `app_service` (strongly discouraged) we suggest you use the `teleport-cluster` chart in [custom mode](https://goteleport.com/docs/deploy-a-cluster/helm-deployments/custom/) (you provide your own config to the chart) instead of editing resources deployed by Helm. Helm does not handles gracefully ressource drifts, in the best case you'll loose
