### ISSUE TITLE
12 UNIMPLEMENTED: resource type node does not support pagination

### ISSUE THREAD

**Issue by JamesHawkinss** [gravitational/teleport#16831]
Expected behavior:
The Teleport Connect client (Windows) will show a list of all available nodes on the nodes page.

Current behavior:
The Teleport Connect client (Windows) shows an error (`12 UNIMPLEMENTED: resource type node does not support pagination`) when on the nodes page. It is still possible to directly connect to a node by entering `tsh ssh username@node` to the command box.

Curious if this error is just caused by running Teleport v8, in conjunction with the new Teleport Connect client? Are the two incompatible? If so, any chance of backwards compatibility being implemented for this client?

Bug details:
- Teleport version: Teleport v8.3.16 git:v8.3.16-0-g70d2102b9 go1.17.10
- Recreation steps: Login to the Teleport Connect client (Windows), connect to a Teleport cluster running v8, observe
- Debug logs: None

**Comment by zmb3** [comment]
> Curious if this error is just caused by running Teleport v8, in conjunction with the new Teleport Connect client? Are the two incompatible? If so, any chance of backwards compatibility being implemented for this client?

Yes, they are incompatible. Teleport Connect follows the same versioning as other Teleport products. Clients can connect to a server that is of the same major version, or one major version newer. Since Teleport Connect is currently on v10, that means it can connect to v10 or v11 (which doesn't exist yet) Teleport clusters.

We won't be implementing support for v8 clusters in Teleport Connect because Teleport Connect did not exist when Teleport 8 was released.
