### ISSUE TITLE
ProvisionTokenV3 prevents cluster downgrades

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#16917]
With the changes in https://github.com/gravitational/teleport/pull/16361 it becomes impossible to downgrade from v11 to v10:

```
Re-init the cache on error: server resource version v3 is not supported.
```

Find an approach that allows for downgrading in case of an issue with the 11.0.0 release.

**Comment by r0mant** [comment]
Worth pointing out that that "server resource version v3" message is actually coming from trying to unmarshal provision token:

https://github.com/gravitational/teleport/blob/master/lib/services/provisioning.go#L109

Maybe fix that message as well :)

**Comment by strideynet** [comment]
As far as I can tell, introducing new resource versions within Teleport is always going to break downwards compatibility due to how we structure the `Unmarshal*` functions within `lib/services`.

This forces my hand a bit, we should address this in future but for now, I'll remove that work and produce an alternative build that leverages the existing `ProvisionTokenV2` resource.

**Comment by espadolini** [comment]
If it becomes possible to downgrade after deleting the offending resources then I think it's acceptable, isn't it? Isn't that how we handled most other resource version changes in the past too?

**Comment by strideynet** [comment]
I think the biggest issue is that it's not clear which resource you need to delete to fix this, as the error emitted by `Unmarshal*` doesn't specify the name/id of the resource.

I've raised #16933 to revert the work anyway, since I think releasing a patch version to 10.x.x to fix the error message may not be feasible.

**Comment by strideynet** [comment]
Closed by https://github.com/gravitational/teleport/pull/16933
