### ISSUE TITLE
Audit Logs: Displaying the actual kube command ran in the cluster in the audit logs

### ISSUE THREAD

**Issue by akgoteleport** [gravitational/teleport#16973]
What would you like Teleport to do?
Currently, if a user runs any command in the kube cluster, for exp- kubectl delete pod- this creates an event in the audit logs. To check the details about the request, the user has to click on the kube-request in Teleport UI > Audit Logs and then view the request. Nice to have the actual command ran in the cluster displayed in the Audi logs.

What problem does this solve?
Ease the navigation through the Audit logs.

If a workaround exists, please include it.
N/A

**Comment by russjones** [comment]
Improve what's being shown in the header.

**Comment by russjones** [comment]
@zmb3 Can you add more details on exactly what needs to be changed.

**Comment by vitorenesduarte** [comment]
I'm seeing the following 2 audit events being generated if I run e.g. `kube exec nginx-deployment-9456bbbf9-9dvdt date` (in my cloud tenant):

<img width="892" alt="Screenshot 2022-11-24 at 21 24 35" src="https://user-images.githubusercontent.com/4520516/203864859-d6ff44d9-987a-4761-b6a0-5f4396a31618.png">

Below are the contents of __Kubernetes Request__ (i.e. `kube.request`) and __Session Ended__ (i.e. `session.end`):

```json
{
  "addr.local": "...",
  "addr.remote": "...",
  "cluster_name": "vitor.teleport.sh",
  "code": "T3009I",
  "ei": 0,
  "event": "kube.request",
  "kubernetes_cluster": "vitor-dev",
  "kubernetes_groups": [
    "system:authenticated",
    "system:masters"
  ],
  "kubernetes_labels": {
    "teleport.internal/resource-id": "7a426893-c720-4baf-b234-2688606579cf"
  },
  "kubernetes_users": [
    "vitor.teleport.sh-vitor-dev"
  ],
  "login": "vitor-local",
  "namespace": "default",
  "proto": "kube",
  "request_path": "/api/v1/namespaces/default/pods/nginx-deployment-9456bbbf9-9dvdt",
  "resource_api_group": "core/v1",
  "resource_kind": "pods",
  "resource_name": "nginx-deployment-9456bbbf9-9dvdt",
  "resource_namespace": "default",
  "response_code": 200,
  "server_id": "...",
  "time": "...",
  "uid": "...",
  "user": "vitor-local",
  "verb": "GET"
}
```

```json
{
  "addr.remote": "...",
  "cluster_name": "vitor.teleport.sh",
  "code": "T2004I",
  "ei": 0,
  "enhanced_recording": false,
  "event": "session.end",
  "initial_command": [
    "date"
  ],
  "interactive": false,
  "kubernetes_cluster": "vitor-dev",
  "kubernetes_container_image": "nginx:1.14.2",
  "kubernetes_container_name": "nginx",
  "kubernetes_groups": [
    "system:authenticated",
    "system:masters"
  ],
  "kubernetes_labels": {
    "teleport.internal/resource-id": "7a426893-c720-4baf-b234-2688606579cf"
  },
  "kubernetes_node_name": "ip-192-168-77-72.us-west-2.compute.internal",
  "kubernetes_pod_name": "nginx-deployment-9456bbbf9-9dvdt",
  "kubernetes_pod_namespace": "default",
  "kubernetes_users": [
    "vitor.teleport.sh-vitor-dev"
  ],
  "login": "vitor-local",
  "namespace": "default",
  "participants": null,
  "proto": "kube",
  "server_hostname": "vitor.teleport.sh",
  "server_id": "...",
  "session_recording": "node",
  "session_start": "...",
  "session_stop": "...",
  "sid": "58b0fd5d-a037-400d-a1cd-4d2a9b859612",
  "time": "...",
  "uid": "...",
  "user": "vitor-local"
}
```

Is the idea that we change the web UI so that the __Session Ended__ description includes the `initial_command` (if present)?

**Comment by zmb3** [comment]
@vitorenesduarte today the audit log just says the following for all kube requests:

```
User [foo] made a request to kubernetes cluster [bar]
```

The issue with this is that all requests look exactly the same in the audit log view, and you have to click into the details and look at the JSON to tell them apart.

For this issue, the goal is to just change the description of the event in the audit log. I would include the request path, verb, and response code.

So that would change the title to something like

```
User [foo] received a 200 OK from /api/v1/namespaces/default/pods
```

The description for the event is set up here: https://github.com/gravitational/webapps/blob/ee5b12db69691096b8a451225a2b98094f710288/packages/teleport/src/services/audit/makeEvent.ts#L685-L690

The info here might also be helpful: https://github.com/gravitational/webapps#adding-an-audit-event

**Comment by vitorenesduarte** [comment]
Thank you for all the tips @zmb3. Opened https://github.com/gravitational/webapps/pull/1384.
