### ISSUE TITLE
Investigate and resolve Teleport and CentOS 7 integration issues

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#17046]
Investigate and resolve any issues that exist when using Teleport with OpenSSH on CentOS 7.

* Ensure Teleport SSH servers speak the cryptographic algorithms supported by the version of OpenSSH that ships with CentOS 7.
* Ensure that `tsh` generates configuration that can be used with `ssh` when connecting to Teleport servers.

**Comment by jakule** [comment]
There are currently two issues with OpenSSH 7 (installed in CentOS 7). Teleport is not able to connect to `sshd` as currently, the connection fails on the negotiation of the signing algorithm. This issue should be fixed by https://github.com/gravitational/teleport/pull/18181
The second problem is SSH tracing channel tracked as https://github.com/gravitational/teleport/issues/18183

**Comment by zmb3** [comment]
@jakule can we close this one now?
