### ISSUE TITLE
Display Allowed DB Logins in tsh status

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#17148]
**What would you like Teleport to do?**
Display the DB usernames that the Teleport user is allowed to log in to DBs with. 

Note: We already display allowed K8s users, ssh logins, and Databases. 

**What problem does this solve?**
Users do not know what DB logins they have available to them.

**Comment by russjones** [comment]
We show them in `tsh db ls`.

It's not clear if it makes sense to show them in `tsh status` and logins are specific to a particular database.

**Comment by r0mant** [comment]
@jkinkead If you see a wildcard in `tsh db ls`, it likely means that one or more of your Teleport roles allow you to connect with any database user to this particular database. Teleport does not have a way of enumerating all users within a database.

If you want to see specific database users you can connect as, I would recommend setting up your Teleport roles in a way that grant access to specific users rather than a blanket wildcard (which means "any"). So for example instead of:

```yaml
spec:
  allow:
    db_users: ["*"]
```

to allow any database user, you can set it up to be more specific e.g.

```yaml
spec:
  allow:
    db_users: ["postgres", "alice", "bob"]
```

Then they would show up in `tsh db ls` as well. Take a look at https://goteleport.com/docs/database-access/rbac/ for more information. Hope it helps.
