### ISSUE TITLE
Add Option to Expose Metrics Port in Helm Chart

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#17233]
**What would you like Teleport to do?**
The helm chart should have an option to expose port 3000 for metric gathering purposes. 

**What problem does this solve?**
Customers would like to access metrics about their Teleport Cluster. 

**If a workaround exists, please include it.**
Fork the Helm Chart and refactor it so that it exposes port 3000.

**Comment by hugoShaka** [comment]
I'm not sure what this issue is about.

If the customer wants to monitor individual pods from inside the cluster, they can already create a `PodMonitor`, this does not involve forking the chart. To ease this common use-case we already have an open issue: https://github.com/gravitational/teleport/issues/13260. This is a low hanging fruit and it definitely makes sense to add the feature to the chart. We can also add a headless service if this helps with less common monitoring stack (but Prometheus looks up endpoints directly, so it's not strictly required).

If this issue is about exposing the metrics port to workload living outside of the cluster, I'm afraid this will not allow the customer to gather useful nor accurate metrics. Each pod is reporting its own metrics and you have to monitor all the pods at the same time to have a full view of the cluster. Exposing metrics through a loadbalancer, like we do for the other ports, will randomly route the monitoring requests to different pods. The users will end up with incomplete and mostly useless metrics.

@corkrean could you help clarify the need behind the feature request?

**Comment by corkrean** [comment]
@hugoShaka Ahhh yes. You are definitely right. Exposing port 3000 through an LB would be useless. 

I will close this issue.
