### ISSUE TITLE
Provide web API for fetching database IAM policy

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#17395]
## Description

We're working on [Teleport Discover](https://github.com/gravitational/teleport/pull/13440) Day-1 experience for Database Access which will allow users to join their databases to the cluster using web UI based guided wizard flow, similar to what we've implemented for Server (and soon, Kubernetes) Access.

When adding an RDS/Aurora/Redshift database, one of the Discover wizard steps will ask the user to set up an IAM policy that will allow their database service to connect to it. For day-1 experience we don't want the user to worry about configuring auto-discovery and just want them to register the database, give Teleport permissions to access it and let them connect to it.

Teleport already knows what IAM policy is needed for a particular AWS database because it configures them during auto-discovery, but it doesn't expose an API to fetch this policy given a database name. This API will be used by the Discover wizard to fetch the policy and display an appropriate `aws` CLI command a user would need to run to set up access to the database they've just registered.

## Scope

Let's start with:

- [ ] RDS
- [ ] Aurora
- [ ] Redshift

but design the API in way so it can be extended to support other AWS-hosted (and potentially, non-AWS as well) resources when we get to adding them to Discover wizard.

## API

This is just a suggestion, feel free to tweak however appropriate during implementation, but I would imagine this API to be something like:

```
GET /webapi/sites/:site/db/:db/iam
```

The database named `:db` should already be registered in the cluster. For non-supported database (e.g. non-AWS for now like self-hosted) the API should return an error.

When called for an RDS database, the response would be something like:

```json
{
  "aws": {
    "policy": "policy text"
  }
}
```

Let's reuse the logic that currently handles auto-IAM configuration, factor it out and make sure that it's used by both this API and auto-IAM that database service runs.

**Comment by greedy52** [comment]
I got confused by the `aws iam create-policy` part from figma.

Are we creating a separate **managed** policy per database? I assume that's not the case since there is a limit on how many **managed** policies can be attached to a role/user (default 10, max 20).

So I think we want `aws iam put-role-policy` for **inline** policies? If so, the same question applies whether we are doing a separate inline policy per database, or all databases will share the same inline policy like in the auto-iam logic. Ideally, all databases should share a single inline policy to avoid potential duplications. But that's not always feasible in discovery flow as the Proxy/DB agent may not have `GetRolePolicy` permission to get the current state.

To make the aws cli command, we also need to know the AWS identity of the DB agent. Will the user manually provide it or we should go fetch the identity from the DB agent?

**Comment by greedy52** [comment]
one other alternative would be asking the user to input the resource id when creating the database. I think we can provide instructions on how to get it. I don't think it's too much work as users have to retrieve uri around the same place anyway.

Account id probably can be extracted from the iam identity and added when creating the database as well.

**Comment by smallinsky** [comment]
@greedy52 
> one other alternative would be asking the user to input the resource id when creating the database (and pass it to types.NewDatabase).

Yes the UI will be extended to support  AWS ResourceID input box. 

>  we also need to know the AWS identity of the DB agent. Will the user manually provide it or we should go fetch the identity from the DB agent?

if db agent already has AWS identity we can report it back to to the proxy by calling  ` aws sts get-caller-identity` SDK alternative  from db agent during reverse tunnel ping call but if a db agent doesn't have any AWS Idenitty we can just return a placeholder values.
