### ISSUE TITLE
Unable to access EKS cluster issuer cert when proxying with Teleport

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#17627]
Expected behavior:
Be able to access the EKS cluster issuer cert when proxying with Teleport

Current behavior:
The customer is currently having issues retrieving the AWS EKS OIDC issuer certificate when using Teleport in conjunction with Terraform and the Kubernetes Terraform provider. They are able to retrieve this data if they are not using Teleport as the proxy.

- AWS console application has been configured and working in Teleport and they can successfully run commands like `tsh aws eks list-clusters`
- Kubernetes cluster is setup in Teleport; There is a kubeconfig file generated when logged in to the EKS cluster via `tsh kube login <cluster-name>`. They are also able run commands successfully using that kubeconfig file (via env variable or CLI flag) like `kubectl get pods`
- They are running the `tsh proxy aws -p XXXXX` and setting the displayed env variables for use with Terraform
- They can successfully reference the EKS cluster in Terraform, modify the cluster, or retrieve other metadata about the cluster when using the Teleport proxy. For instance, this simple Terraform (where “./kubeconfig” points to the kubeconfig file generated by the tsh kube login cluster-name command):

```
provider "aws" {
  region  = "us-east-1"
}

provider "kubernetes" {
  config_path = "./kubeconfig"
}

data "aws_eks_cluster" "cluster" {
  name = "cluster-name"
}

output "platform_version" {
  value = data.aws_eks_cluster.cluster.platform_version
}
```

produces the expected output - the platform version:

```
$ /Users/mhinkle/bin/terraform plan

Changes to Outputs:
  + platform_version = "eks.11"
```

However, if data block for the EKS OIDC issuer cert is added to the above Terraform, like:

```
data "tls_certificate" "cluster" {
  url = data.aws_eks_cluster.cluster.identity.0.oidc.0.issuer
}
```

It results in the below error when running Terraform plan:

```
$ ~/bin/terraform plan

 Error: Failed to identify fetch peer certificates

   with data.tls_certificate.cluster,
   on tmp.tf line 39, in data "tls_certificate" "cluster":
   39: data "tls_certificate" "cluster" {

 failed to fetch certificates from URL 'https': Get "[https://oidc.eks.us-east-1.amazonaws.com:443/id/XXXXXXXXXXXXXXXXXXXXXXXXXXXX](https://oidc.eks.us-east-1.amazonaws.com/id/XXXXXXXXXXXXXXXXXXXXXXXXXXXX)": x509: "oidc.eks.us-east-1.amazonaws.com" certificate is not trusted
```

When the above error is produced, the below output in stdout is also noticed from the running `tsh proxy aws` like:

```
2022/10/13 18:50:12 http: TLS handshake error from 127.0.0.1:61205: remote error: tls: bad certificate
2022/10/13 18:50:12 http: TLS handshake error from 127.0.0.1:61207: remote error: tls: bad certificate
```

which would seem to indicate that the request is hitting the proxy.

Teleport version
tsh version
Teleport v10.2.1 git: go1.19.1

auth/proxy:
Teleport Enterprise v10.1.9 git:v10.1.9-0-g8f6f6cc go1.18.3

**Comment by smallinsky** [comment]
The teleport `tsh aws ...` and `tsh proxy aws` command forward AWS API-related requests through Teleport Proxy where the TLS traffic is terminated with the Teleport certificate. The `data "tls_certificate" "cluster"` terraform resource tries to obtain a TLS cert from the ` url = data.aws_eks_cluster.cluster.identity.0.oidc.0.issuer` URL but due to forwarding traffic via HTTPS_PROXY to Teleport the request reaches the Teleport Proxy, not the real URL destination. 

Depending on how tls_certificate.cluster TLS resource is used the workaround for that  issue is to set `NO_PROXY` env variable telling the teleport proxy to route the request to the real target instead forwarding this request through teleport proxy: 
```bash
$ export NO_PROXY=oidc.eks.eu-central-1.amazonaws.com
$ terraform apply
```
or set the `verify_chain = false` to tell the TLS provider to not verify the self-signed chain returned by Teleport Proxy. 
```terraform
data "tls_certificate" "cluster" {
  url          = data.aws_eks_cluster.cluster.identity.0.oidc.0.issuer
  verify_chain = false
}
```

**Comment by r0mant** [comment]
@oshati Sounds like this is not really a Teleport issue and they just need to exclude their OIDC provider URL from the local proxy. Can you please reach out to customer and let them know about the workaround provided above? In the meanwhile, I'm going to close this.

**Comment by ahoehma** [comment]
Hello, I have a similar error but in my case the terraform code runs in a gitlab-runner which is running in a aws-account. Its a "company development setup", so proxies etc. Is it general a good idea to exclude oidc.eks.eu-central-1.amazonaws.com from proxy?

**Comment by aprohorov-callsign** [comment]
Faced with the same issue and I've discovered the alternative solution:
```
provider "tls" {
  proxy {
    from_env = false
  }
}
```

**Comment by 19D** [comment]
not sure if its especially relevant in this case but i've spent an ungodly amount of time troubleshooting my AWS EKS OIDC issues. The fix for me was pinning the **hashicorp/tls** provider version to` 3.4.0`. Other 3.x.x versions may work but apparently there were some changes made in 4.x.x that impact EKS.
