### ISSUE TITLE
`tctl inventory status` requires `admin` role

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#18016]
Expected behavior:
I should be able to run `➜  tctl inventory status --connected` locally, to find old connected hosts to my Teleport cloud cluster.  I had to get access to my auth server box and run it there. 

Current behavior:
```bash
➜  tctl inventory status
Nothing to display.

hint: try using the --connected flag to see a summary of locally connected instances.
➜  tctl inventory status --connected
ERROR: requires builtin admin role
```
Bug details:
- Teleport version: 11.0.1

**Comment by fspmarshall** [comment]
As of https://github.com/gravitational/teleport/pull/27895 most of the inventory methods have normal rbac instead of requiring builtin admin, but the `--connected` option will continue to require a local admin connection.  


Many of these, including `tctl inventory status`, can't show anything interesting unless you are either using teleport cloud or running your auth servers with `TELEPORT_UNSTABLE_ENABLE_INSTANCE_HB=yes`, but this will be changing in the future.
