### ISSUE TITLE
tsh touchid diag not in tsh help

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#18166]
Expected behavior:

Commands like `touchid` and `touchid diag` are available within `tsh help`

Current behavior:

`tsh help` does not show touchid and `tsh help touchid` does not show that `diag` is another command.

Bug details:
- Teleport version: 11.01
- Recreation steps

`tsh help`
`tsh help touchid`

**Comment by codingllama** [comment]
Discussed a bit outside of GitHub: not showing on help was intentional, as `tsh touchid diag` is essentially a debug command (and not something most users should be concerned about). I'm happy to change it so `tsh help touchid` does display `diag`, but at first would still keep it hidden from `tsh help`. I would keep additional support commands hidden too, at least for now.

Happy to revisit if folks think otherwise.

**Comment by codingllama** [comment]
As it turns out, if we make `tsh touchid diag` visible, then it shows up on `tsh help` too. I don't think that's worth it.

Do you mind if we close the issue, @stevenGravy?

**Comment by stevenGravy** [comment]
Not planned due to the interaction of the `tsh help` required.
