### ISSUE TITLE
Hashes missing from new downloads page and CDN

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#18186]
@mcbattirola @xinding33 

The old download page had SHA256 hashes for all downloads to allow customers to verify the integrity of all assets they downloaded. This seems to have gone missing.

![image](https://user-images.githubusercontent.com/5017502/200092614-f48ac38e-8cfd-4b77-8fe0-b58b2f808705.png)

<img width="1223" alt="image" src="https://user-images.githubusercontent.com/5017502/200092612-e87058ff-7432-4d2a-aafd-0d1b58c649ee.png">

----

@justinas 

Downloads from `get.gravitational.com` always supported adding `.sha256` to the URL to get the hash. This doesn't seem to be supported by the new CDN.

How is the user supposed to get the SHA256 of an asset with the new CDN?

**Comment by justinas** [comment]
> Downloads from `get.gravitational.com` always supported adding `.sha256` to the URL to get the hash. This doesn't seem to be supported by the new CDN.
>
> How is the user supposed to get the SHA256 of an asset with the new CDN?

Hm, I can't say this workflow was on my radar (or considered in the design). The hashes are currently only stored in the database, not in the bucket/CDN. It has a small added benefit that S3 bucket (only) compromise would not allow the attacker to override the hashes.

The hashes are definitely exposed in the API:

```console
$ curl -sS 'https://rlz.teleport.sh/teleport?majorVersion=11' | jq '.[0].assets[0] | [.name, .sha256]'
[
  "teleport-11.0.1-1.arm64.rpm",
  "7449535c86966dfa36a2715d036888e7be8f9a681f0b97d1367024687d9c018f"
]
```

and were available in the frontend post CDN rollout, they only disappeared after the changes to the downloads page design.

**Comment by mcbattirola** [comment]
Yeah, they are still available by adding `.sha256` to the link, the install script downloads them (see [here](https://github.com/gravitational/next/blob/7bdeded40701d50b0ec2ed9ec6eb96222fa0efe5/apps/next/public/static/install.sh#L151)).

We decided to remove it from the new downloads page. It didn't provide much security, since someone tampering with the site could change both the binaries and the checksum, and downloading over HTTPS should guarantee integrity.

Do you think we should add it back?#18204 

cc @xinding33

**Comment by mcbattirola** [comment]
We can either do like the old download table and show the sha256 directly (it is available from the download list endpoint), or have a separate button to download it (like in this demo https://next-git-mcbattirola-add-checksum-gravitational.vercel.app/download/).

The demo is using the old `get.gravitational.com` link, as the CDN does not serve the checksums yet.

**Comment by justinas** [comment]
> We can either do like the old download table and show the sha256 directly (it is available from the download list endpoint), or have a separate button to download it (like in this demo https://next-git-mcbattirola-add-checksum-gravitational.vercel.app/download/).
> 
> The demo is using the old `get.gravitational.com` link, as the CDN does not serve the checksums yet.

I personally never use the canonical "shasum" files and `sha256sum -c`, instead I do the "eye-test" on the displayed hash :sweat_smile: But it is definitely not a good option for an automated script.

**Comment by alexfornuto** [comment]
Note that all the docs have been updated to use the CDN, and we provide examples of downloading the checksum to compare.

**Comment by alexfornuto** [comment]
Cross-noting to revert d9d8822528763bbd8d88d598ce9cf746b83ae286 from #20212 once this is resolved.

**Comment by wadells** [comment]
As implemented by the old clientbuilds.gravitational.io s3 bucket distribution, the checksums were stored in the same bucket alongside the artifacts themselves.  This meant that if one was compromised, it is probably that the other could be compromised as well.

If we want to do this well, we should look at storing signatures/checksums in a independently verifiable source -- decoupled from the release infra.  Sigstore?  In my opinion this is probably more of a new security feature than a notable regression in security.

**Comment by r0mant** [comment]
I put this in Q1 goals. Just FYI, as an MVP in order to fix this regression we're just going to restore checksums the same way as they used to be implemented previously i.e. store in the bucket alongside artifacts so this doesn't turn into yet another weeks-long project. I agree decoupling this is the way to go longer term and more of a new security feature, so we can reeval later if this is something that will be worth our time in a later quarter.
