### ISSUE TITLE
Unable to rename role on Web UI

### ISSUE THREAD

**Issue by oshati** [gravitational/teleport#18771]
Expected behavior:
User should be able to rename roles via the Web UI

Current behavior:
When an attempt is made to rename roles using the web UI, The following error is received 

```
cannot find resource with name "xyz"
```

Bug details:
- Teleport version
Observed in versions 10.3.1 and 10.3.8

- Recreation steps

1. On Teleport web UI, navigate to the **Team > Roles**  section 
2. Select any role of choice to edit and modify the **name**
3. Save the changes and it results in the error. 

See attached image for error

- Debug logs
n/a

![image](https://user-images.githubusercontent.com/74545288/203784852-1de23f5a-a256-49a8-bbc9-553318b3cd6d.png)

**Comment by vitorenesduarte** [comment]
@russjones renaming doesn't seem to be supported using `tctl` (and in general in teleport). Is that correct?

If so, below are two options I can think of for addressing this issue.

Note that this seems to also be a problem for auth connectors and trusted clusters:

<img width="1390" alt="Screenshot 2022-12-14 at 14 22 15" src="https://user-images.githubusercontent.com/4520516/207623201-8b9c19de-4922-4730-98d4-509cf30086c5.png">
<img width="1402" alt="Screenshot 2022-12-14 at 14 30 52" src="https://user-images.githubusercontent.com/4520516/207623210-e1cce0e4-6432-453d-a27d-531cf727dd3b.png">

---

### Option 1

As it can be seen in the second option below, role renaming doesn't seem trivial. If we don't want to implement it for now, we could simply improve the error message to say something like:

`Role renaming is not supported. To achieve this, create a different role and then delete this one.`

### Option 2

This is how role editing works today:

- PUT `webapi/roles` with the new `role` as a payload
- if a role named `role.Metadata.Name` does not exist, return the `"cannot find resource with name"` error (seen in the issue description)
- otherwise, validate & update the backend with new `role`

To support renaming we could:
- Extend the `webapi/roles` PUT endpoint so that it takes the role name being updated as an argument (`webapi/roles/:name`)
- PUT `webapi/roles/:name` with the new `role` as a payload
- if `role.Metadata.Name == :name`, then this is not a rename; proceed as before
- otherwise, this is a rename:
  1. validate `role`
  2. create `role`
      - if it fails, then a role named `role.Metadata.Name` already exists and the rename is not possible; so an error returned
      - otherwise, the rename is possible (and no error should be returned below)
  3. just like when deleting a role, go through each user and, if they have the role named `:name`, update it to `role.Metadata.Name`: https://github.com/gravitational/teleport/blob/10ceaf57782f5277c99d84a3d4d6f9997efb80b6/lib/auth/access.go#L51-L101
  4. delete role named `:name`

As the above steps are not executed atomically, it's possible that step `iv` fails if:
- a user is created/updated with the role named `:name` (after `iii`)
- the role named `:name` is deleted by another user (at any time)

To avoid this, ideally this role should be "deactivated" before step `ii`.

**Comment by zmb3** [comment]
> renaming doesn't seem to be supported using tctl

Not directly. Today people `tctl get resource > resource.yaml`, edit the file, and then `tctl create -f resource.yaml`.

This has the same problem though, we'll create a new role instead of renaming the existing role.

(Also note, I'm going to merge `tctl edit` soon which will behave more like the web UI does today).
