### ISSUE TITLE
Run teleport-aws-quickstart as a part of CI/CD hook

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#1894]
## Description

Every time a PR is issued to teleport-aws-quickstart, Jenkins job should build packer image, create a stack, delete a stack.

Logs should be shipped to our stackdriver instance the way robotest ships them for further inspection.

**Comment by klizhentas** [comment]
https://github.com/gravitational/teleport-quickstart-aws

**Comment by klizhentas** [comment]
btw, we no longer need this to be a separate repo, can you move this repo to assets/marketplace instead

**Comment by webvictim** [comment]
Repo has been moved under assets/marketplace in the main telegram repo. @klizhentas would you like me to commit a README saying that it's moved, or should we just delete the repo?

**Comment by klizhentas** [comment]
yeah, let's add a README note

**Comment by webvictim** [comment]
The PR is for basic functionality that will build Packer AMIs and a Cloudformation stack any time a PR is raised against teleport.

Still to do:
- Isolate builds so they only run when things under assets/marketplace are changed?
- Make sure we're building the latest git commits into Packer AMIs rather than specific alpha binaries from S3 storage?
- Work out an improved heathcheck mechanism if necessary
- Ship logs to Stackdriver for archiving and inspection
- Integrate Jenkins with Github PRs so it gives the thumbs up/down on the relevant PRs

**Comment by webvictim** [comment]
PR is merged.

After a bit of research, I'm following some instructions (https://stackoverflow.com/questions/36850485/how-to-trigger-a-jenkins-2-0-pipeline-job-from-a-github-pull-request) and changing Jenkins to use a standard pipeline job rather than a multibranch pipeline job - this should mean that it's able to track PRs and start builds for them.

**Comment by webvictim** [comment]
@klizhentas Yeah, I think so. We're still not shipping the logs to Stackdriver but I'll open another issue for that.
