### ISSUE TITLE
Clarify information in the Application Access getting started guide

### ISSUE THREAD

**Issue by AlexRRB** [gravitational/teleport#18972]
## Applies To

https://goteleport.com/docs/application-access/getting-started/
## Details
Describe the documentation improvements you wish to see.

## Related Issues

<img width="733" alt="image" src="https://user-images.githubusercontent.com/55767682/205117359-68eabef7-4cc4-4848-82d1-d0b64eb5d47e.png">
<img width="710" alt="image" src="https://user-images.githubusercontent.com/55767682/205117587-ad4a6c9c-0aeb-49bb-b3b2-f9500cf98503.png">

**Comment by zmb3** [comment]
Hi @AlexRRB - could you describe a little bit more what improvements you'd like to see?

Is it that it's not clear what the difference between the proxy and app service is?

**Comment by lsgunn-teleport** [comment]
@AlexRRB,
I recently made some changes in this section (ver14), but I'm not sure if the changes quite address your issue.
I'm also considering replacing the command-line instructions with instructions for using the web UI because that's really much simpler and less error-prone.

Here are some of the changes in the current 14.x version:

Step 1/5. Generate a token
An invitation token is required to authorize a Teleport Application Service instance to join the cluster. Generate a short-lived join token and save it on the host where you will run the Teleport Application Service. For example, you can generate the invitation token by running the following command on a server where the Teleport Auth Service runs:

tctl tokens add \
    --type=app \
    --app-name=grafana \
    --app-uri=http://localhost:3000

Copy the output from this command and save the token in a separate file so it can be passed to the Teleport Application Service. 

-----
Create the configuration file for Grafana at /etc/app_config.yaml with a command similar to the following:

sudo teleport configure \
  --output=file \
  --proxy=
teleport.example.com
teleport.example.com
:443 \
  --token=/tmp/token \
  --roles=app \
  --app-name=grafana \
  --app-uri=http://localhost:3000

- Set the --proxy command-line option to the address for your Teleport cluster (for example, teleport.example.com or mytenant.teleport.sh).
- Set the --token command-line option to the file location on the Application Service host where you saved the invitation token that you generated earlier.
- Change the --app-name and --app-uri command-line options if you're configuring access to a different web application.

Configure the Teleport Application Service to start automatically when the host boots up by creating a systemd service for it. The instructions depend on how you installed the Teleport Application Service.

**Comment by lsgunn-teleport** [comment]
Closing as addressed in current documentation. Please re-open if needed.
