### ISSUE TITLE
FIDO2 touch token login with each finger

### ISSUE THREAD

**Issue by bahmanjafari** [gravitational/teleport#19048]
Expected behavior:
I have some FIDO2 touch and FIDO2 normal tokens. I install webauth in teleport and register both tokens. with the normal tokens, everything is working fine. I just push the button and then log in.
but with touch tokens after registering the tokens anybody with any finger can login to teleport and fingerprint no check unless active passwordless. when login with the password-less feature fingerprint is checked and just login with the fingerprint that was before registered. 

my touch tokens model: FEITIAN BioPass K27 USB Security Key

Current behavior:
when the password-less set is off for touch tokens check the fingerprint

Bug details:
- Teleport version 11
- Recreation steps
- Debug logs

**Comment by bahmanjafari** [comment]
my touch tokens model: FEITIAN BioPass K27 USB Security Key

**Comment by bahmanjafari** [comment]
I think this is a very important issue. Can you check it ?

**Comment by codingllama** [comment]
Hey @bahmanjafari, thanks for raising the issue.

It sounds to me it's working as intended. You can think of Teleport second factors as running in 2 different "modes": MFA or passwordless.

In passwordless mode, the security key asserts both your identity (for example, via fingerprint checks) and your presence (as you have to be there to touch it).

In MFA mode, the password asserts your identity, so the security key performs a "user presence" check. This means it doesn't need to verify your identity (the password did that), it just wants a human to be present and touch the security key (so a malicious software can't drive your login). Some security keys do biometric checks in "MFA mode" anyway, some like yours may elect not to - that is fine and up to spec. There is no loss in security because the password is still necessary, and that is the factor that asserts the user's identity.

"require_session_mfa" is similar to "MFA mode". At this point Teleport already verified the user's identity and the request carries a valid certificate, so once again the check is only a "user presence" check.

I hope this answer your question.
