### ISSUE TITLE
Redshift Serverless Documentation

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#19043]
## Applies To
https://goteleport.com/docs/database-access/guides/postgres-redshift/

## Details
Document Teleport [AWS Redshift Serverless Access](https://aws.amazon.com/redshift/redshift-serverless/) implemented in https://github.com/gravitational/teleport/pull/18651 https://github.com/gravitational/teleport/pull/18974

Related:  https://github.com/gravitational/teleport/issues/10550

**Comment by greedy52** [comment]
Documentation details

# Background
[Redshift Serverless](https://aws.amazon.com/redshift/redshift-serverless/), as the name suggests, is the serverless version of the AWS Redshift service. Beta was introduced back in late 2021 and [GA](https://aws.amazon.com/about-aws/whats-new/2022/07/amazon-redshift-serverless-generally-available/) in July 2022.

However, the architecture is quite different from Redshift so I would suggest treating this as a different service with a separate database guide (unless we find an easy way to add this to the existing Redshift guide).

# Database guide draft
Teleport supports access (connect and auto-discover) to both Redshift Serverless [workgroups](https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-workgroup-namespace.html) and Redshift Serverless "managed" [VPC endpoints](https://docs.aws.amazon.com/redshift/latest/mgmt/serverless-connecting.html#serverless-secure-vpc).

### Step 1/7 Install Teleport
(same as other guides)
### Step 2/7 Create a Teleport user
(same as other guides)

### Step 3/7. Create a Database Service configuration
```
teleport db configure create \
   -o file \
   --proxy=teleport.example.com:3080 \
   --token=/tmp/token \
   --redshift-serverless-discovery=us-west-1
```
(note using `redshift-serverless-discovery`)

### Step 4/7 Create an IAM policy for Teleport
(same as other guides)

### Setup 5/7 Create an AWS IAM role for accessing Redshift Serverless
(not sure if it makes more sense as step 4 or 5)

Create an AWS IAM role e.g `teleport-redshift-serverless-access`. Make sure that this IAM role has a trust relationship with the IAM role of the database agent so the agent can assume this role.

The IAM role should have the following IAM permission:
```
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "redshift-serverless:GetCredentials",
      "Resource": "*"
    }
  ]
}
```
For best security, use the ARN of the Redshift Serverless workgroup as the resource like
```
{
...
      "Resource": "arn:aws:redshift-serverless:us-west-2:1234567890:workgroup/some-workgroup-id"
...
}
```

Then optionally, users (database admins) can connect to the Redshift Serverless workgroup as the admin user, `CREATE USER` with username `IAMR:teleport-redshift-serverless-access`, and grant this user appropriate in-database permissions.

### Step 6/7 Start the Database Service
(same as other guides)

### Step 7/7 Connect
Sample `tsh db ls` output from my setup.

```
 $ tsh db ls
Name                          Description                                Allowed Users Labels                                                                                       Connect 
----------------------------- ------------------------------------------ ------------- -------------------------------------------------------------------------------------------- ------- 
steve-wg                      Redshift Serverless workgroup in eu-west-2 [*]           Env=dev,Owner=STeve,account-id=xxxxxxxxxx,endpoint-type=workgroup,namespace=steve-ns,re...         
steve-wg-vpc-steve-teleport-2 Redshift Serverless endpoint in eu-west-2  [*]           account-id=xxxxxxxxxx,endpoint-type=vpc-endpoint,namespace=steve-ns,region=eu-west-2,vp...   
```

Connect
```
tsh connect --db-user teleport-redshift-serverless-access --db-name postgres my-workgroup
```

# Testing setup tips

- Not all regions support redshift serverless. I personally use `eu-west-2` since `ca-central-1` doesn't have it
- You need a VPC, and minimum 3 subnets, for deploying Redshift serverless
- Workgroup endpoints can be public.
- AWS IAM role `teleport-redshift-serverless-access` will be mapped as postgres user `IAMR:teleport-redshift-serverless-access` inside the database. If this in-database user is not created inside the database when we first connect as this role, the `IAMR:xxx` user will be created automatically by AWS. This database user by default can create tables owned by itself but it will have no access to other tables.

Redshift Serverless is still new so certain things are still flaky in my opinion and the official doc lacks clarity in many places. Feel free to use my setup in eu-west-2 for testing or let me know if anything needs to be clarified.
