### ISSUE TITLE
Question: How is PAM configured with Teleport in pam.d

### ISSUE THREAD

**Issue by ocha** [gravitational/teleport#1930]
I was looking at PAM support for Teleport. I was able to build Teleport with PAM and enabled `pam` under `ssh_service`  in `teleport.yml`. However I am not clear how to configure it in `/etc/pam.d` so that teleport works with it. Currently I have google authenticator TOTP configured in `sshd` and it works with normal ssh, however when I use teleport, it bypasses it completely. 

Is there some documentation how PAM is used by teleport and configured? My expectation was that `tsh ssh` would go through PAM but thats not what happened...

**Comment by klizhentas** [comment]
Teleport supports only account management and session management PAM functions:

https://github.com/gravitational/teleport/issues/1766

It does not support `pam_authenticate` and will probably never will, because it contradicts teleport's invariant of using SSH and X509 certificates as the only form of authentication in the cluster available.
