### ISSUE TITLE
Teleport documentation lacks a step by step how to guide to manually configure an HA cluster on AWS EC2

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#19465]
### Problem Statement
Teleport Enterprise implementors lack direction from the documentation on how to properly deploy a production-grade Teleport cluster on EC2 instances. 

Our open-source Terraform code does not remedy this issue because it is challenging for users to modify the Terraform code without something unexpectedly breaking. As a result, few Enterprise users use our Terraform code. 

### Ideal State
An ideal state would be to have a guide that walks user's through, step by step, the process of deploying an HA Teleport cluster on EC2 instances. The guide would include an architecture diagram, load balancer configurations, networking configurations (including security groups), opinionated TLS recommendations, IAM configurations, storage configurations, and prescribed config files for the auth and proxy. 

Ideally, if a user were to go step by step through this guide, they could deploy an HA production-ready Teleport cluster without leaving this single page.

**Comment by webvictim** [comment]
https://github.com/gravitational/teleport/pull/19217 is a great start on this, but does fall short on AWS-specific implementation steps.

**Comment by ptgott** [comment]
I think a separate step-by-step guide that uses copy/pasteable AWS CLI commands to deploy resources would be good here. #19217 is more of an introduction to a general architectural pattern that users can implement in their infra of choice.

On a separate note, @corkrean, how salvageable is our AWS Terraform guide? I do see some issues related to this guide on GitHub (#17840, #17733, #16714, #5377)—should we look into fixing this guide, or would it make more sense to move it outside the "hot path" for new users who want to get started with a production Teleport deployment?

**Comment by corkrean** [comment]
I think the Terraform guide is fine. The terraform code is seldom used because it's inflexible, does not conform to users' requirements, and has a lot of complicated dependencies that cause breaks. 

We should move it out of the hot path.

**Comment by webvictim** [comment]
Terraform is on the list for care and attention in Q1 once the Helm chart improvements have landed. The chances are that the guide will be overhauled then anyway and the code should become much more usable, so if we're OK waiting a while I think that's a good idea.

**Comment by ptgott** [comment]
@webvictim Looks like there's been some work on the HA Terraform guide since the last comment in this thread. How ready are we to resolve this GitHub issue?

**Comment by webvictim** [comment]
I think https://goteleport.com/docs/deploy-a-cluster/high-availability/ does a decent job of explaining the overall concepts required for HA, but certainly isn't AWS-specific.

With this said, though, I haven't seen strong demand for a non-Terraform AWS HA deployment guides lately. We have more options now:
- Teleport Cloud hosts a fully production-ready HA cluster for you with no effort
- The `teleport-cluster` Helm chart is the best-in-class deployment method for any self-hosted cluster
- The `ha-autoscale-cluster` Terraform fills in the gaps for AWS folks who can't/won't use Kubernetes

As such, I don't think this issue as written is really a requirement any more. SEs and TAMs tend to steer people away from non-orchestrated manual HA deployments, solely because it doesn't set them up for success in the long run. Therefore, if folks won't use Teleport Cloud and won't deploy outside of the Helm/Terraform bubble, they're on their own. We can close this issue.
