### ISSUE TITLE
Teleport accepts access requests with an invalid cluster name

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#19494]
The Teleport API will allow you to create an access request with an invalid cluster name.

For example, a common mistake is to include the port in the cluster name field - something like `mycluster.teleport.sh:443`.

Teleport will happily accept this request and allow you to assume an elevated role set once it is approved, but you'll find that you don't have access to any resources due to the incorrect cluster name.

Investigate ways to improve the UX:

- consider rejecting the request to create the access request in the first place
- consider validating that the requested resource UUIDs belong to the specified cluster (may not be possible with trusted clusters)
- at a minimum, try to detect this state and present a clear error message rather than making it appear that everything is working

**Comment by nklaassen** [comment]
At the moment the code would just assume that "mycluster.teleport.sh:443" is a remote cluster, completely separate to "mycluster.teleport.sh".

> consider rejecting the request to create the access request in the first place

We could do this by checking the list of known remote clusters, and rejecting any request with an unknown cluster name.

> consider validating that the requested resource UUIDs belong to the specified cluster (may not be possible with trusted clusters)

Right. If all requested resources are in the local/root cluster, we do check that at least one of them is real and present, otherwise [this](https://github.com/gravitational/teleport/blob/f6f6ebb0059d0af3f4cb7cbbb0f13ddba313f6d6/lib/services/access_request.go#L1528) error will be hit (that error could also be improved). But for remote clusters we do not check, and since this case currently thinks its a remote cluster, it isn't checked

**Comment by zmb3** [comment]
Filed as `good-starter-issue` for the _rejecting any request with an unknown cluster name_ part.

**Comment by EdwardDowling** [comment]
@zmb3 Could you provide some steps on how you replicate this issue. When trying against master teleport is correctly rejecting the request with `ERROR: remote cluster "localhost:9876" is not found`

**Comment by zmb3** [comment]
How did you create the access request? The original issue occurred when creating it via the Go API, but I would expect creating it with `tctl -f request.yaml` should also reproduce it.

Is it possible we fixed this recently?

**Comment by EdwardDowling** [comment]
A thank you I was using the instructions [here](https://goteleport.com/docs/access-controls/access-requests/resource-requests/) and the error must have been thrown from somewhere else before the access request part.
