### ISSUE TITLE
Prompt before rewriting systemd service file

### ISSUE THREAD

**Issue by jwieder** [gravitational/teleport#19687]
**What would you like Teleport to do?**
- Currently, updating Teleport on SSH nodes through a package manager like apt or yum will overwrite the systemd teleport.service file without prompting the user for permission first. This behavior can break (and in my case, has broken) agents that rely on a custom agent configuration, like passing the "--skip-version-check" flag to the Teleport binary. The teleport.service file doesn't appear to be actually updated during this process; the upgrade just re-writes the default service over and over again.

**What problem does this solve?**
Relieve additional burden on Teleport admins on complex enterprise networks. Reduce time + complexity required to patch insecure clients.

**If a workaround exists, please include it.**
Not one that I would recommend to anyone else. Ansible or similar tools aren't a great solution for this.

**Comment by zmb3** [comment]
The solution here is to use systemd overrides to do your custom configuration rather than modifying the unit file that the package manager installs. This allows you to do whatever customization you'd like while ensuring that it isn't overwritten by future updates.

See https://askubuntu.com/questions/659267/how-do-i-override-or-configure-systemd-services for example.

**Comment by jwieder** [comment]
When an agent version conflict currently occurs, Teleport agents (at least v9+) tells their users to manually edit the service files in /lib/systemd/system/ directly. You can easily reproduce this by connecting a v10 client to a v11 cluster.

The overrides are fine, but at the very least don’t have the teleport agent inform users to create a breaking action as a solution for another problem.
