### ISSUE TITLE
Expand API Documentation with practical use examples

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#19716]
Today, in our Golang API section we only have Golang getting started:

https://goteleport.com/docs/api/getting-started/

We should expand by adding guides on how to actually use our API:

* Place a lock 
* Receive and renew credentials
* Create resources for discovery (servers, apps) etc.

I would also ask our CS team for most common use-cases customers are asking for and add those guides as well.

**Comment by strideynet** [comment]
> Receive and renew credentials

Potentially an interesting crossover with Machine ID here in terms of providing a set of renewed credentials to a Go utility that wishes to access Teleport.

**Comment by ptgott** [comment]
Since we have comprehensive reference docs on [`pkg.go.dev`](https://pkg.go.dev/github.com/gravitational/teleport/api/client#section-readme), we can focus the API section of the docs on:
- How-to guides
- Conceptual guides that help guide a user through some oft-used or particularly important types/functions in the API client library

**Comment by ptgott** [comment]
I've done a bit of research into this. Here is what I'm thinking we could do with the API section of the docs. I've structured this as a table so we can track sub-issues.

|Task|Issue|PR|
|---|---|---|
|Fold the existing "Architecture" guide into a conceptual guide that functions as an overview of useful Go packages within the `api` module, including:<br/><br/>- `client`, `events`, `types,` and `profile` (authenticating to and interacting with the Auth Service)<br/>- `proxy` and `webclient` (interacting with the Proxy Service)<br />- `identityfile`, `keys`, `ppk`, `sshutils`, and `tlsutils` (using Teleport-issued credentials to access third-party services)| ||
|Add a guide to writing your own Access Request plugin, e.g., to forward Access Requests to a generic HTTP API|||
|Add a guide to using the API to update roles. For example, this could listen for audit events related to a new role (`RoleCreate`), look up the new role, and replace wildcard values in the `allow` section with more sensible defaults in order to prevent overly permissive roles|||
|Add a guide to automating token creation for joining new agents to the cluster|||
|Add a guide to obtaining credentials from the Auth Service via the API to connect to an SSH node and execute a command|#5489||

**Comment by klizhentas** [comment]
@ptgott this all makes sense to me. Here is a bit more guidance on guides in terms of what I've seen customers are interested in the most:

Most popular:

* Creating and updating users and roles are requested more frequently when teams integrate first.
* Joining nodes, creating and updating Teleport's resource inventory (creating/updating apps, servers, resources, updating labels) goes next
* Processing events, downloading sessions starts after that

Advanced:

* Creating their own Access Requests plugins is more advanced topic, asked by largest customers and teams
* Issuing their own certs - advanced topic

Here are other considerations:

* Go code is Using certificates issued by MachineID instead of long-lived credentials
* Props if you find a way to give Stripe-like one-liner examples of how to use API. It's possible with something like https://github.com/fullstorydev/grpcurl. This will give a massive boost in the way people can discover and play with the API.

I haven't seen anyone asking to talk to proxy or anything like that.

**Comment by ptgott** [comment]
@klizhentas Thanks for the context! I'll update my tracking table to include the most popular requests. 

When customers use the API to create and update users/roles, what are some common use cases? For example, would users want to:

- Validate that new local users/roles meet certain security requirements, replacing overly permissive values with secure defaults
- Create/destroy local users automatically from some external source for on- or off-boarding (i.e., if it's not possible to use SSO for some reason)
- Update roles to coincide with changes in infrastructure

**Comment by klizhentas** [comment]
Usually customers auto create roles based on their external existing systems, when they sync permissions from their apps. 

For example, you can take Github API and write a script that will generate roles based on Github's teams and their permissions to access repositories.

Furthermore you can improve this example by using login rules API and role templates.

**Comment by ptgott** [comment]
@klizhentas Thanks! I've updated the issue tracking table.

**Comment by ptgott** [comment]
Closing as completed. There is definitely more room for practical examples in the API section of the docs, but we can create new issues for specific guides instead of using this one.
