### ISSUE TITLE
Teleport for terminal sharing behind firewalls

### ISSUE THREAD

**Issue by Overbryd** [gravitational/teleport#1981]
Hi,

I saw the number of tickets, and despite, I decided to open another one. Maybe you can help me out with this:

I would like to add my local machine as a node to my freshly setup cluster.
It is running behind a router, and it is not directly reachable from the internet.

Thus trying to establish a ssh session to my node fails, because the connection to my public IP times out.

What can I do to setup this so I can reach my node behind the router?

I check the Admin Manual for "trusted clusters". But that is kind of misleading, because I do not want setup another cluster, I actually just have a node that is connected to my remote teleport server, that is not reachable from the outside.

I would need something like a temporary remote proxy, so that I could share my terminal.

This would be big for pair programming.

**Comment by nikatjef** [comment]
Greetings,

   Just like any other networked service, you have to have the right connectivity.  For example;
*ws* -- This is the machine you are actually sitting at typing.
*tp* -- This is the Teleport proxy machine that *ws* must be able to connect to on port 8023 (by default anyway)
*rn* -- This is the remote node that you want to connect to.  *tp* must be able to connect to it on port 8022 (by default)

  Based on what I am reading of your comment, you have a cluster (*rn* and *tp*) behind your router. And you want to connect to it from *ws*.  If I am reading you correctly, you will need to forward requests destined for your router on port 8023(by default) to *tp* port 8023 so that your pair could connect to *rn* via Teleport.

  Additionally, you will also need to use Teleport to connect to *rn* so that there is a session to actually share.

  I hope this clarifies things a bit.

**Comment by benarent** [comment]
@Overbryd  You can now do this with Teleport 4.0. 

https://gravitational.com/teleport/docs/quickstart/#adding-a-node-located-behind-nat

```teleport start --roles=node --token=n92bb958ce97f761da978d08c35c54a5c --auth-server=teleport-proxy.example.com```

^ The magic is using the URL for the Auth server vs an IP. 

Let me know how you get on, and if you end out using it for pair programming. Please tell us about your experience.

**Comment by klizhentas** [comment]
@benarent 

> ^ The magic is using the URL for the Auth server vs an IP.

The magic is using the public web address of the Proxy server instead of the auth server. The fact that it's IP or DNS does not matter.

**Comment by Overbryd** [comment]
@benarent Awesome, thank you so much for following up on this. I will check that out asap.
