### ISSUE TITLE
Permissions issue with scp command since switching to sftp

### ISSUE THREAD

**Issue by jacobb84** [gravitational/teleport#19959]
Expected behavior:
Assuming the user has read access to the files, tsh scp should be able to retrieve files from a server running teleport. If the user doesn't have access to a file or can't write that file to the local directory for some reason it should skip to the next file.

Current behavior:
On Macs, certain files are causing the copy to fail. The only one we've been able to reproduce this on are .htaccess files that are generated by the Drupal CMS. Drupal generates the .htaccess files with chmod 444 attributes. When those files are reached during a copy, the user receives the following error:

`ERROR: error creating local file "files/.htaccess": open files/.htaccess: permission denied`

All the other files transfer fine, so I don't think it's a local permissions issue on the user's machine. And with the windows version of the client doesn't have any issues copying the files, even when the user's have the exact same permissions on the server. 

Bug details:
- Teleport version: 11.0.3
- Recreation steps:
Using the mac version of the tsh client, attempt to copy a file from a Linux machine starting with a period with read only permissions from a remote server to a local machine. Example:
`tsh scp -r myuser@myserver:/var/www/html/web/sites/default/files .`
- Debug logs
[debug.txt](https://github.com/gravitational/teleport/files/10362344/debug.txt)

**Comment by capnspacehook** [comment]
The issue seems to be that `files/.htaccess` is a read-only file, so after it gets copied and created locally the first time any subsequent transfers will fail to overwrite the existing read-only file. This is how `tsh scp` has always behaved, and is how OpenSSH `scp` behaves as well. As for why this doesn't happen on Windows, it's hard to say. Windows has a much more complex permissions model than UNIX based OSes, and translating from UNIX based file permissions to Windows permissions (and vice versa) is not a straightforward task. My guess is the copied `files/.htaccess` on the Windows machine isn't read-only  for your user.

I created a feature request for a flag to change this behavior here: https://github.com/gravitational/teleport/issues/21191. Discussion on whether this will be added/progress will be tracked in that issue.
