### ISSUE TITLE
Migrate macOS Drone tag build pipelines to GitHub Actions

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#20319]
- All Darwin Drone tag build pipelines move to GitHub Actions.
  - Use similar approach to arm64 pipelines where Drone invokes GHA via API.
- Investigate why macOS builds are slow due to building dependencies from scratch and see if we can speed it up by caching them.
- Start building M1-compatible binaries as well as part of this work.

Breakdown of all tasks:
- Build Teleport binaries
- Build Teleport connect with unsigned binary (push build)
- Build Teleport package
- Build TSH package
- Build Teleport Connect package
- Hook into Drone pipelines
- Cross-build ARM64
- Build universal binaries
- Move to notary-tool from altool
- Build from teleport-private too (or other teleport repos)
- Make release server upload script and put in enterprise repo
  - Call from GHA release workflows to remove open scripts in yaml

**Comment by wadells** [comment]
Some more drone mac pipelines:

teleport.e: https://github.com/gravitational/teleport.e/issues/1191
teleport-plugins: https://github.com/gravitational/teleport-plugins/issues/809

I'm not sure if you want to track these as part of this issue or not, which is why I filed them as separate tickets.  They'll need to be addressed before we can e.g turn of the macstadium builder (which we'll want to keep around anyhow until we know we won't support v9).

**Comment by camscale** [comment]
This now done for master and all supported branches (13, 12, 11). There are still some pipelines that use the Mac runners, but these are not the tag or push build pipelines (those created by dronegen). @wadells has raised some issues for the remaining pipelines. This issue can now be closed.
