### ISSUE TITLE
Unable to drop locked access requests

### ISSUE THREAD

**Issue by corkrean** [gravitational/teleport#20318]
**Expected behavior:**
Users should be able to drop ("switch back" in webUI) locked access requests because doing so does not result in increased permissions and users are always able to effectively drop an access request by logging out and logging back in. 

**Current behavior:**
In order to drop ("switch back") a locked access request, users must log out and log back in. This applies to both the WebUI and tsh. 

**Bug details:**
- Teleport version: 11.2.1
- Debug logs:

tsh client logs:
```
$ tsh request drop
Dropping all active access requests...
ERROR: [10] access denied
```

webui error message:
![image](https://user-images.githubusercontent.com/62527488/213034408-d94d5a25-26b9-45f6-8156-ade9aceac9c5.png)

Audit log of unsuccessful drop: 
`INFO [AUDIT]     session.rejected access_requests:[b1dfe30b-a3a9-4cb5-bb1e-220d409a3a41] addr.local:192.168.5.99:443 addr.remote:68.65.212.68:25454 cluster_name:cluster.com code:T1006W ei:0 event:session.rejected login:ubuntu max:0 namespace:default proto:ssh reason:lock targeting AccessRequest:"b1dfe30b-a3a9-4cb5-bb1e-220d409a3a41" is in force server_id:1bb6d974-6ac6-4ed3-95f1-9daf1899cafd time:2023-01-17T23:19:38.116Z uid:8cf69321-2fdf-4b23-bafe-5e177f9449ee user:escalator events/emitter.go:263`

**Comment by nklaassen** [comment]
I'm not sure if this is a bug or working as designed. I see the rationale on why this sounds like it should be possible. The technical reason this doesn’t work today is that in order to drop the request/switch back, you need to generate a new cert. Generating a new cert requires you to authenticate with your current cert. You cannot authenticate with your current cert if any of your active access requests are locked.

If current user certs were stored in a stack client-side, with "assume roles" pushing a new cert on the stack and "switch back" popping the previous cert of the stack, this could work. But currently only one cert is stored client side and assuming a request or switching back always creates a brand new cert. It would require some non-trivial changes in teleport to make this work as desired.

**Comment by corkrean** [comment]
The customer reports this was not an issue in 11.1.3.

**Comment by zmb3** [comment]
This is the same issue as #10512 but for `tsh` instead of the web UI.

**Comment by zmb3** [comment]
I've combined this with #10512 for easier tracking.
