### ISSUE TITLE
[Login Rules] Infra as Code

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#20340]
The upcoming login rules feature should simplify the process of configuring RBAC (traits, users, groups, etc) with an infrastructure-as-code approach.

Provide tutorials for how to set up login rules with an existing SSO provider for:

- [x] https://goteleport.com/docs/access-controls/login-rules/terraform/?scope=enterprise
- [x] https://goteleport.com/docs/access-controls/login-rules/kubernetes/?scope=enterprise

Additionally, we should expose a clean Go API for modifying login rules and create an example program demonstrating how to use it.

**Comment by nklaassen** [comment]
@zmb3 I wrote up some guides on configuring login rules via terraform and the k8s operator, they're linked to this issue. But looking back here I realized you mentioned documenting a PR-based workflow for terraform and FluxCD for k8s, which I haven't done.

Honestly for both of those it feels like I would just have to document so many pre-reqs that would have to be very specific+prescriptive in order for it to be actually possible to follow along with the guide, but would probably not _quite_ fit in to any org's specific setup. I don't think we currently document anything like this, and I'm wondering if it's worth investing a bunch of my time diving into it, or if the docs team is already thinking about it.

I'll tag in @ptgott since you left a [comment](https://github.com/gravitational/teleport/pull/23888#issuecomment-1492212877) on one of those PRs on figuring out how we want to structure our IaC guides for login rules and other resources going forward

**Comment by ptgott** [comment]
@nklaassen Thanks for the tag. I'm working on a Getting Started guide to setting up Teleport using a pure infrastructure-as-code approach with Terraform and Spacelift. The goal is to get it done this quarter. If it works out, it should hopefully provide an example of a guide organized around infrastructure-as-code and GitOps. 

Since the guide I'm writing is for users starting from scratch, I think there are fewer issues with the setup integrating with the user's existing environment, though I'll be on the lookout for unanticipated oversights.
