### ISSUE TITLE
Ability to provide additional proxies when joining node to teleport

### ISSUE THREAD

**Issue by elijahsgh** [gravitational/teleport#21256]
What would you like Teleport to do?
I would like to be able to provide a list of proxies when joining a teleport cluster.
Example:
```# /etc/teleport.yaml
version: v3
teleport:
  join_params:
    token_name: iam-token
    method: iam
  proxy_server: https://teleport.example.com:443
```
The `proxy_server` field here could be a list or a comma separated string in the CLI.

What problem does this solve?
Customer would like to provide a "fallback" instance to join in the event that the first server fails (various reasons, ex: incorrect version, proxy offline, proxy in a different region, etc).

If a workaround exists, please include it.
Customer is currently using a bash script for this.

**Comment by zmb3** [comment]
I'm confused - proxy_server specifies the address of the **proxy** the agent should connect to, but the request is to put a list of _nodes_ there?

Did you mean a list of proxies instead? If so, is this a list of proxies in the same cluster or separate clusters?

For context, in v11 we changed from a list of proxies to a single endpoint in order to fix a number of issues in Teleport. It's unlikely we will switch back to a list.

**Comment by elijahsgh** [comment]
> I'm confused - proxy_server specifies the address of the proxy the agent should connect to, but the request is to put a list of nodes there?

This is becoming a "Who Is On First?" exercise in terminology. A cluster node is a node is a node... six of one, half dozen of the other. I'll be mindful to use the more teleport specific definition of "node" in the future to avoid confusion.

> Did you mean a list of proxies instead? If so, is this a list of proxies in the same cluster or separate clusters?

Separate clusters.

**Comment by zmb3** [comment]
> six of one, half dozen of the other

In this case, the distinction of whether or not we're talking about the thing that is joining the cluster (node, agent, etc) or the thing that is accepting new members (proxy/auth) is important.

I'm not sure this request makes sense for the product. I'm concerned that it complicates the configuration and makes things non-deterministic.

- All clusters would have to have a join token of the same type and name, increasing operational burden.
- When the agent starts with said config file, you have no guarantees as to which cluster it joins. Further, since the config file no longer contains the information necessary to know which cluster the agent is a member of, troubleshooting becomes more difficult, increasing the support burden.
- Future restarts of the process would have to know to ignore the values of `proxy_server` for the proxies that were not used on the initial join.

**Comment by elijahsgh** [comment]
> In this case, the distinction of whether or not we're talking about the thing that is joining the cluster (node, agent, etc) or the thing that is accepting new members (proxy/auth) is important.
The distinction is clear in context. The general computing term _node_ applies to _proxy nodes_ in the cluster. In context and with the example configuration and explicit mention of the proxy flag.... the disambiguation is obvious.

The user wants to be able to specify multiple proxy _nodes_ (this is unambiguous) to join their _node_ to a cluster _composed of nodes_.

>>> All clusters would have to have a join token of the same type and name, increasing operational burden.
When the agent starts with said config file, you have no guarantees as to which cluster it joins. Further, since the config file no longer contains the information necessary to know which cluster the agent is a member of, troubleshooting becomes more difficult, increasing the support burden.
Future restarts of the process would have to know to ignore the values of proxy_server for the proxies that were not used on the initial join.

💯 
All of this makes sense and is currently being handled by a bash script with "clean up" (rm -rf /var/lib/teleport for example) as well as `--config` to "flip" through configurations. They would prefer teleport provided a mechanism that was less fragile than a bash script.

**Comment by webvictim** [comment]
Edited the title and comment because it took me far too long to work out that the comment is talking about a list of proxies.

**Comment by zmb3** [comment]
As recently discussed, this is not something we plan to add to Teleport since it can be done outside of the product for those who really want this functionality.
