### ISSUE TITLE
Allow EC2 instance to load all RDS DB. 

### ISSUE THREAD

**Issue by moisesmejia1200** [gravitational/teleport#21309]
What would you like Teleport to do?

Create an EC2 instance with a Teleport agent that loads all RDS databases and allows access to them. It should work similarly to teleport-kube-agent

What problem does this solve?

In many cases, it's not trivial to keep network level separation when using EKS networking, so a separate EC2 instance only in charge of databases with specific security groups makes sense.

If a workaround exists, please include it.

Using the teleport-kube-agent helm chart instead of the EC2 version, but as I've mentioned, that's not always practical or possible

**Comment by dubniczky** [comment]
Thanks for the reference @zmb3, any ETA on the feature?

**Comment by r0mant** [comment]
We're working on the improved flow for discovering and joining AWS resources in the Access Manager interface in our Web UI and currently targeting Teleport 13.

The ticket description is quite unclear though:

> Create an EC2 instance with a Teleport agent that loads all RDS databases and allows access to them. It should work similarly to teleport-kube-agent

Is the ask for Teleport to provision an EC2 instance? This is outside of scope of what Teleport is going to do. Users are responsible for creating an EC2 instance that can connect to their databases.

It's also unclear what "it should work similarly to teleport-kube-agent" means.

I'm going to assume you're looking for the improved discovery/enrollment flow I mentioned above, in which case this is tracked by the ticket linked above.

Otherwise feel free to reopen with a better description and usage scenario.

**Comment by dubniczky** [comment]
Hi @r0mant, for more context, I can share the initial support ticked we've opened in the shared Slack channel: https://prezi.slack.com/archives/C04DLGVM0MN/p1675332027023889
