### ISSUE TITLE
SSH file copy is undocumented

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#22456]
We have SSH file copy parameter in the SSH service config file that is not documented

https://github.com/gravitational/teleport/blob/be9fee43de7a5850ebed3cf05d9976c016e481fa/lib/config/fileconf.go#L1304

Also, when SSH SFTP fails, you get non-desciptive error: 

User Message: ssh: subsystem request failed

This generates support load. Improve error message and document the option.

**Comment by capnspacehook** [comment]
PR to improve SFTP error message here: https://github.com/gravitational/teleport/pull/18657

Requires a bit more modification of github.com/pkg/sftp fork which we don't want to do though.

**Comment by jakule** [comment]
We have plans to change the SFTP implementation. That will allow close of many SFTP-related issues. The main issue with `User Message: ssh: subsystem request failed` is that it also happens when people try to use `tsh v11+` with unsupported Teleport (v9, for example). I'm not sure what else we can do in this case apart from adding something like `make sure that the node is in version v10.1+` when this error is returned from the backend.

**Comment by zmb3** [comment]
@jakule you could also add a FAQ section to the docs with common errors and troubleshooting steps

**Comment by zmb3** [comment]
This is documented now:

```
teleport/docs on master [$]
➜ ag ssh_file_copy
pages/access-controls/reference.mdx
102:| `ssh_file_copy` | Allow SCP/SFTP | Logical "AND" i.e. if all roles allows file copying, it's allowed |

pages/includes/config-reference/ssh-service.yaml
92:    ssh_file_copy: true

pages/includes/role-spec.mdx
17:    # ssh_file_copy controls whether file copying (SCP/SFTP) is allowed.
19:    ssh_file_copy: false

pages/server-access/rbac.mdx
142:    # ssh_file_copy controls whether file copying (SCP/SFTP) is allowed.
144:    ssh_file_copy: false

pages/api/rbac.mdx
864:    ssh_file_copy: true
911:    ssh_file_copy: true

pages/reference/terraform-provider.mdx
1509:| ssh_file_copy              | bool             |          | 
```
