### ISSUE TITLE
tctl get connectors

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#2246]
## Problem

It is annoying that `tctl get` does not have a convenient connector resource type and instead of we're forcing users to remember their type, like 'saml' or 'github'. You can't even tell WHAT connectors are present until you try them all. It makes it hard to reason about security and it's easy to overlook connectors that (maybe?) shouldn't be there

## Solution

```bash
$ tctl get connectors
```

It should dump all known connector types.

**Comment by klizhentas** [comment]
most likely you see stack trace because you have `DEBUG` environment variable set.

**Comment by aberoham** [comment]
The UX `User Message: creating resources of type "saml" is not supported` is not as helpful as a message such as `The version of Teleport does not support [plain english feature description], please check that you running commercial Teleport binaries or a version that includes the '[raw]' resource type`

Also, end-users who aren't familiar with golang development often will miss the human-readable error messages because they're wrapped in golang'isms and then only repeated at the very end.

Could the human-readable error be more human, be listed as the first thing before the stack trace, then be repeated below the stack trace?

**Comment by klizhentas** [comment]
@aberoham yes, just create a separate ticket for this so we can track

**Comment by russjones** [comment]
Reopening to make this a documentation ticket, this is what the output looks like:

```
$ tctl get connectors
- kind: oidc
  metadata:
    name: google
  spec:
   ...
  version: v2
- kind: saml
  metadata:
    name: okta
  spec:
   ...
  version: v2
- kind: github
  metadata:
    name: github
  spec:
     ...
  version: v3
```

```
$tctl get connectors --format=text

OIDC:
Name   Issuer URL                  Additional Scope 
------ --------------------------- ---------------- 
google https://accounts.google.com profile,email    

SAML:
Name SSO URL                                                                                                    
---- ----------------------------------------------------
okta https://dev-683790.oktapreview.com/app/1234/sso/saml 

GitHub:
Name   Teams To Logins            
------ -------------------------- 
github @gravitational/1234: admin 
```
