### ISSUE TITLE
No IAM joining example for EKS

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#22849]
I found this guide:

https://goteleport.com/docs/management/guides/joining-nodes-aws-iam/

For nodes, but nothing in EKS or K8s section. Please add the guides/references in K8s and app/DB access if applicable.

**Comment by ptgott** [comment]
I am working on moving the "Joining Nodes" guides into a single subsection of the docs, which also clarifies that these join methods can apply to a number of Teleport services, including the Kubernetes Service. However, [the PR](https://github.com/gravitational/teleport/pull/22111) that does this also includes a large and (as it turns out) misguided find/replace. 

I'm thinking about separating the node-joining part of that PR into a separate PR that also addresses this issue. @zmb3  since you reviewed the PR I'm linking to, what do you think?

**Comment by zmb3** [comment]
Works for me!

**Comment by r0mant** [comment]
@ptgott I think this request is still valid. We have a guide for installing a Kube agent as a Helm chart and we have a guide for joining agents using IAM auth but we don't have a single guide that explains how to use both of these combined and how to join a Kube agent deployed on EKS using IAM auth.

I have asked @tigrato to write one (he already had an instruction somewhere we can convert into a guide), unless @ptgott your PR adds it already (I looked briefly and didn't see it).

**Comment by espadolini** [comment]
This would've been nice for https://gravitational.slab.com/posts/2023-03-12-invalid-join-token-6jqwd75j .
