### ISSUE TITLE
Inconsistency Between CLI and Web for Combining Resource and Role Requests

### ISSUE THREAD

**Issue by djohns7** [gravitational/teleport#22907]
Expected behavior:
Combine roles and resources from the web console in a single Just-In-Time request. 

Current behavior:
Web displays an error about being unable to combine role and resource requests. CLI allows them to be chained together. 

Bug details:
- Teleport version: 12.0.5
- Recreation steps: In web UI, select both roles and resources for a Just-In-Time request. Submitting will display an error.
- Debug logs
```
tsh request create --resource /teleport.dev.example.com/kube_cluster/dev-aws-us-west-2-generic-2 --roles=cluster-admin --reason "test cluster-admin" 
Creating request...
Request ID: 3d3d5cd1-23fb-4ee1-b8a3-32386f68fdde                                                 
Username:   developer                                                                            
Roles:      cluster-admin                                                                        
Resources:  ["/teleport.dev.example.com/kube_cluster/dev-aws-us-west-2-generic-2"] 
Reason:     "test cluster-admin"                                                                 
Reviewers:  [none] (suggested)                                                                   
Status:     PENDING                                                                              

hint: use 'tsh login --request-id=<request-id>' to login with an approved request

Waiting for request approval...

Approval received, getting updated certificates...
```

**Comment by zmb3** [comment]
This is working as designed, and is consistent across the web UI and `tsh`.

- `tsh request create` will **always** submit a resource request when you use `--resource`
- by default, Teleport will select the underlying roles for you automatically when you create a resource access request. You can override this behavior by using `--roles`, but you must be careful because you can select a role that actually blocks access to the requested resources.
- Even if you specify `--roles`, you are not requesting access to everything granted by those roles, you are still doing a resource-based request that only grants access to the resources specified. You are _not_ combining resource and role requests.
- The web UI also allows you to do the equivalent of tsh's `--roles` when creating a resource access request. This was implemented in https://github.com/gravitational/webapps/pull/1321

Feel free to reach out to me directly if there is further confusion or if you have suggestions for how to make this more clear.
-
