### ISSUE TITLE
Connect should not steal keyboard shortcuts when terminal is focused

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#23104]
Expected behavior:

If I'm using the terminal tab on Windows or Linux, pressing shortcuts such as Ctrl+W should send those shortcuts to the shell. Pressing Ctrl+W while using a bash shell should remove the word before the cursor.

Optimally, the shortcut should be first sent to the terminal and only if it doesn't trigger action there it should be interpreted by Connect. For example, Ctrl+Tab should let me switch tabs in Connect but Ctrl+W should remove the word in the shell.

Current behavior:

Using any shortcut recognized by Connect while the terminal is focused sends the shortcut to Connect. Pressing Ctrl+W while using a bash shell closes the current tab.

We have a few Windows users complaining about not being able to use nano because some of its shortcuts are being eaten by Connect.

---

As a temporary workaround to this issue users can reassign the shortcuts used by Connect through the config file (https://github.com/gravitational/teleport/pull/22898).

---

We have to look at what VSCode is doing and think through how we want the shortcuts to interact with the terminal. Windows Terminal might be doing something interesting here as well. If the terminal traps all shortcuts then it might be inconvenient since you can no longer switch tabs etc.

We use Ctrl + K for the search bar but in nano that's the default for cutting text. Ctrl + E is probably even worse because it's used in bash in general, not just a single editor and Connect uses it for the cluster selector.

**Comment by ravicious** [comment]
How VSCode approaches the issue:

(also, I think you get a notification if you're in the shell and press a shortcut which is captured by VSCode and not the shell)

![commands to skip shell](https://user-images.githubusercontent.com/27113/227592771-05213140-dd2b-4d72-810e-2330d6f9e0d6.png)

**Comment by gzdunek** [comment]
A word of explanation: Connect steals all keyboard shortcuts, because the [keyboard events handler](https://github.com/gravitational/teleport/blob/328182ee7bd5db210f32d1453a611ab79ab3059e/web/packages/teleterm/src/ui/services/keyboardShortcuts/keyboardShortcutsService.ts#L111) uses `capture: true`.

From MDN:
>capture
A boolean value indicating that events of this type will be dispatched to the registered listener before being dispatched to any EventTarget beneath it in the DOM tree. If not specified, defaults to false. 

To make the events go to xterm first we would have to remove the flag, however it will create another issue like inability switch tabs or close tabs while using the terminal.

**Comment by ravicious** [comment]
@gzdunek Can we close this as not planned since we changed the keyboard shortcuts on Windows and Linux to not conflict with regular bash shortcuts?
