### ISSUE TITLE
Can't access GetInventoryStatus via Go SDK (requires builtin admin role)

### ISSUE THREAD

**Issue by jryberg** [gravitational/teleport#23164]
Expected behavior:
Returns inventory

Current behavior:
Fails due to requires builtin admin role

The user used to generate identity was the first user created during installation. There are no "admin" role to assign.

Do I have to create a new role and assign it to the user to make inventory to work? How would that look? I can't find any documentation about this requirement. 

Bug details:
- Teleport version: 12.1.1
- Recreation steps
```
package main

import (
	"context"
	"log"

	"github.com/gravitational/teleport/api/client"
	"github.com/gravitational/teleport/api/client/proto"
)

func main() {
	ctx := context.Background()

	//	clt, err := client.LoadIdentityFile("id2")

	clt, err := client.New(ctx, client.Config{
		Addrs: []string{
			"<redacted>:443",
		},
		Credentials: []client.Credentials{
			client.LoadIdentityFile("id2"),
		},
	})

	if err != nil {
		log.Fatalf("failed to create client: %v", err)
	}

	defer clt.Close()
	resp, err := clt.Ping(ctx)
	if err != nil {
		log.Fatalf("failed to ping server: %v", err)
	}

	log.Printf("Example success!")
	log.Printf("Example server response: %s", resp.String())
	log.Printf("Server version: %s", resp.ServerVersion)
	inventory, err := clt.GetInventoryStatus(ctx, proto.InventoryStatusRequest{Connected: true})
	if err != nil {
		log.Fatalf("failed to read inventory: %v", err)
	}
	log.Printf("Inventory: %s", inventory.String())
}
```

- Debug logs

**Comment by zmb3** [comment]
See #18016

The built in admin role this refers to is what you get when you run tctl on the auth server. 

The inventory isn't yet available to general purpose API clients. 

@fspmarshall let's add a note to the godocs

**Comment by fspmarshall** [comment]
As of https://github.com/gravitational/teleport/pull/27895 most of the inventory methods have normal rbac instead of requiring builtin admin, but the `Connected` option will continue to require builtin admin.  

For the time being, iterating specific services (e.g. nodes) as mentioned above is still the most portable option for learning about what teleport instances exist.  In the future, instance heartbeats will be enabled by default, at which point `GetInstances` will be the best way to list all teleport instances.  For those that prefer to use them now, instance heartbeats can be enabled by setting the env var `TELEPORT_UNSTABLE_ENABLE_INSTANCE_HB=yes` on all auth servers (takes about 10 minutes after enabling for the full set to populate).
