### ISSUE TITLE
Machine ID: Teleport Discover integration

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#23172]

**Comment by strideynet** [comment]
We'll want to get this shipped in Teleport 13, so I'd like to suggest an iterative approach to this build in order to get as much of this in that we can. One of the biggest benefits of this will be surfacing Machine ID for newer users to Teleport and making them aware of the feature. Because of this, we can focus on a minimal viable approach that includes analytics so we can determine what direction to invest in further.

I'd like our initial focus to be on GitHub Actions. I'd expect the following experience per protocol in the minimal viable build:
- User opens "Enrol integration" selects "GitHub Actions ($RESOURCE_TYPE)" 
- User provides name for bot
- User provides details of the repository/workflow they want to grant access to.
   - Initially simple, potentially just offering repository name and environment. 
- User provides details of what resources the bot should be able to access - this step will vary per protocol.
   - (MAYBE) User is shown the generated role YAML (?)
- Upon proceeding, this creates a role and a bot with the ability to impersonate that role.
- User is shown an example GitHub Actions workflow that uses the created bot/token to access that resource.

To make sure we ship something in Teleport 13, I'd like to complete a PR per protocol and complete this in the following order (based on information I have about the most common Teleport Machine ID + GHA use-cases):
- SSH Access
   - Access Control:
     - User selects "All hosts" or provides a list of label restraints.
     - User lists the principals they wish to grant access to.
- Kubernetes Access
   - Access Control:
     - User selects "All clusters" or provides a list of label restraints.
     - User must provide name of a Kubernetes group they wish to grant access to - with a simple bot name derived one recommended. User will be responsible for creating RoleBinding and Role for that group, but linked to a simple example for each.
- Application Access:
   - Access Control:
     - User selects "All apps" or provides a list of label restraints.

Out of scope:
- "Connection" testing.
- Label modification of existing resources

I'd like to keep the "connection testing" out of scope for now - with Machine ID this seems much more complicated to prove, especially over all three supported protocols.

**Comment by strideynet** [comment]
This task is at risk for 13.0 due to a dependency on other work to refactor the integrations discover page.

**Comment by strideynet** [comment]
Rescoped this to take an MVP approach - we'll add the buttons and link out to the docs for now to gauge interest in a full wizard.
