### ISSUE TITLE
Headless SSO accept hangs if session is invalid

### ISSUE THREAD

**Issue by jakule** [gravitational/teleport#23436]
As described in https://github.com/gravitational/teleport/pull/22914#pullrequestreview-1352576304 WebUI hangs when a session ID is invalid. We should try to reduce the deadline if possible.

Bug details:
- Teleport version v13-dev
- Recreation steps
- Debug logs

**Comment by Joerger** [comment]
This hanging is caused by a fundamental aspect of the implementation - https://github.com/gravitational/teleport/blob/master/rfd/0105-headless-authentication.md#unauthenticated-headless-login-endpoint

`GetHeadlessAuthentication` cannot immediately return a not found error because we may just be waiting for the headless login attempt to add the login details on demand. We could reduce the deadline from the standard 30s timeout, but realistically it could take several seconds in environments with high latency due to the additional round trips necessary in this approach.

**Comment by Joerger** [comment]
One improvement we can make is to alter the proxy endpoint to redirect the user to login as the specified username rather than using whatever existing session they have: `/webapi/users/:username/headless/:headless_authentication_id`.
