### ISSUE TITLE
Controlling multiple nodes at the same time

### ISSUE THREAD

**Issue by dkrutsko** [gravitational/teleport#2345]
I'm sorry if this was mentioned before but I'd like to propose a new feature for easily controlling multiple nodes through a single terminal window (either through `tsh` or the web client). I have multiple servers which are identical or close to identical and I'd like to be able to start a parallel session between some or all of them (on a single cluster) and issue the same command to all of them.

One possible implementation is to have a button, `Start Parallel Session`, which would bring up the servers I want to control. After selecting the servers, it would bring me to a single terminal window where inputting commands sends them to all selected servers, and the output would be one of the selected servers, although I should be able to choose the output of the server I want to view through a select picker.

While commands are executing on all machines, the input window would wait until all have finished. I'd also like the option of inputting a command to a single machine in case one machine needs a special command. This can be enabled through maybe a checkbox that says `send command only to this machine`. But regardless, the input window would wait until all servers are ready to accept input.

I would like to know your thoughts. Thanks

**Comment by klizhentas** [comment]
we already multiplex commands using cli - tsh can run the same command on multiple hosts:

```
tsh ls role=node ls
```

Or you can do the same with ansible and teleport.

It will be pretty unusual and very complicated task to multiplex commands on an interactive terminal, mostly due to the inevitable differences on the output, so it's unlikely we are going to add such a feature in the UI.

Gonna close this ticket for now, but let us know if you have any other questions.

**Comment by dkrutsko** [comment]
Thanks for your reply, I'll take a look!
