### ISSUE TITLE
`TestLocalProxyPostgresProtocol` flakiness

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#23528]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101

#### Relevant snippet

```
=== CONT  TestLocalProxyPostgresProtocol
[289](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:290)
    helpers_test.go:231: 
[290](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:291)
        	Error Trace:	/__w/teleport/teleport/lib/srv/alpnproxy/helpers_test.go:231
[291](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:292)
        	            				/__w/teleport/teleport/lib/srv/alpnproxy/proxy_test.go:314
[292](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:293)
        	Error:      	Not equal: 
[293](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:294)
        	            	expected: ""
[294](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:295)
        	            	actual  : "database handler response"
[295](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:296)
        	            	
[296](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:297)
        	            	Diff:
[297](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:298)
        	            	--- Expected
[298](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:299)
        	            	+++ Actual
[299](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:300)
        	            	@@ -1 +1 @@
[300](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:301)
make: *** [test-go-unit] Error 1
[301](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:302)
        	            	-
[302](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:303)
        	            	+database handler response
[303](https://github.com/gravitational/teleport/actions/runs/4493921743/jobs/7905755101#step:6:304)
        	Test:       	TestLocalProxyPostgresProtocol
```

**Comment by zmb3** [comment]
@GavinFrazar should I close this or do you want to keep it open while you track the actual ProxyConn fix?

**Comment by GavinFrazar** [comment]
@zmb3 didn't see this earlier - I'd like to keep these open until I push a proxy conn fix

**Comment by GavinFrazar** [comment]
@zmb3 After investigating the proxyconn issue, I've come to the conclusion that there's no good way to do it, so I'm just going to close this issue.

TCP connections gracefully close with a 4 way handshake: FIN -> ACK (FIN) -> FIN -> ACK(FIN)
After one side initiates the handshake process with FIN, the other side may continue writing data before sending the final FIN.

Our `ProxyConn` function does not handle graceful TCP connection close - when either side sends a FIN, the proxy will close both connections immediately, without giving the other peer a chance to finish writing data.

`*net.TCPConn` has a `CloseWrite()` method, which sends a FIN packet to indicate to the peer that no more data will be sent and initiates that 4-way handshake process. Unfortunately in go, I don't see how to access this method when the underlying connection is TCP, due to the way most of our types (and external types) just embed a `net.Conn` interface, and are then passed into `ProxyConn` as a `io.ReadWriteCloser` - so there's no way to tell if the underlying embedded net.Conn is a TCPConn and call its `CloseWrite` method, unless we use some kind of reflection hack I think. Which is unfortunate, because i'm sure most of the time the underlying connection really is TCP.

If there were a way to do that, then we could just call `CloseWrite` when its available to do graceful TCP connection close.

The `socat` man page actually has a section on doing exactly this:
https://linux.die.net/man/1/socat:
> When one of the streams effectively reaches EOF, the closing phase begins. Socat transfers the EOF condition to the other stream, i.e. tries to shutdown only its write stream, giving it a chance to terminate gracefully. For a defined time socat continues to transfer data in the other direction, but then closes all remaining channels and terminates.

```mermaid
sequenceDiagram
    participant Client
    participant Server

    Note over Client, Server: ...Data exchange...

    Note over Client,Server: Server initiates connection close
    Server->>Client: FIN
    Note over Server: state: FIN_WAIT_1
    Client-->>Server: ACK (FIN)
    Note over Client: state: CLOSE_WAIT
    Note over Server: state: FIN_WAIT_2
        alt Client keeps writing data
            Client->>Server: Data
            Server-->>Client: ACK
        else OR Client decides to close the connection
            Client->>Server: FIN
            Note over Client: state: LAST-ACK
        end
    Server-->>Client: ACK (FIN)
    Note over Client: state: CLOSED
    Note over Server: state: TIME_WAIT
    activate Server
    Server->>Server: waiting to close
    deactivate Server
    Note over Server: state: CLOSED
```

**Comment by zmb3** [comment]
@GavinFrazar can you do a type assertion?

```
type closeWriter interface {
    CloseWrite() error
}

if cw, ok := conn.(closeWriter); ok {
    cw.CloseWrite()
} else {
    conn.Close()
}
```

**Comment by GavinFrazar** [comment]
If the conn is embedded as a `net.Conn`, then that type assertion doesn't work.

https://go.dev/play/p/bVBLxE_Hg71
```go
package main

import "net"

type closeWriter interface {
	CloseWrite() error
}

type connWrapper struct {
	net.Conn
}

func main() {
	var wrapper net.Conn = &connWrapper{&net.TCPConn{}}
	// _ = wrapper.(closeWriter)  // panics
	_ = wrapper.(*net.TCPConn) // also panics
}
```

**Comment by GavinFrazar** [comment]
I mean I suppose we could try to do the type assertion, it will just only succeed for code paths that don't use a wrapper type
