### ISSUE TITLE
GHA nightly unit tests workflow

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#24169]
Flaky tests detector can't catch all issues because it only runs on new/modified tests and doesn't catch issues that lead to flakiness due to some code changes, or when one test makes others flaky (we've had both of these happen recently).

In addition to flaky tests detector, we want to build a GHA workflow that runs daily on some cron schedule and runs the entire unit tests suite for 2 hours (or X number of attempts, say 100-200-500? idk what's the reasonable number, we can experiment)

It won't prevent flaky tests from slipping though but it will help surface them the same day as the offending commit that caused it landed so troubleshooting will be much easier.

The workflow should send a notification to #dev-teleport Slack channel once a day with a list of top-10 flaky tests this day so we can quickly see if there are new contenders (and people on the team can recognize their own tests and fix them if something slipped through the flaky tests detector).

**Comment by camscale** [comment]
This has been deployed and should run each day at 3am PDT.

A couple of variations from the original issue description:
* The tests run about 25 times which takes about 2 hours. There is a 2 hour time limit too so if they are slow one day, fewer than 25 runs will occur
* The top 20 are listed partly because if a test fails, that package also fails and is listed too. Worst case, 10 tests from separate packages fail, so we would list those 10 as well as the 10 packages that failed. We need to list the failed packages as race detector failures are reported only against a package not a test.
* Only `test-go-unit` is run. There are other tests that are of a much smaller scope that have different build tags that cannot be run in the same test run due to those build tags. It is possible to re-work the structure of the tests in the makefile to be able to run multiple tests targets consecutively and feed that output into the flaky test detector/reporter, but that's more work that is not yet done.

Currently we run on GitHub-hosted runners, 32 core machines. This can be quite expensive, but we will have self-hosted alternatives imminently so we will retarget to them when deployed. We may also be able to use 128 core machines to get more runs in if we want.

**Comment by jakule** [comment]
> We may also be able to use 128 core machines to get more runs in if we want.

I think for this, we should get 16 or 32 cores machine. It's easier to find flaky tests when the machine is slower. If a test passes on something that is faster than our CI, the test can still fail in the CI, which defeats the purpose. IMO

**Comment by camscale** [comment]
This is essentially done, but one wart is that when tests fail, this is a github actions failure. This is not so important except I get an email every time it fails :(. Instead I think I'll need to make the workflow step that runs the tests to capture success or failure and set an output variable which is used by the subsequent steps to send a success or failure message to slack instead of using `success()` and `failure()`.

**Comment by camscale** [comment]
Going to leave it as-is - neither way is perfect.
