### ISSUE TITLE
Document Google SAML or OIDC setup

### ISSUE THREAD

**Issue by aberoham** [gravitational/teleport#2418]
Various folks have asked for detailed step-by-step documentation on how to configure Google SSO with Teleport Enterprise. Their SAML bits work for sure, with the caveat that the underlying IAM schema on Google's side doesn't by default have a traditional "group" assertion. Google OIDC should work too, or at least, following the Gravity Google OIDC docs works for basic auth without specific claims.

**Comment by aberoham** [comment]
Note that this matters -- ":443 in the teleport yaml ACS URL but not in the GSuite config."

**Comment by harshvardhanS** [comment]
I am able to integrate teleport authentication with Google SAML but its very complicated !!
While trying SAML integration, the tool does not fetch user group details automatically to map group with roles.
In order to make it work, I manually created custom attribute "**groups**" for each user and then defined attribute mapping. But it's a tedious manual process that we need to do for all users whenever they are added to a group !!.
I'm looking for a better workaround to this maunal task !!

**Comment by webvictim** [comment]
Detailed G Suite documentation lives here, along with a video on how to set it up - https://gravitational.com/teleport/docs/ssh_gsuite/

With regard to the comment from @harshvardhanS - this appears to be a Google-imposed limitation and is not something we can change. Personally, I would recommend using something like Auth0 instead of going direct to Google for authentication - Auth0 can authenticate with Google, but then add custom claims/details to the response before it's processed by Teleport. Alternatively, I would advise using a different, more fully-featured SSO provider (Okta, OneLogin etc) as Google is clearly not interested in providing a full service.
