### ISSUE TITLE
Handle 409 from release service gracefully in arm64 pipeline

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#24815]
We keep getting bit by release service returning 409 if you re-trigger a failed build while the old arm64 workflow is still running. Let's gracefully ignore 409 from release service instead of failing the entire build. We already wasted multiple hours waiting for retries builds due to this problem.

**Comment by r0mant** [comment]
@camscale Same applies to GHA-based macOS pipelines.

**Comment by camscale** [comment]
@tcsc I'll take care of this for the linux pipeline too -I have some changes locally (still to test) that does this for both linux and mac pipelines almost ready to go.

**Comment by camscale** [comment]
I think that the underlying cause of this problem is that when we cancel a drone pipeline, it does not cancel the corresponding GitHub workflow. We should update `gh-trigger-workflow` to handle whatever signal drone will send it on cancellation and abort the GitHub workflow. Then when the drone release is re-started, the pipeline that cleans up the existing draft release on the release server will not race with a GitHub actions workflow currently running.

However, for now we'll handle a 409 on uploading an asset as a non-error. I did think at first that maybe this would be reasonable as we already ignore 409 errors when registering a release with the release server, but now I understand why that is (there is a many-to-one relationship between assets and releases so we may try to register the release multiple times as we iterate the assets), it is perhaps a little dodgy to ignore 409 errors - it has the potential to release an old build of a tag that somehow was mis-built when rebuilding the proper release. However if there are any changes to the code or workflows at all, that would require a new tag/version so maybe this would never happen given good release discipline.

This would be properly cleaned up when we look to remove the shell-in-yaml code entirely and find a better way of performing this step in the workflow (likely something around [relcli](https://github.com/gravitational/cloud/tree/master/scripts/relcli), which already has drone-specific handling that could be updated/extended for use in github actions.

**Comment by tcsc** [comment]
Yep - I'm looking at adding cancellation handling to `gh-trigger-workflow` as a separate issue

**Comment by camscale** [comment]
All backported and done now.
