### ISSUE TITLE
Add automatic joining functionality for self-hosted on-prem servers

### ISSUE THREAD

**Issue by pschisa** [gravitational/teleport#25069]
What would you like Teleport to do?
Similar to automatic discovery or IAM joining for AWS, allow for on-prem servers to have a secure method of automatically joining a Teleport cluster without relying on the customer to design a secure join token distribution method

What problem does this solve?
Customers who host on-prem servers globally need to join resources dynamically and securely.  

If a workaround exists, please include it.
Configure a method of storing a server join token in a secret store that can be accessed by on-prem servers when they come online.

**Comment by zmb3** [comment]
I think we need a little more information in order to make this actionable.

In order to allow a node to join a Teleport cluster, we have to establish that we trust the node.

For platforms like AWS, GitHub Actions, etc. we leverage features of the platforms that cryptographically validate the identity of the workload. This allows us to establish that the workload should be trusted and allow the node to join the cluster.

In the absence of a service like this, we establish trust by verifying that the node has knowledge of a shared secret (a join token).

If the desire is to avoid using a token, then we need to integrate with some sort of trusted service that can vouch for the identity of the workload. Does this feature request come with any sort of service in mind?

**Comment by pschisa** [comment]
An initial suggestion had been something physical that could be connected to the server (like an HSM or yubikey) that can be used to establish the trust.

**Comment by gpothier** [comment]
I think I have a similar use case. We need to be able to remotely connect to users' Ubuntu workstations to provide support. Currently, we have a private Debian package repository that only machines authenticated through LDAP can access; whenever we provision a workstation, the first thing our provisioning script does is to create an LDAP principal for the machine, and then install one of our private packages from that repository. That package sets up a connection to our VPN, so all workstations are always connected. That is how we currently ssh into them. However, we would like to use Teleport instead, as the VPN solution is cumbersome (workstations do not have fixed IPs inside the VPN, and no resolvable name either, so we have to go into the VPN server's status page to obtain the IP of the host we want to connect to).

What I would like our provisioning script to do is to enroll to Teleport using the LDAP identity, instead of installing our VPN package. Is there a way for Teleport the verify that we trust a node using LDAP?
