### ISSUE TITLE
Enroll New Resource: Database Wizard missing step(s)

### ISSUE THREAD

**Issue by Valien** [gravitational/teleport#25153]
Expected behavior:

Following the Enroll New Resource for the Database (In my case RDS) you can follow the wizard and it should work out of the box.

Current behavior:

Following the wizard it breaks on this step:

![image](https://user-images.githubusercontent.com/1424442/234345913-fb55236d-6c6a-4dcc-b461-e326a9c0aba9.png)

The CLI command creates the policy with no issue but it does not attach it to a role, and therefore you cannot attach this to your EC2 instance. 

We need to add another step in mentioning that this policy needs to attach to an existing role or a new role (or even create the role at the same time) that then needs to be added to the AWS resource.

Even this part of our docs: https://goteleport.com/docs/database-access/guides/rds/#step-36-create-an-iam-policy-for-teleport - is a little confusing  to be honest.

Bug details:
- Teleport version: Cloud 12.2.3
- Recreation steps: go through wizard.
- Debug logs: none

**Comment by GavinFrazar** [comment]
This issue has been mostly addressed, since the step now explains attaching to a role and attaching the role to an instance:

![Image](https://github.com/user-attachments/assets/04aa916d-9493-4fcf-b88a-e5cbf78b7eea)

Do we want to do anything differently here @r0mant?

As a reminder for context, you can only end up on this page if the "deploy" page is skipped due to an existing `db_service` that matches the database labels.
