### ISSUE TITLE
Automatic agent installation for Teleport Discover

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#25521]
As part of improving our Discover RDS flow, we want to provide users with ability to automatically provision a database agent for them without asking them to come up with an instance they want to deploy it to and setup IAM permissions for it (e.g. SSM).

Explore the following (in the order of preference):

- Can we run db_service as part of Proxy and use our AWS integration to grant it rds-connect permissions?
  - We don't want to require users to expose the database endpoints publicly but can we use [PrivateLink](https://aws.amazon.com/privatelink/) or [VPC Peering](https://docs.aws.amazon.com/vpc/latest/peering/what-is-vpc-peering.html) for their Proxy to be able to access their private database endpoints without having to run a separate agent?
  - Might be useful article: https://blog.andreev.it/2022/03/aws-access-rds-database-using-privatelink-from-another-account/.
- Can we spin up an agent in "serverless" mode e.g. in Fargate?
- Possible to use Lambda? Can it run Go code? https://docs.aws.amazon.com/lambda/latest/dg/go-image.html
  - I think Lambda may not be suitable for running long-running tasks like agents, so this option may not work?
- If it doesn't work for some reason, what do we need to spin up an EC2 instance automatically with it e.g. from some AMI?

**Comment by marcoandredinis** [comment]
After some investigation we came up with an approach which uses ECS with Fargate.
The major upsides are:
- fast deploy times (less than a minute from 0 to Database Service ready to proxy connections)
- available on most regions (including GovCloud)
- no extra cost except compute
- no tokens if using `iam-join` join method

The major downsides of this approach are:
- it doesn't support Automatic Upgrades
- the integration's role (the assigned role for the OIDC IdP) requires `iam:PassRole` which, when configured in a relaxed way, (eg, no resource limitation) might be dangerous

A PoC can be viewed here:
https://github.com/gravitational/teleport/tree/marco/agent1clickinstall

For the record, the following options were explored but not considered for now:
- EKS using Fargate
Discarded because takes 17 minutes to spin up a cluster, there's no support in GovCloud and the cluster alone (no compute) costs 0.10$/hour
https://aws.amazon.com/eks/pricing/
https://docs.aws.amazon.com/eks/latest/userguide/fargate.html

-EC2 using an SSM agent to install
This assumes a customer is ok with us using an already existing EC2 container.
Otherwise, we would need to create an EC2 instance and 
This also requires the usage of `iam:AttachRolePolicy` which has potential for privilege escalation.
