### ISSUE TITLE
Kubernetes delegated joining support with external Auth Server

### ISSUE THREAD

**Issue by strideynet** [gravitational/teleport#25543]
As it stands, Kubernetes delegated joining only works if the Auth server is inside of the same Kubernetes cluster that a prospective joinee is part of.

This is problematic for a few reasons:

- People often have multiple Kubernetes clusters
- Teleport Cloud does not run in a customers Kubernetes cluster

Allowing pods to join from a Kubernetes cluster where the Auth server is not residing would allow:

- New Machine ID use-cases where customers run `tbot` as a sidecar to their pods to provide access to Teleport protected resources
- Provide greater support for on-prem environments where other join methods cannot be used
- Onboarding of Kubernetes Access nodes without a static token in on-prem environments
- Allow more fine grained access control. Using the IAM/GCP/Azure join method, any pod on a Kubernetes node can join using that token, rather than a specific node.

Problems:
- How would the Auth Server authenticate to the Kubernetes API to perform the TokenReview? Vault allows users to configure a service account JWT for this purpose (https://developer.hashicorp.com/vault/docs/auth/kubernetes)
- Are Customer's Kubernetes APIs accessible to an external Auth server ? Could we allow a Kubernetes Access node in future to act as a "hop" point?

**Comment by tigrato** [comment]
After discussing with @strideynet, a possible better approach for multi-clusters support is to allow users to configure the jwks of the cluster in the token. 

The problem we have is that Kubernetes joining evaluation happens in Auth server and it requires that Auth could access the target cluster's `CreateTokenReview` method. In most cases, this is not possible because the target cluster is not accessible from the Auth's network, but it also requires that auth dials through the internet which won't be allowed for many customers' environments.

Given the problems above, one possible solution is to bypass the `CreateTokenReview` call by checking the signature of the JWT token provided. Each cluster defines its own private key for signing Kubernetes Service accounts JWT tokens and its public `jwks` is publically available at `http://localhost:8080/openid/v1/jwks`. The idea would be to allow users to specify the JWKS payload of the target cluster as part of the Kubernetes joining token spec. When a Kubernetes Join token has JWKS field defined, Teleport validates the JWT token signature with it and ensures it belongs to a service account by checking the JWT payload

```json
{
  "aud": [
    "https://kubernetes.default.svc.cluster.local/",
    "k3s"
  ],
  "exp": 1719568669,
  "iat": 1688032669,
  "iss": "https://kubernetes.default.svc.cluster.local/",
  "kubernetes.io": {
    "namespace": "teleport-agent",
    "pod": {
      "name": "teleport-agent-0",
      "uid": "f7af7ba7-1fc5-4d93-b2b7-8e2bb90d27ce"
    },
    "serviceaccount": {
      "name": "teleport-agent",
      "uid": "3109067c-89b2-4343-8796-eca57bdeda13"
    },
    "warnafter": 1688036276
  },
  "nbf": 1688032669,
  "sub": "system:serviceaccount:teleport-agent:teleport-agent"
}
```

For tokens that do not have the JWT defined, Teleport fallbacks to local `CreateTokenReview`.

Using JWKS instead of `CreateTokenReview` allows attackers to use a token from a deleted service account or belonging to a deleted pod to join a Teleport cluster but reducing the service account token validity would reduce the risk.

We can also warn users about preferring the `CreateTokenReview` as it it's a bit more secure and to use the JWKS only when handling joining for remote clusters. 

This approach also has a limitation when the private key is rotated, users must manually update the JWT token!

cc @hugoShaka

**Comment by hugoShaka** [comment]
I agree that the JWKS-validation approach seems saner and solves most of our issues; a design where the Auth needs internet access to send `TokenValidationRequests` would break most Teleport design patterns.

The security guarantees are weaker, though:
- the token can be replayed, this seems vulnerable to a MiTM attack
- the token can be exfiltrated and used while the pod has been removed
- long-lived tokens can be requested through projected volumes

Most of the Kubernetes community sounds comfortable with those limitations, AFAIK Vault considers this enough. If we are not, this approach might be hardened in the following ways:
- make a separate `kubernetes-remote` join method to avoid fallback from `TokenReview` to the weaker `JWKS` (and rename `kubernetes` to `kubernetes-internal` ?)
- enforce a max JWT duration (the default is currently 1 year, which seems unacceptable when we can't validate if the token has been revoked). This might harm the usability, though as the users would need to request a token through projected volumes with a low TTL. We can mitigate this with the chart (or the next item).
- do a challenge, as we do for IAM joining. This is theoretical, but the `TokenRequest` API seems to allow the requester to choose its audiences. The joining Teleport process could initiate the joining, then use its existing SA token to request a new one with an audience like `teleport-cluster.example.com/<challenge nonce>`. This means the SA role needs permissions like
  ```yaml
    - apiGroups: [""]
    resources:
      - serviceaccounts/token
    resourceNames:
      - <SA name>
    verbs:
      - create
  ```
  Note: to avoid an infinitely renewable token, we might need 2 SAs.

**Comment by strideynet** [comment]
> do a challenge, as we do for IAM joining

Challenge using audience or similar seems like a good idea here to avoid replay and to ensure the pod is "current".

---

As for a new join method - I think a distinct join method makes the most sense here in distinguishing that this is less secure. I would avoid naming it `remote` or renaming the old one to `internal` - there's nothing to say that we don't find a solution for using the TokenReview endpoint remotely in future (e.g leveraging an existing kube agent in cluster to invoke the TokenReview endpoint).

**Comment by tigrato** [comment]
> do a challenge, as we do for IAM joining

I agree with this but if the user still has access to the cluster, he can manually create the SA token with the received audience with the token he stole. But let's follow that. It's also a better approach anw even for in-cluster reviews

**Comment by hugoShaka** [comment]
> I agree with this but if the user still has access to the cluster, he can manually create the SA token with the received audience with the token he stole.

We can mitigate the risk to a minimum with 2SA:
- the one assumed by teleport `teleport-agent` that is allows to issue tokens for `teleport-agent-joining`
- another one use for joining `teleport-agent-joining`

With 1 hour tokens, this means if I steal a `teleport-agent-joining` token I cannot reuse it because of the nonce, and if I steal a `teleport-agent` token I need access to the Kubernetes API to issue new tokens and my access is limited to 1 hour.

> We should reduce the tokens TTL to 10-15min.

The `teleport-agent-joining` token only has to be valid when joining, and in the challenge case, Teleport is requesting the token just before joining. As long as the validity is absorbs potential time skews we should be good.

> there's nothing to say that we don't find a solution for using the TokenReview endpoint remotely in future

Would `kubernetes-tokenreview` / `kubernetes-api` versus `kubernetes-oidc` / `kubernetes-jwks` make more sense?

**Comment by strideynet** [comment]
I almost like `kubernetes-offline` - but I know that'll make no sense to a prospective user.

If we want to encourage the TokenReview one as the golden path, maybe that stays as `kubernetes` and then we have `kubernetes-jwks` as the other one ?

**Comment by strideynet** [comment]
As this significantly departs from the existing join method - I'm going to put together an RFD.
