### ISSUE TITLE
gitref missing from metrics endpoint

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#25573]
### Expected behavior:

the teleport_build_info metric should have a value populated in the gitref. Here's an example of teleport 10.3.7-fips correctly returning the version:

```
curl http://127.0.0.1:3000/metrics | grep gitref
teleport_build_info{gitref="v10.3.7-0-g63c9f949f",goversion="go1.18.6b7",version="10.3.7"} 1
```

### Current behavior:

Teleport 10.3.8 and above does not have the gitref populated.

```
curl http://127.0.0.1:3000/metrics | grep gitref 
teleport_build_info{gitref="",goversion="go1.18.6b7",version="10.3.8"} 1
```

(other major versions of teleport may be affected. I only tested the versions between 10.2.0 and 10.3.15 in a binary search approach to find the first broken version)

### Bug details:
- Teleport version - `gitref="",version="10.3.8"` - the issue appears to affect only fips builds
- Recreation steps - this was observed simply by enabling the metrics endpoint with the affected versions.
- Debug logs - n/a

**Comment by r0mant** [comment]
To add to Jeff's analysis, I also found that it seems to be broken not just on FIPS images but on regular downloaded artifacts, interestingly it works for some architectures but not others.

For example, arm64:

```
working -> Teleport Enterprise v10.3.11 git:v10.3.11-0-gb9d89b8129 go1.19.4
broken -> Teleport Enterprise v10.3.12 git: go1.19.5
broken -> Teleport Enterprise v11.3.11 git: go1.20.3
working -> Teleport Enterprise v12.3.1 git:v12.3.1-0-ga5d6659 go1.20.4
```

Same releases working on amd64:

```
working -> Teleport Enterprise v11.3.11 git:api/v11.3.11-0-g10728c6cc1 go1.20.3
working -> Teleport Enterprise v10.3.15 git:api/v10.3.15-0-g76f10bc72f go1.19.7
```

The customer is also saying they're seeing this on amd64 RPM https://yum.releases.teleport.dev/centos/7/Teleport/x86_64/stable/v10/repo_rpms/teleport-ent-10.3.15-1-fips.x86_64.rpm which is strange considering my above amd64 tests worked (on a non-FIPS build though).

Potential culprits are multi-arch pipelines or arm64 pipelines (because it seems to affect arm64 more?):

https://github.com/gravitational/teleport/commit/2520e779039eafe6305536075cdabd09cd9a97cc
https://github.com/gravitational/teleport/commit/812cf733db2861746611eddd2d9bd8373c23f3c1
https://github.com/gravitational/teleport/commit/07a7b9555864c67cc423883dd5c44c69fe482f55

**Comment by r0mant** [comment]
Will be fixed in next patch releases.
