### ISSUE TITLE
SSH sessions sometimes fail when enhanced recording is enabled

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#26273]
## Expected behavior:

Users can start SSH sessions when enhanced recording is enabled.

## Current behavior:

Sessions sometimes fail with error `Failed to open enhanced recording (interactive) session` caused by the cgroup not existing:

```
*fs.PathError mkdir /cgroup2/teleport/cc39b5ec-c7fc-427a-a0f7-00ebaa635f2c/6c6d5971-251f-4049-94ec-da859dfe6e02: no such file or directory
```

The issue is resolved after the node is rebooted.

## Bug details:

- Teleport version: 12.3

## Repro

1. Configure an SSH node with a `public_addr` and enhanced recording:

```
ssh_service:
  enhanced_recording: { enabled: true }
  public_addr: [ node.example.com:3022 ]
```

2. `tsh` into the node using a role with `enhanced_recording: command` and `require_session_mfa: true`. Everything should work correctly.

3. From another session (best to `ssh` to the node instead of `tsh`), add an extra `public_addr` and save the config.

```
ssh_service:
  enhanced_recording: { enabled: true }
  public_addr: [ node.example.com:3022, node.example.internal:3022 ]
```

4. Send a SIGQUIT to the node to restart the SSH service.
5. The open `tsh` session from step 2 should be terminated.
6. `tsh ssh` again. Observe a client-side error:

```
$ tsh ssh --cluster=foo node
Tap any security key
Detected security key tap
ERROR: EOF
```

The node logs show the following:

```
2023-04-27T20:29:56Z ERRO [SESSION:N] Failed to open enhanced recording (interactive) session error:[
ERROR REPORT:
Original Error: *fs.PathError mkdir /cgroup2/teleport/ab48fe0e-8ae4-4d34-bf2e-ddd77bce7edc/e2e9d6dc-c4e8-4672-8923-80a763b23dd9: no such file or directory
Stack Trace:
	github.com/gravitational/teleport/lib/cgroup/cgroup.go:115 github.com/gravitational/teleport/lib/cgroup.(*Service).Create
	github.com/gravitational/teleport/lib/bpf/bpf.go:225 github.com/gravitational/teleport/lib/bpf.(*Service).OpenSession
	github.com/gravitational/teleport/lib/srv/sess.go:1010 github.com/gravitational/teleport/lib/srv.(*session).startInteractive
	github.com/gravitational/teleport/lib/srv/sess.go:269 github.com/gravitational/teleport/lib/srv.(*SessionRegistry).OpenSession
	github.com/gravitational/teleport/lib/srv/termhandlers.go:125 github.com/gravitational/teleport/lib/srv.(*TermHandlers).HandleShell
	github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1644 github.com/gravitational/teleport/lib/srv/regular.(*Server).dispatch
	github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1517 github.com/gravitational/teleport/lib/srv/regular.(*Server).handleSessionRequests
	github.com/gravitational/teleport/lib/srv/regular/sshserver.go:1251 github.com/gravitational/teleport/lib/srv/regular.(*Server).HandleNewChan.func1
	runtime/asm_amd64.s:1598 runtime.goexit
User Message: mkdir /cgroup2/teleport/ab48fe0e-8ae4-4d34-bf2e-ddd77bce7edc/e2e9d6dc-c4e8-4672-8923-80a763b23dd9: no such file or directory] session_id:e2e9d6dc-c4e8-4672-8923-80a763b23dd9 srv/sess.go:1011
```

**Comment by espadolini** [comment]
The repro steps say "Send a SIGQUIT to the node to restart the SSH service", was that meant to be SIGHUP?

**Comment by espadolini** [comment]
After inspecting some logs, we've come to the realization that this bug can also be triggered by a change in principals, which forces a reissue of credentials and then an in-process restart.

The bug is caused by Teleport unmounting the cgroup2 filesystem even if it's being restarted, after the new instance of Teleport (either in a new unix process, after SIGHUP, or a new instance of `TeleportProcess` in case of an in-process restart) has already verified that the mountpoint is in place.

There's an argument to be made about simply leaving the mountpoint in place (which would also allow Teleport to be pointed at `/sys/fs/cgroup` if there's a cgroup2 hierarchy already mounted there) but without changing too many things, we can simply avoid the unmount step if Teleport is internally restarting (which is similar to what we're already doing for App access, to avoid deleting heartbeats).
