### ISSUE TITLE
Document Teleport IOT architecture and config

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2674]
## Description

Document new Teleport IOT feature and configuration.

**Comment by russjones** [comment]
Teleport IoT configuration changes occur in two places: proxy and node.

For nodes, instead of setting the address of the Auth Server under `auth_servers` in Teleport configuration, set the address of the Teleport web proxy (by default running on port 3080). From this address, Teleport nodes will automatically discover the address of the SSH reverse tunnel server.

For proxy settings, it is encouraged to set `ssh_tunnel_public_addr` because this address will be returned when a node tries to discover the address of the reverse tunnel server. If this address is not set, Teleport will fall back to `tunnel_listen_addr`.

**Comment by klizhentas** [comment]
@russjones If this address is not set, Teleport should fall back to `public_addr` of the proxy (without the port), if set, then to the `public_addr` of the general section if set, then to the `tunnel_listen_addr` if set and then to the `listen_addr` if set.

**Comment by brant4test** [comment]
Looking forward to the guide.

**Comment by kontsevoy** [comment]
@benarent do you want to tackle this? Random thoughts:

* We can have "Adding a node located behind NAT" to the Quick Start. Pros: more people will learn about this feature. Cons: Quick Start won't be so quick.
* We can add a sub-section to "Adding Nodes" to the cluster.
* We can add a sub-section to "Trusted Clusters", saying that "if you do not need to have entire clusters behind NAT, but a single node, take a look at XXX"
* Add a question to FAQ. In fact, it's been indeed a very frequently asked question when Teleport was originally released.

... or all of the above.

**Comment by benarent** [comment]
Yes, I'll take this one on. 

I'll also add a  version of https://gravitational.com/teleport/docs/img/everything.svg to show it working in IoT mode.

**Comment by kontsevoy** [comment]
@benarent BTW when I tired to get IoT to run for the first time, I forgot to open some ports. The user [here)(https://github.com/gravitational/teleport/issues/803#issuecomment-497158747) probably had the same issue. Probably worth mentioning in the docs.

**Comment by kontsevoy** [comment]
@benarent Also, you're probably better off with this:
https://gravitational.com/teleport/docs/img/tunnel.svg from "Trusted Clusters" section.

IoT is the same thing as "trusted clsuters", i.e. uses the same underlying framework.

**Comment by benarent** [comment]
Deployed in 4.0 Docs release.
