### ISSUE TITLE
Add Timestamp to logging output

### ISSUE THREAD

**Issue by aaronmell** [gravitational/teleport#2676]
It would be super useful if application logs could include a timestamp on each line. Without a timestamp the logs are useless when doing log aggregation.

**Comment by aberoham** [comment]
e.g. 
```
log:
       output: /var/log/teleport.log
       severity: WARN
```

**Comment by klizhentas** [comment]
I think it would be cool to add format string compatible with our formatting

```yaml
log:
    format: "{{timestamp}} {{component}} {{message}}"
```

**Comment by Nuru** [comment]
@benarent why did you remove this from 4.3? Can we at last get a flag that enables timestamps in the default logger format, i.e. change: https://github.com/gravitational/teleport/blob/5b916564ef23947bd5dd21f2236de1e7deb642f5/lib/utils/cli.go#L63 to 
```yaml
 DisableTimestamp: true, 
```
@klizhentas What do you think?

I find the lack of timestamps in the logs to be a real problem.

**Comment by klizhentas** [comment]
I originally proposed the format:

```
log:
    format: "{{timestamp}} {{component}} {{message}}"
```

for two reasons:

1. Users can control the format output with additional lines to match their existing format
2. Users can use text/template and we could export some functions to allow them control the timestamp in the future:
   `format: "{{Format(timestamp, 'custom-format-here')}}`
I was assuming that `text/template` should help implementing this logic:


```
   template.New(format)
   tpl.Render(map[string]interface{}{timestamp: utc.Now(), ...}
```

I'm open to discussion, but unless there are no specific concerns you may have, I'd stay on this route.

**Comment by a-palchikov** [comment]
Ok, I understand and initially thought about using text/template. The problem with it is that the format needs to be slightly modified to make it compatible with the text/template package because as written, the fields will appear as function calls to the package's parser. E.g. prefixing them with a `dot` at least:
```yaml
log:
    format: "{{.timestamp}} {{.component}} {{.message}}"
```
I agree we can provide rich formatting facilities but it also leaves some questions open. For instance, where does it output the arbitrary opaque fields that teleport might programmatically attach to each log entry - always after the `message` or does the user get somehow to choose. Are we allowed to do any preformatting - e.g. whether `component` is implicitly enclosed in square brackets or is it also user-specific but the default format would stay close to how the logs look now?

**Comment by quinqu** [comment]
For now should implementation be parsing an input such as originally proposed: 
```
log:
    format: "{{timestamp}} {{component}} {{message}}"
```
Then the next feature/step can be allowing users to control timestamp format? I think the main issue here that needs to be addressed immediately is that there is no option to enable timestamp in the logs at all.

**Comment by klizhentas** [comment]
@quinqu you are right, let's not make it more complex than needed in the MVP.

Actually, the way you implemented it as-is:

https://github.com/gravitational/teleport/pull/5898/files

is good to go, we can introduce new formats later.

**Comment by Nuru** [comment]
@quinqu @a-palchikov Please do not forget about #4407 JSON log format. Any "leading system" (as they say in commercials) that is going to store and index logs is going to prefer to receive them in JSON format.

**Comment by a-palchikov** [comment]
@Nuru this will be resolved separately.
