### ISSUE TITLE
Application enroll resource in UI should be Web Application

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#27005]
Expected behavior:

Application adding should identify what type of application is available

Current behavior:

Multiple other application types are available (AWS, TCP,...).  This identifies as just Application and does not give any context that it supports just Web Applications and there are other app types.

Bug details:
- Teleport version: 13.0.3
- Recreation steps
Go to Management section and enroll new resource

**Comment by zmb3** [comment]
So the request is just to change "application" to "web application" in the UI?

**Comment by stevenGravy** [comment]
> So the request is just to change "application" to "web application" in the UI?

More why type of apps they are.  Here is the list of apps in an example.  This includes SAML, tcp and web.  There's no specific label or type like the db list.

<img width="1386" alt="image" src="https://github.com/gravitational/teleport/assets/60704961/6c669f69-c975-4b3a-931c-317eef92079a">

**Comment by zmb3** [comment]
The description column in the table distinguishes SAML apps from web apps. (TCP apps aren't shown at all in the web UI since you can't connect to them from there).

I am still confused though, the title refers to enrolling applications, but now we're talking about the listing of apps that are already enrolled.

**Comment by zmb3** [comment]
Closing as deprecated by unified view.
