### ISSUE TITLE
Potential deadlock in reader.go

### ISSUE THREAD

**Issue by hhheiaenia** [gravitational/teleport#27064]
I notice that all the r.cond.Wait() and r.cond.Broadcast() are protected by the mutex lock r.cond.L.Lock() in the file https://github.com/gravitational/teleport/blob/master/lib/client/escape/reader.go#LL192C16-L192C16. So I doubt whether this situation can cause a deadlock. 

Maybe what I said is not right, thank you for taking a look.

**Comment by tigrato** [comment]
Hey @hhheiaenia 

Thank you for bringing this into our attention.

Explaining deeply what's inside:

`Reader` uses a `sync.Cond` to wake up multiple readers once something is written into it. `sync.Cond` is conditional variable that allows one/multiple goroutines to wait for a given condition and to wake up once the condition is signaled/broadcasted.

`sync.Cond` receives a `sync.Mutex` as a parameter and expects it to be locked once `cond.Wait()` method is invoked. Internally, `cond.Wait()` registers the goroutine into go's runtime and unlocks the mutex before parking. After the wake condition happens and before returning  from `cond.Wait()`, the mutex is locked again (check the snippet bellow).

```go
// Wait atomically unlocks c.L and suspends execution
// of the calling goroutine. After later resuming execution,
// Wait locks c.L before returning. Unlike in other systems,
// Wait cannot return unless awoken by Broadcast or Signal.
//
// Because c.L is not locked while Wait is waiting, the caller
// typically cannot assume that the condition is true when
// Wait returns. Instead, the caller should Wait in a loop:
//
//	c.L.Lock()
//	for !condition() {
//	    c.Wait()
//	}
//	... make use of condition ...
//	c.L.Unlock()
func (c *Cond) Wait() {
	c.checker.check()
	t := runtime_notifyListAdd(&c.notify) // register the notify into go's runtime
	c.L.Unlock()  // unlock the mutex
	runtime_notifyListWait(&c.notify, t)   // park until notify is invoked.
	c.L.Lock()
}
```

When calling `cond.Wait()`, it's mandatory that the mutext is held lock otherwise a panic occurs when `cond.Wait()` tries to unlock the mutex before parking. Regarding the `cond.Broadcast()`, it's allowed but not required that the mutex is held during the call as per docs: `It is allowed but not required for the caller to hold c.L during the call.`

Since `cond.Wait()` unlocks the mutex while parked, there is no deadlock and multiple goroutines can park on wait and unlock when a broadcast is received.

Thanks again for bringing this to our attention and I hope I was able to explain the behavior of the difficult and often unintuitive `sync.Cond`.
