### ISSUE TITLE
Teleport Application Access should add `X-Forwarded-For` headers to pass the real client IP to the server

### ISSUE THREAD

**Issue by eedgar** [gravitational/teleport#27201]
What would you like Teleport to do?
when using the application feature endpoint servers see the app server ip as the source of the connection when this is not accurate.

What problem does this solve?
In order to figure out the offending client in this case you have to then look through the teleport logs and history to see which ip was the origination of the request.

If a workaround exists, please include it.

please see https://docs.nginx.com/nginx/admin-guide/load-balancer/using-proxy-protocol/

**Comment by zmb3** [comment]
@r0mant @AntonAM don't we already do this for IP pinning?

**Comment by AntonAM** [comment]
@zmb3 yes, we do that internally, so the Teleport app server sees the real client IP. I'm not sure, but I think this issue talks about client IP on the actual application outside of Teleport, we don't send PROXY headers with client IP there.

**Comment by webvictim** [comment]
Proxy protocol is layer 4. What you want is for Teleport application access to add `X-Forwarded-For` headers to outbound requests which contain the connected user's remote IP.

**Comment by webvictim** [comment]
@johnecapps Did you mean to comment on a different issue? AFAICT not passing the client IP to a proxied app wouldn't affect asset loading.

**Comment by webvictim** [comment]
Looking at the output of the built-in dumper app (activated via `debug_app: true`), it looks like this has been implemented as of Teleport v14.0.0-beta.2. However on a single-node Teleport installation I'm seeing the same address twice in the `X-Forwarded-For` header rather than just once:

```
X-Forwarded-For: 1.2.3.4, 1.2.3.4
```

Not sure if this is a bug, but I know Teleport itself fails to trust any `X-Forwarded-For` header with more than one IP present.
