### ISSUE TITLE
Teleport log noise from NLB healthcheck make the logs hard to read

### ISSUE THREAD

**Issue by cove** [gravitational/teleport#2815]
Have a question? Please use [Our Forum](https://community.gravitational.com)

**What happened**:
```
Jun 28 17:21:43 xxx /opt/teleport-ent/teleport[32735]: WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *net.OpError read tcp xxx:3080->xxx:61777: i/o timeout\nStack Trace:\n\t/home/rjones/Development/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:257 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/home/rjones/Development/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:197 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/usr/local/go/src/runtime/asm_amd64.s:1338 runtime.goexit\nUser Message: failed to peek connection\n" logrus/entry.go:140
```
**What you expected to happen**:
Healthchecks don't generate errors in the logs

**How to reproduce it (as minimally and precisely as possible)**:
Setup teleport proxy behind an AWS NLB

**Environment**:
- Teleport version (use `teleport version`):  Teleport Enterprise v3.2.6git:v3.2.6-0-g67b4ddfb go1.11.5
- Tsh version (use `tsh version`): Teleport v3.2.6 git:v3.2.6-0-g67b4ddfb go1.11.5
- OS (e.g. from /etc/os-release):CentOS release 6.10 (Final)

**Browser environment**

- Browser Version (for UI-related issues): na
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- tsh --debug
- teleport --debug

**Comment by webvictim** [comment]
I believe this particular log spam is also caused by TCP healthchecks:

```
Aug 16 19:49:04 ip-172-31-43-50.us-west-2.compute.internal /usr/bin/teleport[9157]: ERRO             read tcp 172.31.43.50:3023->172.31.43.253:22619: read: connection reset by peer
Aug 16 19:49:14 ip-172-31-43-50.us-west-2.compute.internal /usr/bin/teleport[9157]: ERRO             read tcp 172.31.43.50:3023->172.31.43.253:47961: read: connection reset by peer
Aug 16 19:51:04 ip-172-31-43-50.us-west-2.compute.internal /usr/bin/teleport[9157]: ERRO             read tcp 172.31.43.50:3023->172.31.43.253:63845: read: connection reset by peer
Aug 16 19:51:14 ip-172-31-43-50.us-west-2.compute.internal /usr/bin/teleport[9157]: ERRO             read tcp 172.31.43.50:3023->172.31.43.253:13943: read: connection reset by peer
Aug 16 19:52:44 ip-172-31-43-50.us-west-2.compute.internal /usr/bin/teleport[9157]: ERRO             read tcp 172.31.43.50:3023->172.31.43.253:39664: read: connection reset by peer
Aug 16 19:53:14 ip-172-31-43-50.us-west-2.compute.internal /usr/bin/teleport[9157]: ERRO             read tcp 172.31.43.50:3023->172.31.43.253:50548: read: connection reset by peer
Aug 16 19:53:57 ip-172-31-43-50.us-west-2.compute.internal /usr/bin/teleport[9157]: ERRO             read tcp 172.31.43.50:3023->172.31.43.253:56575: read: connection reset by peer
Aug 16 19:58:15 ip-172-31-43-50.us-west-2.compute.internal /usr/bin/teleport[9157]: ERRO             read tcp 172.31.43.50:3023->172.31.43.253:13857: read: connection reset by peer
Aug 16 19:58:44 ip-172-31-43-50.us-west-2.compute.internal /usr/bin/teleport[9157]: ERRO             read tcp 172.31.43.50:3023->172.31.43.253:54184: read: connection reset by peer
Aug 16 20:00:15 ip-172-31-43-50.us-west-2.compute.internal /usr/bin/teleport[9157]: ERRO             read tcp 172.31.43.50:3023->172.31.43.253:19349: read: connection reset by peer
```

**Comment by galindro** [comment]
Yes @webvictim, they are. I could confirm that just now. I tried to change the health check protocol to HTTP on the same TCP port (for ex. 3023) and changed the path to /webapi/ping, but it not worked. It only works on 3080 (which is actually the web port).

One solution could be add a support to this kind of request on TCP ports as well.

**Comment by webvictim** [comment]
There is no HTTP listener on ports other than 3080 which is why this happens. We may consider changing this in future.

There is a potential workaround, though. As per https://gravitational.com/teleport/docs/admin-guide/#troubleshooting, you can use `--diag-addr=0.0.0.0:3000` or similar to expose a debugging endpoint which allows you make HTTP requests to `http://<ip>:3000/healthz` and get either `200 OK` or `503 Service Unavailable` in response.

Normally I would only advise making the diagnostic endpoint available on `127.0.0.1` for security, but if you make it listen to all IPs and set up the firewall/security groups to only allow requests to port 3000 from the load balancer, it works as a health check.

**Comment by galindro** [comment]
But if we use AWS NLB as a EKS Service, we could not set the health check options, which means that isn't possible to set a different health check port  :(

**Comment by Aharic** [comment]
Would be worth exploring a log wrap-up option in the interim to make logs easier to read. Since we can't control AWS LB health check burst behavior, we could summarize a burst like this w/ a summary message to decrease amount of log usage and increase readability for troubleshooting purposes. Something along the lines of logging the first instance of the message and then wrapping up the subsequent bursts within a short, predefined period of time with a message along the lines of "Message appears x times over y period".
