### ISSUE TITLE
Handshake failed after update

### ISSUE THREAD

**Issue by Wikunia** [gravitational/teleport#2835]
**What happened**:
I get the error:

```
error: ssh: handshake failed: ssh: principal "<server addr> not in the set of valid principals for given certificate:
```

 when running 

```
$ tsh --proxy=SERVER_ADDR login NAME_OF_CLUSTER && tsh ssh NAME_OF_CLUSTER
Enter password for Teleport user ...:
Enter your OTP token:
XXXXXX
error: ssh: handshake failed: ssh: principal "<SERVER_ADDR>" not in the set of valid principals for given certificate: ["AAAAAAAA-5fe2-4028-a374-AAAAAAAAa7b3.SUB" "SUB.SUB" "SUB" "SUB" "remote.kube.proxy.teleport.cluster.local"]
```

**Environment**:
- Teleport version (use `teleport version`):
Teleport v4.0.2 git:v4.0.2-0-gb7e0e872 go1.12.1

- Tsh version (use `tsh version`):
Teleport v4.0.2 git:v4.0.2-0-gb7e0e872 go1.12.1

- OS (e.g. from /etc/os-release):
Arch Linux -> Ubuntu -> Raspbian

Works in Browser (logging in and change Cluster and login)

**Comment by webvictim** [comment]
The reason for this error is that the hostname you're using to connect to the Teleport proxy is not known to Teleport itself. This was a change made in recent versions to enhance security and help to prevent man-in-the-middle attacks.

The best way to fix this issue is to set the `public_addr` section of the `proxy` config to the hostname you're using to connect and restart the Teleport proxy. This will update the list of hostnames on the certificate and you should be able to log in again.

**Comment by klizhentas** [comment]
@Wikunia for future questions and continuing this conversation, please use community.gravitational.com

**Comment by arkanmgerges** [comment]
I had this issue also, then I've added public_addr to all sections (auth_service, ssh_service, and proxy_service) to  /etc/teleport.yml.
Now I don't have problem when I login, and when I use `tsh ssh`
