### ISSUE TITLE
Improve Kubernetes/RBAC documentation

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#2851]
Via a customer support ticket, this problem is also outlined in https://github.com/gravitational/teleport/issues/2614 

> Description of SSL cert(s) required and preferred practices around this would be very useful -- I'm fairly sure, for instance, that this requires a cert with a wildcard SAN, and requires a wildcard DNS name, and the cert has to be on the proxy machine rather than, say, hosted on an AWS ALB.

### Required Docs
- [ ] Examples of Enterprise RBAC users having different access to Teleport Clusters.
- [ ] Deeper dive into kubernetes cluster naming.

**Comment by webvictim** [comment]
To the customer's points:

1) It doesn't require a wildcard SAN - Teleport will generate the certificates required for Kubernetes with its own CA and validate them. The only TLS certificate that you need to provide that validates with a root CA is the one for your `main` public-facing Teleport proxy, i.e. the one that users will log into via web interface or `tsh`.

2) It does require a wildcard DNS name which should be pointed to the same IP as the `main` Teleport proxy.

3) The cert can be on an ALB as long as you run Teleport with `--insecure-no-tls` and terminate all TLS traffic on the ALB. This method also allows the use of [ACM](https://docs.aws.amazon.com/acm/latest/userguide/acm-overview.html) if desired.

**Comment by tarrall** [comment]
Couple of notes here.  I'm still a total novice with teleport so random readers who stumble on this reply ought to check with Gravitational before assuming this is correct.

Using an ALB in front of port 3080 seems to work fine **without** using `--insecure-no-tls`; per AWS docs the ALB does not validate certs when connecting to the backend.  Hostname for this load balancer will be what users use for `--proxy=<hostname>` and the SSL cert should to be "public" (e.g. from ACM) rather than self-signed.

Port 3026 (for k8s proxy), while HTTPS, does not appear to work with ALB.  **Does** work with NLB passing TCP straight through to the proxies.  No SSL cert needed here; teleport's self-generated cert works fine.  Hostname here needs a wildcard record "above" it, e.g. `k8s-proxy.example.com` and `*.k8s-proxy.example.com` until the SNI stuff is removed, which I think is coming in teleport 4.1?

(Someone with more free time than I have could probably get this working with one hostname + wildcard pointed at the NLB, with the NLB relaying to the ALB, but that requires a lot of silly stuff with lambdas so I'm not going there.)

**Comment by webvictim** [comment]
The SNI method (encoding a cluster name into a hostname) is indeed being deprecated in Teleport 4.1 - cluster information will be encoded into the issued certificates instead.

**Comment by webvictim** [comment]
The main focus of this ticket has changed as wildcard DNS records are no longer needed as of Teleport 4.1.

**Comment by benarent** [comment]
This has been fixed with recent product & Kubernetes changes.
