### ISSUE TITLE
SCP transfer errors are filed as success audit events

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#2861]
When uploading or downloading a file via SCP, failed requests are filed as success events.

Repro:

1. Try download a file from invalid location, notice the error
2. Check the audit events and find corresponding `T3004I` event type instead of `T3004E`

**Comment by awly** [comment]
Looks like the behavior changed since this was filed:
- download success/error codes are populated correctly
- upload code is always success (even if there was a problem uploading)

So I'll try to fix the upload instead.

Also, each SCP command creates 4 audit events, which seems like a lot:
![Screenshot_2020-05-05 Events](https://user-images.githubusercontent.com/1146263/81112397-1f8efc80-8f0e-11ea-9015-79923ba78edf.png)

I'll dig into that too.

**Comment by awly** [comment]
@alex-kovoy looks like some UI icons are incorrectly mapped:
![Screenshot_2020-05-05 Events(1)](https://user-images.githubusercontent.com/1146263/81117037-f2dee300-8f15-11ea-9cb1-dd596ec51ea7.png)

`SCP Upload Failed` should use the icon that `SCP Download Failed` uses (red, arrow pointing up)
`SCP Download Failed` should use an icon with the arrow pointing down, like the success one (below) but red.
![Screenshot_2020-05-05 Events(2)](https://user-images.githubusercontent.com/1146263/81117807-47369280-8f17-11ea-9142-1a54ece0b365.png)
