### ISSUE TITLE
SNI is no longer required for Kubernetes proxy

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2862]
## Description

SNI and as a result wildcard DNS records are no longer a requirement for teleport 4.1 

New versions of teleport receive a special certificate every time they do `tsh login <cluster-name>`
that contains the cluster name encoded in the metadata. That's how teleport proxy can route all requests coming to the main proxy address.

The documentation and architecture should be updated to reflect that.

**Comment by benarent** [comment]
Other reference notes ( to help me ) :
https://github.com/gravitational/teleport/pull/2619
https://github.com/gravitational/teleport/pull/2859

It seems we didn't address this issue before of DNS / SNI in the past. I started to look at where to place this, but since it not being documented resulted in it being a bug, I wonder where the best way to explain it to users without confusing them. 

Any thoughts on this @webvictim ?

**Comment by benarent** [comment]
I chatted with @webvictim, and I've just added a line to the 4.1 docs for Multiple Kubernetes Clusters.
