### ISSUE TITLE
Disable directory listing of Proxy's builtin fileserver

### ISSUE THREAD

**Issue by jonatanzafar59** [gravitational/teleport#28873]
Expected behavior:
shouldn't expose lists in internal teleport directory.

Current behavior:
when browsing to `v1/web/app/` path of the teleport URL, directory listing is accessible. 

Bug details:
- Teleport version: 10.3.16
- Recreation steps: browse to ``v1/web/app/`
- Debug logs

<img width="354" alt="image" src="https://github.com/gravitational/teleport/assets/25728371/a09d884e-b614-47a0-840b-6541f53919e1">

**Comment by strideynet** [comment]
It's worth mentioning that the Proxy uses a Go embedded filesystem (e.g the webasset files are built into the Teleport binary and presented as if it were a filesystem) - this means that this doesn't actually expose files/folders on host's real filesystem.

**Comment by zmb3** [comment]
Thanks for filing this @jonatanzafar59. 

For now, this work is not planned. The directory listing is the default behavior of Go's file server, and as @strideynet mentioned this is not connected to the actual filesystem. Since these are all public assets we are not concerned about the directory listing being available.
