### ISSUE TITLE
Support scp -p using tsh. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#2889]
**What happened**:

This issue has been created by a customer, we currently don't support scp -p which preserve the time stamps of the source files.

`tsh  scp` doesn't support `-p` (preserver timestamps) 

Currently we get `error: unknown short flag '-p'`

**What you expected to happen**:

**Comment by webvictim** [comment]
`-v` (verbose) and `-q` (quiet) are two in common usage that we should probably have support for as well.

**Comment by sjackman** [comment]
Gentle bump on this issue.

I use `cp -a` in nearly all instances rather than `cp` (and `cp -p` if I want to deref a symlink) and `scp -p` instead of `scp`. It’s nice to have timestamps if you ever get into troubleshooting “where and when did this data come from?”

**Comment by sjackman** [comment]
Thank you, @a-palchikov! For others that find this issue, I've been using `rsync -a` as a workaround.

**Comment by murmrs** [comment]
I don't want to fill this closed issue - but @sjackman, I can't seem to get this to work. scp works for me, but rsync dies on a known good folder with the below error after validating host. I am on an M1, so that could be a contributing factor. But just as a heads up, in case others stumble across this.

`
ERROR REPORT:
Original Error: *ssh.ExitError Process exited with status 12
Stack Trace:
	/private/tmp/teleport-20210316-37307-g8ehpd/teleport-6.0.2/lib/client/session.go:487 github.com/gravitational/teleport/lib/client.(*NodeSession).runCommand.func2
	/private/tmp/teleport-20210316-37307-g8ehpd/teleport-6.0.2/lib/client/session.go:158 github.com/gravitational/teleport/lib/client.(*NodeSession).regularSession
	/private/tmp/teleport-20210316-37307-g8ehpd/teleport-6.0.2/lib/client/session.go:475 github.com/gravitational/teleport/lib/client.(*NodeSession).runCommand
	/private/tmp/teleport-20210316-37307-g8ehpd/teleport-6.0.2/lib/client/api.go:1695 github.com/gravitational/teleport/lib/client.(*TeleportClient).runCommand
	/private/tmp/teleport-20210316-37307-g8ehpd/teleport-6.0.2/lib/client/api.go:1178 github.com/gravitational/teleport/lib/client.(*TeleportClient).SSH
	/private/tmp/teleport-20210316-37307-g8ehpd/teleport-6.0.2/tool/tsh/tsh.go:1307 main.onSSH.func1
	/private/tmp/teleport-20210316-37307-g8ehpd/teleport-6.0.2/lib/client/api.go:400 github.com/gravitational/teleport/lib/client.RetryWithRelogin
	/private/tmp/teleport-20210316-37307-g8ehpd/teleport-6.0.2/tool/tsh/tsh.go:1306 main.onSSH
	/private/tmp/teleport-20210316-37307-g8ehpd/teleport-6.0.2/tool/tsh/tsh.go:470 main.Run
	/private/tmp/teleport-20210316-37307-g8ehpd/teleport-6.0.2/tool/tsh/tsh.go:231 main.main
	/opt/homebrew/Cellar/go/1.16.2/libexec/src/runtime/proc.go:225 runtime.main
	/opt/homebrew/Cellar/go/1.16.2/libexec/src/runtime/asm_arm64.s:1130 runtime.goexit
User Message: Process exited with status 12
rsync: connection unexpectedly closed (0 bytes received so far) [Receiver]
rsync error: error in rsync protocol data stream (code 12) at io.c(228) [Receiver=3.2.3]
`
