### ISSUE TITLE
CA Pinning isn't needed in IoT mode

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#2890]
As per customer feedback.

When running 

`teleport start --debug --roles=node --token={good_token} --ca-pin=sha256:1sdf234fdasd1 --auth-server=teleport-proxy.acme.com:3025`

Teleport will throw 
```
Node failed to establish connection to cluster: remote error: tls: internal error. service/connect.go:65
```

This is due to IoT mode not using / needing ca-pin. as the connection between node and proxy is secured using PKI and the CA pin is not needed. 

Note to document this use case, and possibly improve teleport error message.

**Comment by klizhentas** [comment]
Alternatively, we can double check the pin if provided by the user despite the fact that we fetched the CA @russjones what do you think

**Comment by benarent** [comment]
I tried this again today, with CA pinning result was. 

```
pi@raspberrypi:~ $ sudo teleport start --config=/etc/teleport.yaml
[AUTH]    Auth service is starting on 0.0.0.0:3025.
ERRO [PROC:1]    Proxy failed to establish connection to cluster: x509: certificate is valid for *.practice.io, practice.io, not 7069342d6f6666696365.teleport.cluster.local. service/connect.go:65
ERRO [PROC:1]    Node failed to establish connection to cluster: ssh: handshake failed: no matching keys found. service/connect.go:65
ERRO [PROC:1]    Proxy failed to establish connection to cluster: x509: certificate is valid for *.practice.io, practice.io, not 7069342d6f6666696365.teleport.cluster.local. service/connect.go:65
ERRO [PROC:1]    Node failed to establish connection to cluster: ssh: handshake failed: no matching keys found. service/connect.go:65
```

Since we recommend customers to add a server using `tctcl nodes add` provides internal information.

e.g. 
```
teleport-auth-4-usage ~: sudo tctl nodes add
The invite token: 33cac3
This token will expire in 30 minutes

Run this on the new node to join the cluster:

> teleport start \
   --roles=node \
   --token=asdf234 \
   --ca-pin=sha256:asdf234 \
   --auth-server=10.2.1.94:5070

Please note:

  - This invitation token will expire in 30 minutes
  - 10.2.1.94:5070 must be reachable from the new node
```

**Suggestion**
That we add another command to tctl, that will remove CA pinning and `tctl nodes add iot`

```
teleport-auth-4-usage ~: sudo tctl nodes add iot
The invite token: 33cac3
This token will expire in 30 minutes

Run this on the new node to join the cluster:

> teleport start \
   --roles=node \
   --token=asdf234 \
   --auth-server=teleport-proxy-url:5070

Please note:

  - This invitation token will expire in 30 minutes
  - teleport-proxy-url:5070 must be reachable from the new node
```

**Comment by webvictim** [comment]
With Teleport 4.3.0 I can write the auth server, join token and CA pin hash to `/etc/teleport.yaml`, then run `teleport start --config=/etc/teleport.yaml` and the nodes join in IoT mode without a problem. Either we've fixed the bug, or it only happens when you provide the token/CA pin on the command line.

@benarent I did notice that with your second report above, the error wasn't specifically a CA pin problem but an issue with the SAN on your certs. Also, you're using port 3025 rather than 3080 as I would expect for IoT mode?

I think we probably need to retest this.

**Comment by flixr** [comment]
Does this mean that the ca_pin is not checked in "IoT mode" when connecting to a proxy?
It seems like that...
IMHO the ca_pin should always be checked!

**Comment by webvictim** [comment]
That’s correct, the `ca_pin` is not validated in IoT mode. As far as I know, the reason is that Teleport validates that the proxy’s web API presents a valid TLS certificate with correct SNI/SAN and uses this to authenticate the cluster.

The `ca_pin`is only needed when joining directly to the auth server because it’s certificates are self-signed and cannot be validated externally.

**Comment by zmb3** [comment]
@nklaassen @ryanclark can we wrap this up with the changes introduced in config v3? Is it just a docs issue at this point?

**Comment by nklaassen** [comment]
Hmm, we should probably add a `teleport start --proxy_server` flag now for starting teleport in IoT mode without a config file. This flag should not accept a ca pin, and it should never fall back to an insecure join method. The current `--auth_server` flag should always be used with a CA pin even when given a proxy address, to avoid an insecure fallback

**Comment by zmb3** [comment]
Sounds good to me 👍

**Comment by ptgott** [comment]
I'm going to close this one, since the guidance for joining nodes via a join token added in https://github.com/gravitational/teleport/pull/23869 assumes that you are using IoT mode, and makes it clearer that you only need a CA Pin when joining Teleport processes to the Auth Service. If there's more to do on this, I think we should open a new, more narrowly scoped issue instead of reopening this one, which has started to creep a bit.
