### ISSUE TITLE
Add diag port option to helm chart

### ISSUE THREAD

**Issue by aardbol** [gravitational/teleport#29315]
What would you like Teleport to do?
Provide the possibility to expose /healthz via the k8s service in the helm chart.

What problem does this solve?
Allow external healthcheck monitoring

If a workaround exists, please include it.

**Comment by hugoShaka** [comment]
This would not work because:
- the external healthcheck would end up on a random pod. There would be no way to observe all pods.
- if a pod becomes unready, it is moved out of the loadbalancing pool and stops being exposed. This emans it would never show up as unready from an external monitoring tool.

This is a similar situation as in: https://github.com/gravitational/teleport/issues/17233
