### ISSUE TITLE
Document SSM configuration and usage

### ISSUE THREAD

**Issue by Nuru** [gravitational/teleport#2964]
According to the [documentation](https://github.com/gravitational/teleport/blob/6b1bc204518cba6eb82f65650918b90c8d7ad6af/docs/4.0/aws_oss_guide.md#aws-systems-manager-parameter-store) Teleport can store parameters in AWS SSM parameter store, but there is no documentation about how to enable or use this feature. 

The example IAM permissions give a clue, but it is not clear what, if any, flexibility there is with what to name the parameters or what key to encrypt them with.  Do parameters have to be stored under `/teleport/<cluster-name>/`? What parameters are stored there? 

The documentation also says the enterprise license can be stored in SSM, but does not give details. How/where do you store the license and tell Teleport to look for it there?

**Comment by ptgott** [comment]
The docs have changed substantially since this issue was opened. For EC2-based deployments, we recommend [using our reference Terraform modules](https://github.com/gravitational/teleport/blob/a0540c5afe6c8903c6be960202e02124ca32af7d/docs/pages/installation.mdx#L714-L724), and the docs on these include [more complete SSM instructions](https://github.com/gravitational/teleport/blob/master/docs/pages/admin-guides/deploy-a-cluster/deployments/aws-starter-cluster-terraform.mdx?plain=1#L223-L227).
