### ISSUE TITLE
tsh: better profile UX

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#2972]
## Description

When `tsh login/logout` executes right now, it overrides all parameters and rewrites the profile.
This is problematic, because it does not allow users to remember their preferences.

## Proposed design

`tsh login/logout` should preserve the changes made by user instead of overriding them.

In addition to that, users should be able to edit the existing ~/.tsh/profile and set the following:

* Default cluster
* Proxy name
* User name

**Comment by chino** [comment]
Remembering the namespace they were in or letting them customize it per cluster would be nice.

**Comment by travelton** [comment]
+1 Customer would like to set the remote host user, so they don't need to define it each time they ssh into a box. 

For example, if I am using the same username across all nodes, it would be nice to define this user in `~/.tsh/profile` and then... `tsh ssh <host>` rather than `tsh ssh <user>@<host>` or `tsh ssh --login <host>`.

**Comment by zmb3** [comment]
This is tracked over at #3089 - closing as duplicate.
