### ISSUE TITLE
Enforce keepalives for the terminal in the web ui 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3024]
**What happened**:
Websocket connections get terminated by some of the load balancers on idle timeout  

**What you expected to happen**:
The Web UI Terminal will match Teleport Keepalive settings. This means that proxy should keep sending keep-alive messages to the browser within an interval shorter than the idle period to prevent the network (load-balancer) from tearing down the web-socket connection.

[EDITED by @alex-kovoy ] i've updated the description to better describe the problem.

**Comment by benarent** [comment]
@alex-kovoy I know from past experiences that this can be tricky, due to Chrome being strange when a PWA is inactive in another tab. Would you be able to research this as part of terminal updates in 4.2

**Comment by alex-kovoy** [comment]
I discussed it with @russjones some time ago, we need to periodically send keep-alive messages to the client via websocket connection (ping-pong).

**Comment by benarent** [comment]
We reviewed this ticket, and we need to update this on the server side. Removing `ui` label.

**Comment by jon-can** [comment]
This can be reproduced by using Cloudflare's DNS with "proxied" enabled. After about two minutes the web UI's SSH session is terminated. Teleport proxy will need to listen on one of the supported Cloudflare proxy ports rather than 3080: https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with-

For my testing I had my Teleport Proxy listen on port 443. Also ensure that the Teleport Proxy is using signed SSL certificates.

How to use "proxied" with Cloudflare DNS records: https://support.cloudflare.com/hc/en-us/articles/360019093151-Managing-DNS-records-in-Cloudflare

`Jul 16 01:23:16 ip-172-31-9-23 teleport[15158]: INFO             [WEB] removed 1 expired sessions web/sessions.go:393
Jul 16 01:23:16 ip-172-31-9-23 teleport[15158]: INFO             [WEB] closing context joe2b963f0e779c72419cb458ba58e33edfb web/sessions.go:362
Jul 16 01:23:41 ip-172-31-9-23 teleport[15158]: DEBU [WEBSOCKET] Sent close event to web client. web/terminal.go:341
Jul 16 01:23:41 ip-172-31-9-23 teleport[15158]: DEBU [WEBSOCKET] Closing websocket stream for bf70cdfd-c702-11ea-ad14-0a824c4c9c8c. web/terminal.go:241
Jul 16 01:23:41 ip-172-31-9-23 teleport[15158]: DEBU [NODE]      Subsystem proxySubsys(cluster=default/gravitational-demo.com, host=34.220.236.211, port=0) finished with result: read tcp 172.31.9.23:45266->34.220.236.211:3022: use of closed network connection. regular/sshserver.go:1249
Jul 16 01:23:41 ip-172-31-9-23 teleport[15158]: DEBU [PROXY]     Client 127.0.0.1:41734 disconnected. id:2 local:127.0.0.1:3023 login:root remote:127.0.0.1:41734 teleportUser:joe2 regular/sshserver.go:1091
Jul 16 01:23:41 ip-172-31-9-23 teleport[15158]: DEBU [SSH:PROXY] Closed connection 127.0.0.1:41734. sshutils/server.go:432
Jul 16 01:23:41 ip-172-31-9-23 teleport[15158]: DEBU [USAGE]     Ignoring event "session.data". pro/auditlog.go:80`

**Comment by alex-kovoy** [comment]
@jon-can we have a branch with the fix https://github.com/gravitational/teleport/tree/lisa/keep-alive-websocket 
if this is not a trouble could you try it out on your environment to confirm the fix? :-)

@russjones @kimlisa some additional discussion about CloudFlare websocket timeouts https://community.cloudflare.com/t/cloudflare-websocket-timeout/5865/2

**Comment by russjones** [comment]
Best: 1
Worst: 3

**Comment by kimlisa** [comment]
@jon-can tested the branch for us and it worked for him with `keep_alive_interval` set to `5s`, thank you!

First round, he got this warning in the log, within 5 minutes of starting teleport, but everything else ran fine:
```
Jul 21 21:34:53 ip-172-31-9-23 teleport[11024]: WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *trace.BadParameterError failed to detect protocol by prefix: [71 104 48]\nStack Trace:\n\t/home/lisa/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:348 github.com/gravitational/teleport/lib/multiplexer.detectProto\n\t/home/lisa/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:263 github.com/gravitational/teleport/lib/multiplexer.detect\n\t/home/lisa/go/src/github.com/gravitational/teleport/lib/multiplexer/multiplexer.go:197 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\t/usr/local/go/src/runtime/asm_amd64.s:1374 runtime.goexit\nUser Message: failed to detect protocol by prefix: [71 104 48]\n" multiplexer/multiplexer.go:200
```
Second round, he ran teleport for 30 minutes, and warning wasn't reproduced.
