### ISSUE TITLE
Systemctl is unable to start teleport service with teleport config file if .yml extension is used 

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#30306]
What would you like Teleport to do?
Allow teleport service to start with a valid teleport.yml or teleport.yaml file. Alternatively, provide user with a more accurate error that the file cannot be found and or filename check. 

What problem does this solve?
The problem is that we have tenants who are using teleport for the first time, and the default start from systemd expects /etc/teleport.yaml, when users can accidentally set the extension as .yml. So it would be helpful if Teleport checked for both extensions as default. 

If a workaround exists, please include it.
Correct file name extension to yaml.

**Comment by webvictim** [comment]
The root of this issue actually seems to be that the `ExecStart` command in our default `systemd` unit doesn't specify a path to the config file and relies on the default behaviour of reading `/etc/teleport.yaml`.

https://github.com/gravitational/teleport/blob/4583f0c7bd51d66d40fb266c663c59af4d563271/examples/systemd/teleport.service#L9

If a user were to put their config file in the wrong place, it just wouldn't be read at all and Teleport would start with a stock config.

I think the best resolution to this issue is to make the default `systemd` unit files specify `-c /etc/teleport.yaml` instead, which will ultimately result in an error being displayed to the user:

```
root@07bfd175b361:/# /usr/local/bin/teleport start -c /etc/teleport.yaml --pid-file=/run/teleport.pid
usage: teleport start [<flags>]

Starts the Teleport service.
...
<lots of extra output trimmed>
...
ERROR: path '/etc/teleport.yaml' does not exist
```
