### ISSUE TITLE
Add more information to SAML errors

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#3049]
## Description

In the [debugging commit](https://github.com/gravitational/teleport/commit/5280f21810a5918ce6267030f026b99d939b18cf) I had to add additional information to our external dependency to help troubleshoot the case.

Let's create a pull request to this library to add `Warning.Message` structure field that contains additional information. In our [code](https://github.com/gravitational/teleport/blob/sasha/tc/lib/auth/saml.go#L320) let us reference this message when available to add additional information to both log and the error message.

In our dependencies, we can temporary use the fork, using the `override directive` similar to [this](https://github.com/gravitational/teleport/blob/sasha/tc/Gopkg.toml#L160).

Once Russel accepts the PR, switch back to the original version.

**Comment by aelkugia** [comment]
For the `Warning.Message` struct field you mention is that to the struct defined `SAMLAuthResponse`? And what additional info were you thinking? (`InvalidTime`, `NotInAudience` failing to retrieve `AssertionInfo`)

Also in the saml2 import, there is an existing struct `ErrSaml`. Would I be able to instead access that in our [code](https://github.com/gravitational/teleport/blob/sasha/tc/lib/auth/saml.go#L320) instead of needing to end up creating the fork and using the override directive in the dependency. Not exactly, but something along these lines

```
message.ErrSaml{Message: "Invalid time 0: Received assertion, now %v is before time %v.", now, notBefore")
```

Is a separate PR being submitted to Russell's [repo](https://github.com/russellhaering/gosaml2/blob/master/saml.go)?
