### ISSUE TITLE
Installation page does not mention how to get older versions

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#31055]
## Applies To

https://goteleport.com/docs/installation/

## Details

The installation page is focused on the current version. Many enterprise users are using the last or 2 major versions ago. 

Provide information on:
- how to download Enterprise version from enterprise license tenants
- how to get older versions of Teleport

## How will we know this is resolved?

A user can find when to download a specific enterprise version.

**Comment by ptgott** [comment]
@stevenGravy Are self-hosted Enteprise users aware of the version switcher for the docs? If a user is interested in installing an older Teleport version, I think it would make sense to keep them on that version's docs site.

**Comment by ptgott** [comment]
I am closing this since the intended flow is for users to select their major version from the dropdown menu at the top of the docs site. A user can already find a specific Enterprise version by navigating to the correct version of the docs, navigating to the Installation page, and choosing the Enterprise instructions for the appropriate platform.
