### ISSUE TITLE
tctl --format=json returns invalid json

### ISSUE THREAD

**Issue by rifler** [gravitational/teleport#31933]
Expected behavior:
Command returns valid json
```bash
tctl tokens ls --format=json
[
]
```

Current behavior:
Error message is added to the end of string
```bash
tctl tokens ls --format=json

[
]A security patch is available for Teleport. Please upgrade your Cluster to v13.3.5 or newer.
```

Bug details:
- Teleport version
- Recreation steps
- Debug logs

**Comment by strideynet** [comment]
It's my understanding that we output this alert to `stderr` and that the actual JSON is written to `stdout`.

Can you try `tctl tokens ls --format=json 2> /dev/null` - this will redirect stderr rather than displaying it.

For bash scripting, you typically want to make use of this redirection. This blog post has some good info on redirecting in bash: https://catonmat.net/bash-one-liners-explained-part-three

**Comment by rifler** [comment]
Thanks, now I'm trying to exec this command via kubectl exec:

```bash
k exec -ti deployment/teleport-base-auth -n teleport -- "tctl tokens add --type=db --format=json 2> /dev/null"
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "0c7c7cce261d16c36e9ae702b91650bec77359f3b49370a21c9b7fbbb54c3007": OCI runtime exec failed: exec failed: unable to start container process: exec: "tctl tokens add --type=db --format=json 2> /dev/null": stat tctl tokens add --type=db --format=json 2> /dev/null: no such file or directory: unknown
```

**Comment by rifler** [comment]
Find out the solution:
```
k exec -i deployment/teleport-base-auth -n teleport -- tctl tokens add --type=db --format=json 2> /dev/null
```
