### ISSUE TITLE
Ability to kill sessions

### ISSUE THREAD

**Issue by jaxxstorm** [gravitational/teleport#320]
I seem to have some zombie sessions in the web UI:

![image](https://cloud.githubusercontent.com/assets/1622940/14210237/0149e980-f820-11e5-91c0-dc9ad76ab956.png)

It would be nice if I could click a button and terminate the session remotely.

**Comment by kontsevoy** [comment]
@jaxxstorm interesting... care to elaborate a bit more about this use case?

**Comment by jaxxstorm** [comment]
One of the uses cases I see for teleport is the ability for developers to "break glass" into infrastructure. With this ability, I can see who's logged in to which nodes with teleport and then kill sessions as required as an administrator.

**Comment by kontsevoy** [comment]
@jaxxstorm Teleport currently does not have ACLs or roles outside of host logins. Privileged operations currently can only be executed via `tctl` tool. It's unlikely we'll get to this any time soon in the OSS version. I'll mark as "wontfix" for now, because it should be implemented as part of a broader initiative.
