### ISSUE TITLE
teleport cache & tctl requests approve issue 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3213]
While testing https://github.com/gravitational/teleport-plugins @marshall-lee has ran into issues approving workflow requests using `tctl requests approve`. 

It was only possible to get this working by turning off the Teleport Cache, which isn't currently documented. 

```
teleport:
  cache:
    enabled: false
```

Teleport:  v4.2.0-rc.3
OS:           Running on MacOS

**Comment by klizhentas** [comment]
might be that cache logic should account for expiration events @fspmarshall ?

I now vaguely remember something here: https://github.com/gravitational/teleport/blob/master/lib/cache/collections.go

**Comment by fspmarshall** [comment]
> might be that cache logic should account for expiration events

No events were being emitted at all; cache is missing support for access requests.  I made some bad assumptions about cache behavior, and thought I could omit support for MVP.

In terms of why this wasn't caught earlier, it appears that teleport uses different default configuration values based on whether or not a config file exists.  If a config file exists, but does not specify cache policy, cache is on by default.  If no config file exists, cache is off.  This appears to be due to the fact that many of the default configuration values are defined in the `config.FileConfig` type, but the type's defaults are [never propagated](https://github.com/gravitational/teleport/blob/f240b7109d8026c6fdb4acf99c7d334d306c9578/lib/config/configuration.go#L158-L161) if no concrete file exists.
