### ISSUE TITLE
"Configure Teleport to Create Host Users" guide has multiple problems for a Terraform user

### ISSUE THREAD

**Issue by gdubicki** [gravitational/teleport#33288]
## Applies To

https://goteleport.com/docs/server-access/guides/host-user-creation/

## Details

I was using Terraform for this setup and I had multiple issues:

1. The values for `create_host_user_mode` in `options` were numerical, not text and I had to find API docs [here](https://pkg.go.dev/github.com/gravitational/teleport/api/types#CreateHostUserMode) to learn that "keep" is 3.
2. Apart from setting `create_host_user_mode` I had to set `create_host_user = true`.
3. Initially I have placed `options` inside `allow` and Terraform did not show any error that would point to this mistake...
4. The error message from `tsh ssh` and in the agent logs were not very helpful, as it was mentioned in [this comment](https://github.com/gravitational/teleport/discussions/21269#discussioncomment-4876485) already.

Ultimately the code that worked for me looks like this:

```hcl
resource "teleport_role" "my-role" {
  metadata = {
    name        = "my-role"
    description = "My Role"
  }

  spec = {
    options = {
      max_session_ttl = "12h"

      # For auto-creating users to work ALL THE ROLES THAT THE USER HAS NEED TO HAVE THESE PERMISSIONS
      # so effectively, the USER SHOULD HAVE ONLY ONE ROLE or at least not have the predefined roles
      create_host_user = true
      create_host_user_mode = 3 # = keep (see https://pkg.go.dev/github.com/gravitational/teleport/api/types#CreateHostUserMode)
    }

    allow = {
      logins = ["{{internal.logins}}"]

      host_groups = ["staff"]

      host_sudoers = [
        "ALL=(ALL) NOPASSWD: ALL",
      ]

      node_labels = {
        "*" = ["*"]
      }

      rules = [
        # note: maybe some more rules are needed! I have a copy of all of the built-in roles Editor and Auditor here.
        {
          resources = ["instance"]
          verbs     = ["list", "read"]
        },
        {
          resources = ["node"]
          verbs     = ["list", "create", "read", "update", "delete"]
        },
      ]
    }
  }
}
```

## How will we know this is resolved?

Improve the documentation and error messages.

## Related Issues

Not an issue, but a discussion: https://github.com/gravitational/teleport/discussions/21269

**Comment by gardar** [comment]
>       # For auto-creating users to work ALL THE ROLES THAT THE USER HAS NEED TO HAVE THESE PERMISSIONS
>       # so effectively, the USER SHOULD HAVE ONLY ONE ROLE or at least not have the predefined roles
>       create_host_user = true
>       create_host_user_mode = 3 # = keep (see https://pkg.go.dev/github.com/gravitational/teleport/api/types#CreateHostUserMode)
>     }
> 

Ran into this issue myself and figured out that the `off` or `1` value for `create_host_user_mode` seems to have precedence over any of the other values so if any of your roles are set to `off`/`1` then user creation is essentially turned off.

And `off`/`1` seems to be the default value so if you don't define `create_host_user_mode` to something else than `off`/`1` in your role then you have a role which turns off user creation.

**Comment by peteroneilljr** [comment]
thanks this bug write up was helpful! 

Another thing i've noticed when creating through Terraform is `create_host_user_default_shell` doesn't get applied. I can go in and manually add it through the web ui though.

**Comment by eriktate** [comment]
@gdubicki Thanks for the detailed report! We've recently pushed a few changes that I think address most of the problems outlined here.

>1. The values for create_host_user_mode in options were numerical, not text and I had to find API docs [here](https://pkg.go.dev/github.com/gravitational/teleport/api/types#CreateHostUserMode) to learn that "keep" is 3.

We now mention the terraform provider reference (and the fact that values can be different) in the `Next Steps` section of the host user creation guide which will hopefully make this easier to discover in the future.

>2. Apart from setting create_host_user_mode I had to set create_host_user = true.

`create_host_user` should be optional and `create_host_user_mode` is the preferred field for configuring host user creation. If you have at least one role that doesn't specify `create_host_user_mode` or `create_host_user` then host user creation won't be allowed. Setting `create_host_user = true` alone is effectively the same as setting `create_host_user_mode = 3` which is why the more explicit field should be used.

>3. Initially I have placed options inside allow and Terraform did not show any error that would point to this mistake...

This is actually a known issue that exists within Teleport itself #10885

>4. The error message from tsh ssh and in the agent logs were not very helpful, as it was mentioned in https://github.com/gravitational/teleport/discussions/21269#discussioncomment-4876485 already.

We now emit a new agent log line when a role prevents host user creation and the role that caused the failure should be listed by name.

>Another thing i've noticed when creating through Terraform is create_host_user_default_shell doesn't get applied. I can go in and manually add it through the web ui though.

@peteroneilljr This was also reported [here](https://github.com/gravitational/teleport/issues/47283) and was fixed last week!


I'm marking this is closed for now, but please feel free to leave a comment or open a new issue if you find any of these problems persist
