### ISSUE TITLE
teleport-connect on linux not able to show more than the front page of servers.

### ISSUE THREAD

**Issue by pnunn** [gravitational/teleport#33736]
Expected behavior:
I can page through to see 16-77 on my server list.

Current behavior:
Pressing the -> button does nothing. Can only see the first page.

Bug details:
- Teleport connect version - latest linux version, I can't work out how to find it in the app.
- Recreation steps
Run teleport-connect, try to navigate to the next page. Nothing happens.

OS, KDE Neon, under Wayland (have not tested under X11).

**Comment by ravicious** [comment]
Hey, thanks for the report. I cannot reproduce it on 14.1.0:

<details>
<summary>Repro</summary>

https://github.com/gravitational/teleport/assets/27113/a383b781-f13d-46f7-9759-c058fd168d2e
</details>

You can check the app version while running the app by pressing Alt, then Help -> About.

Could you [include logs](https://goteleport.com/docs/connect-your-client/teleport-connect/#submitting-an-issue) from an attempt at navigating to the next page?

**Comment by pnunn** [comment]
Hi there.

The app is 14.1.0.   It seems to work fine under X11 but on Wayland the buttons do nothing.  I'm not sure where I find the logs on KDE.

**Comment by ravicious** [comment]
Ah, it's this kind of an issue. It works for me on both X11 and Wayland, but I'm using a VM on a MacBook Pro. This is probably related to specific hardware and Wayland. We've just recently closed [another issue related to Electron not working with Wayland properly](https://github.com/gravitational/teleport/issues/32832), which I was also not able to reproduce in a VM.

To open the folder with logs, press Alt and then Help -> Open Logs Directory. I'd say it's best to move the existing logs to a separate directory, then restart the app, reproduce the issue and package the logs.

But I'm afraid that those logs alone won't help us much here as they're mostly related to Teleport components, while I believe that the issue here is with Electron.

When reproducing the issue to capture the logs, could you start Teleport Connect with the command below and capture two additional things?

* Standard output from running the command.
* Logs from the Developer Tools console.
   * When Connect is started with the `--connect-debug` flag, you can access the console by pressing Alt and then View -> Toggle Developer Tools, then right click on the console area and choose "Save as…".

```
ELECTRON_ENABLE_STACK_DUMPING=1 teleport-connect --connect-debug
```

[`ELECTRON_ENABLE_STACK_DUMPING`](https://www.electronjs.org/docs/latest/api/environment-variables#electron_enable_stack_dumping) prints stack traces to standard output when Electron components crash – this should tell us more if there are any crashes happening like in the previous issue we saw with Electron and Wayland. `--connect-debug` enables access to developer tools.

**Comment by ravicious** [comment]
Teleport Connect 14.3.0+ ships with an updated version of Electron. Could you check if that version still has this problem?

**Comment by pnunn** [comment]
Hi.

I can confirm that connect now works well with both X11 and Wayland.

Nice. Pitty I can't say the same for Libreoffice :(
