### ISSUE TITLE
New UI misbehaves with invalid `search_as_roles` configuration

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#35673]
### Expected behavior:
The new UI should display the same type of error message as the old UI when an invalid `search_as_roles` value in the current user's roles.

### Current behavior:

With a `search_as_roles` configuration set to `*`, the new interface seems to display what looks like the old UI. The issue was observed by several users, and browser cache problems were ruled out.

```
    request:
      search_as_roles:
      - '*'
```

### Bug details:
- **Teleport version**: 14.2.2
- **Recreation steps**:
   1. Set the `search_as_roles` configuration to an invalid entry (e.g., `- '*'`).
   2. Navigate from access requests to resources within the Teleport interface.
   3. Observe that the UI looks more like the old UI.
- **Debug logs**: See screenshots

After visiting the "New Request" page in the new UI:

![new UI request](https://github.com/gravitational/teleport/assets/37278/b7423b15-815d-48cb-aa54-b546af2482cf)

Then returning to the "Resources" view with an affected role in place.

![reverted](https://github.com/gravitational/teleport/assets/37278/46ffe2c1-8162-4016-b89f-17bce95c9ffc)

Here's what the error looks like in Teleport 13.x. A similar error should be displayed in the new UI:

![The expected error](https://github.com/gravitational/teleport/assets/37278/fdddefaa-896f-4cb0-aee4-3f5830daf894)

**Comment by avatus** [comment]
This seems to be because when we fetch unified resources (on the dashboard or access requests), we switch back to the "old view" if that endpoint returns a 404 to support leaf clusters that may not be updated yet. However, the "role not found" error also returns a 404 status so it's getting caught up in that. I'll see if I can find a workaround that still supports legacy clusters but doesn't return false positives (negatives?)
