### ISSUE TITLE
Monitor Node Usage: add teleport_node_hour_total to /metrics

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#3603]
### Feature Request
We want to be able to monitor node usage so we can anticipate potential cost at renewal.

### Motivation
We want to be able to track how much we should or shouldn't be paying.

### Who's it for?
Enterprise

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1190134506177097/1190158537521289) by [Unito](https://www.unito.io/learn-more)

**Comment by benarent** [comment]
I looked into this. I think the first best option is to out another metric to our /metrics endpoint http://127.0.0.1:3000/metrics . 

Since we should output a node count similar to our internal billing. Teleport currently records usage to 5 min intervals. We could output this as a `teleport_node_hour_total` but I'll need to look into prometheus best practices first. https://prometheus.io/docs/practices/naming/#metric-names
