### ISSUE TITLE
"Connect my Computer" links to a 404 on Mac

### ISSUE THREAD

**Issue by djohns7** [gravitational/teleport#36326]
Expected behavior:
Teleport will link to, and download, the appropriate package for a Mac to be joined over SSH to Teleport.

Current behavior:
![image](https://github.com/gravitational/teleport/assets/117299936/a1b29119-ae1e-40f6-b4a9-43bf068360d9)

Bug details:
- Teleport version
Cloud 14.2.4
- Recreation steps
Use "Connect My Computer" on a Mac

**Comment by gzdunek** [comment]
Thanks for reporting this.

The issue happened because 14.2.4 was a private release, which didn't contain a OSS `teleport` binary. 
Connect checks its app version and attempts to download a corresponding `teleport`  version, but in this case it was unavailable.

As a workaround, please use Teleport Connect 14.3.0, which was a public release.

**Comment by zmb3** [comment]
Given that this is a rare corner case, I'm going to close as not planned for now. We can re-evaluate if it becomes a bigger problem in the future.
