### ISSUE TITLE
Provide tctl binary for Windows

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#36457]
### What would you like Teleport to do?

Provide a `tctl.exe` binary which runs on Windows hosts.

### What problem does this solve?

Windows users currently need access to either a macOS or Linux system to be able to run `tctl`, which is a fundamental requirement for being able to configure user traits or other Teleport features which are not exposed via the web UI.

### If a workaround exists, please include it.

- WSL (not always available in corporate environments, extra dependencies and download requirements, requires some knowledge of Linux)
- Use a secondary macOS/Linux box (cumbersome, not easily handled, requires macOS/Linux knowledge)

**Comment by zmb3** [comment]
For some context: tctl does build for Windows, we just don't ship an artifact because tctl still has OSS and Enterprise variants, and we don't have any enterprise Windows artifacts in our CD pipelines yet (the only Windows artifacts we ship are tsh and Teleport Connect, and there's only a single build type for those).

The plan is to get to a point where there's only one build of tctl used for both OSS and Enterprise clusters (the enterprise features only work when talking to an enterprise cluster). 

We're very close (there's only 1 or 2 commands left).
