### ISSUE TITLE
Allow TSH users to send a pre-approval ID. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#3679]
### Feature Request
The addition of request note along with request notes, that can be matched to 

```
$ tsh login teleport-cluster --request-roles=customer-x-cluster 
# Normal login flow
# Post login modal that shows note UI 
```

### Motivation
Some Teleport customers use an external ticketing system to get access to systems. In this case they have to file a ticket to obtain access to a system. e.g. an MSP needed to access a customers system. Once approved they'll have a ticket ID, this will be sent to the external plugin and will allow for a near automatic approval for system access. 

We could combine this with https://github.com/gravitational/teleport/issues/3677 

### Who's it for?
Enterprise

**Comment by stevenGravy** [comment]
this also would be a good thing to have for online and other tsh sessions.  Currently once you request a role you lose it when you logout of a session.  Having the ability to apply a approved role in the online and cli experience you have been approved for would help since if your machine froze you don't need to go through the whole process again. That's also better that you would only have the approval for the approved time, not more if you had to reset.

**Comment by benarent** [comment]
Fresh off the press. This features has been added to Teleport 4.4.4.

I've started docs here, and the current flow will only work with tctl and the API. Plugins haven't been upgraded.

Review these docs and let me know if have any comments / feedback during setup. https://github.com/gravitational/teleport/pull/4732/files
