### ISSUE TITLE
Ignore default or empty value when import resources with import block

### ISSUE THREAD

**Issue by Bogyie** [gravitational/teleport#36790]
**What would you like Teleport to do?**
Ignore default or empty value(e.g. null, {}, [], "", ...} when import resources with import block.

**What problem does this solve?**
To make terraform code prettier that is generated from terraform cli.
```sh
terraform plan -generate-config-out=generated.tf
```

**If a workaround exists, please include it.**

**Comment by zmb3** [comment]
I'm not sure I understand the ask - can you elaborate?

**Comment by hugoShaka** [comment]
The defaults are not handled by Terraform itself but by Teleport. When sending a reosurce with unset or empty fields, Teleport will hydrate it based on the resource version. AT this point, the resource has all fields set, this is what Terraform recovers during the import.

Terraform should not try to remove fields if they look like default values because defaults depends on many parameters including the resource version. This will lead to unpredictible behaviours.

It is the user's responsibility to cleanup the imported resources as TF has no way of knowing what part of the resource default and what is user-specified.
