### ISSUE TITLE
Desktop session clipboard and directory sharing icon state is unclear

### ISSUE THREAD

**Issue by ibeckermayer** [gravitational/teleport#36825]
I'm unable to visually determine whether clipboard sharing / directory sharing is active during a desktop session by looking at the icons. They're supposed to be "grayed out" (or otherwise disabled-looking) when inactive, and more bold when active. However here is what inactive looks like:

both directory and clipboard sharing disabled by rbac (and inactive):

<img width="77" alt="image" src="https://github.com/gravitational/teleport/assets/13578537/ee0d0315-8ad7-4370-9176-b6338bf6cba8">

clipboard enabled by rbac, but disabled by browser permissions

<img width="87" alt="image" src="https://github.com/gravitational/teleport/assets/13578537/09fe6d83-06e8-4320-8d81-67728e58ab47">

both enabled:

<img width="81" alt="image" src="https://github.com/gravitational/teleport/assets/13578537/07d7c61e-d573-42aa-b7a6-b777cace8736">

**Comment by zmb3** [comment]
Maybe we could use the same accent color that the new toggle components use to indicate an active state.

WDYT, @roraback?

**Comment by roraback** [comment]
I’m thinking that we should do the following:
* If disabled, we should use the disabled color, rather than the “slightly muted” color (what they currently are using)
* If enabled, either make them green OR make them more opaque black with a green dot overlaid in the UR corner
* Add a tooltip on hover, rather than relying on a title attribute—title attributes are less reliable and can require hovering for an extended amount of time before the title appears

An additional note: it looks like the alerts button next to these icons is has a hard-coded white. I'm seeing a white icon and white text regardless of whether I'm in light or dark mode:
<img width="205" alt="image" src="https://github.com/gravitational/teleport/assets/1095531/afd64781-1347-4b3b-bf8b-56c43a02f402"> 
<img width="237" alt="image" src="https://github.com/gravitational/teleport/assets/1095531/e25a4f58-b4ff-408e-a550-9d80016f28c3">

**Comment by roraback** [comment]
Since the icons aren't interactive even when they're active, the data version of our green color is probably most appropriate (but FWIW it is identical to the "interactive/success/default" color in our design system).

**Comment by ibeckermayer** [comment]
@roraback iirc we used to have it green but moved away from that because it was a bit jarring. I'm not too partial on that, but this was the simplest change and works fine to my eye. WDYT?

Disabled:
<img width="143" alt="image" src="https://github.com/gravitational/teleport/assets/13578537/a0d1909f-ce9f-413d-980a-db94a31511de">
<img width="146" alt="image" src="https://github.com/gravitational/teleport/assets/13578537/2c98a850-9b9d-4743-a1e0-93f02144f858">

Enabled:
<img width="147" alt="image" src="https://github.com/gravitational/teleport/assets/13578537/4bf93bdd-bb64-410c-9275-cace36eac1d1">
<img width="143" alt="image" src="https://github.com/gravitational/teleport/assets/13578537/90db1b15-2241-491c-b618-da51dd6a1de6">

**Comment by zmb3** [comment]
@ibeckermayer let's stick to Kenny's suggestions please. 🙏
