### ISSUE TITLE
Guide to moving from OSS to Enterprise

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#3683]
## Summary
Many customers have an existing install of teleport, recent or older.  Currently Teleport does not provide a guide and recommendations on converting from an existing OSS version installation to an enterprise version.  

  The guide should include:

- Recommendations to backing up your current configuration (dir or HA based)
- Process to update executables including for HA configurations
- How to convert existing user database and Github SSO configurations into a RBAC configuration

### Audience
Customers moving to pro, enterprise from OSS.

### Location
New entry in the enterprise section

**Comment by benarent** [comment]
Thanks for creating this @stevenGravy we are are the start of a docs project. I'm going to create a new milestone and schedule this. 

I think as a rule, I would recommend setting up another cluster vs upgrading the old cluster, but I know that's not always convenient. In that case we might want to look at adding a command to `tctl` to help upgrade the database.

**Comment by stevenGravy** [comment]
thanks @benarent .  Yes, that's a important topic.  I"m sure other items will come to mind but keeping the same cluster name is a good highlight if folks are keeping to the same hosts for the new or same cluster.

**Comment by ptgott** [comment]
@stevenGravy @benarent I am considering adding a docs guide for this. Since the last activity on this issue was almost two years ago, I just wanted to check to see if you have anything to add before I schedule any work. Thanks!

**Comment by stevenGravy** [comment]
@ptgott besides the enterprise features like SSO probably just that admin should make sure to use the enterprise `tctl`

**Comment by benarent** [comment]
It would be nice to have a step by step guide for how to migrate from Teleport Community Edition -> Teleport Cloud / Teleport Enterprise. Someone should try this, there are a few gotchas for a smooth setup.

**Comment by ptgott** [comment]
Hi @gregnetau, thanks for reaching out. The current recommendation for moving from Teleport Community Edition to Teleport Enterprise is to contact the Teleport Sales team, and the Teleport team can work with you to figure out the best solution for your infrastructure: https://goteleport.com/contact-us/

**Comment by ptgott** [comment]
@stevenGravy In our Teleport Enterprise (Cloud) [migration guide](https://github.com/gravitational/teleport/blob/d6a87dbc86958384a987b6ababdb9543d6b91878/docs/pages/admin-guides/deploy-a-cluster/migrate-to-cloud.mdx), the procedure for migrating from Self-Hosted Enterprise to Cloud is:

1. Set up a separate cloud-hosted Teleport account.
1. Retrieve dynamic Teleport resources from the Auth Service backend on the
   self-hosted cluster and apply them against the Auth Service backend on the
   cloud-hosted cluster.
1. Reconfigure Teleport agents and plugins to connect to the cloud-hosted
   Teleport cluster.
1. Verify that the migration has succeeded.

This seems to apply to OSS -> Enterprise as well, assuming that instead of setting up a cloud-hosted Enterprise account, the user deploys a self-hosted Enterprise cluster.

Would it make sense to repurpose this guide to apply to the OSS -> Enterprise migration as well?

Also CC @oshati

**Comment by stevenGravy** [comment]
@ptgott that makes sense
