### ISSUE TITLE
TELEPORT_ROLES not available on PAM modules on Ubuntu.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3692]
The `TELEPORT_ROLES` environment variable is not available on PAM modules on Ubuntu. This prevents correct group assignment.

**Comment by awly** [comment]
Recording some notes:
- after lots of struggle reproduced the problem on Ubuntu
  - `pam_script.so` gets all the usual shell env vars and adds a few extras
  - but nothing that we set in `teleport` before calling `libpam` is propagated
  - I couldn't find any suspect changes in `pam_script.so` code, so suspecting `libpam` itself
- I was able to plumb our env vars to `pam_exec.so`
  - using http://www.linux-pam.org/Linux-PAM-html/adg-interface-by-app-expected.html#adg-pam_putenv
  - since this was the main reason for using `pam_script.so` instead of `pam_exec.so`, we could update our instructions, since `pam_exec.so` can execute shell scripts just fine

I'll keep digging on possible `libpam` changes causing this, but also push my changes making `pam_exec` work.

**Comment by awly** [comment]
Oops, I take that back. `pam_script.so` on Ubuntu 20.04 does work fine.
I had been using a binary where I temporarily removed `os.Setenv` calls.

@russjones  do we know which version of Ubuntu / pam / pam-script.so was causing this issue?

**Comment by awly** [comment]
Note to self: backport #3725 to 4.2

**Comment by awly** [comment]
One last touch is to update the docs.
We no longer need to recommend `pam_script.so`.

**Comment by benarent** [comment]
> I was able to plumb our env vars to `pam_exec.so`
> * using http://www.linux-pam.org/Linux-PAM-html/adg-interface-by-app-expected.html#adg-pam_putenv

@awly Do you remember what magic you did to make this work with 20.04. Would i need to update 'pam_exec' or my 'teleport_acct` to get these variables?

**Comment by awly** [comment]
@benarent if you have Ubuntu 20.04, these env vars should be available without extra steps.
what are you trying to do that's missing the env vars?

**Comment by benarent** [comment]
I was able to get this working with the help of @Valien . It seems the comment stops it from working. Going to debug more and update the docs. 

My teleport_acct file (/etc/pam-exec.d):
```
#!/bin/bash
id -u "${TELEPORT_LOGIN}" &>/dev/null || /usr/sbin/useradd -m "${TELEPORT_LOGIN}" -s /bin/bash 2> /tmp/pam.error
exit 0
````

My teleport file in `/etc/pam.d`:
```
account	required	pam_exec.so	/etc/pam-exec.d/teleport_acct
session	required	pam_motd.so
session	required	pam_exec.so	/bin/bash
session	required	pam_permit.so
```

**Comment by sagardeo2105** [comment]
@benarent did this create the home directory for the user you added?
