### ISSUE TITLE
`app.session.start` events do not appear in DynamoDB backend

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#37049]
### Expected behavior:

When an app session starts, the `app.session.start` should appear in the DynamoDB event backend when configured.

### Current behavior:

The `app.session.start` event does not appear in the DynamoDB events table, but does appear in the `file://` and `stdout://` if they are also configured. It always appears in the `INFO` level log line that is emitted by `events/emitter.go:271`.

While testing on one environment, we did observe one attempt to launch an app session result in the event being populated in DynamoDB. It was a bit strange because it appeared twice, but one second apart. I was not able to reproduce this success condition in my lab.

### Bug details:
- Teleport version: observed on 14.3.0, 14.2.0, 14.1.1
- Recreation steps:
  - set up `audit_events_uri` to have a `dynamodb://` destination. (you can have other destinations appear after)
  - launch an app session in the web UI
  - observe `2024-01-22T20:30:40Z INFO [AUDIT]     app.session.start addr.remote:10.0.0.4:32554 app_name:myapp...` appear in the proxy and auth logs (expected)
  - observe the event appear in stdout, file, or any other backend configured
  - Look in Teleport audit event viewer, and/or search DynamoDB table for `EventType=app.session.start`.
  - No `app.session.start` will be present. Only `app.session.chunk` will appear for the given session. The associated `cert.create` event also appears, which has most of the same information.
- Debug logs - N/A

**Comment by zmb3** [comment]
The problem is that the `app.session.start` and `app.session.chunk` events all have the same session ID (as expected) and the same event index (not expected). Data in Dynamo is keyed on (session ID, index), and so subsequent events overwrite prior events.

Session preparer has logic for ensuring that the index gets incremented for each event:

https://github.com/gravitational/teleport/blob/0f0b00b021c2f58034ecf2aea769b60dcd5e32a8/lib/events/setter.go#L113-L114

This logic isn't being applied because for each session chunk we create a new preparer and a new auditor, so the counter is starting over at 0:

https://github.com/gravitational/teleport/blob/0f0b00b021c2f58034ecf2aea769b60dcd5e32a8/lib/srv/app/session.go#L112-L128

If we want to leverage the existing logic that ensures the index is properly incremented, we need to reuse the same emitters for each chunk in the session. (Which is a bit tricky, as app sessions don't end explicitly)
