### ISSUE TITLE
Alias Example Does Not Match Description

### ISSUE THREAD

**Issue by thetuber** [gravitational/teleport#3728]
## Summary
From the user guide:

For example, if you have the following alias defined in your ~/.bashrc: alias ssh="tsh ssh" then you can continue using familiar SSH syntax:

```
# Have this alias configured, perhaps via ~/.bashrc
$ alias ssh=/usr/local/bin/tsh
```

The command should be:

`$ alias ssh="/usr/local/bin/tsh ssh"`

as mentioned in the descriptive paragraph above.

### Audience
new users

### Location
an addition to an existing guide?

**Comment by benarent** [comment]
Thanks for creating the issue @thetuber , I did try out a few options to see if the UX was broken. 

I think for clarity, we would have to add extra notes that when replacing `ssh` with `tsh ssh`, you'll still need to run `tsh login` to receive your certificate at the start of the day / time of access.  I think since TSH does offer extra functionally such as scp, cluster access, and ls.. it should provide more discoverability for new users.
