### ISSUE TITLE
host uuid, not node name show in access request submission page

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#37921]
Expected behavior:

The nodename is shown in the Submit Request. When the user selects the resource they see node name, not host uuid. If the host uuid needs to be shown then would expect a combination of them so it's human readable.

Current behavior:

host uuid is shown on submit request page.

![image](https://github.com/gravitational/teleport/assets/60704961/346ea65c-59ed-4086-9f04-73cdc803cf3f)

Bug details:
- Teleport version: 15.0.1 enterprise
- Recreation steps

Go through a access request, select a ssh server and go to submit.

- Debug logs

**Comment by zmb3** [comment]
Reproduces on master for me. `POST /v1/enterprise/accessrequest` returns an empty `friendlyName`:

```
"resources": [
        {
            "id": {
                "kind": "node",
                "name": "307e091b-7f6b-42e0-b78d-3362ad10b55d",
                "clusterName": "zac-local"
            },
            "details": {
                "friendlyName": ""
            }
        }
    ]
```

**Comment by ravicious** [comment]
Time permitting, could we also make this whole highlighted block something that you can click on (preferably a `<label>`) rather than forcing the user to click that arrow to the right? 😢

<img width="527" alt="additional-options" src="https://github.com/gravitational/teleport/assets/27113/b11d0fd4-61d4-4311-94a7-83433ab264fe">
