### ISSUE TITLE
Documentation on how to create a second proxy 

### ISSUE THREAD

**Issue by buzzzo** [gravitational/teleport#38074]
Please specify how to create a second proxy.
Documentation is lacking the required steps in order to configure various component in non standard way.
Please detail with examples on how to configure the relevant part of the configuration.

Better overview of the architecture is needed (how to have multiple components on the cluster on multiple nodes).

Thx

**Comment by zmb3** [comment]
This isn't quite actionable in its current form. If we're to take action on this, we need to know what you're trying to accomplish, what you tried, what errors you ran into, etc.

Since you're trying to do non-standard things, I think it best that you keep this discussion over on your your discussion post at #37734. Discussions are better suited towards general questions and advice, where GitHub issues are for tracking work once we've settled on what needs to be done.

**Comment by buzzzo** [comment]
Ok thx .
