### ISSUE TITLE
Keep Amazon Machine Images (AMI) updated.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#3813]
Let's investigate ways we can keep our AMI image updated. What are alternatives to submitting to the marketplace? Can we provide an AMI that users can upload then import (along with documentation on how to import).

**Comment by webvictim** [comment]
I think this is mostly a documentation ticket rather than anything else.

AMI builds are going to be automatic when we cut a tag with Drone. If we want a job which can programmatically update the docs with a list of AMI IDs for each region when we build them, we can look into that, but I tend to think that running something like `aws ec2 describe-images --owners 126027368216 --filters 'Name=name,Values=gravitational-teleport-ami-ent-4.3.0' --region us-west-2 | jq -r ".Images[].ImageId"` is the best way to get the correct AMI ID for a given region.

**Comment by webvictim** [comment]
I added commands to automatically create a list of AMIs and update the Terraform README/CloudFormation YAML files as approriate in https://github.com/gravitational/teleport/pull/4219.

Getting this stuff to be done automatically as part of a release should likely be part of #4031

**Comment by webvictim** [comment]
Marketplace builds are also going to be removed in #4502

**Comment by webvictim** [comment]
Marketplace builds have been removed. I think this ticket is basically done.
