### ISSUE TITLE
Use of small caps in the UI can make it hard to tell the actual case of labels/emails

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#3832]
**What happened**: There is a lot of use of "small caps" in the UI which makes it hard to see/know the case of letters in labels. It's aesthetically pleasing, but confusing.

![2020-06-11-164854__321x256__maim](https://user-images.githubusercontent.com/897821/84432848-c6e50a80-ac03-11ea-95a8-480c4d546412.png)

This also applies to email addresses/usernames in the top right which can be a problem for trying to add roles/usernames to nodes.

![2020-06-11-164857__199x48__maim](https://user-images.githubusercontent.com/897821/84432873-d19f9f80-ac03-11ea-8485-b0aa49f69c5d.png)

**What you expected to happen**: We should readily display the actual case of letters for functionality, rather than things which look aesthetically better.

**How to reproduce it (as minimally and precisely as possible)**: As above.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0-alpha.1git:v4.3.0-alpha.1-0-gd82e16ed0 go1.13.2`

**Comment by benarent** [comment]
The labels is fixed, but username / email is still capitalized.  cc @alexwolfe

**Comment by alex-kovoy** [comment]
@kimlisa could you take a look?

**Comment by kimlisa** [comment]
I made a PR for removing upper casing of login names, now the problem is the font size is too tiny (it is 10px) for both the label and username/email. Before, the small font was made up by the uppercasing. 

@alexwolfe @webvictim @benarent @alex-kovoy  if you guys agree, I can change the font size in the same PR, if not, I will leave it alone.

![Screenshot from 2020-06-29 18-16-11](https://user-images.githubusercontent.com/43280172/86071731-d9997500-ba34-11ea-8e55-f94f215ccdf7.png)

**Comment by alex-kovoy** [comment]
@kimlisa   We went over the label size with Alex so 10px is OK.

**Comment by alex-kovoy** [comment]
and as for the email size please make it 12px.
