### ISSUE TITLE
Error reported attempting to connect to MongoDB resources via Teleport Connect 

### ISSUE THREAD

**Issue by TeleLos** [gravitational/teleport#39836]
Expected behavior:
User should be able to seamlessly connect MongoDB resources in Teleport Connect. 

Current behavior:
Attempt to RUN the command via Teleport UI will produce error: _MongoshInvalidInputError: [COMMON-10001] Invalid URI: "mongodb://localhost:55138/?serverSelectionTimeoutMS=5000"_

Bug details:
- Teleport version

      Teleport Connect Version 15.1.9 (15.1.9.92) on macOS 14.4.1 and the mongosh version is 2.2.1.

- Recreation steps

      1. Login to Teleport Connect
      2. Select the Database Tab
      3. Connect to a MongoDB resource with an appropriate user
      4. This creates a new window with the command to RUN. See screenshot.  
      5. Attempt to RUN the command. This will produce error _MongoshInvalidInputError: [COMMON-10001] Invalid URI: "mongodb://localhost:55138/?serverSelectionTimeoutMS=5000"_
      6. If instead you select to open a new terminal in Teleport Connect and past the same command shown in step 4, it works. 
 
- [Proposed solution](https://github.com/gravitational/teleport/issues/39836#issuecomment-2022553281)

**Comment by TeleLos** [comment]
I am able to produce the error message on the terminal by enclosing the connection string in single quotes. 

~ % mongosh '"mongodb://localhost:55138/test?serverSelectionTimeoutMS=5000"'
MongoshInvalidInputError: [COMMON-10001] Invalid URI: "mongodb://localhost:55138/test?serverSelectionTimeoutMS=5000"

**Comment by ravicious** [comment]
This happens because lib/teleterm uses `dbcmd.WithPrintFormat` when generating commands. This option is meant to be used when the command is printed rather than executed, i.e. `tsh db config --format cmd`. It wraps connection strings in quotes. This way when the user copies a command and tries to execute it in a shell, the shell doesn't interpret certain characters in the connection string as special characters.

This worked in Connect because for a long time we did put those commands directly into a shell. However, in #26441 we switched to spawning CLI clients directly, which means the strings are at best unnecessary and at worst cause problems like this one here.

To fix this, `daemon.Service.GetGatewayCLICommand` should return two `exec.Cmd`s: one that doesn't use the print format and one that does. The one that does use the print format should be used for `api.GatewayCLICommand.Preview`, while other fields should come from the `exec.Cmd` that doesn't use the print format.

This way when the user clicks "Run", we execute the command without the quotes. But in the UI we display the version with the quotes, so that the user can simply copy and paste the command somewhere outside of Teleport Connect.

After implementing those changes, it's best to add a test for that and check if this didn't break anything else – there's a couple of functions in `dbcmd` that behave differently depending on `c.options.printFormat`.
