### ISSUE TITLE
Teleport `/web/*` should return 404 where appropriate.

### ISSUE THREAD

**Issue by programmerq** [gravitational/teleport#40567]
### Expected behavior:

```
Host: teleport.example.com
GET /web/aaaaaaaaaaaaaaaaaaaaaaaa

HTTP/1.1 404 Not Found
```

```
Host: teleport.example.com
POST /web/bbbbbbbbb
Content-Type: application/json
Content-Length: 2

{}

HTTP/1.1 404 Not Found
```

### Current behavior:

```
Host: teleport.example.com
GET /web/aaaaaaaaaaaaaaaaaaaaaaaa

HTTP/1.1 200 OK

<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="/web/config.js"></script>
...
```

```
Host: teleport.example.com
POST /web/bbbbbbbbb
Content-Type: application/json
Content-Length: 2

{}

HTTP/1.1 200 OK

<!DOCTYPE html>
<html lang="en">
  <head>
    <script src="/web/config.js"></script>
...
```

Currently, any request that starts with `/web` that doesn't also have an explicitly defined route will return with the same response as `GET /web`. This goes for POST, UPDATE, DELETE, and even made up HTTP verbs.

It should return with a 404, which seems to be what happens for paths outside `/web`. There may be other similar affected URL patterns.

This came up during a security scan, and it was puzzling why a POST was returning a status 200 with a body as part of the response. While this behavior doesn't seem to actually be a security issue, a 404 is a far more appropriate response for a path that doesn't exist.

Bug details:
- Teleport version: 15.2.2
- Recreation steps: `curl -v -d '{}' -X POST -H 'Content-Type: application/json' https://teleport.example.com/web/anything`
- Debug logs: n/a

**Comment by zmb3** [comment]
This is not a bug, it's just how client-side push state routing works for single page applications.

https://developer.chrome.com/docs/web-platform/navigation-api

> Single-page applications, or SPAs, are defined by a core feature: dynamically rewriting their content as the user interacts with the site, instead of the default method of loading entirely new pages from the server.

In other words, each unique URL in the app no longer corresponds to a unique HTML asset. The backend returns the same content for every path under `/web` because it is the responsibility of the SPA to render the right content on screen depending on what the URL path is. The backend doesn't even know what client-side routes are valid and what ones are not.
