### ISSUE TITLE
Cluster view leaks number of nodes to people without permissions to access them

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#4091]
**What happened**: Cluster view shows the total number of nodes in the cluster, rather the number of nodes you can actually log into.

Cluster view shows 6 nodes:

![2020-07-21-142335__980x354__maim](https://user-images.githubusercontent.com/897821/88087107-ccb50080-cb5e-11ea-9800-2fb9b1afd635.png)

Clicking into terminal view shows only 1 node:

![2020-07-21-142342__986x271__maim](https://user-images.githubusercontent.com/897821/88087147-d8a0c280-cb5e-11ea-8474-1b063393a531.png)

**What you expected to happen**: The number of nodes you can see should be the number that you actually have access to.

**How to reproduce it (as minimally and precisely as possible)**: Log into a cluster with `node_labels` set.

### Environment
- Teleport version (use `teleport version`): `Teleport Enterprise v4.3.0git:v4.3.0-0-g73b68f401 go1.13.2`

**Comment by webvictim** [comment]
Polling this node count also appears to cause problems on big clusters where enumerating the number of nodes takes a very long time (~1m30+) for 30 clusters with 10k+ nodes. This makes the web UI unusable.

**Comment by zmb3** [comment]
I think this is resolved with the server-side filtering and pagination. @kimlisa can you confirm?

**Comment by kimlisa** [comment]
the `cluster view` no longer shows the number of nodes (which solves this issue b/c we removed the logic from the backend). I think the primary reason we removed it though was because of the performance issues gus described above and we never got back to adding this column again. I swear I remember an issue (can't find the right keywords to locate it) related to adding back this column, but it got closed because it wasn't deemed important.

just fyi, this is how our `cluster view` looks right now:

![image](https://user-images.githubusercontent.com/43280172/184757818-4be31be6-7a06-4932-a0ad-6af72de615ad.png)
