### ISSUE TITLE
[docs] VarList does not render

### ISSUE THREAD

**Issue by GavinFrazar** [gravitational/teleport#41443]
## Applies To

anywhere we use the `<VarList/>` component, e.g. in
https://goteleport.com/docs/server-access/guides/vscode/

![image](https://github.com/gravitational/teleport/assets/16846283/3bb6167e-d137-4001-85a3-37e0164c2ca0)

## Details

There should be a list of variables rendered, but it's blank.

## How will we know this is resolved?

The above screenshot will display all the variables `<Var/>` from that page.

**Comment by GavinFrazar** [comment]
@ptgott

**Comment by ptgott** [comment]
I've gone as far back as 1fb84dafaa8ac48956eac65a861050b5f838d772, and the `VarList` still doesn't render then. I'm not sure yet what broke it. For me, since very few pages in the docs use it, I think it makes sense to remove the component and rephrase the docs that include it rather than spend time debugging.
