### ISSUE TITLE
Cache Early Reads

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#4183]

**Comment by fspmarshall** [comment]
Summary: Reads made against the cache while it is first initializing (or resetting due to an error) can be missing values which should exist (see #4066 for an example of this in the wild).  In rare cases, it appears that a proxy's cache can end up permanently missing a value.  My working hypothesis here is that that if the proxy's cache attempts an init/reset while the auth server's cache is also performing an init/reset, it ends up permanently holding onto the partial state.

Once I have tests in place to replicate the problem, I'll update this issue.

**Comment by fspmarshall** [comment]
*Update*:  I've got tests in place for reads during init and reset, and the cache is behaving like we thought, returning successfully with missing values.

*Proposal*: In short, we need to not route reads to cache states unless they are complete.  I'm thinking that we handle this in two parts.  For inits (the first time the cache is being constructed), we skip the cache and read directly from source until the cache state has been fully constructed. Once constructed, the cache behaves as normal until a reset is triggered.  When a reset is triggered, we freeze the current cache state, kill all its watchers, and continue to forward reads to it while a new cache sate is built in the background.  Once we have a new healthy cache state, we start forwarding reads to that cache and destroy the old one.

After a reset is triggered, any watchers that are opened against the cache need to be "queued", waiting to be registered with the next healthy cache sate.  In order to ensure correctness of child caches (caches watching caches), the `Init` event must not be sent to enqueued watchers until the next cache state is available.  This will ensure that reads performed after a watcher is established correspond to the correct state (reading the old state could cause child caches to become permanently out of sync).

Assuming the above strategy works, I believe it will actually allow us to simplify some of the existing cache logic since it should render the custom event fanout logic added in #3536 redundant.  The custom fanout logic was intended to eliminate spurious events during init/reset, but the strategy of freezing states on err and enqueueing watchers until the next good state is built should solve the same problem, without the need for special event handling.
