### ISSUE TITLE
EKS Discover enrollment can't download correct chart version for non-standard releases

### ISSUE THREAD

**Issue by AntonAM** [gravitational/teleport#42335]
Because of our recent change in artifacts release strategy (non standard releases like -alpha, -dev, -rc etc go to another repo) when EKS enrollment tries to download chart for a non standard release version it can't find it in the main repo.

**Comment by ravicious** [comment]
We have a similarish issue with Connect My Computer in Connect (cc @gzdunek). It checks what version the Electron app is at and then it tries to download the teleport binary from `cdn.teleport.dev`. But since alpha releases are now on `cdn.cloud.gravitational.io`, Connect My Computer doesn't work with the alpha.

I'm curious how you'll decide to approach this for EKS Discover. One solution would be to check the version string and decide based on that, but this would require some kind of contract from the release team. E.g., anything other than final releases goes to `cdn.teleport.dev`, everything else including alphas, betas and rcs goes to `cdn.cloud.gravitational.io`.

In the case of Connect My Computer, we could always try `cdn.teleport.dev` first and then `cdn.cloud.gravitational.io` if we get 404.

**Comment by AntonAM** [comment]
We went with the "all pre release tags routed to the staging repo" approach. Fred confirmed that all pre releases except for cloud-only ones go to staging, but for EKS Discover on cloud we take version from the cloud/stable channel anyway. There also was a bit of a discussion here: https://gravitational.slack.com/archives/C03LK5ZV4AE/p1717513866311889
