### ISSUE TITLE
Drop Access Request doesn't refresh access

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#42381]
Expected behavior:
When dropping an Access Request in Teleport Connect that the page would refresh what a user had access to prior to escalation.

Current behavior:
Dropping an Access Request does not refresh the page.

Workaround:
You can click on another tab (eg Pinned Resources) and back and the privileges/resources will referesh.

Bug details:
- Teleport version: v15.4.0
- Recreation steps
Create a new Access Request; Assume that approved request and then drop the request in Teleport Connect
- Debug logs
<img width="1392" alt="Screenshot 2024-06-04 at 1 02 39 PM" src="https://github.com/gravitational/teleport/assets/51385814/d20d3f41-c812-46cf-b56d-b7e9cdf4cff3">
<img width="1392" alt="Screenshot 2024-06-04 at 1 02 31 PM" src="https://github.com/gravitational/teleport/assets/51385814/0236c3d7-a8ea-4a23-9032-363a37dfd58b">
<img width="1392" alt="Screenshot 2024-06-04 at 1 03 01 PM" src="https://github.com/gravitational/teleport/assets/51385814/7bcddba4-75fe-4b47-a112-b98771b7eab9">
<img width="1392" alt="Screenshot 2024-06-04 at 1 02 21 PM" src="https://github.com/gravitational/teleport/assets/51385814/790ddcfb-46f4-4932-b2d5-4f23f72329b5">
<img width="1392" alt="Screenshot 2024-06-04 at 1 03 36 PM" src="https://github.com/gravitational/teleport/assets/51385814/aa4ee590-b009-459f-948f-c7d12fd26ee8">

**Comment by ravicious** [comment]
I ran into the same issue a couple of days ago. It certainly is an unexpected thing to happen, especially since assuming a request does refresh the resources.

I believe at the time when this was implemented, we ran into an "architectural" issue and we couldn't think of an easy way to fix this. Long story short, the function that refreshes resources cannot be called when dropping an access request due to hierarchy of React components.

However, I just talked about it with Grzegorz and there should be a straightforward way to address this. We need to move [`<ResourcesContext>`](https://github.com/gravitational/teleport/blob/e513f46d7663df575559941e8d844080fd7fb32d/web/packages/teleterm/src/ui/DocumentCluster/resourcesContext.tsx) in the hierarchy as high as needed. Then the two functions exposed by this context need to accept an extra arg which is the URI of the workspace which should refresh its resources in all open tabs.
