### ISSUE TITLE
Design for SAML application update flow that can be initiated from the resource access tile.

### ISSUE THREAD

**Issue by flyinghermit** [gravitational/teleport#42462]
Admin needs to be able to update SAML application in the Web UI. 

Resource access page is the only place where we show enrolled SAML applications so it seems an optimal place to provide SAML application update flow. 

<img width="893" alt="Screenshot 2024-06-04 at 6 39 33 PM" src="https://github.com/gravitational/teleport/assets/10177602/b0528e97-a641-4423-ad67-a42f8599e9c7">

Maybe an edit icon button or a "more option" that shows edit button that works well in the both grid and table view.

**Comment by roraback** [comment]
Design for buttons here: https://www.figma.com/design/JKd0Bgs30AnNfNCLUuzzc2/Unified-Resources?node-id=3049-67359&t=9isat6vEbxwUje0h-4

**Additional notes:**


* `Login` text becomes `Log In` (to be an action instead of a noun or adjective)
* These buttons are another instance of button groups that we're starting to use in Teleport; I've _started_ a version of these with only the border variant in the [Application Design System](https://www.figma.com/design/Gpjs9vjhzUKF1GDbeG9JGE/Application-Design-System?node-id=16670-91183&t=R3QByNAB2m53efBz-4) doc, but there's a lot of work to be done to work out the full scope of this component.
* Long term, would love to move this edit functionality into a detail page and out of the main Resources view.
* Currently, SAML apps do not have different roles, so won't have a drop-down menu. If we introduce this in the future (before detail pages) we can make the main button a dropdown as well... though this isn't _ideal._ I'm hoping we get to detail pages first!
