### ISSUE TITLE
github.com/microsoftgraph/msgraph-sdk-go causes excessive bloat

### ISSUE THREAD

**Issue by rosstimothy** [gravitational/teleport#42594]
The msgraph dependencies caused the teleport binary to increase by ~50MB.

![image](https://github.com/gravitational/teleport/assets/39066650/03a6b460-4e4d-47b7-877f-cf0d34796e51)

Relevant issue upstream: https://github.com/microsoftgraph/msgraph-sdk-go/issues/129

The ms graph folks seem to recommend building a custom client via https://github.com/microsoft/kiota to reduce the API surface of the package.

There is also an alternative package listed in that issue: https://github.com/manicminer/hamilton.

We could also create our own internal client that interacts with the endpoints that need to be interacted with instead of relying on a external dependency.

**Comment by tigrato** [comment]
cc @justinas

**Comment by justinas** [comment]
I had a cursory look at our options.

* [msgraphsdk-go-core](https://pkg.go.dev/github.com/microsoftgraph/msgraph-sdk-go-core) seems very unergonomic and mostly intended for use in the autogenerated code of `msgraph-sdk-go`. Seems like to use it, we'd need to implement stuff like 
* Hamilton looks pretty good. My one nit is that the only way it does pagination is by accumulating an array of all results, which, to be fair, is what we do anyway at the reconciler level, so it's like, we'll have 2 in-memory copies of a dataset instead of 1. 😅 
* Writing our own client is an option. MS Graph uses [OData](https://www.odata.org/), but we don't particularly need to implement all of it (or pull in a [3rd party library](https://github.com/crestonbunch/godata)), as our usage patterns are pretty simple: mostly "get all", "get one", "create one", "update one". I'd like to keep `azidentity` for this, since we're probably not removing it anytime soon: it is used extensively in `lib/cloud/azure` etc.

Let me know your thoughts about Hamilton vs. writing a client.
