### ISSUE TITLE
Teleport proxy_protocol not working as expected.

### ISSUE THREAD

**Issue by waleed-cariad** [gravitational/teleport#43390]
Expected behavior:
We are running Teleport Cluster (Proxy and Auth) Service on an AKS cluster using the helm chart provided by Teleport itself. The Proxy service is public facing behind an AKS Load Balancer and we have turned on the proxy_protocol to `on` as it's a L4 Load Balancer and it's mentioned in Teleport Docs the following:

on: PROXY Protocol is enabled and mandatory. If a PROXY protocol header is received, Teleport will parse the header and extract the client's IP address and port. If the header isn't present, it will reject the connection with an error.
off: PROXY Protocol is disabled and forbidden. Any connection with a PROXY protocol header is automatically rejected.

That means, as we are running beind the L4 Load Balancer, it should work fine if the proxy_protocol is set to `on` and it should reject connections when proxy_protocol is set to `off`.

Current behavior:

We have faced two issues:

1 - When we turned `on` the proxy_protocol on `proxy` service, everything was working and we could see the client_ip in our audit logs and last week, all of a sudden, proxy service started to reject connections by throwing an error:

`
$ tsh kube login --all --proxy=<proxy_url> --auth=github
ERROR: Teleport proxy not available at <proxy_url>
Get "https:<proxy_url>/webapi/ping/github": EOF
`

We found the following on proxy pods:

`2024-06-20T11:02:13Z WARN [MX:PROXY:] "\nERROR REPORT:\nOriginal Error: *trace.BadParameterError connection (10.64.8.11:57891 -&gt; 10.64.8.33:3080) rejected because PROXY protocol is enabled but required\nPROXY protocol line wasn&#39;t received. \nMake sure you have correct configuration, only enable &#34;proxy_protocol: on&#34; in config if Teleport is running behind L4 \nload balancer with enabled PROXY protocol.\nStack Trace:\n\tgithub.com/gravitational/teleport/lib/multiplexer/multiplexer.go:663 github.com/gravitational/teleport/lib/multiplexer.(*Mux).checkPROXYProtocolRequirement\n\tgithub.com/gravitational/teleport/lib/multiplexer/multiplexer.go:627 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detect\n\tgithub.com/gravitational/teleport/lib/multiplexer/multiplexer.go:339 github.com/gravitational/teleport/lib/multiplexer.(*Mux).detectAndForward\n\truntime/asm_amd64.s:1650 runtime.goexit\nUser Message: connection (10.64.8.11:57891 -&gt; 10.64.8.33:3080) rejected because PROXY protocol is enabled but required\nPROXY protocol line wasn&#39;t received. \nMake sure you have correct configuration, only enable &#34;proxy_protocol: on&#34; in config if Teleport is running behind L4 \nload balancer with enabled PROXY protocol." dst_addr:10.64.8.33:3080 src_addr:10.64.8.11:57891 loglimit/loglimit.go:122`

2 - We turned the proxy_protocol to `off` on teleport proxy service, restarted our pods and it started to accept connections BUT we saw client ips still preserved and appearing in audit logs where we were expecting the connections should be rejected now. Currently, no matter we turn the proxy_protocol to `on` or `off`, it doesn't seem to effect anything and the client_ip is always preserved given that the proxy's kubernetes service (kubernetes service of type `LoadBalancer`) has the following configured on it: `externalTrafficPolicy: Local`

Bug details:
- Teleport version: 15.3.1
- Recreation steps: 
- Debug logs: Provided above

**Comment by webvictim** [comment]
As far as I can see, Azure LBs don't support sending PROXY protocol headers:
- https://learn.microsoft.com/en-us/answers/questions/1285904/does-azure-loadbalancer-support-proxy-protocol
- https://learn.microsoft.com/en-us/azure/load-balancer/concepts#load-balancing-algorithm

This means that for your setup to work correctly, you should set `proxyProtocol: off` in your chart values.

Teleport is displaying the client IP because `externalTrafficPolicy` on your `LoadBalancer` service in k8s is set to `Local` which means the traffic hits the pod directly and the source IP is preserved. If you were to change it to `externalTrafficPolicy: Cluster`, you would likely see the internal/private IP associated with the Service object instead.

As far as Teleport is concerned, setting `proxyProtocol: off` only means that IF an incoming connection has a PROXY protocol header, it will be rejected. If it has no PROXY protocol header (as in your case, where the underlying LB does not support PROXY protocol) then the connection will still be allowed.

**Comment by waleed-cariad** [comment]
@webvictim Thanks for the promt feedback.
