### ISSUE TITLE
User is locked out if role expires before Access List

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#43775]
A customer has reported that a user will be locked out from Teleport if they are granted access by an Access List and one of the roles in the Access List has a TTL that has been expired.

From the customer:

> For instance, when using the tsh login command with a request id, it respects the shortest TTL among the granted roles for the identity file TTL. However, it does not respect the shortest TTL among roles in the access lists that associate with the user. This means that if there's a short-lived role in the access list, the certificate will still be issued with the default TTL. The error arises when the role is deleted but still in the identity file. We anticipate that the issued identity file will also adhere to the shortest TTL of the roles in the access lists.

Steps to reproduce are below.

1. Create a role with a TTL
2. Create an access list without TTL and set the user as the owner and grant the created role
3. Re-login to acquire the new role
4. Once the role expires, the error will occur
5. The user will be completely locked out and unable to re-login

**Comment by fspmarshall** [comment]
My 2¢ is that we shouldn't be supporting roles with TTLs at all, for a number of reasons:

- Teleport resource TTLs are a fairly weak guarantee and resources often persist up to 48h after their TTL.  TTL was always meant as a garbage collection mechanism, not a means of enforcing controls.
- A TTL'd resource is not distinguishable from a resource that was removed for another reason and/or never existed, meaning that any mechanism of supporting TTL'd roles would indirectly also change how teleport reacts to misconfiguration.
- It is not sane to just "ignore" a role that cannot be found because that role might contain deny rules.  If any role reference is invalid, we have to assume the entire identity is invalid, otherwise it's a privilege escalation risk.

There is one exception to the "must assume broken links contain deny rules" policy, which is that we treat access lists as atomic units, meaning that we allow access lists to fail to be applied "as a unit" if something about the list is invalid.  We cannot partially apply privileges from an access list, but it would be sane to allow a TTL'd role to invalidate the access list as a whole if we felt that were necessary.
