### ISSUE TITLE
Please add Active Users and TPR as metrics that can be exported

### ISSUE THREAD

**Issue by phall-teleport** [gravitational/teleport#44310]
What would you like Teleport to do?
Customer would like to be able to use Active Users and TPR via Prometheus or another method in their own observability system

What problem does this solve?
Customer would like to be able to work with this data in their own system. 

If a workaround exists, please include it.
Using the existing customer billing dashboard

**Comment by zmb3** [comment]
Closing in favor of gravitational/teleport.e#4186

**Comment by Mazorius** [comment]
@zmb3 can you fix the link you mention, please.

**Comment by zmb3** [comment]
The link is correct. Unfortunately, it resides in our enterprise repo which is not open to the public.

**Comment by Mazorius** [comment]
This means it is not possible to track this?The issues was created due to an support issue and I like to know what the status of this implementation is. On 18. Jul 2024, at 16:40, Zac Bergquist ***@***.***> wrote:﻿
The link is correct. Unfortunately, it resides in our enterprise repo which is not open to the public.
