### ISSUE TITLE
Teleport Shutdown Event

### ISSUE THREAD

**Issue by travelton** [gravitational/teleport#4506]
### Feature Request
When a Teleport binary is gracefully terminated, it would be nice to emit an event to audit logs that the Teleport binary was terminated. Or, when a node is no longer heart beating, emit an event for audit purposes. 

### Motivation
When a node goes offline, it seemingly disappears from the node list. It would be helpful to be able to review the audit logs and understand the timeline of the node's existence. 

### Who's it for?
All

**Comment by francisco-srodriguez** [comment]
Hi all.

In my opinion, currently Teleport is not very clear in this sense, that is, if you have 10 nodes you can control them easily throug Teleport UI or CLI.
The problems starts when Teleport has 500 nodes and 3 of them have been shutdown gracefully or these nodes are no longer heart beating, they will dissapear from Teleport and you couldn't trace the problem or you will not notice that 3 nodes are missing.

My request is that Teleport log these issues in some way in order to help us what is happened.

On the other hand, it would be good if the "broken" node does not disappear from Teleport, that is to say, that it continues being shown but with some failure indicator.

Thanks a lot.

**Comment by zmb3** [comment]
Let's combine this with #3657 since they're asking for the same thing - a way to identify when nodes go offline instead of having them just disappear.
