### ISSUE TITLE
http2 issue when using the API

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#4518]
### Description

**What happened**:

Customer is reporting an issue using http2 with Teleport API, it works with `--http1.1`

```
curl -XPOST -H "Content-Type: application/json" --data '{"roles": ["Trusted_cluster"]}' --cacert ./kb-test.cas --cert ./kb-test.crt --key ./kb-test.key https://[cluser-url]:3025/v2/tokens -vvv
> REMOVED
> REMOVED
> User-Agent: curl/7.54.0
> Accept: */*
> Content-Type: application/json
> Content-Length: 30
> 
* Connection state changed (MAX_CONCURRENT_STREAMS updated)!
* We are completely uploaded and fine
* HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
* Closing connection 0
* TLSv1.2 (OUT), TLS alert, Client hello (1):
curl: (92) HTTP/2 stream 1 was not closed cleanly: INTERNAL_ERROR (err 2)
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

### Environment
- Teleport version (use `teleport version`): 4.3.7 rc

**Comment by russjones** [comment]
Yes, this is due to how Teleport multiplexes HTTPS and GRPC.

We used to multiplex at the [application layer](https://github.com/gravitational/teleport/blob/branch/4.3/lib/auth/grpcserver.go#L480-L489) but we could not do that any longer due to missing functionality, like backpressure, unless you used the GRPC http server. See https://github.com/gravitational/oom for more details.

If you use the Teleport client, it should automatically select the protocol correctly for you. We now have documentation on how to use it: https://github.com/gravitational/teleport/blob/43ae5db239304a0c2e3f4236678fed6d0a826646/docs/4.4/api-reference.md
