### ISSUE TITLE
Teleport Connect - Device Trust - Different user logged in

### ISSUE THREAD

**Issue by scottpgallagher** [gravitational/teleport#45714]
Expected behavior:
When clicking the Launch Teleport Connect button when Device Trust is enabled it should give an option to login to Connect if the user is different.

Add a Logout button to Teleport Connect in this scenario. 

Current behavior:
If a different user is logged into Connect then what user is attempting the login through the Web you will get an error message. 

<img width="482" alt="Screenshot 2024-08-22 at 4 19 55 PM" src="https://github.com/user-attachments/assets/bed733c5-bc22-421f-a434-f808ce68d1a7">

Bug details:
- Teleport version: 16.1.7
- Recreation steps: Login to Connect as one user; login to the web as a different user and click Launch Teleport Connect and then Launch Browser
- Debug logs

**Comment by gzdunek** [comment]
I'm wondering if we necessarily have to log out the user. In the deep link we get the username, so we can compare it with the currently logged in user, and if they differ, we can show an appropriate message with a button to relogin.
This button would open the `cluster-connect` dialog with the username prefilled. After logging-in, the warning would disappear and the user could continue in the already opened tab. The UX of this would be super-smooth as everything would stay in-place, you would just have to relogin. 

I'm only concerned if changing the user without a full logout is a good idea (on tsh side it's probably fine, but in electron you would still see tabs/connections of the previous user). OTOH, it's possible even now, nothing prevents you from logging in as a different user.
Another thing is that the scenario with logging out the user seems more complex (should we reopen the "authorize web" tab after the user logs in again? or just say to retry the action from Web UI?)

Do you have anything thoughts @ravicious?

**Comment by ravicious** [comment]
I don't think there's anything in tsh or Connect which takes into account a scenario where you log in as a different user without logging out first. During relogin, tsh won't let you pick another local user, but I suppose it might be possible to log in as a different SSO user. But tsh in general doesn't have to worry about persisting anything since it mostly works on a "one-shot" basis.

Connect could (should?) make the username field readonly during relogin. It'd still be possible to log in as another user with SSO though.

That is all to say, it's not a scenario we really handle anywhere because most people just don't have more than one account. I'd say it mostly affects people working at Teleport. 😏

So I don't think we should implement special handling for this case beyond a button which logs you out and then opens a login form with the cluster address and the username pre-filled. As I mentioned, logging in as another user without logging out is not a path that is well tested.

Even then, I'm not sure if we should spend time on addressing a scenario which 1) mostly affects Teleport employees when testing/demoing the product, as their needs are already different than those of regular users 2) already has a rather straightforward workaround (log out and log in as another user).

If there was a situation where it can happen during normal use than a logout button would be fine, but I just don't think it's worth spending time on this given that (I believe) most users don't have more than one account.

## Possible attack vector? (probably not)

I'm not sure if we should even prefill the username field at all. I don't know if it would be an attack vector, but an attacker could create a bogus deep URL with a different username and Connect would just say "Oh, you're not logged in as <bogus-username>, please click 'Log in again' and then I'll show you a login form with <bogus-username>".

But then I can't think of what benefit it'd have for the attacker. They wouldn't be able to make you log in as another user unless the passwords for both accounts were the same.

**Comment by gzdunek** [comment]
>So I don't think we should implement special handling for this case beyond a button which logs you out and then opens a login form with the cluster address and the username pre-filled. As I mentioned, logging in as another user without logging out is not a path that is well tested.

Right, it's better to avoid switching users. 

>Even then, I'm not sure if we should spend time on addressing a scenario which 1) mostly affects Teleport employees when testing/demoing the product, as their needs are already different than those of regular users 2) already has a rather straightforward workaround (log out and log in as another user).

Yeah, it probably affects only Teleport employees, although this quarter I'm addressing our internal feedback, so I think I will add a simple logout button. 
The benefit of relogging before making an attempt to authorize the session is that your web token is not invalidated, so you can click 'Launch Teleport Connect' again. After you try to authorize the session, you will need to log out and log in again both in Connect and Web UI.

**Comment by ravicious** [comment]
> The benefit of relogging before making an attempt to authorize the session is that your web token is not invalidated, so you can click 'Launch Teleport Connect' again. After you try to authorize the session, you will need to log out and log in again both in Connect and Web UI.

That's the part that I was missing. It seems like a good improvement then.
