### ISSUE TITLE
Rename EC2 Auto Enrollment to EC2 Auto Enrollment via AWS Systems Manager

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#45842]
Teleport AWS EC2 Auto Enrollment provides a seamless experience, but it requires AWS Systems Manager. Which isn't always a default of users. Instead it makes assumptions that most accounts already meet the prerequisites.  

For someone not using AWS Systems Manager, or not having SSM agent installed. There is a lot of extra work to get this integration to work.  While wordy, `AWS EC2 Auto Enrollment via Systems Manager` is a more true statement for this integration.

**Comment by benarent** [comment]
What if we use SSM instead of the full AWS Systems Manager (SSM)

**Comment by milos-teleport** [comment]
Another +1 for this, especially because currently if customers try to cross-reference this enrollment type with our integration, they run across [this document](https://goteleport.com/docs/enroll-resources/auto-discovery/servers/ec2-discovery/) titled "Configure Teleport to Automatically Enroll EC2 instances", which explains how to set up an EC2 instance with a teleport agent.
