### ISSUE TITLE
Consider adding support for Open Policy Agent

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#4597]
### Feature Request

https://www.openpolicyagent.org/

Embed it as a library to support RBAC definitiions, people can create OPA roles in our RBAC:

```yaml
role: v3
name: opa-policy
spec:
   policy | 
      package application.authz

      # Only owner can update the pet's information
      # Ownership information is provided as part of OPA's input
      default allow = false
      allow {
          input.method == "PUT"
           some petid
           input.path = ["pets", petid]
           input.user == input.owner
      }
```

**Comment by klizhentas** [comment]
Any community interest? :+1:  if you are interested in using it and share your use case

**Comment by benarent** [comment]
We've a +1 from a community user. https://github.com/gravitational/teleport/issues/3454#issuecomment-679830076

**Comment by rosskusler** [comment]
One use case would be fine grained control over who can login under what conditions.  Alice can login to this server, but only between 8-5 PT, etc.  Kelly can log into this server, but only from the Miami jumphost.  Jerry can ssh into this server, but only if running a non-interactive command that matches the pattern 'rm /home/jerry/logs/*/*.gz', etc.

**Comment by jonathanmyers** [comment]
We've encountered a limitation of teleport's existing yaml RBAC scheme that OPA would solve.  `kubernetes_label` and `kubernetes_group` are not related, so it's not possible to selectively grant a role on one cluster without granting it on all clusters.  For example, we would like to grant a role `system:masters` permissions on one cluster, but a limited role on all others, but today adding `system:masters` to a role grants them that permission on all enabled clusters.

Of course, this could be fixed by changing teleport's current yaml configuration to support binding these two flags, but I suspect there will be other cases like this as users try to set up more complex RBAC controls.  Open policy agent as a general purpose solution is attractive since it would support arbitrarily complex policies.  

OPA is also an interesting possibility for more standard authorization, which would be helpful since many current teleport users like us have to juggle identity provider RBAC (eg. Okta), teleport RBAC, cloud provider RBAC (e.g. AWS IAM), and kubernetes RBAC.

**Comment by Valien** [comment]
+1 for interest here as well. Talking to a group that is also interested in adding this capability into Teleport.

**Comment by tz-torchai** [comment]
It seems this issue has gained a lot more community interests comparing to other open issues.

Just to add some info here, there is [gatekeeper](https://github.com/open-policy-agent/gatekeeper) with some [benefits](https://github.com/open-policy-agent/gatekeeper#how-is-gatekeeper-different-from-opa) comparing to OPA.

**Comment by kotyara85** [comment]
+1

**Comment by kotyara85** [comment]
Would be cool to actually plug it in as an external rbac system

**Comment by dumez-k** [comment]
Was just asked by a potential customer about Teleport's OPA support at KubeconEU.
