### ISSUE TITLE
pgevents: wrong retention period calculation and no way to disable cleanup on CockroachDB

### ISSUE THREAD

**Issue by espadolini** [gravitational/teleport#46125]
Expected behavior:

The pgevents audit log storage driver deletes events after the configured retention period. Setting the `disable_cleanup` option disables event cleanup.

Current behavior:

The effective retention period is wrong by a factor of 1000 (as the retention period is sent as a count of nanoseconds but interpreted as a count of microseconds) and then subject to overflow, resulting, in the default case (one year), in a negative retention period and thus events being deleted on every cleanup period.

Disabling cleanup with the `disable_cleanup` option results in an error at auth start time, as Teleport tries to reset the `ttl_expiration_expression` storage option for the `events` table rather than resetting the `ttl` "metaoption".
```
User Message: initialization failed
  configuring CockroachDB retention
    ERROR: &#34;ttl_expire_after&#34; and/or &#34;ttl_expiration_expression&#34; must be set (SQLSTATE 22023)
```

Workaround:

To temporarily disable event cleanup, it's possible to connect to the CRDB cluster on the database used for event storage and executing the query `ALTER TABLE events SET (ttl_pause = 'on');`. To undo that setting once a fixed version of Teleport is deployed on the Auth Service instances, issue the same query with `off`.

Bug details:
- Teleport version: 15.4.1+, 16.0.0+

**Comment by mol-george** [comment]
Hi Teleport Team,

I think the issue is two-fold:
1. a mismatch between the between RetentionPeriod value between the Teleport and the CockroachDB
2. CockroachDB constraints when it comes to resetting ttl related configuration (i.e. `ttl_expiration_expression`, `ttl_expire_after`)

## 1. Mismatch between the between RetentionPeriod value between the Teleport and the CockroachDB
* `time.Duration` [defaults to nanoseconds](https://pkg.go.dev/time#Duration)
* CockroachDB seems to expect the `ttl_expiration_expression` as [microseconds](https://www.cockroachlabs.com/docs/stable/row-level-ttl#ttl-storage-parameters)
* the fact that that we initially pass the time as microsecond confirms this also

```go
	schemaV1CockroachSetRowExpiry   = "ALTER TABLE events SET (ttl_expiration_expression = '((creation_time AT TIME ZONE ''UTC'') + (%d * INTERVAL ''1 microsecond'')) AT TIME ZONE ''UTC'' ');"
```

## 2. CockroachDB constraints when it comes to resetting ttl related configuration (i.e. `ttl_expiration_expression`, `ttl_expire_after`)
Once you use `ttl` on a table by either setting `ttl_expiration_expression` or `ttl_expire_after` it looks like you must either:
* keep one of the values set as per the error replicated in the attachment
* or reset the whole `ttl` e.g. `ALTER TABLE events RESET (ttl)`


## Proposed fixes
1. update `configureCockroachDBRetention` function to convert the `cfg.RetentionPeriod` to microseconds before passing it to the `schemaV1CockroachSetRowExpiry` query
2. update the `schemaV1CockroachUnsetRowExpiry` query to reset the `ttl` configuration on the table - assuming that this is what we want
```go
    schemaV1CockroachUnsetRowExpiry = "ALTER TABLE events RESET (ttl);"
```

As far as I can tell this might have been introduced in a41df22ed5d0b08387826edac65f38f488d2801e.

As per [contributing guidelines](https://github.com/gravitational/teleport/blob/master/CONTRIBUTING.md), please let me know if I can contribute to this issue.
[reproducing-issue-46125.md](https://github.com/user-attachments/files/16850994/reproducing-issue-46125.md)

Regards,
George Moldoveanu
