### ISSUE TITLE
Let Teleport to initialize DynamoDB tables with auto-scaling enabled

### ISSUE THREAD

**Issue by alex-kovoy** [gravitational/teleport#4661]
We need to be able to initialize DynamoDB tables with autoscalling enabled. The additional settings for the auto scaling policies may come from the config file. @webvictim can provide more information on the extra parameters. These extra parameters do not need to be documented and should be considered internal. 

@russjones would be nice to make it part of 5.0.

**Comment by webvictim** [comment]
We'd be looking to enable PITR (point in time recovery) for Teleport Cloud's DynamoDB tables, otherwise known as `ContinuousBackups`.

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_UpdateContinuousBackups.html
https://docs.aws.amazon.com/sdk-for-go/api/service/dynamodb/#DynamoDB.UpdateContinuousBackups
