### ISSUE TITLE
Teleport AMIs deployed via our Terraform templates have their teleport.yaml reset on reboot

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#4680]
### Description

**What happened**:
Rebooting an EC2 instance that has been launched via our Terraform causes the instance's teleport.yaml to be replaced with the original default teleport.yaml.

**What you expected to happen**:
The teleport.yaml should not be replaced on reboot.

**How to reproduce it (as minimally and precisely as possible)**:
Launch a cluster using our Terraform template. Edit the teleport.yaml, reboot the the instance.

### Environment
- Teleport version (use `teleport version`): This has been seen in several versions, but most recently in 4.3.7
- OS (e.g. from `/etc/os-release`): AMIs

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by webvictim** [comment]
In general, the idea is that `/etc/teleport.yaml` _should_ always be regenerated on boot so that the configured Teleport settings are in line with the Terraform-configured values, which in turn are set in the EC2 instance's user-data and written to `/etc/teleport.d/conf` to be sourced by the scripts inside the AMI. If any of the values present in `/etc/teleport.d/conf` are what's being changed in `/etc/teleport.yaml` then these changes should be made in that file instead.

If someone wishes to disable the config generation on boot, they should be able to `sudo systemctl mask teleport-generate-config.service` to disable this behaviour. 

If and when the config is rewritten, it should be backed up to `/etc/teleport.yaml.old` so it can be easily restored if needed.

**Comment by webvictim** [comment]
We discussed this issue and agreed that we'll address it by changing the `teleport-generate-config` script to only run when `/etc/teleport.yaml` is not present. If `/etc/teleport.yaml` is present, the script will print a message and `exit 0`.

https://github.com/gravitational/teleport/blob/master/assets/aws/files/bin/teleport-generate-config#L6-L10
