### ISSUE TITLE
WebUI Keyboard Shortcuts

### ISSUE THREAD

**Issue by Omeryl** [gravitational/teleport#471]
Is there a trick to getting this to work? For example, in tmux, `^b + d` to detach, or `^b + 3` to switch to window 3?

**Comment by Omeryl** [comment]
I wouldn't even so much deem it a feature request, the web terminal is kind of useless without being able to send key combos ;).

**Comment by pirogoeth** [comment]
I think this may be one of those things that is a little easier said than done, simply because there are some key combos that should typically override the "send-to-server" behaviour (I really miss being able to Ctrl-C / Ctrl-V :cry:). There are definitely things like Ctrl-A, Ctrl-B, Ctrl-Z, Ctrl-C that should *always* be forwarded to the session through the web terminal, but we also need an alternate binding for clipboard actions -- if not just being able to right-click -> paste (since right-click -> copy works okay as-is).

**Comment by Omeryl** [comment]
They usually do things like ctrl+shift+c and ctrl+shift+v for that in terminal emulators, that's not really a problem specific to a web shell @pirogoeth.

**Comment by kontsevoy** [comment]
This has been documented here:
https://gravitational.com/teleport/docs/faq/

and here:
https://gravitational.com/teleport/docs/user-manual/#web-ui

**Comment by aqiank** [comment]
Hi, I don’t see anything that provides the desired functionality in the pages above. Could we perhaps take another look at this? Apologies if I missed it.
