### ISSUE TITLE
RDS Discover flow connection test fails with per-session MFA enabled

### ISSUE THREAD

**Issue by greedy52** [gravitational/teleport#47206]
Expected behavior:
MFA prompt and continue connection test.

Current behavior:
<img src="https://github.com/user-attachments/assets/c51a69fb-eaa4-43a9-be2b-e974db81a0aa" width="400">

Bug details:
- Teleport version: 16.4.2 cloud
- Recreation steps: enable per-session MFA (example, `require_session_mfa: true` in `access` role) then follow RDS discover flow till connection tester

**Comment by greedy52** [comment]
Alternatively, we can replace the connection tester with our web shell which should support per-session MFA when the feature is released.

**Comment by GavinFrazar** [comment]
In https://github.com/gravitational/teleport/pull/49336 I noted that this issue was fixed in https://github.com/gravitational/teleport/pull/48811 addressing a duplicate issue. But I also found an Aurora-specific error case when you clear the database name (shouldn't be able to).

![Image](https://github.com/user-attachments/assets/fbd8f8b1-8873-4d10-b402-4bb014e3031e)

Hence, I'm leaving this open until https://github.com/gravitational/teleport/pull/49336 merges to fix that.
