### ISSUE TITLE
Indicate when a Teleport Connect session is on a trusted device

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#47249]
Expected behavior:

Like the web ui if I log in to Teleport Connect a green shield would appear next to my user.  

Current behavior:

After logging into Teleport Connect there is no indication that you are on a trusted device with your login. The only way to confirm is to open a terminal and run `tsh status` to see the extensions.

```bash
  Extensions:         login-ip, permit-X11-forwarding, permit-agent-forwarding, permit-port-forwarding, permit-pty, private-key-policy, teleport-device-asset-tag, teleport-device-credential-id, teleport-device-id
```

If I'm in an environment where they auto-enroll my device this makes it harder to know when my device is enrolled or not.

Bug details:
- Teleport version: 16.4.2
- Recreation steps

1. Register a trusted device
2. Login via Teleport Connect on that device

**Comment by gzdunek** [comment]
Definitely it's a good idea to indicate in Connect that the user is on a trusted device.
However, I'm not sure if we should display the shield icon next to the user icon so that it is always visible, like in Web UI. For reference, this is how it looks like there:
<img src="https://github.com/user-attachments/assets/0d29fe59-f6a6-458a-9c1d-90fef7001e7f" width="500">

In Connect, I was thinking about something more subtle:
<img src="https://github.com/user-attachments/assets/08904972-e756-48e1-bc22-791ec804ed02" width="500">

My reasoning was that device enrollment is persistent, you don't need to authorize every session, as in Web UI. Because of that, you probably don't need this information visible all the time, it can be hidden in the menu.

What do you think @stevenGravy, @roraback?

**Comment by stevenGravy** [comment]
> What do you think [@stevenGravy](https://github.com/stevenGravy), [@roraback](https://github.com/roraback)?

Sure, that makes sense!

**Comment by gzdunek** [comment]
I just realized that we can also quite easily show an indication when device trust is required but the user didn't enroll (I thought it's more work). It would look more or less like this (with a warning icon always visible):
![Image](https://github.com/user-attachments/assets/e465e925-2a46-4be6-ad64-a75dba7ada83)

This should partially address https://github.com/gravitational/teleport/issues/43020.

I'm also considering changing the language a bit. Since we don't need to authorize per session, maybe we should say: `This device is trusted.` and `Device is not trusted, access is restricted. Learn how to enroll.`
