### ISSUE TITLE
Terraform ha-autoscale-cluster does not work out of the box.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#4739]
Tried Terraform ha-autoscale-cluster cluster, does not work out of the box.

https://github.com/gravitational/teleport/tree/master/examples/aws/terraform/ha-autoscale-cluster

* `/etc/teleport.d/roles.all` was misnamed, was called `/etc/teleport.d/roles.auth`.
* The systemd unit file contained a pre-start script, the Let's Encrypt block had to be manually commented out to start Teleport.

**Comment by webvictim** [comment]
> /etc/teleport.d/roles.all was misnamed, was called /etc/teleport.d/roles.auth.

`role.all` isn't written by default. When you launch `ha-autoscale-cluster` via Terraform, each instance starts with an individual role - either `role.auth`, `role.proxy`/`role.proxy-acm` or `role.node`. This information is sourced from the instance's EC2 user-data at startup, and this is what allows us to have one `teleport-generate-config` script which handles all roles.

The logic which handles this is here: https://github.com/gravitational/teleport/blob/master/assets/aws/files/bin/teleport-generate-config#L225 - the idea is that if you want to run an all-in-one instance, you specifically have to do this by setting `TELEPORT_ROLE=auth,node,proxy` in your instance's user-data or `/etc/teleport.d/conf`.

This is also how the `starter-cluster` Terraform works: https://github.com/gravitational/teleport/blob/master/examples/aws/terraform/starter-cluster/data.tpl#L3

This was done to allow us to have just one AMI that works for everything - either of the Terraform setups, or just someone who wants an AMI with Teleport pre-installed. This probably needs to be explained better in the docs somewhere.

> The systemd unit file contained a pre-start script, the Let's Encrypt block had to be manually commented out to start Teleport.

Do you mean this line: https://github.com/gravitational/teleport/blob/master/assets/aws/files/system/teleport-proxy.service#L15 ?

LetsEncrypt is enabled by default, so the process works like this:
- one of the Teleport auth servers wins the DynamoDB lock
- this winning auth server automatically acquires LetsEncrypt certs for the domain configured (it also generates the CA pin hash and join tokens, and writes these to AWS SSM parameter store)
- the auth server uploads the LetsEncrypt certs to an S3 bucket
- all Teleport proxy servers poll this S3 bucket and try to sync it locally, when that succeeds (because there are certs in the bucket) then the Teleport proxy will start.

If this wasn't happening for some reason I'll look into it.
