### ISSUE TITLE
ssh: certificate signed by unrecognized authority

### ISSUE THREAD

**Issue by alperaydemir** [gravitational/teleport#477]
Hi,

I'm trying to get the Trusted Clusters functionality work somewhat unsuccessfully. The goal is to connect nodes behind a firewall with no public IP through reverse tunneling. `main` is the main cluster and `cluster-b` is the one behind the firewall.

Following the admin manual I was able to configure the reverse tunnel however, `tctl auth ls` shows this
```
CA keys for the local cluster main:

CA Type     Fingerprint
-------     -----------
user        8c:1a:c7:15:82:87:01:fb:1a:7f:06:7e:95:0e:e0:75
host        b4:68:f7:81:32:a0:0a:90:a1:13:e4:a6:62:eb:e6:ee
```

And not the keys for the trusted clusters. Digging deeper where's what the `main` cluster prints with verbose printing enabled. I can verify that the IPs are from `cluster-b`

`failed auth user 43dc0dcb-11bd-4c84-928c-5876d612b40e.43dc0dcb-11bd-4c84-928c-5876d612b40e, err: ssh: certificate signed by unrecognized authority  file=auth/tun.go:379`

Is there a way to make teleport accept insecure certificates for testing? I'm trying to make a proof of concept so if it works, we plan to use teleport in production.

**Comment by kontsevoy** [comment]
@alperaydemir apologies for the delay! do you want to get on Google Hangout and I will help you debug these issues? Teleport has useful sample configurations in `vagrant` directory and we can interactively play with them and I'll answer your questions.

**Comment by kontsevoy** [comment]
@alperaydemir I am closing this issue because it's a support request. But you're still welcome to jump on Google Hangout with me. Your question can be answered with "yes" (via `--insecure` flag to `tsh`) but your error doesn't have anything to do with HTTPS: most likely you have not configured cluster keys properly as described in "Trusted Clusters" chapter in the docs. Again, ping me if you need help on video: ev@kontsevoy.com
