### ISSUE TITLE
Document `--request-roles` functionality for additional roles 

### ISSUE THREAD

**Issue by aelkugia** [gravitational/teleport#4818]
### Feature Request
A customer would like to see promote in place functionality added for approval workflows. Currently a user can request a role for example:

`$ tsh login --request-roles=dba`

But then to request another role the user will need to logout `tsh logout` and request new role.

### Motivation
This would be an improved user experience for approval workflow when a user is in a session they would no longer need to logout to request a new role, instead in current session can request an elevated role or different role as they prefer. 

### Who's it for?
OSS User, Pro, Enterprise

**Comment by fspmarshall** [comment]
Actually, this already works!  Its confusing because `tsh login` doesn't just log you in, `tsh login` is also the command used to *re-issue* certs (thats why you also run `tsh login` again when changing your target cluster).  If a user runs `tsh login --request-roles=<additional-roles>` while logged in, the requested roles will be added to their current set of roles if their request is approved.
