### ISSUE TITLE
session recorded openssh server 

### ISSUE THREAD

**Issue by Jazb** [gravitational/teleport#482]
I've been testing teleport in production environments. And this was the only thing I really wanted, because although its integration with vanilla SSH is splendid both when running OpenSSH Client and Server. And I can use the ssh command to get a shell provided by Teleport where the session is recorded.

I have seen that at least I have to have 2 ports open one on the server that I want to connect the 3022 default, this is normal. But while this server you want to connect me has to reach the server that makes the role of auth typically port 3025.

This is necessary to make huge changes throughout the infrastructure that already exists deployed on vanilla, I wonder if it is possible to implement a session Recorded with OpenSSH Server or otherwise if I can only have a single port in one direction at the server end that runs the instance of teleport.

What I mean is if there is any way to deliver on the sequence of authentication and authorization through the connection itself, which is done by 3022, as OpenSSH.

Finally it seems that features both count as great improvements to enhance the product.

**Comment by kontsevoy** [comment]
@Jazb the reason Teleport needs port 3025 is because it needs to ship recorded session to the session store, and regular port 22 is used for the actual session. You're right, it could have been possible to implement recording on the proxy (this way your existing fleet of OpenSSH machines wouldn't need to be changed) but this wasn't our internal use case, unfortunately.

**Comment by kontsevoy** [comment]
Closing because it calls for a serious structural change we're do not have resources for.
