### ISSUE TITLE
Links on the help&support page don't point to version-specific documentation

### ISSUE THREAD

**Issue by bl-nero** [gravitational/teleport#48201]
Expected behavior:
Links on the help&support page should point to version-specific documentation.

Current behavior:
Links contain the expected version in the query, but the documentation page displays documentation for the latest release, as the version is expected to be a part of the URL path.

Bug details:
Teleport version: v17, v16 (perhaps earlier, too; didn't test)

**Comment by zmb3** [comment]
I think this was intentional. 

We used to link to version-specific pages, but customers run EOL versions of Teleport after the docs are no longer live, and end up getting broken links. 

By linking to latest most times we will at least take them to the relevant page even if the version isn't quite right.

**Comment by bl-nero** [comment]
@zmb3 I think the intention here was to link to version-specific documentation, since the links contain the version information, but only the format is wrong. For example, in case of "getting started guide", the link is `https://goteleport.com/docs/get-started/?product=teleport&version=oss_17.0.0-alpha.2`, while it should be `https://goteleport.com/docs/ver/17.x/get-started/`. It means that at some point of the time, the version syntax was changed on one side, but not the other. If it was as you describe it, these links wouldn't have version information in them at all.
