### ISSUE TITLE
UI tables have inconsistent hover state

### ISSUE THREAD

**Issue by zmb3** [gravitational/teleport#48363]
Most of our UI tables have a hover state with a white background (in light mode) and a drop shadow. This is the correct behavior.

![Image](https://github.com/user-attachments/assets/9a312b94-3776-449f-97a7-1a39a5785bea)

The Trusted Devices table has a purple hover state, and the purple doesn't extend all the way to the bottom of the row, leaving a sliver of the original lighter background color. This is incorrect.

![Image](https://github.com/user-attachments/assets/569fa857-d7b0-48f8-8711-1ae40d0e3172)

**Comment by avatus** [comment]
The purple comes from the [figma design ](https://www.figma.com/design/v6GunK50D2VC7w7I2FBDNf/Access-(Management)?node-id=4303-43344&t=iKsZhACV8tXFoUgP-4) but, to be fair, the _other_ changes like colored icons and colored 'Enrolled/Not Enrolled' cahnges didnt go through so "I just followed the design" isnt the best excuse.

![Image](https://github.com/user-attachments/assets/25729d85-1013-4799-9740-6261eb148fab)

Without the added colors for the hover states, because the design of the empty state has a White background (instead of transparent like the page), the hover effects don't show at all. example below (ive hovering the second linux)
![Image](https://github.com/user-attachments/assets/48f6cb59-d3fa-4c0f-985b-87df0a7ceee3)

I think the best idea to keep everything consistent is to remove the white background from the example table
![Image](https://github.com/user-attachments/assets/2eef9845-8a15-4202-8827-9128d87ef06b)


What are your thoughts @roraback

**Comment by roraback** [comment]
Sounds good, re: keeping hover states consistent between pages and within the empty-state visualizations.

If someone also feels inspired to add full color icons to the actual table in lieu of the simple icons, even better! 😄
