### ISSUE TITLE
Authorizing web session doesn't work when a users's role has short TTL

### ISSUE THREAD

**Issue by gzdunek** [gravitational/teleport#49629]
Expected behavior:
Web session is authorized with device trust.

Current behavior:
Web session is not authorized when the user has short TTL set on a role.

Bug details:
- Teleport version
17.0.2
- Recreation steps
1. Enable device trust requirement for the user and enroll a device.
2. Add a new role and assign it to the user:
```yaml
kind: role
metadata:
  name: short_ttl
spec:
  allow: {}
  deny: {}
  options:
    max_session_ttl: 3m2s
version: v7
```
3. Try to authorize the web session by confirming the popup in Connect, it should work at this point.
4. Now, change `max_session_ttl` to `3m1s`, logout in Web UI, and try to authorize the web session again. 
5. It should fail (you should see a yellow shied in the top right corner).
- Debug logs
In the audit log there is a following entry:
```
{
  "cluster_name": "main",
  "code": "TV009I",
  "device": {
    "device_id": "<device-id>",
    "web_authentication_id": "<authentication-id>"
  },
  "ei": 0,
  "event": "device.authenticate.confirm",
  "message": "token move check failed",
  "success": false,
  "time": "2024-12-02T13:28:55.617Z",
  "uid": "ae2e8b0d-cd8c-4cc9-87f1-356f54f175c2",
  "user": "testuser"
}
```

**Comment by codingllama** [comment]
What is happening here is that, because the max TTL is so small, the session is renewed almost immediately by the Web UI. The token move check wants to see a confirmation in the same session that created the token, sees the new session and fails.

https://github.com/gravitational/teleport/blob/911f3e3ffcbbd7157c21c33b4889d17f5ee20e8c/web/packages/teleport/src/services/websession/websession.ts#L31

I'll see what we can do.

**Comment by zmb3** [comment]
@codingllama are we good to close this one?

**Comment by codingllama** [comment]
Yes, we can! Thanks.
