### ISSUE TITLE
Unable to add cluster name with '/' Or ':' in kube_service

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#4995]
### Description

**What happened**:
Attempted to add a cluster that contained a `/` in its cluster name. The AWS EKS cluster ARN automatically includes a `/` as shown below before the cluster name as created.  This occurs in EKS and non-EKS k8s clusters.

`arn:aws:eks:us-east-2:838293:cluster/clusterExample`

If the ARN is then used from a command  like below the cluster could not be made available in `kube_service` using that name.
```bash
$(kubectl config current-context)"
```

**What you expected to happen**:
Able to add cluster names with a `/`.

**How to reproduce it (as minimally and precisely as possible)**:

Attempt to add a cluster in `kube_service` that has a '/` as part of its name.

### Environment
- Teleport version (use `teleport version`): 5.0.0
- OS (e.g. from `/etc/os-release`): ubuntu

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS EC2

**Relevant Debug Logs If Applicable**

Did not see this specific warning in my environment but was reported by another.
```bash
WARN [KUBERNETE] Heartbeat failed rpc error: code = InvalidArgument desc = invalid kubernetes cluster name: "arn:aws:eks:us-east-1:<ACCOUNT>:cluster/<CLUSTER_NAME>
```

**Comment by stevenGravy** [comment]
^ @awly

**Comment by stevenGravy** [comment]
also seeing an issue with `:`

**Comment by alex-kovoy** [comment]
@stevenGravy 

If this is a k8s cluster name then it cannot have these characters. k8s cluster name must be a valid FQDN string.

https://github.com/kubernetes/apimachinery/blob/master/pkg/util/validation/validation_test.go#L53
https://github.com/kubernetes/apimachinery/blob/master/pkg/util/validation/validation_test.go#L549

**Comment by stevenGravy** [comment]
> @stevenGravy
> 
> If this is a k8s cluster name then it cannot have these characters. k8s cluster name must be a valid FQDN string.
> 
> https://github.com/kubernetes/apimachinery/blob/master/pkg/util/validation/validation_test.go#L53
> https://github.com/kubernetes/apimachinery/blob/master/pkg/util/validation/validation_test.go#L549

that is a valid name though for the context and how it's referred.

**Comment by awly** [comment]
@stevenGravy this is intentional: https://github.com/gravitational/teleport/blob/master/lib/services/server.go#L1002-L1006
Allowing special characters could introduce subtle directory traversal vulnerabilities in `tsh`. We could try to support this with some clever handling in `tsh`, but I don't want to add complexity unless there's a _good reason_.

Other than convenience, is there any other reason to support special characters?

**Comment by jon-can** [comment]
Kubeconfigs generated when using EKS have names like arn:aws:eks:us-east-2:4444:cluster/clusterExample. I had to edit my kubeconfig to get EKS working with Teleport. I imagine customers will run into this as well so we should either fix this or make a clear note in our EKS documentation.

**Comment by awly** [comment]
The kubeconfig for EKS is generated following https://docs.aws.amazon.com/eks/latest/userguide/create-kubeconfig.html.
This works on a local workstation or EC2 because of IAM auth. It shouldn't work anywhere outside of AWS, because it tries to dynamically fetch a token via an exec plugin.

I'm going to punt it to the next release, since it's an inconvenience but not a blocker.

To whomever picks this up: one option is to change how we store certs in `~/.tsh`, for example base64-encode the k8s cluster name for use as directory name. Note that there may be problems with OS filename length limits.
Another option is to have `kubernetes_service` escape the context names it reads from `kubeconfig` before registering them as k8s clusters in teleport.
A third option is to lean into https://github.com/gravitational/teleport/blob/master/examples/k8s-auth/get-kubeconfig.sh and have it do some escaping or take an explicit cluster name argument.
