### ISSUE TITLE
Splunk/HIDS compatible logging format

### ISSUE THREAD

**Issue by jaxxstorm** [gravitational/teleport#502]
Currently, the log messages are split into two files:

a JSON log file with events, and a bytes file which shows the terminal output.

When demoing the application to our security team, they loved the playback features. They were however interested in being able to incorporate all the session data into splunk/HIDS tooling, but the bytes file presents a problem, as it has no timestamp associated with each action.

How feasible is it to modify the output format of the bytes file to have support for some kind of timestamp, or even incorporate all of the output into the existing log?

**Comment by programmerq** [comment]
gravitational/teleport-plugins#326 added the ability to ship the session events associated with a session recording. The `print` event type has information about timing but doesn't include the actual corresponding bytes from the session recording.

Instead of attempting to parse the bytes from the session recording, a best practice is to enable enhanced session recording. That gathers more information than only looking at the bytes that appear on the screen. The event handler with session event forwarding will forward those events.

I think between the event handler and the enhanced session recording, this issue can be closed.
