### ISSUE TITLE
Run a command on a node through the API

### ISSUE THREAD

**Issue by Joerger** [gravitational/teleport#5024]
### Feature Request
Add API endpoint/capability to run commands on a node, in a similar way to os.Exec. 

### Motivation
Currently the API does not give access to some `tsh` features, such as using `tsh ssh` to run remote commands. This would be nice to have, if this is indeed something we want to support.

### Who's it for?
OSS User, Pro, Enterprise

**Comment by awly** [comment]
I'm skeptical about adding this into the API.
The assumption here seems to be that "you can do everything via the auth API".

IMO, the auth server API should be the "control plane" - managing cluster resources and handling authn/z.
After resources were configured and a client obtains appropriate credentials, they should switch to a different protocol appropriate for the action:
- SSH for running commands on nodes
- k8s REST API for talking to k8s clusters
- HTTP via web browser for talking to web apps
- appropriate wire protocol for DB access

Otherwise, we'll have to re-implement all the features of the above protocols in our auth API.

A better approach is to make using SSH easy:
- 1 function call to load credentials from `~/.tsh`
- 1 function call to get a Go SSH client from those credentials and a node address

**Comment by klizhentas** [comment]
I agree with Andrew, the api to run commands on the node is SSH. Auth server is not responsible for running actual commands
