### ISSUE TITLE
How do I cleanup old Kubernetes clusters?

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport#5229]
### Description

**What happened**:

I logged into an a Teleport cloud cluster and I still see a range of clusters that I've previously disconnected. 

```
$ tsh kube ls
Kube Cluster Name        Selected
------------------------ --------
asteroid-sun.teleport.sh *
do-teleport-cloud
gke-teleport-cloud
```

**What you expected to happen**:
Remove clusters or show them clusters as office from kube ls after they are removed, TTL can be reasonable but some of these have been offline for a month now.

**Comment by awly** [comment]
Kubernetes clusters should get cleaned up ~10min after their `kubernetes_service` goes offline.
The problem is that this TTL is specified by `kubernetes_service` itself (not the auth server or backend) and between 5.0.0-5.0.1 we didn't set that TTL. Your clusters are probably leftover from 5.0.0 instances.

To manually clean up:
- run `tctl get kube_service`
- for each old instance that references those old clusters, run `tctl rm kube_service/$UUID` with the UUID of the instance

We could add TTL defaulting on the auth server, or some automated cleanup logic for 5.0.0 `kubernetes_service` instances without TTL. But it doesn't feel worth it for the few early adopters that used 5.0.0 before 5.0.1.
WDYT?

**Comment by benarent** [comment]
Thanks for the explanation. 

You're right, there is no reason to make any code fixes for this for early adopters.  I've tried to use delete a cluster, but I'm running into a RPC error. Do you happen to know what resource I need to add to my role to delete kube_service? 

``
➜  ~ tctl rm kube_service/a16b34ca-1c01-46fe-ba7f-ee78d3c2c3a7
error: rpc error: code = PermissionDenied desc = access denied to perform action "delete" on "kube_service"
```

**Comment by awly** [comment]
Oh, you're doing it remotely.
It should be either `server/delete` or `kube_service/delete`
