### ISSUE TITLE
tctl nodes add 

### ISSUE THREAD

**Issue by vignesh-v-nutanix** [gravitational/teleport#5249]
### Description

**What happened**:
I ran tctl nodes add in the proxy.
copied the command and went to one of the nodes and pasted it.
the node gets added, but if i try to connect i get an error

**What you expected to happen**:
To log in to the shell

**How to reproduce it (as minimally and precisely as possible)**:

**error**: 
disconnected
failed connecting to node ip-172-31-38-97.us-east-2.compute.internal. dialing through a tunnel: no tunnel connection found: no node reverse tunnel for 93713410-a909-4af6-b48e-6d2d3d50b797.ip-172-31-44-55.us-east-2.compute.internal found, dialing directly: dial tcp 18.188.91.147:3022: i/o timeout

### Environment
- Teleport version (use `teleport version`): Teleport v5.0.1 git:v5.0.1-0-ge8b21a143 go1.15.5
- Tsh version (use `tsh version`): Teleport v5.1.0 git:v5.1.0-0-g46679fb34 go1.15.5
- OS (e.g. from `/etc/os-release`): CentOS Linux 7

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware): AWS
 

**Browser environment**

- Browser Version (for UI-related issues): Chrome
- Install tools:
- Others:

**Relevant Debug Logs If Applicable**

- `tsh --debug`
- `teleport --debug`

**Comment by stevenGravy** [comment]
hi @vignesh-v-nutanix , is the port 3022 open on that machine?  that looks to be the issue. If you can't open it then you should change from the 3025 port to the 3080 port so it opens a reverse proxy.

**Comment by vignesh-v-nutanix** [comment]
@stevenGravy 
sure, that solved!
Do you have recording of how you have setup kubernetes and elastic behind teleport. 
Just happened to see the teleport session on David's youtube channel.
`ERRO [AUTH]      Failed to register through auth server: invalid character '<' looking for beginning of value; f
`
i got the same error as David got when setting up kubernetes with teleport..specifically after the installation of the helm chart

**Comment by benarent** [comment]
@vignesh-v-nutanix  You shouldn't have to worry about this error message, we've since fixed it so it's less worrying. https://github.com/gravitational/teleport/issues/4663 

We don't a video of setting up Kubernetes but I would recommend using the info provided here https://goteleport.com/teleport/docs/kubernetes-access/#option-1-standalone-teleport-gateway-for-multiple-k8s-clusters 

I'm going to close this issue for now but please re-open or post any other question on our community. https://community.goteleport.com/ Thanks for using Teleport.

**Comment by vignesh-v-nutanix** [comment]
@benarent do i need to any workaround for this?
or just try it again?
