### ISSUE TITLE
Update teleport k8s helm charts to reflect the addition of kubernetes_service in 5.0+

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#5269]
## Summary
Logging issue to track the request for an updated helm chart example using kubernetes_service on teleport 5.0+ to complement the existing helm chart examples.

### Audience
kubernetes admins

### Location
Update the teleport/examples/chart/ documents to include a helm chart example for the new k8s service addition in 5.0+

**Comment by lord-kyron** [comment]
Hi @Aharic - I am Radoslav from DraftKings / SBTech.
Yes, this request was created by our request as we are trying to migrate our prod clusters to k8s. And since we are also going to upgrade from 4.4.6 to 5.1 we want to use the new feature of "kubernetes_service", but it seems it is still not available for the helm chart of teleport. I am aware of the small "kube agent" that of your clients are using, but in our case we prefer to use as less pods as possible in our clusters, so we are more keen on using the "traditional" way of connecting to many k8s clusters behind one teleport cluster!
We hope that this will be implemented soon!
Thanks!

**Comment by lord-kyron** [comment]
Still updates on this one?

**Comment by lord-kyron** [comment]
@Aharic I can see that the chart for single node standalone cluster was updated, however the chart for HA cluster is still not.
Please, update the full chart as we are unable to test/use it this way!

**Comment by Aharic** [comment]
Closing this one as upgrades were completed as requested. Going forward, however, the new [teleport-cluster](https://github.com/gravitational/teleport/tree/master/examples/chart/teleport-cluster) chart should be used as old charts (w/ exception of kube-agent charts) are being deprecated.

**Comment by lord-kyron** [comment]
@Aharic as far as I understand this will deprecate the "teleport" cluater chart also but it seems to me, that it ia the one providing the possibility to have more than one proxy and more than one auth server. If the only chart left is the single cluster one, how will we be able to achieve this setup?
