### ISSUE TITLE
Duplicate contexts in kubeconfig after tsh login

### ISSUE THREAD

**Issue by HagaiBarel** [gravitational/teleport#5396]
### Description

**What happened**:

After running `tsh login` there are 2 entries in the `kubeconfig` file pointing to the same cluster but with different names. It seems that setting `kube_service.kube_cluster_name` isn't fully respected.

**What you expected to happen**:

To have just one entry containing the cluster name

**How to reproduce it (as minimally and precisely as possible)**:

using the following config:

```yaml
...
auth_service:
  cluster_name: teleport-staging

kubernetes_service:
  enabled: yes
  listen_addr: 0.0.0.0:3027
  kube_cluster_name: staging
```

After running `tsh login`, I'm getting the following:

```shell
$ tsh status

> Profile URL:        https://teleport-staging.example.com:3080
  Logged in as:       HagaiBarel
  Cluster:            teleport-staging
  Roles:              admin*
  Logins:             root, nobody
  Kubernetes:         enabled
  Kubernetes cluster: "teleport-staging"
  Kubernetes groups:  system:masters
  Valid until:        2021-01-26 02:52:06 +0200 IST [valid for 12h0m0s]
  Extensions:         permit-agent-forwarding, permit-port-forwarding, permit-pty

* RBAC is only available in Teleport Enterprise
  https://gravitational.com/teleport/docs/enterprise

$ kubectl config get-contexts

teleport-staging-staging            teleport-staging                     teleport-staging-staging             
teleport-staging-teleport-staging   teleport-staging                     teleport-staging-teleport-staging
```

I'd expect to see just the `teleport-staging-staging` entry in the `kubeconfig` file

### Environment
- Teleport version (use `teleport version`): `Teleport v5.1.0 git:v5.1.0-0-g46679fb34 go1.15.5`
- Tsh version (use `tsh version`): `Teleport v5.1.0 git:v5.1.0-0-g46679fb34 go1.15.5`
- OS (e.g. from `/etc/os-release`): Ubuntu 20.10

- Where are you running Teleport? (e.g. AWS, GCP, Dedicated Hardware):
Kubernetes self hosted on AWS

**Comment by awly** [comment]
This is a compatibility hack for pre-5.0 setups.

Before 5.0, teleport didn't have a concept of k8s clusters natively.
Instead, you had to configure one k8s cluster per teleport cluster, and the relation was implicit.
In order to keep old setups and workflows working, we generate a "fake" k8s cluster named after your teleport cluster name (`teleport-staging`), and select it by default on `tsl login`. You can also see it in `tsh kube ls`

Until all users migrate to `kubernetes_service`, we can't break that behavior. And it's going to be very hard to convince all users to migrate, so I don't expect this hack to go away any time soon :(

**Comment by awly** [comment]
Note: all future `kubernetes_service` members to your teleport cluster won't generate any more unnecessary contexts. It's only one per teleport cluster.

**Comment by HagaiBarel** [comment]
Thanks @awly for the explanation, much appreciated
