### ISSUE TITLE
Session Recordings to Remain on Node

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport#5517]
### Feature Request
Requesting for an option to have session recordings to be stored on the node they were recorded from rather than the Auth server when setting storage to dir.

### Motivation
There are times when ssh nodes are not own and host sensitive data, there is a preference to leave all data on that node and not extract unless absolutely necessary. 

### Who's it for?
OSS User, Pro, Enterprise, Cloud

**Comment by klizhentas** [comment]
I think it would be much cooler if we allowed the node to encrypt the data, but don't have the decryption key. Then it would not make any difference if auth server would have the recording, only the party with the decryption key would be able to view it. This would be stronger guarantee, because already encrypted sessions will not be readable even on the node. @yjperez would that solve customer's problem?

**Comment by yjperez** [comment]
@klizhentas I will follow up with the CSM (@christinahaidemenos) on this

**Comment by yjperez** [comment]
@klizhentas the CS team is meeting with the customer in two weeks and will get feedback.
