### ISSUE TITLE
standalone SSH/Proxy mode

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#554]
## Description

When loosing connection to the auth server, it would be very helpful if SSH Node and SSH Proxy will continue functioning using local copy of the data.

Right now every auth attempt causes SSH server to connect to auth server:

### SSH Node:

https://github.com/gravitational/teleport/blob/master/lib/srv/sshserver.go#L369

I suggest instead, here use local backend copy and sync this data from auth server.

### SSH Proxy

https://github.com/gravitational/teleport/blob/master/lib/reversetunnel/agentpool.go#L91

#### Implementation proposal

The fastest way would be to re-use the local backend implementation of the services and swap 

https://github.com/gravitational/teleport/blob/master/lib/services/local/users.go

### Desired behavior

1. Stop auth servers
2. Still should be able to login into the nodes.
3. Reverse tunnels should be up

**Comment by kontsevoy** [comment]
After two weeks at trying to implement this, here's the verdict:

1. Yes, it is possible to continue running all proxies and nodes if the auth is down. 
2. It is not possible to survive a cluster reboot if all auth nodes are down, because the auth keeps too much state and duplicating it on the clients side is very, very costly. (this is not true for nodes, but definitely true for proxies)

There will be a PR addressing this issue with more details.
