### ISSUE TITLE
Upload kubectl exec sessions sooner than grace period if a pod dies

### ISSUE THREAD

**Issue by jon-can** [gravitational/teleport#5624]
### Description

**What happened**:
When I do kubectl exec the session is recorded as long as I close the session by typing exit or ctrl+D, but if the pod unexpectedly dies (which is by design in k8s) there is no recording until after the 12 hour grace period.

**What you expected to happen**:
Teleport should be able to detect this and upload the recorded session sooner.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
You can just do kubectl exec and send kill -9 to the process. The pod will die and in the audit logs you will only see session started.

### Server Details
- Teleport version (run `teleport version`): 5.1.2

### Which platform(s)
- [x] Teleport Open Source
- [ ] Teleport Cloud
- [x] Teleport Enterprise
- [ ] Other

### Which component(s)
- [ ] Server Access
- [x] Kubernetes Access
- [ ] Application Access
- [ ] Database Access
- [ ] CLI Clients
- [ ] Web Clients
- [ ] Other

**Comment by jon-can** [comment]
Even after the 12 hour grace period the pod recordings are not being uploaded.

**Comment by awly** [comment]
@jon-can which pod is getting killed?
The teleport pod (auth/proxy/other?) or a different target pod unrelated to teleport?

**Comment by jon-can** [comment]
A target pod unrelated to Teleport.

**Comment by awly** [comment]
The problem seems to be that we abort the exec handler when `executor.Stream` returns an error (when the remote pod dies for example): https://github.com/gravitational/teleport/blob/91dab1dcf343a38f26c5d1a3765f09812c1af754/lib/kube/proxy/forwarder.go#L837-L955

We should emit audit events when an error is returned at any point in the handler.
We should also review other k8s handler code for similar issues.
