### ISSUE TITLE
Improve error message when tsh tries to connect to an offline proxy

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#5736]
### What
When using `tsh` to connect to a Teleport proxy that isn't yet online (behind an HTTP load balancer or similar) you get a confusing error message:

```
$ tsh --proxy=asdf.example.com:443 login
error: invalid character '<' looking for beginning of value
```

This is similar to https://github.com/gravitational/teleport/issues/4663

### How
Make the error and the reason for it a little more obvious - i.e. point out that there's no proxy listening or that the connection couldn't be completed.

### Why
Confusion for users when using `tsh`.

### Workaround
None known currently.

**Comment by awly** [comment]
This is probably because the load balancer returns a generic HTTP response (Bad Gateway or Not Found) with HTML content. Our client tries to unmarshal that as JSON and produces the above message.

Most likely, the fix is to check the HTTP status code before unmarshaling.
@webvictim do you have the exact repro steps? Is it just setting up an AWS load balancer without a running proxy behind it?

**Comment by zmb3** [comment]
@Tener recently fixed this.
