### ISSUE TITLE
Validate GRPC API resources

### ISSUE THREAD

**Issue by gzigzigzeo** [gravitational/teleport#5811]
### What

I tried to create user via API using completely random values. I set version to v5, kind and subkind to some weird strings, just to see what happens. It creates user successfully, but when I try to remove it via `tctl users rm`, Teleport reports that “user resource version v5 is not supported”. So, my teleport instance is completely unusable now. 

Here are the logs and terraform definition: https://gist.github.com/gzigzigzeo/60da7a7b34ffe9a3e8857b664fccb862

### How

There's `Check()` method which does some basic validations on newly created objects. The problem is that this method is called in constructor, before I set values from Terraform definition file, so, my invalid values pass through. Plus, it does not check values themselves. For example, it checks that version field is not blank, but does not check if it is valid.

I propose to:

* Implement detailed validations in `Check()` method.
* Call `Check()` in the corresponding GRPCServer methods before object gets added to the database and return error if it is invalid. 

I've spotted that there is also `services.ValidateRole` method, so, possibly we may update it and implement corresponding method for Users, ProvisionTokens and their underlying structures (Metadata, Spec, etc).

### Why

Terraform user might make a mistake in his resource definition, we must be protected from the consequences.

**Comment by Joerger** [comment]
@russjones I know we've talked about this a bit before, is there a reason for us to let the client set `Version`, `Kind`, and other similar values freely? or should a `UserV2` always have `Version="v2"` and `Kind='user'`? If so we should add these checks to `Check() | CheckAndSetDefaults()`.

Otherwise I made this [PR](https://github.com/gravitational/teleport/pull/5768) which handles invalid versions in the marshalers since that has the potential to break the teleport instance.
