### ISSUE TITLE
Providing a way for customers to partially configure the cluster

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#5857]
### What

For cloud customers who would wish to use sync recording mode, there should be a configuration resource that allows them to set this parameter.

Currently we only have auth preference as the resource. We have to be careful not to allow to change all parameters for cluster configuration (like cluster name, etc), so making this resource visible should go with caution.

**Comment by andrejtokarcik** [comment]
At this time, the only needed field is apparently `session_recording`. This is not the only restriction however: the set of `session_recording` values available for dynamic configuration also has to be restricted, the only allowed values should be `off`, `node` and `node-sync` (setting `proxy` or `proxy-sync` in this way shouldn't be possible).

My proposal is therefore simple:
1. Create a new resource `SessionRecordingAtNode` that can be handled by all the ordinary `tctl` operations. It'd have a single `spec` field, `mode`, with two possible values: `node` and `node-sync`.
2. Whenever `SessionRecordingAtNode` is attempted to be created (*OR* loaded upon auth server startup) it is verified that the usual `session_recording` option (i.e. the field `SessionRecording` of the `ClusterConfig` resource) is set to `off`. If this holds, the resource is created together and the assignment ```ClusterConfig.SessionRecording = SessionRecordingAtNode.Mode``` is performed. If `session_recording` is not `off`, the `SessionRecordingAtNode` resource is rejected (*OR* deleted). 
3. To go back from `node` or `node-sync` to `off`, users would use the [proposed `tctl rm` semantics](https://github.com/gravitational/teleport/pull/5673).

Since this resource has no config-file counterpart, no `origin`-related logic from [RFD 16](https://github.com/gravitational/teleport/blob/master/rfd/0016-dynamic-configuration.md#implementation) comes into play here.

We would proceed in a similar way with any other fields/resources that cannot be fully exposed via `tctl`.

**Comment by andrejtokarcik** [comment]
If it's overly cumbersome to add a new resource because of all the backend/caching plumbing needed, it should be sufficient work on the fly with a thin "user-facing" resource that would actually translate to a `ClusterConfig` resource labelled with `patched: SessionRecordingAtNode` or some such.

**Comment by awly** [comment]
I'm 90% sure we'll end up exposing other `ClusterConfig` fields in the future (even though we prefer not to).
An API resource per field (with CRUD endpoints, caching and authz logic, etc) would get noisy quickly.

I'd recommend either a new `ClusterConfigOverride` resource, which is a subset of `ClusterConfig`.
Or just adding allowlist-based validation on `UpdateClusterConfig` RPC, but that may be less intuitive for the caller.

**Comment by andrejtokarcik** [comment]
The desired functionality is ready for 7.0, implemented in the following commits:
* 1d17aea01db583d88ab5531b1274621a400b01df
* ad00c6c789bdac9b04403889d7ed426242205d64
* 555695dfdd88f3e8222d52e5739b45775c0c6d12
* 833da36de972f0b5f4135e009d05ea79069e69b7
* 3ca21aca9a9a1d4235cdc331ff10b5749965e10e
* a92dcc3df4df1f8e204bf5de4cfb0ee2e2a87704
* 2747cc75bfafbc1981af9b4059e1afee69f4ad64
* 9410346b8d0dae04288847be5c7bf90b95fed4bd
* 3d22eaac0ece85ddb75c4465c535408b5142f412
* d63d144e8e0202cd373205402072572ca3810b42

For the most part, these also implement [RFD 28 - Cluster configuration related resources](https://github.com/gravitational/teleport/blob/master/rfd/0028-cluster-config-resources.md): the only missing piece is `PAMConfig`. That resource needs to be introduced (by adapting the code from https://github.com/gravitational/teleport/pull/6087) and then made dynamically configurable as demonstrated e.g. in 9410346b8d0dae04288847be5c7bf90b95fed4bd.
