### ISSUE TITLE
MFA management polish

### ISSUE THREAD

**Issue by awly** [gravitational/teleport#5878]
Remaining work to support multiple MFA devices per user:

- [x] web UI login page with multi-MFA support
![image](https://user-images.githubusercontent.com/1146263/110159280-59839600-7d9f-11eb-895a-0847bbd130f7.png)
![image(1)](https://user-images.githubusercontent.com/1146263/110159285-5be5f000-7d9f-11eb-9fcf-e87f66372bfc.png)
- [x] unhide CLI commands
- [x] docs
- [x] U2F attestation cert validation
- [x] graphical QR code during CLI OTP registration
- [x] CLI prompt cancellation

**Comment by mdeboer** [comment]
Looking at for example Github, they use a two-stage process. First the user enters his credentials, once they validated a user is presented a screen which defaults to U2F (if configured), otherwise OTP. If the user has no access to their U2F token, the user can cancel the U2F request and click on the option to use OTP instead (or any other supported method).

To me this seems a little more secure and user friendly. I have also seen many other services besides Github use this process.

**Comment by awly** [comment]
@mdeboer thanks for the suggestion.
We might restructure our API to work that way (separate user/pass and 2FA steps) in the future.

Right now we need some simple UI updates to fit with the current API (combined user/pass/2FA validation in one request) to release Teleport 6.1 in a few weeks.

**Comment by awly** [comment]
Remaining items are nice-to-have but don't block 6.1
