### ISSUE TITLE
Some GUI database clients require DER private key

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#6116]
### What

[DBeaver](https://dbeaver.io/) does not understand the private key in PEM format and produces the following error when trying to configure it with Teleport secrets:

```
Could not read SSL key file /path/to/.tsh/keys/private-key
  extra data given to DerValue constructor
```

The following issue explains the reason and shows a workaround:

https://github.com/dbeaver/dbeaver/issues/2859

DBeaver expects the private key to be in a DER format. Converting Teleport's PEM key to DER format fixes the issue.

### How

Can we put a DER formatted key alongside PEM key in .tsh?

### Why

To support GUI database clients that don't understand PEM keys.

### Workaround

Convert PEM to DER like shown in the above ticket:

```
openssl pkcs8 -topk8 -inform PEM -outform DER -in postgresql.key -out postgresql.pk8
```

**Comment by webvictim** [comment]
@r0mant Is it possible that we'll implement this from the `tsh db login` side with a flag to use DER-formatted private keys? At the moment people need to re-run the `openssl` command every time their cert expires which is awkward.

**Comment by gabrielbiasi** [comment]
My coleagues uses DBeaver a lot and we cannot support them at the moment because of this anoyning bug in DBeaver.
Having a extra option, like `tsh db login my-db --format der` would be awesome!!

**Comment by r0mant** [comment]
Yes I agree we should do it. Let me see if we can schedule it sometime in Q1 after 9.0 release.

**Comment by gabrielcorado** [comment]
@r0mant @smallinsky Do you think we can use the [`tsh proxy db --tunnel`](https://github.com/gravitational/teleport/pull/11720) to solve this issue? Using the proxy would not require users to set SSL configuration on DBeaver. I can write a guide on setting up this like [the one we have for SQL Server](https://goteleport.com/docs/database-access/guides/gui-clients/#sql-server-dbeaver).

I'm proposing this as an alternative to adding a new flag to `tsh db login` because the private key is not per database, and the UX might be confusing. Since users might log in to multiple databases, we would need to keep multiple copies of this new file (with the same contents) for each database. Alternatively, we could have a single key and keep it even after a `tsh db logout` to not impact other databases.

If you have any suggestions, let me know. Thanks.

**Comment by r0mant** [comment]
@gabrielcorado Good thinking. Yes, I think it's a better way, I was planning to update our GUI client docs to switch to the tunnel proxy mode anyway and make it preferred method cause it simplifies UX for external clients a lot.
