### ISSUE TITLE
DynamoDB build

### ISSUE THREAD

**Issue by jeremyd** [gravitational/teleport#632]
Would it be possible to include DynamoDB support into an official build?  It's hard to maintain our own builds when all we need is that DynamoDB flag enabled...  Even if it was a separate build I'd be ok with that.

**Comment by kontsevoy** [comment]
@jeremyd we cannot include so much 3rd party code into mainline Teleport because of security concerns. The core Teleport (and all of its dependencies) are frequently subject to security audits, and by including AWS dependencies (and their dependencies) and so on we'll face a dramatic increase of surface area.

Instead, let me ask you this: why is it hard for you guys to set an environment variable before calling make? Controlling the build process via environment variables is the oldest and simplest trick in the book. Is there something on your end that makes it hard?

**Comment by jeremyd** [comment]
I was just preferring to use an official release instead of doing any
building. If I end up building then I have to do more maintenance and keep
a build environment updated. If I can just use the release binary this is a
lot less effort.  Since you already have a good build and release process I
was wondering if it was easy to spin an additional one for dynamodb
support.  If it was just go it'd be easier to build but it seems I also
need to build npm including phantomjs.  Thanks for the explanation, I have
a build working in alpine and I will use that for now.  I can close this
out if building additional isn't worth it.

**Comment by kontsevoy** [comment]
Gotcha. We'll look into simplifying it. Perhaps publishing builds for different plugins enabled. Also going to look into using plugins via dynamic libraries `.so`

**Comment by kontsevoy** [comment]
@jeremyd Suggestion: 

Take a look at `build.assets/Makefile`. This is what we're actually using internally. It uses Docker-based build environment to produce Teleport builds. 

You can create Docker-based build for Dynamo. This would simplify maintenance of Teleport builds dramatically because Docker is the only dependency you'd need in this case.

**Comment by jeremyd** [comment]
I created this if anyone else needs some build help.
https://github.com/gravitational/teleport/pull/643
