### ISSUE TITLE
Merging DynmoDB into mainline Teleport

### ISSUE THREAD

**Issue by kontsevoy** [gravitational/teleport#672]
@jeremyd @apestel We want to merge DynamoDB backend into mainline Teleport. When we tried, we encountered a number of issues. Do you mind helping out a bit (I am assuming you have more DynamoDB expertise than we do).

List of changes we've made can be seen in this PR: #671 

## Changes we're making:

* Vendoring AWS SDK dependency into Teleport repository
* Updating build/release scripts to always build DynamoDB backend

## We need help

@jeremyd @apestel this is where we'd like to ask for your help. As you can see in #671, we had to rename "Key" column/attribute to "FullPath" because "Key" cannot be used as a column name in DynamoDB because it is a [reserved keyword](http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/ReservedWords.html) and some queries refuse to run.

We need to write a migration function (and you are probably the only user who'll need to migrate at this point) which migrates to a new schema. I suspect the proper implementation would:
- Create a new table with a temporary/unique name and with a new schema 
- Copy every value from the legacy table to the new table replacing "Key" with "FullPath" while keeping other values intact.
- Dropping the old table.
- Renaming the new table to the original name.

Thoughts?

**Comment by jeremyd** [comment]
Hey, yeah I was trying dynamodb but I realized it was too buggy for
production use so I switched to etcd. Was running into some weird panics
just during normal usage (even with dynamic compile) that don't happen with
etcd.

**Comment by apestel** [comment]
@jeremyd most of the problem I had with DynamoDB implementation was when I reached the provisioned limit (read / write) of DynamoDB.
@kontsevoy I'm gonna have a look at your PR as I wish to test the new RBAC feature coming in 1.5. I will let you know ASAP.

**Comment by kontsevoy** [comment]
@apestel thanks, but please be careful! the master branch builds are not recommended to run on production data! In fact, it's safe to assume you can ruin your existing deployments by running anything else but official releases.

**Comment by kontsevoy** [comment]
@apestel perhaps we should move those limits into the configuration and use different defaults? Right now there are 5/5 whatever that means.

**Comment by klizhentas** [comment]
@apestel can you tell us more about your cluster setup and writes/sec?

**Comment by apestel** [comment]
@kontsevoy I'm still using teleport beside our current workflow to manage SSH authentication, no worries if I break something. Anyway I will backup to S3 my table before doing the migration.
5 (reads per seconds)/5 (writes per second) is the free tier for DynamoDB. Users won't be charged if they are below those threshold. It's definitely not enough for production use. Each host will add more requests to DynamoDB (ie: in order to refresh TTL) same apply if you add more users.
We should had gracefull handler in case DynamoDB does not return the attended value (if we reach current provisioned threshold). This edge case should be managed outside of the backend implementation aswell. There is some script available that manage some kind of autoscale for DynamoDB. Teleport's user might use this if they don't want to have a close look on those metrics.
@klizhentas I have an ELB (that I should replace by ALB) in front of two instances with Teleport Auth role. the folder /var/lib/teleport is shared using EFS (NFS managed by AWS). They do have the same host_uuid and log/sessions can be seen on either nodes. Obviously the DynamoDB table is the backend to store users and hosts. I should also create an autoscaling group (2:2) for Auth likewise I should not have to worry in case of an instance going down.

**Comment by kontsevoy** [comment]
Ah... Looks like reads/writes should be in a config then... Re-opening this.
@klizhentas more weight towards my proposal on stateless membership bookeeping. this way teleport will be perfectly usable on free Dynamo

**Comment by apestel** [comment]
@kontsevoy you can change read/write at anytime you want directly in AWS console. You can do this multiple times per day. IMHO you should stick to the default and then let the user adjust this setting depending on his needs (size of the infrastructure and number of users).

**Comment by kontsevoy** [comment]
@apestel agreed. Closing it again. [will update the docs]
