### ISSUE TITLE
Send Teleport roles with every app access request

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#6821]
### What

Send full Teleport user's role specs in some encoded format to the target application with each HTTP request.

### How

Couple quick ideas, needs more research on the best way:

* Post them in HTTP headers. Will prob. need some signing?
* Encode them in JWT token.

### Why

To allow applications behind app access easier integrate with Teleport's RBAC. This way they would only need to use our API module to parse the role. Currently they have to go and fetch roles via API.

**Comment by klizhentas** [comment]
@r0mant @alex-kovoy @justinas 

this should not take very long if we keep implementation to the minimum:

1. Do not send the full role spec list in the header, but limit it to the user-defined resources.
2. Always send compiled and rendered role set with user-defined resources in JWT

This means if application developer has defined their resources, e.g. 

role-a:
allow:
   sales/app: [read, create, delete]

role-b:
deny: 
    sales/app: [read, delete]

AAP should detect that, take the resulting set, compile it, and send only sales/app resources.

AAP can easily identify if roles have special user-defined resources if they are using namespaced notation like sales/

This will make the code on the other side trivial as well, because there will be no need for a complex role checker, could be a lightweight API wrapper:

get(resource).allow and not get(resource).deny

All templating, privilege escalation, etc will be handled by Teleport

**Comment by r0mant** [comment]
Makes sense to me, looks like we already allow adding arbitrary resource names in our roles' "rules" section so the only pieces missing are:

* Determining what the role resource that gets sent to the app actually looks like. Should probably still be versioned, so maybe a stripped down version of our regular role resource (with only app_labels and custom resource rules) will work.
* Encoding these roles in the JWT header alongside other claims we already send.
* Should probably also have some sort of detection if roles changed and regenerate the token.

**Comment by MarkCupitt** [comment]
Very interested in this functionality so we can apply consistent RBAC across entire application. 

JWT will work, if it has user name and roles, another option would be to provide as querystring appended to the http request, not as ideal, but would work is nome scenarios

**Comment by klizhentas** [comment]
this is already implemented https://github.com/gravitational/teleport/blob/b4e1f39742f04561ce9be9afef0c651604ebba29/lib/auth/sessions.go#L236

**Comment by klizhentas** [comment]
@justinas we should not send RBAC rules in JWT, folks can use our API to pull those if necessary.

**Comment by MarkCupitt** [comment]
Hi thanks for the response, we are happy with the list of roles, not the definition, we want ti use them to match up with RBAC in applications, so the definitions and rules are not required .. 

We can assume that if the request gets to the application, the user is authorized and we can use the list of roles supplied to determine further restrictions from an app standpoint. We will likely add teleport roles targeted specifically at the application and not actually use them in teleport RBAC.

having said that, it just occurred to me that to keep things tidy, you may want to consider adding `ApplicationRoles` to the app and user specs, that are app specific to further with Application RBAC
