### ISSUE TITLE
Update G Suite SSO Documentation

### ISSUE THREAD

**Issue by yjperez** [gravitational/teleport#6923]
## Details
The G Suite setup has changed on the Google side.

- Need to update the URL on [doc](https://goteleport.com/docs/enterprise/sso/ssh-google-workspace/#configure-g-suite ) to add link to Credential Page https://console.cloud.google.com/apis/credentials
- "Manage API Client Access" has moved from Security -> Settings to “Security -> API Controls ->  Manage Domain Wide Delagation” (link: https://admin.google.com/ac/owl/domainwidedelegation)
- Swap the order of the `Note` and `Warning` block located in [Manage API Scopes](https://goteleport.com/docs/enterprise/sso/ssh-google-workspace/#manage-api-scopes)
- Update screenshots

### Category

- Improve Existing
- Remove Outdated

**Comment by stevenGravy** [comment]
@yjperez did you want google workspace sso backported to a specific version?  This is the current version that reflects google workspace. https://goteleport.com/docs/enterprise/sso/ssh-google-workspace/

**Comment by inertial-frame** [comment]
The URL has been updated: https://github.com/gravitational/teleport/pull/7070

**Comment by ptgott** [comment]
@yjperez We've done a lot of work on this guide since this issue was opened. Does this issue still apply? Thanks!

**Comment by ptgott** [comment]
Since we've done a lot of work on this guide since this issue was opened ([GitHub history](https://github.com/gravitational/teleport/commits/91c89b612680f96d662bfe2c7a460e9258db3fa0/docs/pages/enterprise/sso/google-workspace.mdx?browsing_rename_history=true&new_path=docs/pages/access-controls/sso/google-workspace.mdx&original_branch=master)), I am going to close this issue. If there are any lingering issues, would you mind re-opening the issue and explaining them? Thanks!
