### ISSUE TITLE
tsh FOSS client should warn when it talks to an enterprise server (or there should be no enterprise client)

### ISSUE THREAD

**Issue by highb** [gravitational/teleport#6952]
### What
What would you like Teleport to do differently?

When tsh FOSS connects to an enterprise server, it should emit some sort of recommendation that the user install the enterprise version instead.

### How
How would you implement this?

Server-side API should emit a Enterprise vs FOSS flag, client-side should check that its flag matches. Or, even better, only ship one `tsh` binary that works regardless of Enterprise or FOSS.

### Why
Why do you need this?

Users are my company are definitely going to install with `brew install teleport` and then we're going to have to deal with support tickets that tell them to re-install the enterprise version.

### Workaround
If a workaround exists, please include it.

Re-install the enterprise client.

**Comment by webvictim** [comment]
@highb There's only one version of `tsh` for both OSS and Enterprise. Did you mean `tctl` instead?

**Comment by highb** [comment]
Ah, when I was chatting with support they indicated that we need to download the ent version of tsh. If that isn't the case then this can be closed.

**Comment by webvictim** [comment]
Yep, there's only one version of `tsh` for both OSS and Enterprise so `tsh` installed via `brew` should work OK against any Teleport cluster.

FWIW, I would recommend that end-users install the Teleport-provided signed `tsh` pkg for Mac (https://get.gravitational.com/tsh-6.2.0.pkg) from our [downloads page](https://goteleport.com/teleport/download) rather than using `brew`, as the package is smaller and it offers greater control of the version used.
