### ISSUE TITLE
Expand Installation and Setup Section

### ISSUE THREAD

**Issue by inertial-frame** [gravitational/teleport#7229]
## Details

Some of the setup and config steps for CLI tools can be tricky the first time or two. We should:

1. Add common operations into includes or articles and out of third-party sites alone (but still link to them - if we're totally dependent on external sites it breaks the flow and can cause 404's, but it's also nice to drive traffic as a courtesy).
2. Some of these are documented here temporarily: https://docs.google.com/document/d/1C8CT-JSFpRcxPxfP1zX4a-LwTb5NKlWyG0mk4f6q5MI/edit#

Examples:

1. Get a `PEM`
2. Configure `eksctl` and IAM roles.
3. Opening ports.
4. Domain Names and Subdomain mappings.

These should be fairly brief (enough so that someone can copy-paste to get through them) and we can link to other sites and resources too. We should avoid duplication of efforts.

This will be part of the refactor layout: https://github.com/gravitational/teleport/pull/7039 for the Setup Section as we refactor, regroup, and move a lot of subsections.

This should also be well-factored so that key operations are in include format, we can inject these where we need to but also maintain a "main page/source of truth" for these.

1. One way of doing this: (1) includes are very terse, (2) setup articles have further explanation and links, (3) links are to third-party websites (documentation, reference docs, blogs) as needed. So, readers can choose the level of depth that they need.
2. Another approach is to use some kind of UI/UX modal to help shape the experience. Users could drop-down the modal for more info (so the include contains the full content but is wrapped in the UI/UX drop-down). Here, there's total reuse but the Setup Guides lack the UI/UX drop-downs.

### Category

- New Feature
- Improve Existing
- Remove Outdated

**Comment by inertial-frame** [comment]
https://github.com/gravitational/teleport/pull/7340 addresses some of these.

**Comment by ptgott** [comment]
As of now, this issue is pretty difficult to act on, since we would need to analyze all of our docs pages for opportunities to create includes. (As of now, there are 176 docs pages in `master` per `find ./docs/pages -name "*.mdx" | wc -l`.) I think it would make more sense to define includes in the course of responding to another GitHub issue so the scope of the work is more manageable. If there is an opportunity to reuse content across a batch of pages, we can create a separate issue listing those pages so there can be discussion around implementation details. This approach would also make it easier to match PRs with issues so we don't lose track of progress.
