### ISSUE TITLE
AWS node lifecycle issues

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport#7263]
### Description

During rolling blue/green deploys, instance IP could be reused and then node can not join, because cache does not expire until 24 hours. Users had to write the script to remove nodes from the cache.

**Comment by fspmarshall** [comment]
Proposal:  Make the node routing strategy configurable and add a "most recent" option which always routes to the node with the most recent heartbeat.  Keep the current behavior of erring on ambiguous targets as default in order to prevent silently routing to the incorrect node when "most recent" behavior is not intended (better security and reduced chance of user error).

Est. time to implement: 2 days.

Additional improvement:  Make the default behavior of rejecting ambiguities a little less strict.  Instead of relying on resource expiration to prune offline nodes, decide on a specific number of missed heartbeats that will remove the node from consideration (should definitely be more than 1, as we don't want network instability to result in silent changes to routing behavior, but a 24 hour wait is definitely excessive).

**Comment by russjones** [comment]
@rosstimothy @fspmarshall I think this was resolved in https://github.com/gravitational/teleport/pull/8567 right? If so, can we close it?

**Comment by fspmarshall** [comment]
@russjones yeah, should be resolved.
