### ISSUE TITLE
Feature: pam integration?

### ISSUE THREAD

**Issue by Kellel** [gravitational/teleport#742]
## Initial Comment

Present motd information on login similar to OpenSSH 
https://www.ietf.org/rfc/rfc4252.txt  Section 5.4

## Proposal

Teleport is going to (optionally) use PAM to create user sessions. This will enable the full pipeline of PAM-driven session customization, which will give us access to all PAM plugins, including [motd](https://linux.die.net/man/8/pam_motd)

**Comment by kontsevoy** [comment]
@Kellel OpenSSH is most distros is actually configured to integrate with pam and it's pam who's displaying motd-like prompt. 

Frankly we feel this will only add unneeded complexity because Teleport performs authentication on a cluster-level, i.e. individual nodes can be as dumb as they come (for example people use Teleport to SSH into docker containers randomly flying around).

The utility of pam is somewhat obsolete in a clustered environment, where user identity is stored elsewhere. But if someone is willing to look into _lightweight_ integration with pam, we're open to accept a decent PR. :-)

I'll mark it as "help wanted".

**Comment by eiginn** [comment]
One use case we have for using pam is assigning an "auid" that is processes inherited via pam_loginuid.so and we capture this is auditd logs. Allows users to sudo to root while maintaining a tail.

**Comment by russjones** [comment]
Implemented in https://github.com/gravitational/teleport/issues/1766.
