### ISSUE TITLE
Verify tsh.exe works with VSCode on Windows.

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#7444]
Verify that `tsh.exe` works with VSCode on Windows and write documentation on how to integrate with VSCode.

**Comment by timothyb89** [comment]
I've begun looking at this. First off, the upcoming `tsh ssh` support for Windows (https://github.com/gravitational/teleport/pull/7790) works fine in VSCode's builtin terminal. Additionally, with some SSH config tweaks, recent versions of Windows can use VSCode's Remote Development (SSH) plugin to attach to a remote Teleport node. On my Windows 10 20H2 system (1809+ should be supported), I installed Microsoft's official OpenSSH client [per their documentation](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_install_firstuse) then created a config file for my user at `%HOME%/.ssh/config` with the following content:

```
#
# Begin generated Teleport configuration for proxy.example.com:3080 from `tsh config`
#

# Common flags for all proxy.example.com hosts
Host *.proxy.example.com proxy.example.com
    UserKnownHostsFile "C:\Users\Tim\.tsh\known_hosts"
    IdentityFile "C:\Users\Tim\.tsh\keys\proxy.example.com\tim"
    CertificateFile "C:\Users\Tim\.tsh\keys\proxy.example.com\tim-ssh\proxy.example.com-cert.pub"

# Flags for all proxy.example.com hosts except the proxy
Host *.proxy.example.com !proxy.example.com
    Port 3022
    ProxyCommand C:\Windows\System32\OpenSSH\ssh.exe -p 3023 proxy.example.com -s proxy:%h:%p

# End generated Teleport configuration
```

(Note that hostnames and paths will vary per user.)

This is adapted from the existing `tsh config` output and I'd like to extend `tsh config` to generate this output automatically for Windows clients. Users can paste the generated config into their SSH config file, run `tsh login`, and then connect to the remote node through VSCode's interface.

I'll note that this includes `IdentityFile` and `CertificateFile` in the SSH configuration. We don't require this on UNIX since we can generally assume an ssh-agent is available. Microsoft's OpenSSH client [does support `ssh-agent`](https://docs.microsoft.com/en-us/windows-server/administration/openssh/openssh_keymanagement#user-key-generation) but it is not enabled by default so I think it's safer to assume it won't be available.

**Comment by russjones** [comment]
> I'll note that this includes IdentityFile and CertificateFile in the SSH configuration. We don't require this on UNIX since we can generally assume an ssh-agent is available. Microsoft's OpenSSH client does support ssh-agent but it is not enabled by default so I think it's safer to assume it won't be available.

This is a good point, in-fact I think this has been a source of problems for us on Windows, but you might want to look in GitHub history for the other `tsh.exe` issues to verify.

**Comment by timothyb89** [comment]
We've got a new guide for using VS Code with Teleport (building on top of new `tsh config` support on Windows): https://goteleport.com/docs/ver/8.0/server-access/guides/vscode/
