### ISSUE TITLE
Stale node TTL with in-memory cache

### ISSUE THREAD

**Issue by JonGilmore** [gravitational/teleport#7486]
### Description

After the proxy/auth cluster has been booted for a little while, stale nodes are reported when you run `tsh ls`. These nodes do not show up in dynamo, which leads us to believe it's an in-memory cache cleanup issue. When we deploy new auth/proxy clusters (for example, when we bump versions), the stale nodes go away.

**What happened**:
nodes aren't properly TTL'ed

**What you expected to happen**:
old nodes that have been recycled (as part of ASGs) should not show up when we run a `tsh ls`

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. boot proxy/auth cluster
2. boot ~8-10k teleport nodes
3. continually deploy those 8-10k nodes and observe the issue

### Server Details
- 6.1.5 (and all prior versions)
- ubuntu 18.0.4
- AWS
- single cluster in iot mode

### Client Details
- n/a

### Debug Logs

```
Jul 06 15:23:50 ip-10-66-145-96 /usr/local/bin/teleport[1029]: ERRO [DYNAMODB]  Poll streams returned with error: ExpiredIteratorException: Shard iterator has expired. dynamo/shards.go:59
```

[More info in a private slack thread](https://gravitational.slack.com/archives/CAHQS4HB5/p1625583894045700)

CC @fspmarshall

**Comment by fspmarshall** [comment]
Update:  Been able to confirm that stale resources are due to missed expiry events during teleport's handling of the expired iterator error.  The root of the issue is that a broken event stream doesn't necessarily resume from the exact point that the previous one left off, meaning that events (expiry or not) may be missed.  Teleport's cache is designed to handle broken event streams by resetting, but the dynamo backend wasn't signaling the break to the watchers, so the cache didn't recognize a problem and didn't reset.

Looking into this issue, it appears other backend implementations may have a similar problem.
