### ISSUE TITLE
docs: Add guide to using the Web UI

### ISSUE THREAD

**Issue by twakes** [gravitational/teleport#7547]
## Details

Would be nice to have better documentation on the Web UI. There is no information on what is included, how a user should navigate or use the Web UI. A tour with screenshots would be ideal.

### Category

- Improve Existing

**Comment by zmb3** [comment]
Updated the title to better reflect the ask here.

This would fit well in the new "Use Teleport" section alongside the "Use tsh" and "Use Teleport Connect" guides.

**Comment by ptgott** [comment]
Closing since this page exists now: https://goteleport.com/docs/connect-your-client/web-ui/

There's not a lot of content yet, but we should create separate issues with more specific requests for new sections in this guide.

A lot of the Web UI is discoverable without docs, so I would prefer a more targeted approach to documenting it instead of shooting for a comprehensive reference.
