### ISSUE TITLE
`GetAppServers` and `GetDatabaseServers` APIs no longer respect RBAC

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#7618]
### Description

**What happened**:

`tsh db ls` and `tsh app ls` commands (as well as respective tabs in the UI) no longer respect `db_labels` and `app_labels` in the user role and show all entries.

1. Create a role with app/db labels e.g. 
```yaml
spec:
  allow:
    app_labels:
      env: prod
    db_labels:
      env: aws
```
2. Registed a few apps/dbs with different labels (apps/dbs don't have to be actually working, just as long as there are registered).
3. Login with `tsh login` and use `tsh app ls`/`tsh db ls` to see that it always displays everything. Same for UI.

Previously, those calls used auth_with_roles.go methods which would filter out objects user doesn't have access to:

[GetAppServers](https://github.com/gravitational/teleport/blob/v7.0.0-beta.2/lib/auth/auth_with_roles.go#L2798-L2811)
[GetDatabaseServers](https://github.com/gravitational/teleport/blob/v7.0.0-beta.2/lib/auth/auth_with_roles.go#L2682-L2689)

Did this change?

**What you expected to happen**:

Those commands/tabs should only display apps/databases user has access to.

### Server Details
- Teleport version (run `teleport version`): 7.0.0-beta.2

### Client Details
- Tsh version (`tsh version`): 7.0.0-beta.1

**Comment by Joerger** [comment]
This issue is caused by https://github.com/gravitational/teleport/pull/6846, which changed `NewImplicitRoles` to use `types.NewRole` instead of being a static constant. Since `type.NewRole` sets the `role.Version` to `V3`, the implicit role gets wildcard labels.

I'd like to avoid reverting to the constant values since it will become a larger pain to maintain over time, and may lead to unexpected bugs like this one if `CheckAndSetDefaults` is ever called on the constant role.

Instead, I'll fix this by changing the default role version to `V4` and making sure that all of the default roles get the correct values set, making them equivalent to the prior constant values.
