### ISSUE TITLE
[v.6.2] /docs/pages/getting-started.mdx

### ISSUE THREAD

**Issue by sabueso** [gravitational/teleport#7690]
## Details
IMHO should be more efficient/easier to pipe the download command and untar it in some place in the skell:

```
curl https://get.gravitational.com/teleport-v6.2.7-linux-amd64-bin.tar.gz| sudo tar -xz -C /usr/local/
cd /usr/local/teleport
sudo ./install
```

### Category
- Improve Existing

**Comment by ptgott** [comment]
@sabueso Thanks for pointing this out and sorry for the delay in responding. I don't think this change is worth making since:
- The first command becomes longer, making it more likely to overflow the code snippet box if the window is narrow enough
- There is a button that allows you to copy all commands in the code snippet at once, so readers would not save any clicks
