### ISSUE TITLE
Docker-compose getting started missing steps

### ISSUE THREAD

**Issue by stevenGravy** [gravitational/teleport#7872]
## Details
The docker-compose example at https://goteleport.com/docs/getting-started/docker-compose/  does not work following the instructions.  it is relying on other assumed folders that are in the github repository.  The instructions say to download a specific docker-compose file but you can't run it in isolation.

### Category
docker-compose getting started

**Comment by stevenGravy** [comment]
docker-compose now working for teleport to start.  submitted PRs #7903 #7902 for the tsh alias corrections for the `term` machine.  lastly not seeing ssh connection session recordings.

**Comment by ptgott** [comment]
Hi @stevenGravy, just checking to see if any work remains to be done on this. It looks like session recording is mentioned [briefly](https://github.com/gravitational/teleport/blame/fb23a39fccf66a52f3fce2bb7b4398de40ce60d3/docs/pages/getting-started/docker-compose.mdx#L121) in the docker-compose Getting Started guide. Should there be more instructions for using session recording in this guide? Alternatively, we could remove the sentence that mentions session recording, since the "Next steps" section is directly below it.

**Comment by zen** [comment]
Also one more issue on MacOS with docker- desktop, accessing WebUI is impossible using dns names, they are not accessible from host machine. 
Accessing them on localhost:443 does not work even with --ignore-certificate-errors 
In addition `ssh root@mars.openssh.teleport` asks for password launched from term container
