### ISSUE TITLE
Proxy Protocol & Proxy SSH listener issues

### ISSUE THREAD

**Issue by russjones** [gravitational/teleport#7924]
Customer has reported Teleport is not honoring Proxy Protocol V1 when emitting audit events for when a user creates a session.

---

The Proxy SSH listener (3023) does not support Proxy Protocol. When connecting with PROXY V1, the client's real address is not captured, and when connecting with PROXY V2, the binary format results in the server SSH conn failing to instantiate, leading to the connection being dropped.

As many customers do not make use of the ALPN multiplexing, we should aim to support Proxy protocol on this port. We can do this by leveraging the existing multiplexer code, and using that to correct the remote address. This will resolve the connection dropping when PROXY V2 is used, and ensure the correct IP address is captured on both protocols.

**Comment by russjones** [comment]
@Joerger Can you update this ticket with details about what you find and what you feel the issue is? It looks like the client IP address is correctly propagated from the Web UI but not from `tsh`?

**Comment by Joerger** [comment]
I reproduced this with an AWS ELB with Proxy Protocol V1 enabled. At first I thought it was working as intended because the `session.start` audit events had `addr.remote` set to my local IP when connecting through the Web UI. However when connecting through `tsh ssh`, the `addr.remote` was set to a `10.0.0.x` address. A quick skim of auth logs for each method showed that the addr mixup was occurring early on in the call, so this may be an issue with the multiplexer, or an issue within `tsh`. Since the Web UI audit events works as intended, I don't expect this to be an exceptionally difficult bug to dissect and fix from here.

**Comment by russjones** [comment]
@nklaassen Let's look at this in the context of https://github.com/gravitational/teleport/issues/7081 and make sure we support ProxyProtocol.

**Comment by zmb3** [comment]
@strideynet is this related to the work you're doing?

**Comment by strideynet** [comment]
I'm going to go ahead and test this for situations without an ELB, with Proxy Protocol v1 and with v2 to check if this is still the case, and then see what we can do about it.
