### ISSUE TITLE
Unknown Event Type "" session.end

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#7946]
### Description

**What happened**:

Customer attempted to check audit logs via WebUI but ran into an error message stating `unknown event type: ""`

**What you expected to happen**:

Having even one corrupt session/issue shouldn't cause the whole list operation to fail. At the least, we should have clearer logging to indicate where the issue is originating.

### Server Details
- Teleport version (run `teleport version`): 6.2.3

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- No useful information could be gathered from the network panel and no specific logs were noted in auth and proxy server. However, based on the error on webUI customer searched in the event log file and found one event type `session.endend`. He replaced it with "session.end" and this resolved the problem.

gz#4175

**Comment by 1inh** [comment]
I'm encountering a similar issue after upgrading from `7.3.8` to `8.1.0`. When I checked Audit Logs and Session Recordings on the UI, I got `unknown event type: ""`. All of my audit logs + recordings are not viewable through the UI even though they are still there. Debug logs aren't helpful. 

I also checked the audit logs but found no abnormal events. I have a feeling that my particular issue is not due to bad logs since I got the same error when browsing logs on different dates. However, next day logs can be seen on the UI just fine (starting from midnight)

**Comment by stevenGravy** [comment]
what the user sees when this happens. 
![image](https://user-images.githubusercontent.com/60704961/152578057-473991d7-44f7-410a-ab13-206c9e95a215.png)

**Comment by kimlisa** [comment]
I upgraded my cloud cluster staging to `v9.0.0-beta.1`, and I cannot view my audit/session recording view. The error message is unhelpful and logs don't seem to tell me anything? among the actions I took today on the cluster is: log in with my auth connectors (saml,oidc,github), and starting/ending sessions

I get the same error with `v8.3.1`, i think working version was `7.3.7`

![image](https://user-images.githubusercontent.com/43280172/155926633-0586aaa3-62ab-44d4-9b9e-96c4a7b2c35a.png)

**Comment by pierrebeaucamp** [comment]
@kimlisa this usually happens if an incorrect / unknown event is written to the audit log. Rolling back your Teleport version would not help at this point, since the incorrect data is still in your data-store.

**Comment by zmb3** [comment]
This has been fixed.

**Comment by strideynet** [comment]
Supposedly fixed by https://github.com/gravitational/teleport/pull/10665
