### ISSUE TITLE
Is it possible to auto run a script after login?

### ISSUE THREAD

**Issue by stephencheng** [gravitational/teleport#814]
openssh supports execution of a script after user login, is it possible in teleport and how?

Thanks,

Stephen

**Comment by klizhentas** [comment]
if you mean executing .bashrc this is controlled by your shell, not openssh or SSH server. Can you clarify?

**Comment by stephencheng** [comment]
here is what I mean: 

Match User foo
    ForceCommand /path/to/script.sh

see link: http://stackoverflow.com/questions/33713680/ssh-force-command-execution-on-login-even-without-shell

**Comment by klizhentas** [comment]
we don't support this, what is your use-case?

**Comment by stephencheng** [comment]
I'd like to have a login user to:
1. only to login and automatically run one application automatically
2. not to even to give user interactive shell access
3. the app is kind of CLI or curses program with basic GUI
4. if user quit or kill the app, the session will be terminated or the user will be kicked out of login ssh connection

Not sure if this is even possible, the standard sshd server does allow force command so that at least immediately after the login, I can startup the app script.

**Comment by klizhentas** [comment]
I think this is something you should do outside of Teleport - e.g. create a user with shell limited to launching only this command and using linux groups permissions to restrict access. So closing this for now

**Comment by Beanow** [comment]
Excuse me for gravedigging, just want to add I was looking for the same feature.

My usecase being a tightly locked down rsync task (server forces path, options and bandwidth).
The technical implementation is pretty much the same as what was requested, a bash script that figures out how to invoke rsync.

While Teleport offers an easy way to set up a bastion/proxy server, because of the `Match User ... ForceCommand` equivalents missing, the node wound up needing OpenSSH. The downsides of this being, the audit logs don't mention anything in node session recording mode, and having to roll my own authentication for the node rather than using Teleport's (which makes it a lot more tempting to go with long-lived certs / pubkey auth).
