### ISSUE TITLE
Integration with workflow automation and DevOps tools.

### ISSUE THREAD

**Issue by KranthiveerDontineni** [gravitational/teleport#8200]
### What
What would you like Teleport to do differently?
I have been using teleport for logging into my instances but as automation is required for managing my environment and as teleport is my main means to login to my servers, my automation scripts are not working.

### How
How would you implement this?
Currently we are using interactive access for running the script but as this should not be the case. If you could do something for running my playbooks or cookbooks or recipes it would be really great like some integration with Jenkins, Ansible, Chef, puppet and n8n.

### Why
Why do you need this?
I have a huge IT infrastructure to manage. I don't want anyone to have a direct access because of security policy. I want them to run their scripts through teleport.

### Workaround
If a workaround exists, please include it.
There are several work around like aws lamda functions.

**Comment by zmb3** [comment]
Hey @KranthiveerDontineni - [Machine ID](https://goteleport.com/docs/machine-id/introduction/) is our new solution for running automation against Teleport.

Give it a look and let us know if something's not working for you by filing a new issue. In the meantime, I'm going to close this one.

**Comment by ivan-tkatchev** [comment]
@zmb3 Unfortunately machine id is not the solution. Current implementation makes it impossible to use machine id in a realistic scenario.

Each machine id is tied to a particular host and a particular role. This means you either need to create NxM machine ids (one for each role and host) and then implement some sort of custom mapping from Teleport user and host to machine id (not practical and you're duplicating core Teleport functionality in a bespoke way), or you create one superuser machine id with complete access to everything, which defeats the purpose of RBAC.

A proper solution would be to expose the /v1/webapi/ssh/certs API endpoint in a documented way, so that interactive tools could generate SSH keys for a particular user and use them in SSH configs. 

A correct way to do this would be through the Teleport application proxy. The app proxy could be modified to send an additional HTTP header with a user session key, and this user session key could be used by the web app to retrieve the user's SSH keys.

(I assume the SSH web interface of the Teleport admin UI works in a similar way. Third-party web apps should have access to this functionality too.)
