### ISSUE TITLE
kube_cluster_name error logs

### ISSUE THREAD

**Issue by deusxanima** [gravitational/teleport#8229]
### Description

Configuring `kubernetes_service` without configuring a `kube_cluster_name` parameter for the service (when no kubeconfig is provided either), throws a missleading error log:

```
2021-09-09T05:08:21Z ERRO [PROC:1]    Critical service kube.init has exited with error no Kubernetes credentials found; Kubernetes_service requires either a valid kubeconfig_path or to run inside of a Kubernetes pod, aborting. service/signals.go:144
ERROR: no Kubernetes credentials found; Kubernetes_service requires either a valid kubeconfig_path or to run inside of a Kubernetes pod
```

We should specify the correct error in these cases to make troubleshooting easier and error logging clearer. 

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Configure `kubernetes_service` on a server w/out specifying a `kube_cluster_name` (when no kubeconfig is provided)
2. Start service and observe misleading log message

### Server Details
- Teleport version (run `teleport version`): 6.2+

**Comment by tigrato** [comment]
`kube_cluster_name` is the name of the cluster in Teleport when running the `kubernetes_service` inside a Kubernetes Cluster - i.e. when using  `teleport-kube-agent`  chart.

Kube service now requires one of the following clauses:
- Providing a kubeconfig with credentials to the target cluster
- Providing `kube_cluster_name` and running in a Kubernetes Cluster
- specifying dynamic watcher with a `resources` entry.

The error you see is correct. You must specify one of them to start the `kubernetes_service`, otherwise, Teleport won't register the cluster.  `kube_cluster_name` is the name of the Kubernetes cluster you want to register in Teleport and it's not the kube_service name. 

When using kubeconfig, the name is inferred from the contexts configured
