### ISSUE TITLE
AWS Local Proxy 

### ISSUE THREAD

**Issue by smallinsky** [gravitational/teleport#8610]
### What
Add support for AWS local proxy in order to handler AWS access from third party applications like terraform.

### How
the `tsh proxy aws` command should be introduced allowing to start the AWS proxy manually.  

gz#4128

**Comment by greedy52** [comment]
AWS profile currently does **NOT** support endpoint url: https://github.com/aws/aws-cli/issues/4454
AWS environment currently does **NOT** support endpoint url: https://github.com/aws/aws-cli/issues/4454

so if the client is using AWS SDK (terraform for e.g.), there is currently no way to make it work.

if the client is aws cli, best we can do is this alias hack mentioned in the above issue `alias aws='aws --endpoint-url http://website'`

**Comment by r0mant** [comment]
@greedy52 Yes, for terraform users will need to use custom endpoints which is fine. Let's not worry about supporting plain `aws` client, `tsh aws` already does basically what you've described.

**Comment by greedy52** [comment]
@r0mant yeah, we should certainly have this local aws proxy. Just pointing out that since there is no generic way for specifying the endpoint url, client apps will need some extra configurations on their side and it will be different from client by client. I will try out different once as many as I can.
