### ISSUE TITLE
missing session cookie

### ISSUE THREAD

**Issue by galenzhao** [gravitational/teleport#868]
`
INFO[0038] [SSH:auth] closed connection                  file=sshutils/server.go:257 func=sshutils.(*Server).handleConnection.func1

WARN[0038] http: named cookie not present                file=web/apiserver.go:1620 func=web.(*Handler).AuthenticateRequest request=GET /web

WARN[0039] http: named cookie not present                file=web/apiserver.go:1620 func=web.(*Handler).AuthenticateRequest request=GET /webapi/sites

WARN[0039] http: named cookie not present                file=web/apiserver.go:1620 func=web.(*Handler).AuthenticateRequest request=GET /webapi/user/acl`

**Comment by galenzhao** [comment]
not the same as #557,
I'm sure enabled cookie in browser,
and the server time as same as my client ,

**Comment by alex-kovoy** [comment]
Did you have any other browser tab open with the teleport? In case of terminated teleport web session (due to sever restart, for example), a web-client would keep pinging the server for a little while until it finds out about ended session. When that happens, a web-client should stop querying the server and show a login page.

**Comment by kontsevoy** [comment]
@galenzhao I'll close it for now unless you come back.
