### ISSUE TITLE
WINRM Support?

### ISSUE THREAD

**Issue by beaudryj** [gravitational/teleport#872]
Probably a pretty crazy request, but have you thought about implementation of this using WinRM?  This would be amazing for windows environments/Azure

Also would be really nice for heavily mixed environments

**Comment by kontsevoy** [comment]
@beaudryj thanks for your suggestion! cool ideas are always appreciated. however, with Teleport, since it's a security tool, we have made a decision (a while ago) to never implement other protocols because we believe in specialized tools to do one job, in this case SSH access. We've had requests for RDP and VNC as well. Sorry! :)
