### ISSUE TITLE
Self-hosted MariaDB support

### ISSUE THREAD

**Issue by r0mant** [gravitational/teleport#8904]
### What

Teleport database access should support self-hosted MariaDB databases.

### How

MariaDB is fully compatible with MySQL protocol (to the point where `mysql` and `mariadb` CLI clients can be used interchangeably) which database access already supports. So chances are, MariaDB is already supported, we just need to validate it and write a documentation guide.

Action items:

- [ ] Use X.509 authentication with MariaDB similar to MySQL.
- [ ] Update MySQL integration to use `mariadb` shell client if it's available. Many guides recommend using this client even for MySQL databases.
- [ ] Write documentation guide.
  - If it's similar to MySQL (for instance, only differs in the way you setup mTLS in the database config), update existing MySQL [guide](https://goteleport.com/docs/database-access/guides/mysql-self-hosted/) - use tabs to show configuration for MySQL vs MariaDB.
  - Otherwise, create a separate guide page.

**Comment by jakule** [comment]
@r0mant I see two problems with using `mariadb` client instead of `mysql`. `mariadb` doesn't support `ssl-mode` flag and returns an error if that option is in the config file:
```bash
$ tsh db connect prod-mysql
mariadb: unknown variable 'ssl-mode=VERIFY_IDENTITY'
ERROR: exit status 7
```
As you probably know the legacy option still supported by MariaDB `ssl-verify-server-cert` has been removed in MySQL 8.0 https://dev.mysql.com/doc/refman/5.7/en/connection-options.html#option_general_ssl-verify-server-cert

But this is the least interesting part of that story. Ubuntu in the official repository has 2 packages: `mysql-client` and `mariadb-client`. The first one contains Oracle's version of `mysql`
```
% mysql --version
mysql  Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
```
that support `ssl-mode`, but the second one contains `mysql` and `mariadb`:
```
% mysql --version
mysql  Ver 15.1 Distrib 10.3.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
% mariadb --version
mariadb  Ver 15.1 Distrib 10.3.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
 ```
and this one fails if `ssl-mode` is being used:
```
mysql: unknown variable 'ssl-mode=VERIFY_IDENTITY'
```
This error happens even on the current master.

1. Do you think it's safe to assume that if `mariadb` is installed we should use "MariaDB compatible mode" (use `ssl-verify-server-cert` instead of `ssl-mode`) even for MySQL? I know that you mentioned this in the issue, but I just want to confirm.
2. Config file is created on login not connect. Should we check for the available binaries on login and create a "matching" config file or do we want to move that logic to `tsh db connect`? Technically the "state" may change between these operations may change, although I'm not sure if this is common enough to worry about it. An alternative would be creating 2 sections/files one for `mysql` and second for `mariadb`, but this sounds like a bit overkill.

**Comment by r0mant** [comment]
@jakule This is because of the options file, right? How about instead of using the options file we just construct a `mysql`/`mariadb` command with proper CLI flags like we do for other databases? E.g. see https://github.com/gravitational/teleport/blob/v8.0.1/tool/tsh/db.go#L484. I originally decided to use options files (and Postgres' connection service files) to make the respective "psql"/"mysql" commands shorter, but I think that now that we have a `tsh db connect` command, their relevance is reduced. Does everything work with MariaDB otherwise?

**Comment by jakule** [comment]
@r0mant I was able to successfully connect the the MariaDB and run a few questions, so integration looks fine. The only thing that can be problematic is unsupported flag when you're using MariaDB's version of mysql (which I'd assume is the case when you try to connect mariadb instance). Currently on my Linux box I'm getting this error when I install `mariadb-client` package:
```
mysql: unknown variable 'ssl-mode=VERIFY_IDENTITY' 
```

> How about instead of using the options file we just construct a mysql/mariadb command with proper CLI flags like we do for other databases? E.g. see https://github.com/gravitational/teleport/blob/v8.0.1/tool/tsh/db.go#L484.

Yes, this would solve the problem. Do you also want to remove the Postgres file now or just the MySQL? 
Also how in this case can we preserved options passed on `tsh db login`? Related code: https://github.com/gravitational/teleport/blob/6b9726f961226ac4bd96ea68660f0ce3c5e1460a/lib/client/db/mysql/optionfile.go#L80-L90

**Comment by r0mant** [comment]
@jakule User/database name should be already encoded in the client certificate obtained with `tsh db login`.

I'm thinking that we might actually have to keep the options file to preserve backwards compatible behavior for MySQL, but not use it and construct the command when using a MariaDB client. Is MariaDB client also called `mysql`? Is there a way to distinguish between the two?

**Comment by jakule** [comment]
@r0mant We can do something like this to distinguish between Oracle and MariaDB flavor of `mysql`: https://github.com/gravitational/teleport/compare/jakule/mariadb-support?expand=1#diff-dae87d4d3799335d85a5fa6ff17cfcbfb30705ae145c9e67ef70286423676a48R551-R582

I just don't know how to support `tsh db login --insecure` flag here, as we cannot store that value in the config file. MariaDB returns an error if this flag is set. We could run this check on login too, as a simple workaround.
