### ISSUE TITLE
EC2 Node Join Tunnel Connectivity Issues When Two Nodes Share Nodename

### ISSUE THREAD

**Issue by Aharic** [gravitational/teleport#9110]
### Description

**What happened**:

Customer has a test suite where they tear down and bring up EC2 nodes with the same exact config (including nodename). Pre 7.3.3 ec2 node join the behavior was such that two nodes would appear in the webui and `tsh ls` temporarily (until the first aged out), but the tunnel connection would work for the new node as soon as it joined. WIth the new ec2 node join process, however, both nodes still appear in the webui and `tsh ls`, but the tunnel does not work for either until the first either ages out completely or is deleted manually.

**What you expected to happen**:

Would expect behavior consistent with previous versions where the latest node to join and/or heartbeat would have a live tunnel that could be used for connections.

### Reproduction Steps
As minimally and precisely as possible, describe step-by-step how to reproduce the problem.
1. Join node to cluster using EC2 node join process with a static nodename (hostname)
2. Turn off node.
3. Join another node to same cluster using EC2 node join process with the same static nodename (hostname) as the previous one
4. Observe 2 nodes show up in the webui/`tsh ls`, but tunnel connection for both fails.

### Server Details
- Teleport version (run `teleport version`): 7.3.3+

### Debug Logs
Please include or attach debug logs, when appropriate. Obfuscate sensitive information!
- Start Teleport with --debug flag (`teleport --debug`)
- Run tsh with --debug flag (`tsh --debug`)

**Comment by Aharic** [comment]
Additional context: When two nodes are joined w/ EC2 Node Join using the same nodename but different UUIDs, the tunnel fails for both. This same setup works, however, using the normal join token method.

**Comment by nklaassen** [comment]
**Root cause:**
When using EC2 node joining the name/uuid field of the node is not a valid v4 UUID, but rather a unique string including the EC2 node's AWS account and node ID. This causes teleport to attempt to match on the hostname rather than the name/uuid field here https://github.com/gravitational/teleport/blob/4e324e74e33a53269806e4b6a51a6ec40bef0e14/lib/srv/regular/proxy.go#L462-L474 and return an error when the match is ultimately ambiguous.

**Workaround:**
set the routing strategy to `most_recent` instead of the default `unambiguous`, eg:
```yaml
# teleport.yaml
auth_service:
  routing_strategy: "most_recent"
```
Both entries for the matching hostname/nodename should then resolve to the new node and tunnel connections will work.

**Planned Fix:**
Match on the name/uuid field by default if the host ID looks like an EC2 node ID.
