### ISSUE TITLE
Add EC2 join token functionality to Terraform provider

### ISSUE THREAD

**Issue by nickbrennan1** [gravitational/teleport#9420]
Currently there is no way to create the EC2 join token mapping using the Teleport terraform provider.

It would be very helpful to have a mechanism to pass the configuration through the terraform provider to enable nodes to auto-join the cluster once the cluster nodes have been stood up and available.

As part of the initialisation a new dynamic token would be created on the auth node per documentation [here](https://goteleport.com/docs/setup/guides/joining-nodes-aws/#step-24-create-the-aws-node-joining-token).  The parameters here would be:

```
name
expires
roles
aws_iid_ttl
aws_account
aws_regions
```

Once created, join_params in joining nodes `teleport.yaml`/ start command to be populated:

```
token_name
auth_servers
```

**Comment by hugoShaka** [comment]
The Terraform provider seems to currently support creating `ProvisionToken` with IAM and EC2 join methods. I added a test and example [here](https://github.com/gravitational/teleport-plugins/pull/722/commits/6f224e21ff9d22df779776f16a8b20a95c6dc7a4). It might have been added after the issue was created.

If I misunderstood the issue or you believe it is not fixed, please reply, and I'll reopen it.
