### ISSUE TITLE
Connect to generic SSH daemon

### ISSUE THREAD

**Issue by lcaflc** [gravitational/teleport#953]
I'm testing teleport in order to deploy a _"bastion"_ service to filter access to my platform systems.
My environment is mainly made of network equipment on which I cannot run a teleport daemon directly.

I however found in documentation a way to integrate using the export of certificate authority for users and add it into authorized_keys. It still need to check if ssh implementation of my equipment support this. But anyway I didn't find any documented way to _"manually"_ add this node to the cluster.

The greatest way would be to support a generic SSH node, that only need an standard public key to add to the system to support login to this host. In order to still support audit, auth etc... this could go through a  teleport node that act as a teleport->ssh gateway as backend instead of local shell.

Maybe I miss something and this is already available.
Thanks.

**Comment by kontsevoy** [comment]
@lcaflc when using `sshd` (OpenSSH ssh daemons) you do not need to "add them to cluster" anymore because you're manually configuring certificates as explained in the docs, see "Integrating with OpenSSH Servers" section [here](http://gravitational.com/teleport/docs/2.0/admin-guide/#using-teleport-with-openssh)
