### ISSUE TITLE
[v.8.0] /docs/pages/setup/reference/terraform-provider.mdx

### ISSUE THREAD

**Issue by moabu** [gravitational/teleport#9551]
## Details

Several of the terraform property keys are not accurate such as the following in `teleport_role`: 

In  `spec.allow` and `spec.deny` : 
- `database_labels` which should be `db_labels `
In `spec.options` : 
- `bpf` and `certificate_format` don't exist in the terraform module. 

The above are just examples. I think most of it is just not matching the `teleport.yml` source key names.

### Category

- Improve Existing

**Comment by marcoandredinis** [comment]
It looks like this was fixed in this PR
https://github.com/gravitational/teleport/pull/8851

I verified the fields you mentioned and a couple more
All of them seem to match with Teleport v8

As for v9, we are missing a couple of things:
- update provider's source to match our Terraform Registry
- new retry fields
I'll open a PR for those

If there's something else not accurate, please let me know
