### ISSUE TITLE
Windows Desktop token type name inconsistent with other services

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport#9752]
### Description

**What happened**: The capitalisation and spacing of the command `tctl tokens add --type=WindowsDesktop` is inconsistent with all other service types: `node`, `db`, `app`, `kube` etc.

**What you expected to happen**: At the very least, `tctl tokens add --type=windowsdesktop` should work. At the moment there's an error which is confusing:

```
~ » sudo tctl tokens add --type=windowsdesktop
ERROR: role Windowsdesktop is not registered
```

`tctl tokens add --type=windows_desktop` should probably work too. The forced capitalisation that currently exists is very confusing as no other service expects it.

### Reproduction Steps
See above.

### Server Details
- Teleport version (run `teleport version`): `Teleport v8.1.0 git:v8.1.0-0-g3dc269bef go1.17.3`

**Comment by zmb3** [comment]
This happens because when Teleport canonicalizes the provided role name we run it through `strings.Title`, which just capitalizes each word.

It works for `app`, `kube`, `db` because the actual system roles are named `App`, `Kube`, and `Db`.

It doesn't work for `windowsdesktop` because `strings.Title` will produce `Windowsdesktop`, which doesn't match the actual role name `WindowsDesktop`.

I suspect it behaves the same for `ProvisionToken` and `RemoteProxy`.

I don't see any reason why a case-insensitive compare shouldn't be allowed here, but it would make Teleport more gracious in what it accepts, as this logic is used not only in `tctl tokens add`, but in `tctl nodes add` and when roles in cert extensions and validating static tokens from configuration files.

Alternatively, we can add a special case in the `tctl tokens add` command to fix the role before it is passed into our common parsing logic.

**Comment by pzduniak** [comment]
FWIW this also happens within the Terraform provider (but for all role names), as it doesn't `.Title` the roles.

**Comment by zmb3** [comment]
After discussion: we'll make the comparison case-insensitive, but also will add some new code to prevent creating a user role with a name that conflicts with a builtin system role.
