### ISSUE TITLE
Prometheus metric backend_requests help message is incorrect

### ISSUE THREAD

**Issue by rcanderson23** [gravitational/teleport#9865]
### Description

Metric `backend_requests` has a help message that states "Number of write requests to the backend" but this is incorrect as `trackRequest()` does not use the `opType` to make any decisions (unused completely). The help message would allude that this should only be incremented on `Put` or `Delete` ops.
https://github.com/gravitational/teleport/blob/9a8dfc35fae81290d38699a9c0bcd1fa1fc3ee5a/lib/backend/report.go#L266-L288
This metric is also not documented on our public docs.

### Possible solutions:
1. Update the help message to accurately state that it encompasses all requests and update public docs with metric entry.
2. Add logic to increment only on `Put` and `Delete` ops and update public docs with metric entry.  
3. Add an `op` label that indicates what type of operation is being done against the `req`, update help message to properly reflect behavior, and update public docs with metric entry.

Option 3 seems the best but I am hesitant to recommend it as it is already our highest cardinality metric by far with the `req` label being there.

**Comment by zmb3** [comment]
FWIW, my vote would be option 1 - just update the help message to make it as accurate as we can.

If we change the behavior of the metric we may confuse customers or even trigger alerts due to the value suddenly changing.

If this metric is unfortunately not capturing what we originally intended it to (due to an implementation error) then we can always add a new metric without disturbing the existing one.
